### ISSUE TITLE
[DUNGEON] jarConverter.sh funktioniert unter Windows nicht

### ISSUE THREAD

**Issue by Lena241** [Programmiermethoden/Dungeon#1006]
Beim Ausführen von `.\jarConverter.sh .\dungeon\assets\scripts\task_test.dng` passiert nichts. Auch wenn das Skript und die .dng Datei innerhalb desselben Ordners sind, passiert nichts.

Aufgetreten unter Windows 11 22H2

**Comment by AMatutat** [comment]
fixed in https://github.com/Programmiermethoden/Dungeon/pull/1016
