### ISSUE TITLE
[Dungeon] Update auf Java 21 LTS

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#1010]
Lt. https://openjdk.org/projects/jdk/21/ [^1] kommt am 19.09.2023 die neue LTS-Ausgabe von Java-SE raus: Java 21 LTS.

Bitte (dann) das Projekt updaten.

[^1]: auch hier: https://www.java.com/releases/ und hier: https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by AMatutat** [comment]
@Lena241 hat mir heute mitgeteilt, dass ein einfaches hochziehen der Version auf Java 21 (auf Windows 11) nicht ausreicht. Vermutung liegt nahe dass der Gradlew-Wrapper ein update braucht.

**Comment by fwatermann** [comment]
Aktuell unterstützt Gradle Java 21 nur so halb.
Compiling & Testing geht, jedoch lässt sich Gradle nicht mit Java 21 ausführen, dafür muss eine Java Version zwischen 8 und 20 installiert sein. Siehe https://docs.gradle.org/current/userguide/compatibility.html

**Comment by cagix** [comment]
> Aktuell unterstützt Gradle Java 21 nur so halb. Compiling & Testing geht, jedoch lässt sich Gradle nicht mit Java 21 ausführen, dafür muss eine Java Version zwischen 8 und 20 installiert sein. Siehe https://docs.gradle.org/current/userguide/compatibility.html

@fwatermann Danke für die Recherche! Irgendwie verstehe ich das noch nicht ganz: Warum kann Gradle selbst nicht auf Java 21 laufen? Gradle wird irgendwelche Features nutzen aus früheren Versionen, aber die sollten ja auch in Java 21 vorhanden sein (Abwärtskompatibilität)?

**Comment by fwatermann** [comment]
Das verstehe ich auch nicht so ganz. Ich spiele damit gleich mal ein bisschen rum.

**Comment by cagix** [comment]
Ich würde vor allem bei libGDX Probleme erwarten, weil die irgendwelche Sonderspielchen machen mit nativem Code und so. Hmmm. Naja, vielleicht ist es überzogen, jetzt schon auf JDK21 zu schielen und das kann dann erst im Januar/Februar passieren.

**Comment by cagix** [comment]
@fwatermann Schau mal https://docs.gradle.org/current/release-notes.html: 
> "... [Java 21](https://docs.gradle.org/current/release-notes.html#java-21) is now supported for compiling, testing, and running such projects. ..."

**Comment by cagix** [comment]
Gradle 8.5 unterstützt JDK21: https://docs.gradle.org/8.5/release-notes.html
