### ISSUE TITLE
[GAME] First Frame of Fireball is MissingTexture

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#1029]
Der erste gezeichnete Frame eines Feuerball ist immer die "MissingTexture".

Vermutung woran es liegt: 
Der Fireball hat keine Idle-Animation, das DrawComponent setzt die erste Animation aber immer auf eine Idle-Animation (und da es keine gibt, auf MissingTexture).

Möglicher Fix.
Option A (quick but dirty): Feuerball um eine Idle-Animation erweitern. Dazu müsste nur ein neues Verzeichnis "fireball/idle" erstellt werden und darin eine einzelne Textur des Fireballs gelegt werden (die könnte kopiert werden).

Option B: Beim erstellen des Projektils (in `DamageProjectile`) muss anhand der velocity die richtige Animation gesetzt werden (im Grunde würde man hier die Logik des `VelocitySystem` übernehmen. 

Edit: Option A ist vermutlich die sinnvollste.

**Comment by cagix** [comment]
ist (a) wirklich so dirty? für mich klingt es irgendwie sinnvoll: so lange der feuerball noch nicht fliegt, ist er "idle" und hat die passende animation?

bei (b) höre ich grad code-duplizierung aus einem system in eine component(?) hinein - wenn es das wirklich ist, dann wäre _das_ für mich dirty :)

**Comment by AMatutat** [comment]
> ist (a) wirklich so dirty? für mich klingt es irgendwie sinnvoll: so lange der feuerball noch nicht fliegt, ist er "idle" und hat die passende animation?

Ja hmm vielleicht hast du ja recht. Unter betrachtung des Aufwands vielleicht auch die bessere lösung.
Ich hab ein Feuerball immer als "der fliegt immer" betrachtet. Aber von mir aus kann er im ersten Frame auch idlen aka Anlauf nehmen

> bei (b) höre ich grad code-duplizierung aus einem system in eine component(?) hinein - wenn es das wirklich ist, dann wäre _das_ für mich dirty :)

Nicht direkt in ein Component, eher in eine Factory hinein. Richtig zufrieden bin ich damit auch nicht.
