### ISSUE TITLE
[GAME] Ausrüstungscomponent und System

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#1044]
1. "Wir haben Strukturen, um Ausrüstungs-Items zu implementieren (z.B. Rüstungen). Es gibt aktuell aber noch keine Möglichkeit, diese Items dann auch wirklich zu verwenden/anzuziehen.

2. Ich schlage ein `EquipmentComponent` vor, welches verschiedene Attribute für die verschiedenen Ausrüstungs-"slots" hat.

```java 
HelmItem helm;
HoseItem hose; 
XyzItem xyz;
...
```

Über Setter kann man dann die einzelnen Attribute setzen (die Rüstung also anziehen). Das wäre für mich Teil der `onUse`-Funktion des Rüstungsitems. Also `armor.onUse(entity -> entity.fetch(EquipmentComponent.class).armor(armor))` (oder so). Wenn bereits ein Item in den Slot liegt, dann müsste man das austauschen (braucht es so etwas wie eine "onAusziehen" Callback-Funktion?)

Wo ich mir noch nicht ganz sicher bin, ist, wie die Ausrüstungswerte (z.B. der Rüstungswert) dann dem Spieler gutgeschrieben wird. Wir haben ein `StatsComponent`. Das wäre vermutlich der Punkt, wo die Werte gesetzt werden, aber welches System macht das? Wie wird das gemacht (jeden Frame oder nur bei Änderungen?)

Ich sehe da auf Anhieb zwei Möglichkeiten:
   1. Das `StatsComponent` speichert einmal die Basiswerte und einmal die aktuellen Werte. Verschiedene Systeme (z.B. `EquipmentSystem`) verändern die Werte (am liebsten über eine Art Anfrage-Queue). Sprich: Das `EquipmentSystem` schaut im `EquipmentComponent`, welche Ausrüstung angelegt ist, und sagt dem `StatsComponent` => "Erhöhe Rüstungswert um 5)". Ein Debuff (haben wir aktuell nicht, aber könnte ja kommen) würde dann so etwas machen wie "Reduziere Feuerresistenz um 5".
   Das `StatsSystem` würde dann die Basiswerte mit den Queue-Anfragen verrechnen (aktueller Wert = Basiswert + Summe(Werte in Queue)).
   Dann käme das `HealthSystem` und würde Schaden hinzufügen, etc.

   Das würde bedeuten, dass jeden Frame die Stats neu gesetzt werden müssten.
   Nachteil: Gerade bei Ausrüstung irgendwie seltsam, ich ziehe ja nicht jeden Frame neue Rüstungen an.
   Vorteil: Gerade so etwas wie Debuffs wäre dann eigenständig dafür verantwortlich, dafür zu sorgen, dass sie ausreichend lange ticken.

   2. Alternative wäre die Werte im `StatsComponent` dauerhaft zu ändern.
   `onRüstungAnziehen` => erhöhe Wert
   `onRüstungAusziehen` => verringere Wert
   `onDebuffActive` => verringere Wert
   `onDebuffDeactive => erhöhe Wert.

   Vorteil: Wir bräuchten keine einzelnen Systeme für die Stats und das Equipment.
   Nachteil: Wir "verstecken" die Logik im Callback der Items, da würde ich als Außenstehender erstmal nicht gucken. Und zusätzlich muss ich bei Debuffs darauf achten, den Wert auch wieder zurückzusetzen.

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
