### ISSUE TITLE
[Projekt] Issues, Labels und PRs aufräumen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#1048]
Kurz vor Projektende sollten nochmal alle Issues und PRs angeguckt werden und ggf. ausgemistet oder besser beschrieben werden.

**Comment by AMatutat** [comment]
Wir haben einige Issues die sich auf das hinzufügen von Spiel-Features beziehen.
z.B #229 oder #614 

Die Features haben jetzt keine tiefere Verbindung zu dem Projekt selbst, sondern sind mehr "Macht das Spiel spaßiger". 

Das sind auch die Issues, die sich super als bounty Aufgaben (oder "normale" Praktikumsaufgabe) eignen würden.

Aktuell sind die alle mit https://github.com/Programmiermethoden/Dungeon/labels/struct%3Acontrib und https://github.com/Programmiermethoden/Dungeon/labels/later versehen.


Die Frage ist: Wollen wir die behalten? Die könnten als inspiration für die Studis dienen (das könnte man aber auch in einer Liste führen, dafür braucht es keine Issues)

**Comment by cagix** [comment]
> Wir haben einige Issues die sich auf das hinzufügen von Spiel-Features beziehen. z.B #229 oder #614
> 
> Die Features haben jetzt keine tiefere Verbindung zu dem Projekt selbst, sondern sind mehr "Macht das Spiel spaßiger".
> 
> Das sind auch die Issues, die sich super als bounty Aufgaben (oder "normale" Praktikumsaufgabe) eignen würden.
> 
> Aktuell sind die alle mit [ struct:contrib](https://github.com/Programmiermethoden/Dungeon/labels/struct%3Acontrib) advanced game features for contrib und [ later](https://github.com/Programmiermethoden/Dungeon/labels/later) not now, maybe later versehen.
> 
> Die Frage ist: Wollen wir die behalten? Die könnten als inspiration für die Studis dienen (das könnte man aber auch in einer Liste führen, dafür braucht es keine Issues)
> 
> Wenn ja: umlabeln um sie besser von den Projek-Issues zu trennen?
> 
> @cagix Willst du nach Ende des Projekts eigentlich das Project-Board dicht machen? Ansonsten wäre das eigentlich eine gute Möglichkeit um die verbleibenden Issues (aber nur die wirklich direkt mit den Projekt zu tun haben) dort zu gruppieren. Ich halte es nämlich schon für Sinnvoll die Issues auch auf dauer mit den Projekt in Verbindung zu bringen. Alternative wäre ein "project:dungeon22/23" label

Hmmm, gute Frage. Habe ich noch keine Antwort drauf. Aus dem Bauch heraus stimme ich Dir zu: entweder man lässt das als Issue mit passendem Label oder man baut eine Liste mit diesen Themen. 

Issues sind irgendwie "lebendiger" und mehr mit dem Projekt verknüpft - eine Liste wird schneller veralten. Andererseits sind das ja keine Issues im eigentlichen Sinne, d.h. die werden nie zugehen. Sowas nervt irgendwie. Statt einer Liste könnte man das auch im Lecture-Repo als Übungsaufgabe formulieren, dann wäre das auch self-contained im Sinne von alle relevanten Inhalte liegen im Repo vor und man ist nicht auf zusätzliche Features (Issues, Discussions) von GH angewiesen.

Vielleicht sollten die Übungsaufgaben in Zukunft als Issues formuliert werden. Aber dazu bräuchte es ein Semester-Repo, weil ich diese Art Dauer-Issues auch nicht bei mir im Lecture-Repo haben will. Alternativ könnte man die Issues in eine Discussion verwandeln und das als "dynamische" Übungsaufgaben nutzen. In [KI](https://github.com/Artificial-Intelligence-HSBI-TDU/KI-Vorlesung/discussions) nutze ich dieses Jahr Discussions für Ankündigungen und als FAQ. Wenn das gut klappt, könnte das auch ein Weg für die Übungsaufgaben sein.

Muss ich drüber nachdenken.

**Comment by AMatutat** [comment]
@cagix ich würde das hier gerne einmal wieder nach vorne holen.

Außerdem ist bei mir nach der Evaluation noch die Frage aufgekommen, ob wir unsere Features reduzieren sollten.
Wir haben sowas wie `XPSysteme`, `DamageModifiere` etc. was wir effektiv nicht nutzen.  Konzepte für verschiedene Item Typen wie Rüstungen etc. obwohl wir mehr als Tränke trinken nicht implementiert haben.

Der Vorteil an dem `ECS` Konzept ist, dass wir das nicht alles aktiviert haben müssen (hab ich für die Evaluierung auch auf ein minimum gemacht). Aber der Code ist vorhanden und müsste dann auch entsprechend gepflegt werden. 

Ich sehe 3 Möglichkeiten.
1. Alles was "zu viel" ist rauswerfen/löschen. Wir brauchen das fürs Dungeon nicht und für PM können die Studis das selber machen
2. Den Code aus den "aktiven" Branch rausnehmen und irgendwo als "depricated" Ideen-Sammlung festhalten. 
3. Code behalten und Pflegen


Finde Variante 1 nicht uninteressant.

**Comment by cagix** [comment]
@AMatutat Ich sehe den Charme von (1) - für den Dungeon ist dann nur noch das wirklich benötigte Featureset da und muss weiter gepflegt werden, und für PM (aka Prog II) haben die Studis mehr Möglichkeiten zum selber machen.

Aber ich sehe auch, wieviel Projektzeit in diese ganzen nun überflüssigen Features geflossen ist, und mir blutet das Herz, das jetzt einfach wegzuwerfen. Aber ich sehe auch, dass das am Ende irgendwer benutzen und maintainen müsste und dass wir damit auch den PM-Studis Möglichkeiten "rauben". 

Hmmm. 

(2) ist definitiv nicht gut - dann können wir die Features auch gleich begraben (aka löschen). Letztlich kann sich ja jeder vom letzten Commit, wo die Sachen noch im `master` waren, einen Branch rauszweigen bei Bedarf. Nur wird so ein Hilfsbranch von uns eben einfach nur schnell veralten, d.h. das können wir dann auch gleich löschen.

(3) wäre aus Sicht der versenkten Arbeitszeit sinnvoll. Aber es kostet auch in Zukunft mehr Zeit und die Studis müssen drumherum arbeiten. 

Sollten wir das im nächsten Meeting besprechen? Ich tendiere im Moment zu (1), aber ich würde auch gern sehen, was BC dazu denkt.

**Comment by AMatutat** [comment]
> Aber ich sehe auch, wieviel Projektzeit in diese ganzen nun überflüssigen Features geflossen ist, und mir blutet das Herz, das jetzt einfach wegzuwerfen. 

Nicht nur dir, aber dass ist halt eine parade Beispiel der Sunken cost fallacy

> (2) ist definitiv nicht gut -

Ich denke löschen ist schon the way to go, aber vorher ein GitHub Label an die stelle packen. Dann hat man quasi klar gemacht "das ist veraltet", den code sauber und man hat noch relativ gut zugriff auf die Ideen

> Sollten wir das im nächsten Meeting besprechen? Ich tendiere im Moment zu (1), aber ich würde auch gern sehen, was BC dazu denkt.

können wir machen.

**Comment by cagix** [comment]
> > Aber ich sehe auch, wieviel Projektzeit in diese ganzen nun überflüssigen Features geflossen ist, und mir blutet das Herz, das jetzt einfach wegzuwerfen.
> 
> Nicht nur dir, aber dass ist halt eine parade Beispiel der Sunken cost fallacy

ist für mich lessons learned #1: wir hätten in den ersten drei monaten (fast) nur über die aufgaben und potentielle umsetzungen (im sinne von konzepten) reden sollen. damit wäre klar gewesen, was wir brauchen (und was nicht). 


> 
> > (2) ist definitiv nicht gut -
> 
> Ich denke löschen ist schon the way to go, aber vorher ein GitHub Label an die stelle packen. Dann hat man quasi klar gemacht "das ist veraltet", den code sauber und man hat noch relativ gut zugriff auf die Ideen

bin ich dabei. ein branch hilft nicht, d.h. löschen+tag (also option 1) ist vermutlich am besten.


> Und weil es ebene im Meeting auch aufgekommen ist: Ich möchte jetzt nicht größere Strukturen fundamental verändern und nochmal Neudenken, eher minimieren wo es geht. Rauswerfen was wirklich weg kann etc.

die frage ist, haben wir irgendwo einen überblick, also welche strukturen brauchen wir für welches feature? 

wenn es doch nochmal irgendwann weitergeht und vielleicht jemand beispielsweise aufgabentypen realisieren möchte, die wir schon mal vorgedacht hatten - dann wäre es ja ganz nett, wenn wir die nötigen+vorhandenen strukturen dafür nicht schon jetzt rausnehmen? (oder zumindest tatsächlich in den docs den hinweis haben: in dem commit/tag findest du die klassen x,y,z, die für aufgabentyp y ganz nett sein könnten?)

**Comment by AMatutat** [comment]
> wenn es doch nochmal irgendwann weitergeht und vielleicht jemand beispielsweise aufgabentypen realisieren möchte, die wir schon mal vorgedacht hatten - dann wäre es ja ganz nett, wenn wir die nötigen+vorhandenen strukturen dafür nicht schon jetzt rausnehmen? (oder zumindest tatsächlich in den docs den hinweis haben: in dem commit/tag findest du die klassen x,y,z, die für aufgabentyp y ganz nett sein könnten?)

Hmm, ich hab jetzt in erster Linie immer an Spiel-Features gedacht. Bei den Projekt-Strukturen sehe ich garnicht so viel "überhang". Die Ersetzungsaufgaben haben wir nicht durch implementiert, aber die Basis ist da und kann dokumentiert und als todo stehen bleiben.

> die frage ist, haben wir irgendwo einen überblick, also welche strukturen brauchen wir für welches feature?

Jaein. Wir wissen zumindest, dass `core` essenziell und `contrib` nice to have ist. Und ich weiß, welche Features/Strukturen aus `contrib` wir für das Dugeon-Projekt brauchen (Items, Hud etc.) Damit kriegen wir die großen "unnützen" Batzen raus.
Ich hab @Lena241 schonmal auf #385 geschickt, sie findet dann noch klein kram. 



Um das "ich hab im Kopf" zumindest mal grob aufzuschreiben
* `XPSystem` + `XPComponent`, HeroUISystem` (das zeigt einfach die gesammelten XP da) kann raus
* `StatsComponent` kann raus
* Das `HealthComponent` und `HealthSystem` würde ich behalten, die verkomplizierung mit `DamageTypen` und `DamageModifier` kann aber raus
* Items: Hier würde ich die abstrakte Klasse `ItemAmor` entfernen, sowie alle konkreten Items die keine implementierte `onUse` Methode haben/nicht für Crafting genutzt werden. Das sollten effektiv alle sein, außer `ItemResourceEgg`, `ItemResourceMushroomRed`,`ItemResourceBerry`, `HealthPotion` und `WaterPotion` 
* LevelGenerator: Vielleicht alle raus, bis auf den Roombased Graphen-Generator. 

(muss man natürlich alles nochmal konkreter anschauen)
Das würde dann unser Code-Base reduzieren, sollte aber problemlos wieder (von Studis) eingebaut werden können (wir schneiden nur Blätter ab, keine Äste)

**Comment by AMatutat** [comment]
Nur um mal das Problem der Warbarkeit in Zahlen auszudrücken:

Gesamt-Projekt (Framework+Dungeon+DSL)
<img width="1221" alt="image" src="https://github.com/Programmiermethoden/Dungeon/assets/32962412/c4307127-a089-4575-9b7b-20e48043dd98">

Nur Framework (`core`+`contrib`:
<img width="1232" alt="image" src="https://github.com/Programmiermethoden/Dungeon/assets/32962412/8993fa8f-a8ca-4eb2-9e07-3e90e31216e3">


Nur `core` 

<img width="1216" alt="image" src="https://github.com/Programmiermethoden/Dungeon/assets/32962412/83edb63a-e06b-4598-810f-499083b270e7">

**Comment by cagix** [comment]
lese ich das korrekt, core hat 15k lines und contrib dann 10k? und contrib brauchen wir komplett nicht? wahnsinn! 

aber war das nicht so, dass core das basisframework ist, was wir so auch für pm einsetzen und contrib die ganzen sachen für das dungeon-projekt enthält? oder liegt der dungeon-kram nochmal woanders? bin grad zu müde, sry 😴

**Comment by AMatutat** [comment]
> lese ich das korrekt, core hat 15k lines und contrib dann 10k? und contrib brauchen wir komplett nicht? wahnsinn!

Komplett nicht stimmt so nicht, dass ist stark kontext abhängig.
Für das Framework (also PM) brauchen wir das nicht.
Für das Dungeon-Projekt (also das lösen der Augaben im Spiel) brauchen wir schon einiges davon. Aber einiges ist einfach "Feature-Creep" 

> aber war das nicht so, dass core das basisframework ist, was wir so auch für pm einsetzen und contrib die ganzen sachen für das dungeon-projekt enthält? oder liegt der dungeon-kram nochmal woanders? bin grad zu müde, sry 😴
> 
> edit: "dungeon" war ja nur eine menge binde-code zw. dsl und framework, oder? d.h. die nötigen spielelemente hätte ich in contrib gesucht.


Genau. Dungeon ist quasi die Anbindung von DSL an Dungeon.

**Comment by AMatutat** [comment]
@cagix 

Thema Issues:
Ich hab mal alle Issues die ich als "eigentlich ist das kein Issue sondern ein Feature request" mit einen neuen label "close?" (ich bin zu doof das label zu verlinken) versehen.

Kannst du ja mal drüberscrollen und dich bei Fragen/Verwirrungen melden

**Comment by AMatutat** [comment]
Ich würde gerne das "Konzept" Label wieder einfügen. Dann könnte man die Ideen, die jetzt nicht mehr umgesetzt wurden (aber auch keine Bugs etc. sind) nochmal als solche markieren. 

ggf. sollten wir dann auch Issues zusammenfassen. Manche Sachen müssten nochmal neu betrachtet werden etc.

Und dann hätte ich nochmal gerne sowas wie ein "clean code" Label, in den ich alles was mit Codestyle und Codestruktur einsortieren möchte.

**Comment by cagix** [comment]
> Thema Issues: Ich hab mal alle Issues die ich als "eigentlich ist das kein Issue sondern ein Feature request" mit einen neuen label "close?" (ich bin zu doof das label zu verlinken) versehen.

warum "close?" und nicht "feature"?  

wenn es wirklich feature-ideen sind, sollte das imho einfach "feature" heissen. 

ich würde dann auch alle anderen labels (insb. "later") entfernen - die machen ja keinen sinn mehr, wenn man nicht mehr so richtig aktiv dran arbeitet.


> 
> Edit: Ich hab auch nochmal alle Issues die ich in irgendeiner Form für erhaltenswert mit "toArchiv" gelabelt. 

das vorgehen finde ich grad verwirrend. entweder du gehst durch die issues und führst erhaltenswerte zusammen bzw. labelst die "richtig" und schließt die mittlerweile obsoleten. aber jetzt einmal drüberzugehen und überall "toArchiv" dranpappen und dann nochmal drüberzugehen ... finde ich irgendwie anstrengend. ich bin kein großer freund von alles-zwei-mal-anfassen.


> Da müsste man dann mal schauen welche Isseus man mergen könnte (wir haben einige zum Thema Testen und Loggen, das wäre für mich ein Issue "Testkonzept" und ein Issue "Loggingkonzept") 

finde ich gut.

> und die bleibenden Issues dann so Dokumentieren, dass man in Zukunft auch versteht was gemeint ist, wo man hingucken muss und was ggf. schon gemachte Erkenntnisse sind.

hmmpf, ja. das hätte eigentlich bei der erstellung schon passieren müssen. 

---

ich sehe also "bug" für bereits gefundene fehler und "feature" für bereits vorhandene ideen. zusätzlich gibt es "thesis" für mögliche projekte/hausarbeiten/abschlussarbeiten. 

vermutlich werden sich die letzten beiden eher überlappen? aber ich will jetzt nicht an jede "popelige" idee ein "thesis" dranpappen. und nach außen für interessierte studis ist "thesis" irgendwie nachvollziehbarer als "feature".

**Comment by cagix** [comment]
> Ich würde gerne das "Konzept" Label wieder einfügen. Dann könnte man die Ideen, die jetzt nicht mehr umgesetzt wurden (aber auch keine Bugs etc. sind) nochmal als solche markieren.

warum nicht "feature"? 

> ggf. sollten wir dann auch Issues zusammenfassen. Manche Sachen müssten nochmal neu betrachtet werden etc.

ja, da waren wir uns oben ja schon einig :)

> 
> Und dann hätte ich nochmal gerne sowas wie ein "clean code" Label, in den ich alles was mit Codestyle und Codestruktur einsortieren möchte.

ist ehrenswert. aber wer soll sich damit jetzt aktiv beschäftigen? der zug ist abgefahren. (und selbst wenn - du kannst im nachgang nicht qualität einfach "drüberstülpen".)

ich denke, ein issue je für "testkonzept", "loggingkonzept" und vielleicht "codestruktur-konzept" macht sinn (aber das sind die issue-titel), gelabelt als "feature".

**Comment by AMatutat** [comment]
Vielleicht nochmal vorab: Mein Ziel ist es, am Ende ein Repo zu haben, mit so wenigen Issues wie möglich (ohne dabei gute und realistische Ideen zu verwerfen), welche so dokumentiert und strukturiert sind, dass man auch in einem Jahr damit arbeiten kann. Ein Repo mit 150 Issues ist kein guter Anfang für ein neues Projekt.


>> Edit: Ich hab auch nochmal alle Issues die ich in irgendeiner Form für erhaltenswert mit "toArchiv" gelabelt.
> das vorgehen finde ich grad verwirrend. entweder du gehst durch die issues und führst erhaltenswerte zusammen bzw. labelst die "richtig" und schließt die mittlerweile obsoleten. aber jetzt einmal drüberzugehen und überall "toArchiv" dranpappen und dann nochmal drüberzugehen ... finde ich irgendwie anstrengend. ich bin kein großer freund von alles-zwei-mal-anfassen.

Ist für mich eine Form der 'Vorsortierung'. Die meisten Issues sagen mir schon etwas, und ich kann relativ schnell einschätzen, ob es sich lohnt, sie zu behalten, oder ob sie eigentlich gelöscht werden können. Das Archivieren selbst ist deutlich zeitintensiver, das wäre dann aber der nächste Schritt, aber nur für Issues die bleiben.

---

>>Ich würde gerne das "Konzept" Label wieder einfügen. Dann könnte man die Ideen, die jetzt nicht mehr umgesetzt wurden (aber auch keine Bugs etc. sind) nochmal als solche markieren.
> warum nicht "feature"?

Feature klingt für mich immer so, als ob etwas Neues hinzugefügt wird. Testing ist für mich jetzt kein Feature. Aber eigentlich ist mir das auch ziemlich egal, wie es genannt wird, also ja, gerne auch das.

> warum "close?" und nicht "feature"?
wenn es wirklich feature-ideen sind, sollte das imho einfach "feature" heissen.

Wir hatten kurz darüber gesprochen, ob wir solche 'Spiel-Feature'-Issues überhaupt haben wollen. Nach meiner Beobachtung bei der Evaluierung scheint mir hier weniger wirklich besser zu sein. Wir sollten nur Features einbauen, die für die Aufgabenszenarien relevant sind (ja, ich weiß, das hast du gleich gesagt). Die meisten der markierten Feature-Issues gehören nicht dazu. Es handelt sich eher um Ideen für Studierende in PM, was sie tun könnten. Die Frage ist also, wollen wir unser Board wirklich damit 'vollpacken'?

>> Und dann hätte ich nochmal gerne sowas wie ein "clean code" Label, in den ich alles was mit Codestyle und Codestruktur einsortieren möchte.

> ist ehrenswert. aber wer soll sich damit jetzt aktiv beschäftigen? der zug ist abgefahren. (und selbst wenn - du kannst im nachgang nicht qualität einfach "drüberstülpen".)

Es geht mir dabei nicht darum, ob sich jetzt noch wer aktiv damit beschäftigt. Aber wir haben einige Issues, die teilweise sehr allgemein sind (z.B. #577) und teilweise bereits konkrete Ideen enthalten (z.B. #660) zum Thema Clean Code/Clean Architecture. Insbesondere die konkreten Ideen würde ich gerne für die Nachwelt festhalten.

Ein separates Label für diese Issues halte ich daher für praktisch, da es (so denke ich zumindest) einem Außenstehenden oder Neuling dabei hilft, die Issues zu kategorisieren. So könnte man sagen, 'Ah, schau mal, das geht um Clean Code oder ähnliches' und müsste sich nicht erst eingehend damit befassen. Ein Überblick ist beim Neu- oder Wiedereinarbeiten wirklich wichtig.

> ich würde dann auch alle anderen labels (insb. "later") entfernen - die machen ja keinen sinn mehr, wenn man nicht mehr so richtig aktiv dran arbeitet.

Genau, das ist jetzt quasi auch ein Teilziel von mir. Was von "later" kann weg und was von "later" sollte man für die Nachwelt dokumentieren. 

>> und die bleibenden Issues dann so Dokumentieren, dass man in Zukunft auch versteht was gemeint ist, wo man hingucken muss und was ggf. schon gemachte Erkenntnisse sind.
> hmmpf, ja. das hätte eigentlich bei der erstellung schon passieren müssen.

Ich glaube, das ist jedoch die Projektrealität. Man erstellt Issues für sich selbst und für die Leute, die direkt davon betroffen sind. Issues immer so ausführlich zu formulieren, dass auch Neueinsteiger klarkommen, ist sehr zeitintensiv.

**Comment by cagix** [comment]
> > > und die bleibenden Issues dann so Dokumentieren, dass man in Zukunft auch versteht was gemeint ist, wo man hingucken muss und was ggf. schon gemachte Erkenntnisse sind.
> > > hmmpf, ja. das hätte eigentlich bei der erstellung schon passieren müssen.
> 
> Ich glaube, das ist jedoch die Projektrealität. Man erstellt Issues für sich selbst und für die Leute, die direkt davon betroffen sind. Issues immer so ausführlich zu formulieren, dass auch Neueinsteiger klarkommen, ist sehr zeitintensiv.

bin ich durchaus bei dir. aber das ist bei uns teilweise sehr extrem in ein "issue für mich selbst" ausgeartet 🤣

**Comment by AMatutat** [comment]
Meine toArchive issues hab ich abgearbeitet.
Labels enfernen wir am Ende.

**Comment by AMatutat** [comment]
Todo @AMatutat  am Donnertag Abend:

- [ ] Teams aufräumen
- [ ] Labels entfernen
- [ ] Milestones schließen
- [ ] Top-Level Codeownership an @cagix übergeben und andere owner entfernen


Todo @malt-r **bis** Donnerstag Abend:
- [ ] Issues schließen.

**Comment by AMatutat** [comment]
Hab mich übrigens selbst rausgebeten

<img width="498" alt="Bildschirmfoto 2023-12-01 um 00 22 45" src="https://github.com/Programmiermethoden/Dungeon/assets/32962412/c44f68a9-c97b-496e-b65e-aaa24dde929e">
