### ISSUE TITLE
[Projekt] Versionen der Tools und Libs hochziehen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#1050]
Sämtliche Versionen hochziehen (aktuelles JDK LTS, möglichst aktuelles Gradle, möglichst aktuelles libGDX, ...).

**Comment by AMatutat** [comment]
@fwatermann Wenn wir das Projekt abschließen, sperren wir dich ja hier im Repo ein:
Das ist eine super: Mach ich wenn alle weg sind Aufgabe für dich.

**Comment by fwatermann** [comment]
Finde ich gut
