### ISSUE TITLE
[DSL] Referenzanalyse globaler Definitionen

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#1055]
Aus #1053 :

Die Referenz auf die global definierten task-Objekte in den ebenfalls global definierten graph-Objekte stellt ein Problem dar, da nicht zuverlässig in jedem Fall garantiert werden kann, dass die task-Definitionen vor der Interpretation der graph-Definition interpretiert (und damit initialisiert) wurden. Als temporärer Fix dafür werden die graph-Definitionen im ersten Durchlauf nur gespeichert und anschließend in einem zweiten Durchlauf interpretiert, um sicher zu stellen, dass alle task-Definitionen interpretiert wurden.
Eine solidere und sauberere Lösung würde erfordern, dass die Abhängigkeiten zwischen allen global definierten Objekten analysiert und die Interpretation der global definierten Objekte entsprechend dieser Abhängigkeiten sortiert wird.

Das sollte umgesetzt werden, hat allerdings keine Prio.

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
