### ISSUE TITLE
[GAME] Grundkonzept der Items überdenken (Item-JSON?)

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#1062]
Items existieren im Dungeon in zwei Zuständen.
1. Als Entität auf dem Boden, die man einsammeln kann.
2. Als Objekt im Inventar (dann sind es keine Entitäten mehr, sondern nur Datentypen).

Die Klasse 'Item' ist "nur" der Datentyp und speichert alle Informationen, die benötigt werden, um ein Item zwischen den Zuständen 1 und 2 wechseln zu lassen, und implementiert Basisfunktionen für das Verhalten beim Aufsammeln, Benutzen und Fallenlassen.

Mit #1056 sind wir von einer Enum-basierten Implementierung auf einen OO-Ansatz gewechselt. Das erlaubte vor allem die bessere Integration der Items und der 'Task', da so eine 'QuestItem'-Klasse erstellt werden konnte, welche ein 'Item' über ein 'TaskContentComponent' mit einem 'Task' verknüpft (Items können Antworten sein).

Ob das wirklich die beste Lösung ist und so beibehalten werden sollte, sollte nochmals genau analysiert werden. Welche Alternativlösungen gibt es?

              > @AMatutat Ich hatte das früher schon mal gesagt, aber das fühlt sich einfach falsch an.

Es gibt eine Klasse Item mit einigen Eigenschaften. Jetzt leitest Du davon zig Subklassen ab, deren einzige Unterscheidung zur Basisklasse eine bestimmte Belegung der Eigenschaften ist. Für mich klingt das so, als ob Du eigentlich eine Enum-Klasse für Item definieren möchtest? Oder eine zentrale Stelle, wo Du Dir beim Start die verschiedenen Items als "Schablonen"-Objekte anlegst und speicherst und davon dann im Spiel bei Bedarf nur noch Kopien anlegst?

Ich kann da eigentlich nur auf mein [Kommentar](https://github.com/Programmiermethoden/Dungeon/issues/923#issuecomment-1663499048) von damals hinweisen. 

Der Enum Ansatz (das ist ja das was wir vorher hatten) hat sich in der Praxis als a) ganz schön unübersichtlich und b) für den Anwendungsfall "Item als Antwort" als ungeeignet (da ich das `TaskContentComponent` nicht in der Item-Information speicher kann) herausgestellt.
Die neue Struktur ermöglicht mir, ein `QuestItem` zu erstellen und darüber das `TaskContentComponent` abzuspeichern. 

Als Enum funktioniert das nicht (außer ich Hacke mir das über Interfaces, generischen Payloads o.ä zusammen).
Auch der Umgang mit den `onUse` Funktionen finde ich jetzt deutlich Einfachher (überschreiben anstelle eines Consumers).

> Oder eine zentrale Stelle, wo Du Dir beim Start die verschiedenen Items als "Schablonen"-Objekte anlegst und speicherst und davon dann im Spiel bei Bedarf nur noch Kopien anlegst?

Vielleicht versteh ich nicht ganz was du damit meinst, aber das klingt etwas nach "OOP vermeiden um OOP zu vermeiden". 

tldr: Richtig 100% Glücklich bin ich damit auch nicht, aber es ist besser als das was wir haben (auch Einfachher zu verstehen für die studis) und funktioniert für unseren Anwendungsfall in der Kombination mit den Tasks.

Ich mach aber mal ein Issue zum Weiterdiskutieren auf.

_Originally posted by @AMatutat in https://github.com/Programmiermethoden/Dungeon/issues/1056#issuecomment-1737542981_

**Comment by cagix** [comment]
> aber das klingt etwas nach "OOP vermeiden um OOP zu vermeiden".

🤣 Der Punkt, wo sich mir die Fingernägel kräuseln: Die ganzen Subklassen haben keine weiteren Eigenschaften oder Spezialisierungen der Basisklasse. Es werden (soweit ich gesehen habe) lediglich die Attribute der Basisklasse gesetzt. Das ist ein typisches Anti-OO-Pattern - Du meinst statt der _Klasse_ `ItemBookRed` eigentlich ein _Objekt_ namens `itemBookRed` (als Instanz von `Item`).

**Comment by AMatutat** [comment]
> > aber das klingt etwas nach "OOP vermeiden um OOP zu vermeiden".
> 
> 🤣 Der Punkt, wo sich mir die Fingernägel kräuseln: Die ganzen Subklassen haben keine weiteren Eigenschaften oder Spezialisierungen der Basisklasse. Es werden (soweit ich gesehen habe) lediglich die Attribute der Basisklasse gesetzt. Das ist ein typisches Anti-OO-Pattern - Du meinst statt der _Klasse_ `ItemBookRed` eigentlich ein _Objekt_ namens `itemBookRed` (als Instanz von `Item`).

Ja... Ich hab erst geschrieben und dann den Code gesehen (direkt die Strafe kassiert) Man müsste sich im zweiten Schritt eigentlich gescheite Obertypen überlegen, welche sich dann in bestimmten Sachen unterscheiden.
"Trank", "Rüstung", "Buch" o.ä

Die Frage ist dann jedoch, wie sich das Crafting damit verhält, für meine Rezepte muss ich schon konkrete Item-Typen kennen (also Stein, Eisen, Ü-Ei). 

Vermutlich ist die Kombination: OOP und Enum sinnvoll. 
Basis-Typen um zwischen den verschiedenen Item-Typen zu unterscheiden (dann hab ich auch mein QuestItem) und dann für jeden Basis-Typ ein Enum mit den Parametern um das Item zu basteln. Dann kann ich beim definieren der Rezepte den Enum-Wert angeben und vergleichen. 



@cagix @Lena241 Ich finde die Bedenken von Carsten sinnvoll und hadere gerade damit, ob ich die lieber vor dem Merge gefixt haben möchte oder als zweiten PR haben will. 

Für Ersteres spricht: Dann haben wir eine saubere Version im Master. 

Für Letzteres spricht, dass die Arbeit jetzt schon gemacht ist und es für unsere Zwecke läuft. Im Dungeon (also das mit dem Task) "warten" wir ja quasi etwas auf die Quest-Items. Wir könnten mit einem Merge also weiterarbeiten, und ein zweiter PR räumt dann auf. Gerade mit meinem Urlaub im Hinterkopf wäre das vielleicht das Beste.

**Comment by AMatutat** [comment]
@Lena241 wir hatten doch mal die Tage darüber gesprochen Items auch über eine JSON definieren zu können.
Wäre das jetzt nicht der Punkt um es zu machen? Im Code brauchen wir dann nur die Item Klassen sowie Ableitungen für Basis-Items (Tränke,Rüstung,Waffen,etc.)

Type-Object undso

**Comment by cagix** [comment]
@AMatutat Ich bin mir nicht wirklich sicher, ob sich das Thema mit den Items so schnell und so einfach auflösen lässt - hier wird noch ein wenig Gehirnschmalz und ne Menge Kaffee nötig sein. Das schwelt ja schon eine ganze Weile vor sich hin. Mir ist beispielsweise nicht klar, ob ich von einem bestimmten Item wirklich mehrere Instanzen brauche oder ob mir nicht die eine Objektreferenz auf dieses eine Item reichen würde? Oder ob Items nicht tatsächlich unterschiedliche Eigenschaften und/oder Verhalten haben können sollen? Oder ob die vorgeschlagenen Ober-Item-Klassen die Lösung bringen? Oder ob und wie man hier sinnvoll mit Enums arbeiten könnte - ein Item könnte ein Enum sein mit verschiedenen Konstanten und Methoden, ein Item könnte aber auch ein Enum-Attribut haben für den Item-Typ? ... 

---

Mit JSON hadere ich immer etwas, zumal wir hier im Dungeon ja bisher noch andere Konfigurationsmechanismen haben. Wenn wir den Weg gehen (sollten), dann müsste die restliche Konfiguration imho auch aus dem Java- und Gradle-Kosmos raus und nach JSON übertragen werden.

**Comment by AMatutat** [comment]
@fwatermann hier könntest du auch mal nach gescheiten Umsetzungsmöglichkeiten schauen. Perfekt wäre es, wenn du uns verschiedene Möglichkeiten mit Pro/Cons zum Auswählen vorbereiten könntest.
