### ISSUE TITLE
[GAME] Falsch platzierte `Entity`.

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#1065]
Während des Integrationstests von #1063 in #1057 ist folgendes Szenario entstanden:

![2023-09-27_18-05](https://github.com/Programmiermethoden/Dungeon/assets/37513253/36f5fdc3-05b0-4245-b952-7092ad157d1d)

Der "Zauberer" steht auf einem `Walltile`, die debuggte Position des `PositionComponent` passt zu dem Walltile.

**Comment by AMatutat** [comment]
Notiz für mich:
Wir hatten das schon grob durch geduggt und die Position ist zumindest richtig (also die Entität steht da wo sie hingestellt wurde). Sie sollte vom `PositionSystem` nur wirklich nicht dort hin gestellt werden.
