### ISSUE TITLE
[DSL] Zugriff auf Member von `AggregateTypeAdapter`-Datentypen

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#1067]
Folgendes Problem:

Die Datentypen, die per `@DSLTypeAdapter` erstellt werden, bekommen die Parameter der Builder-Methode als Member-Symbole. Diese können dann für die Definition eines entsprechenden Values verwendet werden, als Beispiel hier die aktuelle Umsetzung der Builder-Methode für Single Choice Tasks:

``` java
@DSLTypeAdapter(name = "single_choice_task")
public static Task buildQuizFromSingleChoiceTask(  
@DSLTypeMember(name = "description") String description,  
@DSLTypeMember(name = "answers") List<Quiz.Content> answers,  
@DSLTypeMember(name = "correct_answer_index") int correctAnswerIndex
) {
	// builder method implementation
	return taskInstance;
}
```

In der DSL kann dann wie folgt ein neues Single Choice Task Objekt definiert werden:
```
single_choice_task task_1 {
    description: "Welcher Buchstabe ist der erste im Alphabet?",
    answers: ["Z", "a", "A"],
    correct_answer_index: 1
}
```

Um aus der DSL-Definition eine konkrete `Task`-Instanz zu erzeugen, werden die per DSL definierten Werte an die oben abgebildete Builder-Methode übergeben.
Die Membersymbole des `AggregateAdapterType`, der die Builder-Methode oben im DSL-Typsystem abbildet, haben ab diesem Zeitpunkt keine Verbindung mehr zu den Werten in der tatsächlichen `Task`-Instanz.
D. h. folgender DSL-Code kann aktuell nicht wie erwartet interpretiert werden:
```
single_choice_task task_1 {
    description: "Welcher Buchstabe ist der erste im Alphabet?",
    answers: ["Z", "a", "A"],
    correct_answer_index: 1
}

fn get_description(single_choice_task t) -> string {
	// DOES NOT WORK
	return t.description;
}
```
Falls an die Funktion `get_description` das Objekt `task_1` übergeben wird, welches zu dem Zeitpunkt schon ein instanziiertes `Task`-Objekt kapselt, kann nicht per `description` auf die weiter oben definierte `description` zugegriffen werden.

Die Lösung für dieses Problem besteht im Wesentlich daraus, eine `DSLTypeProperty` zu definieren, welche dann wie folgt implementiert werden könnte:

```
@DSLTypeProperty(name = "description", extendedType = Task.class)  
public static class DescriptionProperty implements IDSLTypeProperty<Task, String> {  
public static DescriptionProperty instance = new DescriptionProperty();  
  
private DescriptionProperty() {}  

// ...
  
@Override  
public String get(Task instance) {  
	return instance.taskText();
}
```

Das wesentliche Problem an dieser Umsetzung ist, dass auch eine `IDSLTypeProperty`-Implementierung als Member-Symbol in den entsprechenden Datentyp eingehangen wird, sodass zwei gleichnamige Symbole (`description`) in dem Datentyp enthalten wären.

Daher sollte für `AggregateAdapterType`s die Möglichkeit vorgehesen werden, ein Symbol mit `@DSLTypeMember` (wie bisher in der Deklaration der Builder-Methode) und ein gleichnamiges Symbol mit dem gleichen Datentyp per `DSLTypeProperty`in den `AggregateAdapterType` einzuhängen. Abhängig von der Art des `IMemorySpace`, der im entsprechenden `AggregateValue` verwendet wird (also ob der `AggregateValue` ein instanziiertes `Task`-Objekt kapselt oder nicht), kann unterschieden werden, wie auf den Wert des Members zugegriffen werden soll.

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
