### ISSUE TITLE
StartPlay: Kontakt zu Projekt "Educational Escape Room" festhalten und herstellen

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#1069]
Auf der StartPlay hat sich ein Kontakt zu Frau XYZ von der Uni XYZ ergeben, die grobe Idee war eine gemeinsame Antragstellung im nächsten Freiraum (Verbundantrag).

Bitte das andere Projekt als "related project" festhalten und nach Möglichkeit den Kontakt herstellen. So ein Antrag dauert ... 

TODO: 
- [x] 1. Eintrag als "related project": ~~URL, kurze Beschreibung (2..3 Sätze)~~ Ergänzung zu https://github.com/Programmiermethoden/Dungeon/blob/master/doc/related_work/digi_komp_ass_escape_room.md: Kontakt auf StartPlay
- [x] 2. Person recherchieren und kontaktieren

**Comment by AMatutat** [comment]
Das andere Projekt haben wir tatsächlich schon dokumentiert (Zufälle gibts). 

In der App bin ich grade zu blöd den link zu finden, aber das hat @AKirsch1 im Dungeon repo festgehalten (escape room).

**Comment by AMatutat** [comment]
https://github.com/Programmiermethoden/Dungeon/blob/master/doc/related_work/digi_komp_ass_escape_room.md

Das müsste es sein

**Comment by cagix** [comment]
> https://github.com/Programmiermethoden/Dungeon/blob/master/doc/related_work/digi_komp_ass_escape_room.md
> 
> Das müsste es sein

ja cool. dann bitte dort noch einen satz dazu, dass sich auf der startplay23 ein kontakt zu ... ergeben hat.
