### ISSUE TITLE
StartPlay: Kontakt zu anderen Projekten festhalten

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#1071]
@bcg7 hat eine Karte mit QR-Code von anderen verwandten Projekten. Bitte die URLs hier einmal posten, damit @AMatutat daraus dann Abschnitte in der "Related Work"-Doku erzeugen kann.

**Comment by AMatutat** [comment]
Wenn ich das richtig verstanden habe, kriegen wir noch ein Konferenzband. Da sollten dann wirklich alle Projekte dabei sein.
