### ISSUE TITLE
[Evaluierung] Spielhandbuch schreiben

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#1096]
Für die Evaluierung braucht es eine Anleitung wie das Spiel gespielt wird.

**Comment by AMatutat** [comment]
Da kann man bestimmt was von https://github.com/Programmiermethoden/Dungeon/blob/master/doc/tasks/anleitung_task_test.md verwenden

**Comment by cagix** [comment]
@AMatutat Im Prinzip bin ich bei Dir. Wenn ich aber das Setup sehe, dann ist es vermutlich deutlich effizienter, den Leuten in der PLAY-Gruppe das einmal kurz vor dem Test live zu zeigen und sie das an einem neutralen Beispiel einmal selbst ausprobieren zu lassen. D.h. vielleicht 10 Minuten vor den eigentlichen 30 Minuten für die Einführung plus ein kurzes Ausprobieren. 

Das Handbuch liest so schnell keiner.
