### ISSUE TITLE
[Dungeon] Dungeon Jars auf Evaluierungssystemen nicht lauffähig

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#1105]
Lutz hat drei Systeme für die Evaluation eingerichtet:

- Fedora
- OpenSUSE
- Ubuntu

Auf diesen Systemen ist JDK 17 von Temurin installiert (laut der [Kompatibilitätsliste](https://github.com/Programmiermethoden/Dungeon/wiki/JDK-Kompatibilit%C3%A4t) sollte das funktionieren).

Bei der Ausführung erhält Lutz eine `GLFW_API UNAVAILABLE error GLX version 1.3 required` Ausnahme (das Programm startet, stürzt aber beim Initialisieren von libGDX ab). Lutz behauptet, dass GLX 1.4 installiert ist. Ich konnte auch keinen Code in unserem Projekt finden, der die Version festlegt, daher vermute ich, dass libGDX hier das Problem verursacht.

Ich habe eine Ubuntu-VM lokal eingerichtet und folgende Beobachtungen gemacht:
1. Das Ausführen des Codes ohne Jar (also `gradlew run`) funktioniert ohne Probleme.
2. Beim Ausführen des Codes über die Jar erhalte ich folgende Meldung: ![image](https://github.com/Programmiermethoden/Dungeon/assets/32962412/74862c34-19d8-40dc-90db-291fa7e70b22)

Ich habe noch nicht vollständig verstanden, warum sich das so seltsam verhält. Ein vages, noch ungeklärtes Gefühl sagt mir, dass es möglicherweise an der Virtualisierung liegen könnte. immerhin wird hier über OS Abhängige Schnittstellen auf die Grafikkarte (o.ä) zugegriffen, und wenn das Dungeon jetzt denkt "ich lauf auf Ubuntu, ich verwende dann die Ubunut Schnittstelle", in wirklichkeit läuft da aber Windows oder Mac Hardware? Dagegen spricht, dass der Code außerhalb der Jar läuft....

**Comment by cagix** [comment]
Idee aus dem Gespräch vorhin: Nur unsere Sourcen in das Jar packen, und dieses zusammen mit unserem Gradle starten - das müsste relativ analog zu `gradle run` sein, nur dass unsere Sorucen dann nicht direkt auf der Platte liegen, sondern im Jar stecken.

**Comment by AMatutat** [comment]
Grade von Lutz die bestätigung bekommen das es mit den normalen jars jetzt doch läuft.
Was er gemacht hat, hat er mir **noch** nicht verraten.

**Comment by AMatutat** [comment]
Grade mit Lutz telfoniert:

Für unsere Evaluierung bedeutet das eigentlich nur, das wir nicht über die x2goclient gehen sondern über die Konsole.


Es gab jetzt noch einen Bug beim anzeigen des Inventars (da konnte er die Font nicht finden `FileNotFountException`), aber das sollte wohl nix großes werden.


Lutz wartet jetzt auf mein go und macht uns dann mit der finalen Version 3x Fedora Umgebungen für die Evaluierung fertig.

**Comment by AMatutat** [comment]
Laut Lutz läuft der spaß .

Lokal konnte ich das nicht reproduzieren (also das laufen), aber nach kurzer Absprache mit Carsten scheinen unsere Testsysteme dieses "outdated" Flag `-X` noch zu unterstützen und moderne Systeme (wie unsere lokalen Rechner nicht) .

Naja, für die Evaluierung ist es wichtig, dass es mit unseren Test-Konstrukt läuft. 


Nochmal danke an Lutz

**Comment by cagix** [comment]
hmmm, über "outdated" und "modern" habe ich nix gesagt. ich weiß nur nicht, wie x-forwarding unter macos funktionieren soll ....
