### ISSUE TITLE
[AUFGABEN] Quizfragen: Single-Choice Aufgaben

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#118]
Im Spiel sollen einfache Single-Choice-Aufgaben implementiert werden.
Dabei soll dem Spieler per UI ein Text mit der Fragestellung angezeigt werden und er soll diese Beantworten.
Die Antwort soll zur Bewertung geloggt werden.
Für eine richtige Antwort soll der Spieler mit einem Item belohnt werden.

- Wie kann dies in das Spiel übertragen werden?
  - Klassisch Textbasiert mit Buttons zum Antworten (NPC Dialog, Kampf (vgl RegEx-Monster)).
  - Als Raum-Rätsel: Im Raum befinden sich vier Truhen, welche die jeweiligen Antworten repräsentieren. 
  - Other?

**Comment by AMatutat** [comment]
Wir haben die Konzepte hierfür Ausgearbeitet und in kleinere Issues gepackt.
Das hier ist dann das erstellen einer Vorzeigbaren Aufgabe als Demo.

**Comment by cagix** [comment]
> Other?

Es liegen Dinge im Level herum, die man entweder gezielt aufsammelt (anschauen und entweder liegen lassen oder aufsammeln) oder die man irgendwo (tor, monster, ...) in der richtigen reihenfolge/anzahl droppen muss.

**Comment by AMatutat** [comment]
Dieses Issue stammt noch aus der Konzeptzeit und erfüllt in meinen Augen keinen Zweck mehr. Hat fast etwas Sammel-Issue-Charakter.

Die Konzeptergebnisse lassen sich in https://github.com/Programmiermethoden/Dungeon/tree/master/doc/tasks nachlesen.
