### ISSUE TITLE
Projekt: Globales Project-Board? Organisationen auflösen?

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#1190]
@AMatutat im zuge der diskussion in #1048: hast du zufällig mal gesehen, ob man issues aus verschiedenen name-spaces in einem globalen project-board referenzieren kann? 

ich wollte gern den studis _eine_ url geben, wo sie _alle_ thesis-label finden. aber irgendwie kriege ich immer nur ein project-board pro namespace hin, also in jeder organisation eines und in meinem persönlichen bereich eines. oder ich stelle mich grad nur zu blöd an?

jedenfalls war ich auch schon fast am überlegen, die ganzen vielen organisationen deshalb wieder einzustampfen und die repos alle unter meinen account zurückzuholen - dann könnte ich dort ein thesis-projectboard aufmachen. aber irgendwie sind die organisationen auch ganz nett für die zusammenarbeit. was denkst du? siehst du noch andere lösungen?

Edit: @fwatermann meinte im letzten SHK Meeting eh, dass Webentwicklung voll toll ist :P

**Comment by AMatutat** [comment]
Hmm, hab jetzt auch nix gefunden. Das scheint auf den Namespace begrenzt zu sein. 

>jedenfalls war ich auch schon fast am überlegen, die ganzen vielen organisationen deshalb wieder einzustampfen und die repos alle unter meinen account zurückzuholen - dann könnte ich dort ein thesis-projectboard aufmachen. aber irgendwie sind die organisationen auch ganz nett für die zusammenarbeit. was denkst du? siehst du noch andere lösungen?

Ich finde die Organisationen auch recht praktisch. Grade weil du dann nochmal gezielter Rechte verteilen kannst (will dich nicht immer fragen müssen, wenn ich ein neues repo brauchen). Und sowas wie Teams etc. geht glaub auch nur in Organistationen, oder? 
Ok gut, du könntest eine "Cagix HSBI"-Org machen und alles da rein stecken.... 

 > siehst du noch andere lösungen?

Ich spinne jetzt mal, aber könntest du dir nicht mit deinem Hugo Webseiten krams eine eigene Seite dafür bauen? Und dann holst du dir per API einfach alle `thesis` Issues aus all deinen Organistationen.

**Comment by AMatutat** [comment]
> hmmm. das wäre tatsächlich ne idee: eine große organisation "swlab at campus minden" (oder so), und dort landet einfach alles drin.

Mach nix kaputt, danke

**Comment by cagix** [comment]
> > hmmm. das wäre tatsächlich ne idee: eine große organisation "swlab at campus minden" (oder so), und dort landet einfach alles drin.
> 
> Mach nix kaputt, danke

was soll denn kaputt gehen? ich habe erstmal nur neue ideen :) ... bis zur umsetzung vergehen höchstens drei jahre ;)
