### ISSUE TITLE
[DEMO] Eine Softwaredemo bereitstellen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#1194]
Bevor wir hier zumachen, sollten wir eine kleine Demo bereitstellen.
Dafür brauchen wir nur ein paar neue Fragen (da kann man ja Allgemeinbildungsfragen nehmen) . 

@Programmiermethoden/codrs denkt euch mal jeder eine Single Choice und eine Multiple Choice Frage aus und postet die hier (bitte mit Antwort), dann mach ich uns daraus ein dng File. 

Ich schreib dann noch eine Anleitung und fertig.
Die kann man dann auch immer super für Präsentationen nehmen (ich muss bald auch wieder vor Schülern tanzen).

**Comment by AMatutat** [comment]
## SingleChoice
Was ist die Hauptkomponente der Luft, die wir atmen?

A) Sauerstoff
B) **Stickstoff**
C) Kohlendioxid
D) Wasserstoff

## MultipleChoice 

Welche der folgenden Aussagen über Katzen sind wahr? (Mehrere Antworten möglich)

A) **Katzen sind nachtaktive Tiere.**
B) **Katzen können Farben wie Rot und Grün erkennen.**
C) Katzen haben eine hochentwickelte Geschmackssinn.
D) **Katzen sind von Natur aus Allesfresser.**
E) **Katzen sind in der Lage zu schnurren.**


## Zuordnen
Ordne die Städte den Ländern zu.

Länder:
- Deutschland
- Norwegen
- Italien
- Frankreich

Städte:
- Paris
- Marseille
- Lyon
- Berlin
- München
- Hamburg
- Rom
- Mailand
- Valencia

Lösung: 
Frankreich:
  Paris
  Marseille
  Lyon

Deutschland:
  Berlin
  München
  Hamburg

Italien:
  Rom
  Mailand

Keinen:
    Valencia

**Comment by AMatutat** [comment]
@fwatermann @AHeinisch @Lena241 PING PING PING

**Comment by Lena241** [comment]
## SingleChoice
Welcher Planet ist auch als roter Planet bekannt?

A) Erde
B) Neptun
C) Merkur
D) **Mars**

## MultipleChoice 

Welche der folgenden Zahlen sind Primzahlen? (Mehrere Antworten möglich)

A) **7**
B) 12
C) 15
D) **23**
E) 30


## Zuordnen
Ordne die Tiere ihrer biologischen Klasse zu.

Klasse:
- Säugetiere
- Reptilien
- Amphibien

Tiere:
- Vogelspinne
- Leguan
- Elefant
- Alligator
- Axolotl
- Salamander
- Schildkröte
- Wolf
- Giraffe

Lösung: 
Säugetiere:
- Elefant
- Wolf
- Giraffe

Reptilien:
- Leguan
- Alligator
- Schildkröte

Amphibien:
- Axolotl
- Salamander
  
Keine:
- Vogelspinne

**Comment by fwatermann** [comment]
## SingleChoice
Aus wie vielen Megabyte besteht ein Gigabyte

A) 500
B) 1200
C) 1024
D) **1000**

## MultipleChoice 

Welches sind Bundesländer von Deutschland?

A) **Nordrhein-Westfalen**
B) Mallorca
C) **Berlin**
D) Düsseldorf
E) Die Niederlande


## Zuordnen
Ordne die Folgenden Komponenten der richten Kategorie zu:

Kategorie:
- Hardware
- Software
- Peripherie

Komponenten:
- Central Processing Unit (CPU)
- Betriebssystem
- Tastatur
- Graphics Processing Unit (GPU)
- Random Access Memory (RAM)
- Windows
- Maus
- Bildschirm
- Powerpoint
- Mac OS

Lösung: 
- Hardware:
	- Central Processing Unit (CPU)
	- Graphics Processing Unit (GPU)
	- Random Access Memory (RAM)
- Software:
	- Betriebssystem
	- Windows
	- Powerpoint
	- Mac OS
-Peripherie:
	- Maus
	- Bildschirm
	- Tastatur
