### ISSUE TITLE
[AUFGABEN] Quizfragen: Lückentext-Aufgaben

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#120]
Im Spiel sollen einfache Lückentext-Aufgaben implementiert werden.
Dabei soll dem Spieler per UI ein Text mit der Fragestellung angezeigt werden und er soll diese Beantworten.
Die Antwort soll zur Bewertung geloggt werden.
Für eine richtige Antwort soll der Spieler mit einem Item belohnt werden.

Wie geht man mit "alternativen" Antworten um? 

- Wie kann dies in das Spiel übertragen werden?
  - Klassisch Textbasiert mit Eingabefeld zum Antworten (NPC Dialog, Kampf (vgl RegEx-Monster)).
  - Other?

**Comment by AMatutat** [comment]
Wir haben die Konzepte hierfür Ausgearbeitet und in kleinere Issues gepackt.
Das hier ist dann das erstellen einer Vorzeigbaren Aufgabe als Demo.

**Comment by cagix** [comment]
>  Other?

siehe https://github.com/Programmiermethoden/Dungeon/issues/118#issuecomment-1417874032

**Comment by AMatutat** [comment]
Dieses Issue stammt noch aus der Konzeptzeit und erfüllt in meinen Augen keinen Zweck mehr. Hat fast etwas Sammel-Issue-Charakter.

Die Konzeptergebnisse lassen sich in https://github.com/Programmiermethoden/Dungeon/tree/master/doc/tasks nachlesen.
