### ISSUE TITLE
[Projekt] `blockly` Struktur Projektweit verwenden

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#1204]
[Blockly](https://github.com/Programmiermethoden/Dungeon/tree/master/blockly) hat sowohl eine eigene `.gitignore` als auch einen eigenen `./doc` Ordner im Projektvereichnis.

Für `Dungeon/DSL` und `game` haben wir das ganze auf Top-Level Ebene gelegt. Ich finde die Struktur von `blockly` dafür eigentlich ganz sexy. Dann weiß ich genau, wozu der ganze spaß gehört.

**Comment by cagix** [comment]
gitignore: ich bin ein großer freund einer zentrale definition. d.h. ich würde gern eine zentrale .gitignore für alle unterprojekte haben, und gegebenenfalls ergänzende unterdefinitionen. @AMatutat weisst du zufällig, ob die sich addieren oder gegenseitig überschreiben (also eine  .gitignore top-level und eine weitere in einem unterprojekt: gilt dann im unterprojekt die summe der regeln oder nur die definition aus dem unterprojekt?).

doc: es klingt irgendwie logisch und sinnvoll, die docs in jedem unterprojekt zu pflegen. im top-level `doc` wäre dann nur noch der einstieg plus eine verlinkung auf die unterprojekte?

**Comment by AMatutat** [comment]
> gitignore: ich bin ein großer freund einer zentrale definition. d.h. ich würde gern eine zentrale .gitignore für alle unterprojekte haben, und gegebenenfalls ergänzende unterdefinitionen. @AMatutat weisst du zufällig, ob die sich addieren oder gegenseitig überschreiben (also eine .gitignore top-level und eine weitere in einem unterprojekt: gilt dann im unterprojekt die summe der regeln oder nur die definition aus dem unterprojekt?).

Keine Ahnung, aber das lässt sich rausfinden. Ich meld mich

>  im top-level doc wäre dann nur noch der einstieg plus eine verlinkung auf die unterprojekte?

Das würde ich in die top level Readme packen.

**Comment by AMatutat** [comment]
> gitignore: ich bin ein großer freund einer zentrale definition. d.h. ich würde gern eine zentrale .gitignore für alle unterprojekte haben, und gegebenenfalls ergänzende unterdefinitionen. @AMatutat weisst du zufällig, ob die sich addieren oder gegenseitig überschreiben (also eine .gitignore top-level und eine weitere in einem unterprojekt: gilt dann im unterprojekt die summe der regeln oder nur die definition aus dem unterprojekt?)

Hmm also das Internet sagt, die addieren sich "auf", so wie man erwartet. Ich habe aber keinen eintrag in der Dokumentation gefunden, nur ein haufen Foren Beiträge.

**Comment by cagix** [comment]
> > im top-level doc wäre dann nur noch der einstieg plus eine verlinkung auf die unterprojekte?
> 
> Das würde ich in die top level Readme packen.

die frage ist, ob man ein top-level `doc/` braucht. wenn da nur ein readme mit links auf die projekte drin ist, kann das auch mit ins projekt-readme.

aber wenn wir ein top-level `doc/` haben, könnte man dort (a) related work, (b) manuals und (c) ??? unterbringen.

**Comment by AMatutat** [comment]
> aber wenn wir ein top-level doc/ haben, könnte man dort (a) related work, (b) manuals, (c) das doc/readme.md (how-to) und (d) ??? unterbringen.

good point

**Comment by AMatutat** [comment]
Wir hatten im MEeting drüber gesprochen
- doc in jedes Projektverzeichnis sperat
- in top level doc dann sowas wie related work
- `.gitignore` im global scope behalten und nur unterfiles, wenn es berechtigte Gründe gibt
- top level readme stellt kurz die Projekte etc. vor und verlinkt dann auf die Readmes der einzelnen Projektbausteine
