### ISSUE TITLE
[GAME] executeWhenCoolDownExpired Test schlägt random in Pipelines fehl und blockiert Merges

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#1220]
`contrib.utils.components.skill.SkillTest > executeWhenCoolDownExpired FAILED
    java.lang.AssertionError at SkillTest.java:57`

Aus [Pipeline-Run](https://github.com/Programmiermethoden/Dungeon/actions/runs/6914134843/job/18811780927)

**Comment by AMatutat** [comment]
@AHeinisch ich gibs auf.... ich hab jetzt nochmal an diesen Test rumgebastelt, die Abfragen geändert etc.....

Wenn du magst kannst du nochmal gucken, sonst  bleibt das für die Zukunft offen.
Ich versteh das nit mehr
