### ISSUE TITLE
[CODE-STYLE] Tooling für Clean-Code und Code-Style Konfigurieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#1226]
Wir haben eine grundlegende Konfiguration für Spotless, ~~Spotbugs~~ und ~~Checkstyle~~, wobei wir (bis auf Spotless) diese weitgehend ignorieren. Einige Einstellungen sind teilweise nicht optimal für unseren Anwendungsfall geeignet (beispielsweise hat ein Framework mehr Methoden pro Klasse, um bessere API-Zugriffe zu ermöglichen).

Es wäre sinnvoll, sich jetzt die Zeit zu nehmen und geeignete Parameter für diese Tools zu überlegen. Möglicherweise gibt es auch bessere oder zusätzliche Tools, die wir in Betracht ziehen können.

---

Edit: Checkstyle ist für immer verbannt (#1316, #1318). Die kriegen ihre eigene Konfiguration nicht in den Griff (vgl. https://github.com/checkstyle/checkstyle/issues/14123 und https://github.com/checkstyle/checkstyle/issues/14211). Davon abgesehen: Wer möchte im Jahr 2024 immer noch unübersichtliche XML-Konfigurationsfiles manuell editieren?!

Edit: SpotBugs ist ganz nett, um typische Anti-Pattern zu finden bzw. gar nicht erst einzubauen. Allerdings wurde während der gesamten aktiven Projektentwicklung nicht darauf geachtet, und wer soll das jetzt nachträglich alles gerade ziehen?! #1320 entfernt SpotBugs aus der Konfiguration.

Edit: Damit bleibt nur noch Spotless für die Formatierung übrig. Bzgl. der Einstellungen (Google-Style vs. AOSP-Style) ist #944 offen.

**Comment by cagix** [comment]
hier gibts nicht mehr zu tun.
