### ISSUE TITLE
[GAME] testUpdateWithoutPoisitionComponent and testUpdateWithoutAnimationComponent fail every second try

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#124]
Reproduction steps:
1. call `gradle test`
2. if the first try succeeds, call `gradle test` again

#Time:4

**Comment by AMatutat** [comment]
0_o?

**Comment by AMatutat** [comment]
könnte sich mit #131 "von selbst" erledigen.

**Comment by AMatutat** [comment]
`testUpdateWithoutPoisitionComponent` ist mit #180 gefixt. 


Zum Zeitpunkt an dem `testUpdateWithoutAnimationComponen` aufgerufen wird, gibt es zwei entities in der `ECS.entities` Liste. Das ist eines zuviel. Eines davon, hat auch das Animation Component, läuft daher in die Logik des DrawSystems, dort wird dann (aufgrund des fehlenden PositionComponents) ein NullPointer geworfen
