### ISSUE TITLE
[GAME] Skill System

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#125]
Das `SkillComponent` ist bereits grob implementiert.
Jetzt muss noch das System implementiert werden.
Das System soll für jede Entität prüfen, welcher Skills ausgeführt werden sollen. 
Wenn ein Skill ausgeführt wird, soll die `currentAnimation` der Entiät auf die `Skill#animation` gewechselt werden. 
*Anmerkung: Der name `animation` in Skill ist verwirrend. Es handelt sich dabei um die castanimation. Bitte umbenenen*

*Anregung: Irgendwie sollte sichergestellt werden, dass nicht mehrere Skills gleichzeitig ausgeführt werden. Vielleicht sollte man im System nur bis zum ersten aktiven Skill einer Entiät prüfen.* 

#Time:2

**Comment by AMatutat** [comment]
@Lena241 wir sollten auch hier anstelle von Reflection auf Strategy Pattern setzen.

**Comment by cagix** [comment]
Ja, Reflection bitte wirklich nur, wenn es nicht anders geht.

**Comment by AMatutat** [comment]
Frage: Muss das `SkillSystem` die Aktivierung eigentlich wirklich für jede Entität prüfen/machen? 
Hab grade mal drüber nachgedacht und die KI-Gegner führen Skills nur in den Strategien des `AIComponents` durch und das wird vom `AISystem` kontrolliert.
Man könnte sich jetzt ein System überlegen, damit das `AISystem` die Skills markiert und diese dann vom `SkillSystem` ausgeführt werden, aber ich sehe ehrlichgesagt den Grund nicht dafür. Das ist viel Code und Struktur, nur um seltsam die Verantwortlichkeiten zu verschieben.

Daher würde ich folgendes Vorschlagen:

- Die KI führt Ihre Skills in den Strategien der Components aus. Hier muss man sich nur den Umgang mit dem Cooldown überlegen. Gilt für die KI der selbe Cooldown wie für den Spieler? Ich fände einen sepraten Cooldown, der in den Strategien hinterlegt ist, gar nit mal so schlecht. Dann kann ich einen Gegner basteln der ganz langsam oder halt ganz schnell Feuerbälle spuckt.

- Das `KeyboardSystem` übernimmt die Aufgabe, für die Skills der Spieler zu prüfen, ob diese aktiviert werden müssen.
- Das `SkillSystem` macht nix anders, als den aktuellen Cooldown jedes Skills um 1 zu reduzieren. 

Wenn der Cooldown der Skills eh nur für den Helden interessant ist, könnte man die beiden Systeme vielleicht auch mergen und es in `PlayerSystem` umbenennen. Dann hätten wir für alle "nur Spieler bezogenen" Inhalte ein zentrales System. Macht das ganze Lesbarer.

**Comment by cagix** [comment]
> Irgendwie sollte sichergestellt werden, dass nicht mehrere Skills gleichzeitig ausgeführt werden. Vielleicht sollte man im System nur bis zum ersten aktiven Skill einer Entiät prüfen.

Passt nicht in das Component-Schema, aber eine Entität könnte einen Slot "aktiver Skill" haben. Dann braucht man nicht extra suchen.

Alternativ könnten die Skills als Tree organisiert sein, und die Wurzel ist der aktive Skill?

**Comment by cagix** [comment]
> * Die KI führt Ihre Skills in den Strategien der Components aus. Hier muss man sich nur den Umgang mit dem Cooldown überlegen. Gilt für die KI der selbe Cooldown wie für den Spieler? Ich fände einen sepraten Cooldown, der in den Strategien hinterlegt ist, gar nit mal so schlecht. Dann kann ich einen Gegner basteln der ganz langsam oder halt ganz schnell Feuerbälle spuckt.

Das finde ich gut.


> * Das `KeyboardSystem` übernimmt die Aufgabe, für die Skills der Spieler zu prüfen, ob diese aktiviert werden müssen.

Das verstehe ich noch nicht. Das würde doch auch bedeuten, dass das KeyboardSystem auch Bewegung und Hit und sowas mit macht? Müsste das KeyboardSystem nicht die Eingaben irgendwo zentral hinterlegen und die anderen System greifen auf diese Information mit zu?

> * Das `SkillSystem` macht nix anders, als den aktuellen Cooldown jedes Skills um 1 zu reduzieren.

Hmmm. 


Eine andere Frage: Inwieweit unterscheiden sich "KI-Skills" von normalen "Skills"? Ist das nicht immer eine Strategie (mit evtl. Cooldown und anderen Eigenschaften), die ich über das Pattern aktiviere?

**Comment by AMatutat** [comment]
@Lena241   Wenn du hier fertig bist (alles was Skill ist), kann du auch gleich in `doc/ecs/components` und `doc/ecs/systems` deine neue Schöpfung sowohl in den Tabellen eintragen als auch eine entsprechende Datei + Dokumentation anlegen und füllen.
