### ISSUE TITLE
[GAME] externe Assets dynamisch über gradle einbinden

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#1296]
Wir verwenden verschiedene Assets aus externen Quellen (Texturen, Musik, Sounds, etc.). Aktuell haben wir diese alle in unseren Repo integriert, eine bessere Lösung wäre es, diese dynamisch über Gradle einzubinden.

Geht das? Wenn ja, wie? Was müssen wir beachten?
      
---

        > noch viel besser wäre es freilich, das gar nicht erst ins repo einzubinden, sondern per gradle dynamisch runterzuladen.

Ich glaube das ist leichter gesagt als getan. 

Das müsste irgendwie so 
```gradle
task downloadAssets(type: Copy) {
    from 'https://example.com/assets/'
    into 'src/main/resources/assets/'
}
```

gehen, aber im Gegensatz zu Maven Central oder ähnlichen Abhängigkeiten kannst du nicht wirklich sicherstellen, dass der Download-Link auch in Zukunft noch funktioniert. Ich glaube, man macht sich da nur mehr Probleme damit.

Mal davon abgesehen, dass man dann auch von der Ordnerstruktur der Quellen Abhängig ist (das nochmal dynamisch auszupacken und in die eigenen Strukturen zu schieben ist m.M.n unmöglich)

_Originally posted by @AMatutat in https://github.com/Programmiermethoden/Dungeon/pull/1285#discussion_r1409992317_

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
