### ISSUE TITLE
Dungeon: Schiebe game/contrib nach dungeon/contrib

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#1306]
Im Moment haben wir im Projekt `game` zwei Packages: `core` und `contrib`. Dabei ist `core` tatsächlich das, was das Game-(Sub-)Projekt ausmacht. `contrib` ist dagegen zusätzlicher "Kram" (Spielelemente und so) und gehört eigentlich zum Dungeon-(Sub-)Projekt, also nach `dungeon`.

Edit: Eventuell gibt es Auswirkungen, so dass diese Verschiebung nicht wirklich möglich oder sinnvoll ist. Bitte erst analysieren und dann lass uns nochmal kurz drüber sprechen, bevor Du aktiv wirst.

**Comment by fwatermann** [comment]
Die Test-Sources liegen noch im falschen Subprojekt... Das kollidiert jetzt mit #1323
