### ISSUE TITLE
[GAME] Optional für missing Components

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#131]
Was bedeutet `null` als Ergebnis? Die Operation hat nicht geklappt, weil es keine `PositionComponent` und/oder `VelocityComponent` gab? Wäre das nicht die Stelle, eine passende Exception auszulösen (dito in `PositionComponent` und `VelocityComponent`)? Dann braucht der Aufrufer nicht die ganzen `if (wuppie != null) { ...} else {return null;}` ... (das "Pattern" taucht ganz schön häufig auf)

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/128#discussion_r1073873714_

und fortlaufend 

#Time:6

**Comment by cagix** [comment]
Insbesondere könnte das so aussehen (Skizze):

```java
public class Entity {
    public Optional<Component> getComponent(String name) {
        return Optional.ofNullable(components.get(name));
    }
}

PositionComponent pc = (PositionComponent) entity.getComponent(PositionComponent.name).orElseThrow();
```

Die Annahme dabei ist, dass eine Entity keine passende Component zu einem Namen haben darf - in diesem Fall ist die Antwort dann automatisch ein `Optional.empty()`. Der Aufrufer kann dann auf den Inhalt zugreifen, und per `.orElseThrow()` wird bei Abwesenheit von tatsächlichen Werten (also bei `Optional.empty()`) eine entsprechende Exception ausgelöst (== Fehlerzustand, da ja ein Wert erwartet wurde).

Falls eine Entity aber immer eine passende Component haben muss, dann sollte die Exception bereits in der Entity ausgelöst werden.

**Comment by AMatutat** [comment]
> Die Annahme dabei ist, dass es erlaubt ist, dass eine Entity keine passende Component zu einem Namen hat

Annahme richtig und das ist auch ein erlaubter zustand.

**Comment by AMatutat** [comment]
@Lena241 setz bitten den Vorschlag von Carsten um (im PM-Lecture repo sollte auch eine Vorlesung sein, falls Optional noch neu/unbekannt ist). 
.

**Comment by AMatutat** [comment]
Ich glaube ich fände eine `MissingComponentException` (abgeleitet von der `NullPointerException`) recht nett

**Comment by AMatutat** [comment]
@Lena241 ich hätte gerne eine `MissingComponentException` die von `NullPointerException` ableitet und entsprechend beim `orElseThrow();` geworfen wird
