### ISSUE TITLE
Cleanup Gradle Config: Vereinheitliche Definition der Variablen und Dependencies

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#1317]
Das von @AMatutat und @malt-r übernommene [`build.gradle`](https://github.com/Programmiermethoden/Dungeon/blob/master/build.gradle) geht aktuell ziemlich durcheinander:  

- [x] manche Versionen werden separat als Variablen definiert - manche fest im Dependencies-String (#1322), 
- [x] manche Dependencies werden in der Kurzschreibweise definiert - manche in der "Langschreibweise" (#1322, 
- [x] #1339
- [x] #1338
- [x] #1337
- [x] #1336
- [x] #1335
- [x] #1334
- [x] #1333
- [x] #1332

**Comment by tgrothe** [comment]
> * manche Versionen werden separat als Variablen definiert - manche fest im Dependencies-String,

Hallo, ich glaube, die Idee dahinter war, mehrfache gleiche vorkommende Versionsnummern (zum Beispiel `gdxVersion`) an nur einer Stelle zu definieren, um diese gegebenenfalls bei Änderungen nur einmal anpassen zu müssen.

Der Nachteil wäre aber, dass die IDEs (zum Beispiel IntelliJ) neuere Versionen vermutlich nicht automatisch erkennen können.

**Comment by cagix** [comment]
> > * manche Versionen werden separat als Variablen definiert - manche fest im Dependencies-String,
> 
> Hallo, ich glaube, die Idee dahinter war, mehrfache gleiche vorkommende Versionsnummern (zum Beispiel `gdxVersion`) an nur einer Stelle zu definieren, um diese gegebenenfalls bei Änderungen nur einmal anpassen zu müssen.

das hatte ich verstanden. mich stört der "bunte blumenstrauß", also das uneinheitliche vorgehen. 

es erhöht die lesbarkeit und wartbarkeit ungemein, wenn einfach alle versionsnummern einmal an einer zentralen stelle definiert werden ...

**Comment by tgrothe** [comment]
Soll ich versuchen, einige der zuerst genannten Punkte zu bearbeiten?

**Comment by cagix** [comment]
> Soll ich versuchen, einige der zuerst genannten Punkte zu bearbeiten?

@tgrothe das ist ganz lieb, aber letztlich ist das nur ein kleiner punkt unter vielen. ich wollte das ursprünglich in einem pr fixen, aber natürlich kann man das auch schrittweise machen. also tobe dich aus, wenn du dazu lust hast :)

**Comment by tgrothe** [comment]
@cagix ich setze mich mal ran und schaue, ob ich in _einem_ pr _alle_ Punkte bearbeiten kann. das sollte funktionieren. :)

**Comment by cagix** [comment]
> @cagix ich setze mich mal ran und schaue, ob ich in _einem_ pr _alle_ Punkte bearbeiten kann. das sollte funktionieren. :)

wenn ich drüber nachdenke: mach das vielleicht lieber schrittweise.

**Comment by tgrothe** [comment]
> wenn ich drüber nachdenke: mach das vielleicht lieber schrittweise.

das hab ich zu spät gelesen, jetzt sind viele Schritte in einem pr gelandet...
