### ISSUE TITLE
[DSL] Typadapter for simple types

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#133]
Einige Datentypen (bspw. `Animation`) konnen nicht in einen `DSLType` konvertiert werden, da sie bspw. aus dem Framework kommen. Diese Typen müssen allerdings trotzdem aus der DSL heraus erstellbar sein (z.B. für ein `AnimationComponent`). Daher sollte eine "Adapterschicht' geschaffen werden, die z.B. mit einer Builder-Methode eine neue Instanz einer betroffenen Klasse erstellen kann.

Diese Issue bezieht sich auf Datentypen, die mit einem einzelnen Parameter erstellt werden können, was auf DSL Ebene so aussieht (also aus Nutzenden-Sicht nicht von anderne property definitions unterscheidbar ist):

```
game_object my_obj {
    component {
        member_of_adapted_type: "single parameter" 
    }
}
```

**Comment by cagix** [comment]
Das wäre eine gute Gelegenheit, diese libGDX-Typen komplett aus der Dungeon-API zu ziehen?

**Comment by AMatutat** [comment]
'Animation' kommt aus dem Dungeon Framework und nicht aus libGDX. 
Keine Ahnung ob das einen Unterschied macht.

**Comment by cagix** [comment]
Jetzt bin ich verwirrt :)

@malt-r: 
> Datentypen (bspw. Animation) [...], da sie bspw. aus libGDX kommen

@AMatutat:
> Animation' kommt aus dem Dungeon Framework und nicht aus libGDX

**Comment by malt-r** [comment]
Das war dann ein Fehler von mir, da war ich falsch informiert :eyes:

**Comment by AMatutat** [comment]
Ich denke mal am Problem ändert sich nichts, oder?
Du brauchst vermutlich Zugriff auf den Code um deine Annoations hinzuzufügen, oder?

**Comment by malt-r** [comment]
Ja, das Problem bleibt das Gleiche
