### ISSUE TITLE
[DSL] Type Adapter for aggregate values

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#134]
Like described in #133, some external datatypes are used for members marked with `@DSLTypeMember` (e.g. `Animation`, `Point`). As these types are not defined in the Dungeon project and can not be marked with `@DSLType`, they need to be encapsulated in an adapter layer to be usable in the dsl type system.
This issue targets those types, which require more than one parameter for construction (such as `Point`).

#### Estimated work requirements

- extend grammar for inline definition of aggregate types
- implement creation of aggregate adapter types
- include aggregate adapter types in semantic analysis
- implement instancing for adapted aggregate types

#### Subissues:

- #248 
- #267
- #268

#Time:5

**Comment by cagix** [comment]
@malt-r Die Issues dienen auch der Projektdokumentation. Bitte schreibe deutlich präziser, was hier umgesetzt werden soll - also nicht "einige Datentypen", sondern lass uns teilhaben, welche konkret und was geändert werden soll.

**Comment by malt-r** [comment]
@cagix würde dir die aktualisierte Beschreibung von der Granularität (auch im Hinblick auf nächsten Freitag) ausreichen? Oder soll ich da noch mehr ins Detail gehen?

**Comment by cagix** [comment]
@malt-r Ich sehe eine Beschreibung, die ich allerdings ehrlich gesagt noch nicht verstehe. Ich sehe eine Zeitschätzung. 

Was ich nicht sehe: Hängt dieses Issue von anderen Dingen ab (DSL, Dungeon)? Was bedeutet "_some_ external datatypes", was wäre der Adapter-Layer (strukturell)? Wie sieht eine mögliche Umsetzung aus (wie komplex wird das), wieviele Klassen müssen angepasst werden? Vgl. auch die Diskussion in https://github.com/Programmiermethoden/2022-freiraum-dungeon/issues/62#issuecomment-1400431631.

**Comment by malt-r** [comment]
Got it. 

Falls der Anspruch ist, dass man als Außenstehender allein aus der Beschreibung der Issues das *komplette warum* versteht, sehe ich hier allerdings ehrlich gesagt ein Kosten-Nutzen Probelm bei dem Erstellungs- & Verwaltungsaufwand der Issues.
Ich weiß aber nicht, ob so eine vollständige Erklärung von deiner Seite aus in https://github.com/Programmiermethoden/2022-freiraum-dungeon/issues/62#issuecomment-1400431631 gemeint war. 

Andererseits fällt es mir oft als Entwickler der Features schwer, einzuschätzen, was genau ein Außenstehender benötigt, um das komplett zu verstehen. Und einige implemenntierungsbezogene Punkte sind ja auch beim Erstellen der Issues noch nicht klar, wobei es dafür ja jetzt das 'Konzept'-Label gibt.

Evtl. wäre das jetzt ein Zeitpunkt, an dem wir bereits existierende Strukturen & architektonische Informationen in einem Wiki festhalten sollten, um ggfs. in den Issue-Beschreibungen auf bestehende Informationen im Wiki verweisen zu können und das nicht immer von neuem komplett herzuleiten.

Ansonsten müsste ich jetzt hier komplett erklären, wie der TypeBuilder funktioniert, was `@DSLType` und `@DSLTypeMember` bedeuten, und welche Teile der Adapterschicht bereits existieren (die man übrigens über die verlinkte Issue und den verknüpften gemergten PR findet).

**Comment by AMatutat** [comment]
Diskussion verlagert nach #161

**Comment by malt-r** [comment]
Idee für mögliche Syntax der Konfiguration eines `AggregateValues` eines adaptierten externen Datentyps per DSL-Eingabe (das Field `member` der `Component`-Klasse im nachfolgenden Beispiel).

Beispiel-Datentyp:
```java
import some.external.library.ComplexExternalType;

@DSLType
public class Component {
    @DSLTypeMember ComplexExternalType member;
}

public class ComplexTypeBuilder {
    @DSLTypeAdapter(t=ComplexExternalType.class)
    static public ComplexType buildComplexType(String param1, int param2) {
        return new ComplexType(param1, param2, someOtherParam);
    }
}
```

DSL-Eingabe könnte so aussehen
```
game_object {
    component {
        // member hat einen Datentyp, der nicht mit einem Parameter erzeugt werden kann
        member: complex_external_type {
            param1: "Hello",
            param2: 123
        }
    }
}
```

**Comment by malt-r** [comment]
Fixed with #272
