### ISSUE TITLE
CI Aufsetzen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#14]
Alle PRs in den Master sollten für Spotbugs formatiert sein. 
Sollte sich aus dem PM-Dungeon copy pasten lassen.

**Comment by malt-r** [comment]
@AMatutat ist das mit #58 erledigt?

**Comment by cagix** [comment]
> @AMatutat ist das mit #58 erledigt?

Vermutlich nicht ganz - @AMatutat muss noch in der Github-Oberfläche die Checks definieren/konfigurieren, denke ich.

**Comment by AMatutat** [comment]
Bin noch dran... bisschen konfigurations kram

**Comment by AMatutat** [comment]
done
