### ISSUE TITLE
[GAME] ITransition: SelfDefend

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#142]
Es soll eine konkrete Implementierung des Intefaces `ITransition` geschrieben werden.

Bei der `SelfDefendTransition` wird dann `true` zurückgeliefert, wenn der Held die Entität mindestens einmal angegriffen hat (der Status wechselt also nicht mehr zurück).

#Time:8

**Comment by AHeinisch** [comment]
Ich habe hier nun einmal angefangen und gemerkt vielleicht gibt es ein paar Stolper Steine soll selfDefend immer zu gewissen werden können oder ist hier vielleicht ähnlich wie bei der Kombination VelocityComponent-> PositionComponent auch eine Abhängigkeit vorhanden.

Zwei Varianten, die mir einfallen und auch eigentlich recht ordentlich wären.
a. Hier auf die HealthComponente warten und diese dann nutzen, um zu entscheiden, ob die Entität verletzt wurde. Aktuelles Leben war je kleiner als maximales Leben
b. Hier die HitboxComponente erweitern, damit mehr als eine Strategie für die Kollision angegeben werden kann. Oder halt eine Art Observer Pattern in die Hitbox Komponente, wenn je eine Kollision.

**Comment by AMatutat** [comment]
A) klingt irgendwie am besten

**Comment by AMatutat** [comment]
@AHeinisch Das `HealthComponent` ist jetzt da. Aus meiner sich wäre die Implementierung jetzt:

```
HealthComponent hc = ... (component holen mit diesen Optional kram), wenn es das nicht gibt throw MissingComponentException
return hc.currentHealthPoints<hc.maxHealthPoints
```

**Comment by AHeinisch** [comment]
Ja, so hatte ich es mir auch vorgestellt, dies hatte ich bereits implementiert und Tests für geschrieben. Hatte keinen PR aufgemacht, da ich nochmal drüber nachdenken wollte, ob ich vielleicht doch noch ein oder zwei Tests finde.
