### ISSUE TITLE
[GAME] ITransition: ProtectFriend

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#143]
Es soll eine konkrete Implementierung des Intefaces `ITransition` geschrieben werden.

Bei der `ProtectFriendTransition` wird dann `true` zurückgeliefert, wenn der Held eine bestimmte andere Entität oder mich (eines aus einer Liste?) mindestens einmal angegriffen hat (der Status wechselt also nicht mehr zurück).

#Time:8

**Comment by Pascal378** [comment]
> wenn der Held eine bestimmte andere Entität oder mich (eines aus einer Liste?) mindestens einmal angegriffen hat

Wie darf man hier "oder mich (eines aus einer Liste)" verstehen?

**Comment by AMatutat** [comment]
> Wie darf man hier "oder mich (eines aus einer Liste)" verstehen?

Ist doof formuliert, gebe ich dir recht.
Wenn eine andere Entität aus einer spezifischen Liste oder ich (also die Entität die das `ProtectFriend` implementiert angegriffen wird.
