### ISSUE TITLE
[GAME] ITransition: ProtectTreasure

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#144]
Es soll eine konkrete Implementierung des Intefaces `ITransition` geschrieben werden.

Bei der `ProtectTreasureTransition` wird dann `true` zurückgeliefert, wenn der Held sich einer bestimmten Entität nähert (z.B einer Schatzkiste) (der Status wechselt also nicht mehr zurück).

#Time:4

**Comment by Pascal378** [comment]
Soweit ich das sehe befasst sich aktuell keiner mit dieser Bounty? 

Hätte Lust im nächsten Zyklus mich um die Implementierung der Protect Transitions zu kümmern. Mich verwirrt nur das @cagix die Bounty-Labels entfernt hat, gelten diese weiterhin noch als Bountys die auch Punkte und bei einem erfolgreichen Pull Request auch Bonus-Punkte geben? In der Liste stehen sie ja noch.

**Comment by cagix** [comment]
> Mich verwirrt nur das @cagix die Bounty-Labels entfernt hat, gelten diese weiterhin noch als Bountys die auch Punkte und bei einem erfolgreichen Pull Request auch Bonus-Punkte geben? 

@Pascal378 wir haben die label etwas umstrukturiert. das ist jetzt `bounty:5p` und `bounty:10p` ... d.h. dieses issue ist immer noch eine bounty-aufgabe und macht 5p ...

**Comment by Pascal378** [comment]
> > Mich verwirrt nur das @cagix die Bounty-Labels entfernt hat, gelten diese weiterhin noch als Bountys die auch Punkte und bei einem erfolgreichen Pull Request auch Bonus-Punkte geben?
> 
> @Pascal378 wir haben die label etwas umstrukturiert. das ist jetzt `bounty:5p` und `bounty:10p` ... d.h. dieses issue ist immer noch eine bounty-aufgabe und macht 5p ...

Ah, okay. Danke für die Aufklärung, dann schaue ich mal inwiefern ich da eine Lösung für finde und werde ggf. im nächsten Zyklus mich mit diesen Bounties befassen!
