### ISSUE TITLE
[GAME] Javadoc für VelocityComponent falsch

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#146]
Die Javadoc des cTor vom `VelocityComponent` ist falsch.
Da steht `x` und `y` sind Koordinaten, stimmt aber nicht, dass ist die Geschwindigkeit. 

Und wenn jemand schon die Klasse anpackt: Wir sollten die Attriute umbennenen in `currentXVelocity` und `maxXVelocity` (natürlich auch für y) 

#Time:0.25

**Comment by cagix** [comment]
das mit "current" hat geklappt, das mit "max" finde ich nicht in #177?

**Comment by Lena241** [comment]
Siehe bearbeitetes PR #177

**Comment by cagix** [comment]
> Siehe bearbeiteten Kommentar für PR #177

@Lena241 dann bitte aber auch einen kurzen kommentar hier. 

das ticket stellt den auftrag dar - und irgendwie sieht es seltsam aus, wenn es "erledigt" geschlossen wird, aber dann eben doch nicht so umgesetzt wurde 😀 

hintergrund: wir überlegen, die repos wieder zu mergen. dabei können wir nur die git-trees und die tickets mitnehmen, aber nicht die pr's... d.h. nach dem mergen sehen wir nur noch, was gemacht werden sollte, aber nicht mehr, was tatsächlich gemacht wurde.
