### ISSUE TITLE
[GAME] Level Hitbox

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#149]
Das Hitbox-System muss auf die Levelelemente (Wände, Löcher, Böden(?)) übertragen werden. 

@AHeinisch kannst du hier etwas mehr Kontext geben?

#Time:17

**Comment by AHeinisch** [comment]
Um hier das Problem einfach darzustellen.
Das aktuelle Kollisionssystem kontrolliert die Kollision zwischen allen Entitäten, welche eine Konvexe(Rechteckige) Hitbox besitzen. Das Level kann also auf verschiedene Arten mit einer Hitbox versehen werden:
- Jedes Tile ist eine Entität (bzw. jedes, welches nicht betreten werden kann) und bekommt eine eigene Hitbox.
  - Die Tiles werden mit in game.entities abgelegt und sind im Standardsystem in der Kollision
  - Die Tiles werden im Level als TileCollidables oder so hinterlegt und können extra abgefragt werden
- Das Level bekommt eine oder mehrere non konvexe Hitboxen welche dadurch die Anzahl der einzelnen Entitäten reduziert. Dadurch muss aber eine neue Kollisionsabfrage gebaut werden!
- Das Level bekommt konvexe Hitboxen über mehrere Tiles gehangen, welche einmal beim Erstellen berechnet werden.

Hier darf aber nicht vergessen werden jede der Möglichkeiten hat ihre Schwächen und stärken. In jedem Fall muss aus meiner Sicht nochmal für das Level etwas für die Hitboxen getan werden.

Persönlich würde ich eher zum Jedes Tile hat eine Hitbox und sie liegen extra tendieren. Grund für diese Vermutung ist das hier eigentlich die Kollision mit dem Level oder nicht betretbaren Feldern. Meine Beispiele die, mir einfallen wo, dies der Fall wäre:
- Spieler läuft in der Welt herum
- ein Fernangriff fliegt in eine Richtung
- ein Monster läuft Luftlinie direkt auf den Spieler zu (ohne Pfadfindung) 
Dies klingt für mich eher so, als wäre das eine Aufgabe von entweder einem eigenen System oder eher von irgendeiner Helfer/Tool Klasse

**Comment by AMatutat** [comment]
Die Diskussion ob Tiles auch Entities sind, hat hier auch einfluss drauf, oder?  
#504
