### ISSUE TITLE
[DSL] `Value`-Semantik klären

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#156]
Während der Interpretation speichert der `DSLInterpreter` alle "Werte" als `Value`-Instanz in `MemorySpace`s. Ein `MemorySpace` kann bspw. der Scope einer Funktion sein, in der Variablen als `Value` zusammen mit einem Namen in einer Map gespeichert werden. Der eigentliche Wert wird dabei in einem internen Field der `Value`-Instanz gespeichert. Im Falle eines `int` ist das einfach der Integer-Wert, im Fall eines `AggregateValue` (ein Wert, welcher weitere Werte enthält, denke Record-/Klasseninstanz) wird das gesamte Objekt, welches durch den `AggregateValue` repräsentiert wird, in diesem internen Field gespeichert.

Neben diesen benannten Values, die fest in einem `MemorySpace` gebunden sind, gibt es auch unbenannte Values, die bspw. während der Evaluierung eines Ausdrucks verwendet werden (denke Rückgabewert einer Funktion). 

Das Setzen von `Values` (bspw. die Zuweisung einer Variablen) wird durch die `setValue`-Methode im `DSLInterpreter` realisiert und die Gleichheit von `Value`s wird aktuell durch den Vergleich der `Value`-Objects (also die Standard-Implementierung von `Object::equals`. Die aktuelle Implementierung hält allerdings in einigen Fällen nicht stand. Ein Beispiel:

```
fn (single_choice_task t) -> entity<><> {
  var return_set : entity<><>;
  var entity_set : entity<>;

  var item_entity : entity;
  for task_content answer in t.get_content() {
    // Erstellung eines QuestItems aus einem item_type und einem task_content
    var item : questitem;
    item = build_quest_item(item_type, answer);
    item_entity = create_entity_from_item(item);

    // Hinzufügen des erstellten QuestItems zu entity_set
    entity_set.add(item_entity);
  }
  
  // Rückgabeset zusammenbauen
  return_set.add(entity_set);
  return return_set;
}
```

Das Codebeispiel erzeugt für jeden `task_content`-Wert, der eine Antwort der `single_choice_task` repräsentiert, ein neues `QuestItem` aus einem `item_type` (Definition hier nicht mit abgebildet). Jedes so erstellte Item soll in das `entity_set` hinzugefügt werden. Es entstehen folgende Probleme:
Es wird nur ein `QuestItem`-Value zum Set hinzugefügt, da der Hashcode des `Value`-Objekts `item_entity` immer der gleiche bleibt. Das Object wird nur einmal außerhalb der Schleife angelegt und bleibt daher immer bestehen. Im Set wird außerdem eine Referenz auf das `Value`-Objekt gespeichert, sodass durch die Zuweisung `item_entity = create_entity_from_item` der interne Wert des `Value`-Objects in dem Set überschrieben wird.

Diese Probleme und nicht absehbaren Verhaltensweisen sollten analysiert und behoben werden.

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
