### ISSUE TITLE
[Dokumentation] How to document? 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#161]
@cagix Got it. 

Falls der Anspruch ist, dass man als Außenstehender allein aus der Beschreibung der Issues das *komplette warum* versteht, sehe ich hier allerdings ehrlich gesagt ein Kosten-Nutzen Probelm bei dem Erstellungs- & Verwaltungsaufwand der Issues.
Ich weiß aber nicht, ob so eine vollständige Erklärung von deiner Seite aus in https://github.com/Programmiermethoden/2022-freiraum-dungeon/issues/62#issuecomment-1400431631 gemeint war. 

Andererseits fällt es mir oft als Entwickler der Features schwer, einzuschätzen, was genau ein Außenstehender benötigt, um das komplett zu verstehen. Und einige implemenntierungsbezogene Punkte sind ja auch beim Erstellen der Issues noch nicht klar, wobei es dafür ja jetzt das 'Konzept'-Label gibt.

Evtl. wäre das jetzt ein Zeitpunkt, an dem wir bereits existierende Strukturen & architektonische Informationen in einem Wiki festhalten sollten, um ggfs. in den Issue-Beschreibungen auf bestehende Informationen im Wiki verweisen zu können und das nicht immer von neuem komplett herzuleiten.

Ansonsten müsste ich jetzt hier komplett erklären, wie der TypeBuilder funktioniert, was `@DSLType` und `@DSLTypeMember` bedeuten, und welche Teile der Adapterschicht bereits existieren (die man übrigens über die verlinkte Issue und den verknüpften gemergten PR findet).

_Originally posted by @malt-r in https://github.com/Programmiermethoden/Dungeon/issues/134#issuecomment-1400568662_

**Comment by AMatutat** [comment]
> > Falls der Anspruch ist, dass man als Außenstehender allein aus der Beschreibung der Issues das komplette warum versteht,
> 
> Ich denke, das _komplette Warum_ muss man nicht aus einem Issue verstehen, kann man auch gar nicht :) Das kann ja beliebig komplex werden. Aber dann sollte es eben irgendwo strukturierte Dokumente geben, die den größeren Rahmen definieren und die Konzepte darstellen und Startpunkt/Ziel/Schritte formulieren und wo man im Issue Bezug nehmen kann, etwa auf eine Überschrift verlinken o.ä.
> 
> Dennoch sollte eine Issue-Beschreibung self-contained sein und mir erlauben, den Zweck und Umfang der beabsichtigten Arbeiten zu verstehen, wenn ich die zentralen Dokumente kenne.
> 
> "Konzept-Label": Ich finde das gut: Man schreibt im Issue erstmal eine grobe/vage Idee auf, die dann verfeinert werden muss und pappt entsprechend "Konzept" dran. Die Beschreibung kann man ja später weiter editieren und verfeinern bzw. Sub-Issues abspalten.
> 
> > Evtl. wäre das jetzt ein Zeitpunkt, an dem wir bereits existierende Strukturen & architektonische Informationen in einem Wiki festhalten sollten, um ggfs. in den Issue-Beschreibungen auf bestehende Informationen im Wiki verweisen zu können und das nicht immer von neuem komplett herzuleiten.
> 
> Finde ich eine gute Idee. Ich würde sogar einen Schritt weiter gehen und das nicht in ein Wiki auslagern, sondern in eine "richtige" Dokumentation. Das ist ja eh Wiki-like im Markdown, nur im Gegensatz zum Wiki lebt die Doku direkt im Repo und kommt beim Pull mit auf die Platte. Diese Dokumente müssten das Gesamtkonzept erklären und auch grob formulieren, mit welchen Schritten man ins Ziel kommt (das wird freilich obsolet, sobald alles umgesetzt ist - was eher wieder für ein Wiki spräche).
> 
> > Ansonsten müsste ich jetzt hier komplett erklären, wie der TypeBuilder funktioniert, was @DSLType und @DSLTypeMember bedeuten, und welche Teile der Adapterschicht bereits existieren (die man übrigens über die verlinkte Issue und den verknüpften gemergten PR findet).
> 
> Ich glaube, da sind wir vom Verständnis nah beisammen. Wenn es eine Dokumentation gibt, wo diese Konzepte und der Gesamtaufbau erklärt und formuliert werden, muss man das nicht in den Tickets erklären und kann direkt auf die Doku verweisen vom Ticket aus.
> 
> Und ja, die Tickets verlinken auf die PR und umgekehrt, und das ist auch gut so. Für kleine Details kann man sich (sobald man das Ganze verstanden hat) dann da auch reingraben. Dennoch ist es für mich wertvoll, die Informationen abstrahiert und komprimiert im Issue zu finden: Was soll hier gemacht werden, wo finde ich die Konzepte in der Doku, wo finde ich ggf. eine Diskussion dazu. Und im PR sollte analog kurz beschrieben werden, was durch das Mergen des PRs in den Hauptzweig eingefügt wird - das ist ein wenig wie Pflichten- und Lastenheft ;) ...


_Originally posted by @cagix  in 
https://github.com/Programmiermethoden/Dungeon/issues/134#issuecomment-1400742761

**Comment by AMatutat** [comment]
Malte und ich haben eben nochmal disktuiert/geplant und sind zum folgenden Vorgehen gekommen:




Im Wiki halten wir die **Meilenstein-Ziele** fest.

Meilenstein-Ziele sind die konkreten Ausarbeitungen der Projektziele. 
In jedem Meilenstein-Ziel wird festgehalten:
WAS das Ergebnis ist. 
WARUM es Relevant ist, dieses Ziel zu erreichen um die Projektziele zu erreichen. 

Für jedes Meilenstein-Ziel wird dann ein GitHub-Milestone angelegt. Im GitHub-Milestone werden dann die konkreten Issues angelegt. 

Die **Issues** beschreiben ein konkretes ToDo im Scope von maximal einer SHK Woche (ca 15h). 
In den Issues wird beschrieben WAS konkret gemacht werden muss, um welches Ziel (link to Milestone) zu erreichen. 
Es wird eine Aufwandseinschätzung abgegeben. 
Mit dem Label  SHK, WIMI-Dungeon und/oder WIMI-DSL wird die Verantwortlichkeit angezeigt. 

Aus der Summe der Aufwänden der Issues, der verteilten Verantwortlichkeit und der Wochenstunden lässt sich dann ein ungefährer Zeitaufwand für jedes **Meilenstein-Ziel* festlegen. 

Daraus kann dann ein Projektplan-Zeitstrahl erstellt werden, der die Reihenfolge der Meilensteine anzeigt.
Durch die unterschiedlichen Verantwortlichkeiten, werden Meilensteine auch Parallel bearbeitet. (z.B basteln die SHKs noch an Meilenstein A und die WiMis fangen schon mit Meilenstein B an) 

In den Wöchentlichen Sprint-Meetings verteilen wir dann die Issues an die konkreten Personen und erstellen ein Wochen-Meilenstein, der gibt den schnellen Überblick über das, was jetzt grade bearbeitet wird. 



Zusätzlich erläutern wir den Workflow auch im Wiki. 
Im Wiki wird auch die Dokumentation der Projektstrukturen (UMLs etc.) festgehalten. 



> Finde ich eine gute Idee. Ich würde sogar einen Schritt weiter gehen und das nicht in ein Wiki auslagern, sondern in eine "richtige" Dokumentation. Das ist ja eh Wiki-like im Markdown, nur im Gegensatz zum Wiki lebt die Doku direkt im Repo und kommt beim Pull mit auf die Platte. Diese Dokumente müssten das Gesamtkonzept erklären und auch grob formulieren, mit welchen Schritten man ins Ziel kommt (das wird freilich obsolet, sobald alles umgesetzt ist - was eher wieder für ein Wiki spräche)

a) Du kannst dir das Wiki auch clonen und es so lokal auf der Platte haben. b) Sehen wir die Dokumentation auch als Tool zm Diskussionen schneller abzuwickeln. Link auf die entsprechende Wiki Seite und gut ist. Da wir nunmal überwiegend auf GitHub diskutieren ist das Wiki ein einfacher und optisch gut dargestellter weg.

**Comment by cagix** [comment]
> Meilenstein-Ziele sind die konkreten Ausarbeitungen der Projektziele. [...]
> Für jedes Meilenstein-Ziel wird dann ein GitHub-Milestone angelegt. [...]
> GitHub-Milestone werden dann die konkreten Issues angelegt [...]

Ja, das ist das übliche Verständnis. Haben wir bisher nicht oder nur schlampig gelebt, nehme mich da auch nicht aus. Der Trick dürfte nun "nur" noch sein, die Meilensteine so kompakt zu machen, dass man da nicht ein halbes Jahr dran sitzt und letztlich 90% aller Sachen in einen MS gehen :)

> Die Issues beschreiben ein konkretes ToDo im Scope von maximal einer SHK Woche (ca 15h).
In den Issues wird beschrieben WAS konkret gemacht werden muss, um welches Ziel (link to Milestone) zu erreichen.
Es wird eine Aufwandseinschätzung abgegeben.
Mit dem Label SHK, WIMI-Dungeon und/oder WIMI-DSL wird die Verantwortlichkeit angezeigt.

Erscheint sehr sinnvoll. Bitte achtet darauf, dass Issues "actionable" sind, also direkt umsetzbar. Ansonsten müsste dann das Label "Konzept" dran, weil das eben noch ausgearbeitet wird in diesem Ticket.

> erstellen ein Wochen-Meilenstein

Das finde ich immer noch eine Spitzenidee. Aber GH lässt uns da im Stich, habe ich eben ausprobiert: Man kann ein Ticket immer nur genau einem MS zuweisen. 

Unter der Annahme, dass ein offenes Ticket erst im Sprint einer Person zugewiesen wird und dann in diesem Sprint umgesetzt wird, finde ich das aber nicht so dramatisch. Man kann sich im Projectboard leicht einen Filter einrichten, der alle offenen+zugewiesenen Tickets anzeigt - das wären dann genau die der aktuellen Woche.

---

Wiki vs. Dokumentation:

Mir ist bekannt, dass man ein Wiki auch clonen kann :)  Dennoch ist es nicht dasselbe wie eine im Repo selbst verankerte Dokumentation, die dann (je nach Bedarf) auch mit den inhaltlichen Dingen parallel mitgezogen wird - ein PR, der beispielsweise etwas an der API ändert, sollte auch die Beschreibung dann gleich mit nachziehen (müssen).

Ich sehe das Wiki eher für Dinge wie Workflow-Beschreibungen und sowas wie eine Liste mit offenen Punkten o.ä. - also Dinge, die sich schnell ändern und die man nicht in der Git-Historie haben will.

Sowas wie das Konzept, die APIs und Strukturen oder das Zusammenspiel mit der DSL möchte ich aber bitte in der Doku im Projekt (Repo) sehen und nicht im Wiki. Das driftet sonst komplett auseinander. Außerdem hat man so auch beim Zurücksetzen auf einen Zwischenstand auch immer gleich die passende Doku parat.

D.h. wenn man das jetzt weiter denkt, umfasst ein PR den geänderten Code, die Änderungen an der Dokumentation (im Repo) und natürlich auch Javadoc und angepasste/neue Tests (sofern anwendbar). Ich möchte eigentlich keine Tickets mehr sehen, die eine Dokumentation nachfordern o.ä. - wobei mir klar ist, dass wir das für die "alten" Sachen tatsächlich noch machen müssen.

Wenn ihr zeitnah mal eine Rumpfdokumenation aufsetzt und mergt, dann kann man das auch so leben. Wichtig ist, dass die nötigen Dokumente und auch die vermutlichen Strukturen (Überschriften) schon gleich angelegt werden, weil Git sonst recht schnell nen Koller kriegt.

**Comment by AMatutat** [comment]
Find ich gut. 
@malt-r du?

**Comment by cagix** [comment]
> Ich hab das Wiki mal aufgesetzt: https://github.com/Programmiermethoden/Dungeon/wiki Da fehlen jetzt natürlich die Inhalte, aber die Struktur wird klar.
> 
> <img alt="image" width="558" src="https://user-images.githubusercontent.com/32962412/214315936-9ffc5344-3634-4a1a-a331-66e95f47c6c9.png">
> 
> Ja, zwei Milestones kann ein Issue leider nicht haben.

siehe letzter Kommentar: Beim Wiki gehe ich nicht komplett mit. Es gibt für mich Dinge, die gehören in ein Wiki, und es gibt Dinge, die gehören in eine Dokumentation :) ... Wir müssen nur noch sauber definieren, was genau was ist ...

**Comment by malt-r** [comment]
> Find ich gut. @malt-r du?
> 
> > Ich möchte eigentlich keine Tickets mehr sehen, die eine Dokumentation nachfordern o.ä. -
> 
> Ja, bin ich voll bei dir. Projektrealität haut nur manchmal dazwischen. Für mich beinhaltet jedes Issue auch impliziet doc+tests

Find ich grundsätzlich auch gut. 

@cagix Ich würde allerdings trotzdem gerne Tickets für die Doku anlegen, weil die (vollständige) Doku der DSL, die noch nachzuholen ist, nicht trivial ist. Und das sollte für mich eigentlich auf der gleichen Ebene stattfinden wie die 'inhaltliche' Arbeit (also Erweiterung der Codebasis) und dementsprechend auch in Tickets nachgehalten werden können.

**Comment by cagix** [comment]
> @cagix Ich würde allerdings trotzdem gerne Tickets für die Doku anlegen, weil die (vollständige) Doku der DSL, die noch nachzuholen ist, nicht trivial ist. Und das sollte für mich eigentlich auf der gleichen Ebene stattfinden wie die 'inhaltliche' Arbeit (also Erweiterung der Codebasis) und dementsprechend auch in Tickets nachgehalten werden können.

@malt-r Die nachzuholenden Dinge sind natürlich eine Sache für sich, das ist halt so und geht nicht (mehr) anders. Aber wäre es nicht auch für Dich denkbar, wenn Du beispielsweise in einem bestimmten PR etwas in die DSL einbaust, dass Du in diesem PR auch gleich das entsprechende Schnipselchen Dokumentation mit drin hast? Alles andere würde wieder zu einer Divergenz führen, und im Moment sehe ich noch nicht so richtig, warum man die Doku separat mergen wollen würde?

Wenn es Dir um eine "grobe" Doku vs. "hübsch ausformulierte" Doku geht: Da bin ich dabei. Ein PR, der Dinge im Code ändert/hinzufügt, sollte auch immer ein Schnipsel Doku dabei haben. Aber das muss noch nicht für den Druck aufbereitet sein - dafür kann man aus meiner Sicht tatsächlich separate Tickets machen. Aber die Basis sollte immer in den PR gleich mitkommen.

Oder ich habs noch nicht verstanden :) ... Dann nochmal nachsetzen.

**Comment by malt-r** [comment]
> Aber wäre es nicht auch für Dich denkbar, wenn Du beispielsweise in einem bestimmten PR etwas in die DSL einbaust, dass Du in diesem PR auch gleich das entsprechende Schnipselchen Dokumentation mit drin hast? Alles andere würde wieder zu einer Divergenz führen, und im Moment sehe ich noch nicht so richtig, warum man die Doku separat mergen wollen würde?

Mein Kommentar bezog sich jetzt nur auf die nachzuholenden Dinge. 

Für die neuen Inhalte bin ich da 100%ig bei dir, da sollte einfach der geänderte Dokuinhalt mit im gleichen PR wie die Änderungen an der Codebasis enthalten sein, damit man da immer eine direkte Beziehung hat :)

**Comment by cagix** [comment]
ah, verstehe :) 

dann haben wir jetzt das gleiche verständnis, aber die details (wo hört wiki auf und wo geht doku los) müssen noch definiert werden.

da (wenn ich das richtig verstanden habe) noch nennenswert doku erstellt werden muss: wäre es eine idee, die nachzuholenden sachen doch erstmal im wiki zu sammeln und dann zu sichten und die non-wiki-sachen in die doku zu verschieben? das macht aber vielleicht probleme, wenn man _parallel_ für die neuen pr's dann schon den oben beschriebenen ansatz fährt?

**Comment by AMatutat** [comment]
Ich habe die Ziele im Wiki hinterlegt und schonmal mit etwas Inhalt gefüllt. Einige Ziele sind konzeptionell weiter, da steht dann entsprechend mehr andere sind noch nicht so weit (z.b Petri Netze) da steht dann entsprechend weniger

**Comment by AMatutat** [comment]
@cagix @malt-r Ich bin mir bei der zeitangabe in kombination mit dem Konzept-Label noch nicht so sicher.

Die Idee hinter dem Label ist ja, anzugeben dass hier noch ein Konzept erarbeitet werden muss, aus dem sich dann die richtigen ToDo-Issues ergeben. 
Die Zeitangabe ist einmal für die Verteilung der Aufgaben pro Woche hilfreich (nur bei den kleinen "todo"-Issues). 
Auf der anderen Seite dient es aber auch der Einschätzung des Meilenstein Aufwands.

Wenn ich jetzt ein Konzept-Issue habe, welche Zeit schreib ich da ran? Die Zeit die ich für das erstellen des Konzeptes brauche oder die Zeit, die ich für die Erstellung + Umsetzung des Konzeptes brauche. 
Ersteres wäre Einheitlich und auch gut einschätzbar, dann kann ich aber den Meilenstein Aufwand nicht abschätzen. 
Zweiteres würde mir den Meilensteinaufwand anzeigen, aber a) ist die Schätzung des Aufwands ohne Konzept auch einfach ein Schuss ins blaue  und b) kann es verwirren, wenn hier plötzlich so große Zeiten stehen.

**Comment by cagix** [comment]
@AMatutat Klingt für mich so, als ob der erste Vorschlag (Zeitschätzung gilt nur für das Erarbeiten des eigentlichen Konzepts) der einzig praktikable wäre, oder? Wenn man die Umsetzung mitschätzen müsste, obwohl man eigentlich keine Anhaltspunkte hat, dann hilft das ja nicht wirklich.

Und: Die Konzepte müssen irgendwann in naher Zukunft aus dem Backlog "gepflückt" werden und eben bearbeitet werden. Daraus ergeben sich dann eine Reihe von Folgeaktionen, die dann aber ihrerseits im Sprint geplant werden (oder auch nicht, wenn wir übereinkommen, das nicht umzusetzen).

**Comment by malt-r** [comment]
Sehe ich genauso. Eine Aufwandsabschätzung der Umsetzung ohne (oder mit nur teilweise ausgearbeitetem) Konzept ergibt für mich wenig Sinn.

**Comment by cagix** [comment]
> Wie in #203 angesprochen, würden wir die technische Doku in einen `doc` Ordner auf oberster Ebene im Projekt verlegen. @AMatutat und ich haben gerade diskutiert, ob wir das als einfache Markdown-Sammlung aufziehen wollen, oder ob wir z.B. das [docsify](https://docsify.js.org/#/) Tool verwenden, um (zumindest lokal) eine Doku zur Verfügung zu stellen, durch die man sich dann durchklicken kann (ohne von einem externen Markdown-Viewer abhängig zu sein).
> 
> Man könnte dann längerfristig auch darüber nachdenken, ob man die so erzeugte Doku über GH-Pages zur Verfügung stellt, wobei es das laut Andre wohl einige Fallstricke hinsichtlich Impressum etc. gibt. Ich würde das hier einfach mal als TOP ins nächste Meeting mitnehmen.

@malt-r @AMatutat Stop. Es wird ein Ordner mit einer Markdown-Sammlung. Nix weiter.

**Comment by malt-r** [comment]
Juti, das ist natürlich deutlich einfacher :+1:

**Comment by AMatutat** [comment]
@cagix @malt-r eigentlich kann hier zu, oder? Wie wissen wir ja. Jetzt muss nur noch gemacht werden

**Comment by cagix** [comment]
@AMatutat Ja, aus meiner Sicht kann das zu. Es ist alles gesagt/entschieden. 

Lustigerweise habe ich heute früh genau dieses Issue gesucht und nicht gefunden (war ein Gedange wg. Verlinkung von Meilensteinen im Wiki und weil die Meilensteine aktuell ja schrittweise leerlaufen und das dann mit der Verlinkung im Wiki nicht mehr sooo sinnvoll ist dann). => @AMatutat Kannst Du bitte einen möglichst sichtbaren Wiki-Eintrag machen, wo Du die hier besprochenen Kernideen nochmal kurz zusammenfasst und auf dieses Issue für tieferes Schmökern verweist? Das würde sehr helfen! Danke :)
