### ISSUE TITLE
[DSL] Document type building and connection between java classes and dsl types

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#170]
The creation of DSL types from java classes by marking them with `@DSLType` is essential for actually using the DSL together with the Dungeon and is the essential connection layer between DSL and Dungeon. It should be documented

#### Requirements

- [x] How does type building work in general
- [x] How does the `TypeBuilder` work
- [x] Which restrictions does type building have
- [x] How are java classes, which can (for different reasons) not be marked with `@DSLType`, made usable in the DSL? 
  - As required e.g. for bringing the `AnimationComponent` into the DSL, as it uses the `Animation`-class, which is externally defined in another project ("PMDungeon") apart from this project ("Dungeon")
- [x] #280
- [x] #282
- [x] #290
- [x] #292

In [Typebuilding](https://github.com/Programmiermethoden/Dungeon/blob/master/doc/dsl/typebuilding.md)

#Time:5

**Comment by malt-r** [comment]
Ich habe ein Sequenzdiagram fürs Typebuilding im [Wiki - DSL:TypeBuilding](https://github.com/Programmiermethoden/Dungeon/wiki/DSL:-Typebuilding#implementierung) hinzugefügt. Und ich bräuchte einmal von euch @cagix und @AMatutat eine Einschätzung, ob das sinnvoll ist, solche Diagramme da einzubauen. Ich finde die eigentlich ganz elegant, um die Beziehungen und Zuständigkeiten von Klassen für einen bestimmten Use-Case darzustellen.

**Comment by cagix** [comment]
> Ich habe ein Sequenzdiagram fürs Typebuilding im [Wiki - DSL:TypeBuilding](https://github.com/Programmiermethoden/Dungeon/wiki/DSL:-Typebuilding#implementierung) hinzugefügt. Und ich bräuchte einmal von euch @cagix und @AMatutat eine Einschätzung, ob das sinnvoll ist, solche Diagramme da einzubauen. Ich finde die eigentlich ganz elegant, um die Beziehungen und Zuständigkeiten von Klassen für einen bestimmten Use-Case darzustellen.

ich begrüße diagramme sogar ausdrücklich! 👍


zwei aspekte:

1. bitte stelle geeignet sicher, dass die diagrammquellen erhalten bleiben. die ganzen konzept-dokumente sind aus meiner sicht sowieso "dokumentation" und gehören ins repo (nicht ins wiki) - bei der gelegenheit kannst du im `docs/`-ordner noch einen `docs/img/`-ordner anlegen und dort sowohl .png als auch die quellen ablegen.
2. bitte einigt euch auf ein tool, etwa umlet oder drawio ...

wenn ich die doku im wiki sehe mit den todos für die geplanten links, dann wäre meine dringende bitte, die aufteilung jetzt schon zu machen und nicht erst am ende.

**Comment by malt-r** [comment]
1. Siehe #203
2. Ich habe vor kurzem mit @AMatutat darüber gesprochen, und er sprach von [umletino](http://www.umlet.com/umletino/umletino.html), was ja quasi umlet im browser ist, also auch `.uxf` verwendet. Mir wäre das ganz lieb, wenn wir uns auf `.uxf` einigen, da man so nicht von draw.io abhängig ist, sondern im Zweifel immer auf umlet als Standalone Programm setzen kann.

**Comment by cagix** [comment]
passt.

**Comment by AMatutat** [comment]
> Ich habe vor kurzem mit @AMatutat darüber gesprochen, und er sprach von [umletino](http://www.umlet.com/umletino/umletino.html), was ja quasi umlet im browser ist, also auch .uxf verwendet. Mir wäre das ganz lieb, wenn wir uns auf .uxf einigen, da man so nicht von draw.io abhängig ist, sondern im Zweifel immer auf umlet als Standalone Programm setzen kann.

Das hat auch nen super VS-Code Plugin. Da werden die exportieren Bilder auch nicht so schwammig. Keine Ahnung was die auf der Webseite falsch machen

**Comment by cagix** [comment]
> > Ich habe vor kurzem mit @AMatutat darüber gesprochen, und er sprach von [umletino](http://www.umlet.com/umletino/umletino.html), was ja quasi umlet im browser ist, also auch .uxf verwendet. Mir wäre das ganz lieb, wenn wir uns auf .uxf einigen, da man so nicht von draw.io abhängig ist, sondern im Zweifel immer auf umlet als Standalone Programm setzen kann.
> 
> Das hat auch nen super VS-Code Plugin. Da werden die exportieren Bilder auch nicht so schwammig. Keine Ahnung was die auf der Webseite falsch machen

Guter Hinweis: Das Plugin für VSC (wer damit arbeitet) ist ganz nett. Ansonsten gibt es aber auch eine Art Stand-alone-Version (ein JAR), welches man lokal starten kann. Nur die Webversion ist irgendwie Mist beim Exportieren.

**Comment by cagix** [comment]
> > > Ich habe vor kurzem mit @AMatutat darüber gesprochen, und er sprach von [umletino](http://www.umlet.com/umletino/umletino.html), was ja quasi umlet im browser ist, also auch .uxf verwendet. Mir wäre das ganz lieb, wenn wir uns auf .uxf einigen, da man so nicht von draw.io abhängig ist, sondern im Zweifel immer auf umlet als Standalone Programm setzen kann.
> > 
> > 
> > Das hat auch nen super VS-Code Plugin. Da werden die exportieren Bilder auch nicht so schwammig. Keine Ahnung was die auf der Webseite falsch machen
> 
> Guter Hinweis 👍🏻 Das Plugin für VSC (wer damit arbeitet) ist ganz nett. Ansonsten gibt es aber auch eine Art Stand-alone-Version (ein JAR), welches man lokal starten kann. Nur die Webversion ist irgendwie Mist beim Exportieren.
