### ISSUE TITLE
[DSL] Konfiguration aus mehreren Dateien laden

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#171]
Status Quo:
Alles, was vom `DSLInterpreter` übersetzt werden soll, muss sich in einer Datei befinden. Das macht `.dng`-Dateien unübersichtlich.

Im Sinne einer ursprünglich angedachten Standard-Bibliothek (siehe z. B.  https://github.com/Programmiermethoden/Dungeon/discussions/39#discussioncomment-4350427) sollte es möglich sein, zumindestens die Szenario-Builder-Funktionen und alle Strukturen, die diese benötigen (`entity_type`s, `item_type`s und Funktionsdefinitionen) in separate `.dng`-Dateien auslagern zu können. Hiermit könnte eine von Nutzenden erstellte `.dng`-Datei ausschließlich Aufgabendefinitionen, Aufgabenabhängigkeiten und `dungeon_config`-Elemente enthalten, was ja auch mit Kernidee der DSL war.

Der Gedanke, dass alle Strukturen, Typen, Funktionen etc. sich in einer Datei befinden, ist aktuell auch in der Haltung aller der entsprechenden Symbole im globalen Scope während der semantischen Analyse abgebildet. Hier muss mindestens ein "File"-Scope als nächste Ebene über dem globalen Scope eingeführt werden, sodass bestimmte Symbole eben auch nur im Kontext einer bestimmten `.dng`-Datei gültig sind.

Für die Scenario-Builder-Methoden sollte ein fest definiertes Verzeichnis vorgesehen werden, welches standardmäßig vom `DSLInterpreter` nach eben diesen Methoden durchsucht wird.

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
