### ISSUE TITLE
[GAME] Collision per Strategy Pattern

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#174]
In `HitboxComponent` soll das Attribut `Method method` durch das Strategy Pattern ersetzt werden.

Das (funktionale) Interface `ICollide` hat genau eine Methode `void collide(Entity a, Entity b, Tile.Direction from`, 
wobei `a` die Entität ist, die zum Component gehört und Entity `b` die Entität mit der kolidiert wird. 

`HitboxComponent#collide` ruft dann `ICollide#collide` auf
<img width="486" alt="image" src="https://user-images.githubusercontent.com/32962412/215268950-b7fa2b71-725f-42af-9047-e14babf0fd39.png">

Die Definition einer Methode über die DSL, kann dann später als eine Strategy implementiert werden. 
Durch die beschriebene Struktur wird die Lesbarkeit des Codes erhöht und die Implementierung von Vorgabemethoden vereinfacht. 

#Time:2

**Comment by cagix** [comment]
"Kollidiert" man wirklich Objekte oder prüft man nicht eher auf Kollision (checkCollision)?

**Comment by cagix** [comment]
Brauchst Du in der Component wirklich Getter und Setter? Würde man die Methode nicht beim Erzeugen des Objekts mit übergeben? Könnte man hier nicht eine Recordklasse nutzen?

Wenn die Component eigentlich nur ein Wrapper für die Methode ist - warum brauchen wir dann hier überhaupt ein extra Objekt? Da das Interface ein funktionales Interface ist, kann ich hier doch prima eine Methodenreferenz in eine Klasse (die ganz viele dieser Methoden halten könnte) mitgeben oder einfach einen Lambda-Ausdruck mitgeben?

**Comment by AMatutat** [comment]
> Wenn die Component eigentlich nur ein Wrapper für die Methode ist - warum brauchen wir dann hier überhaupt ein extra Objekt? 

Ist ja mehr. Im Diagramm oben sind nur die für die angefragte Änderung betroffenen Attribute/Methoden eingetragen.

**Comment by AMatutat** [comment]
> "Kollidiert" man wirklich Objekte oder prüft man nicht eher auf Kollision (checkCollision)?

Nope. Das ist die "Du kollidierst mit demda, mach was draus" Methode. Das Checken, ob es eine Collision gibt, passiert im zugehörigen System

**Comment by cagix** [comment]
> > "Kollidiert" man wirklich Objekte oder prüft man nicht eher auf Kollision (checkCollision)?
> 
> 
> 
> Nope. Das ist die "Du kollidierst mit demda, mach was draus" Methode. Das Checken, ob es eine Collision gibt, passiert im zugehörigen System

Hä, die Methode prüft doch, ob zwei Objekte kollidieren? D.h. "checkCollision"? Sie "kollidiert" doch nicht, d.h. führt keine Kollision herbei?

**Comment by AMatutat** [comment]
> Edit: Oh. Jetzt. Lange Leitung. Dann sollte das aber trotzdem anders heissen, oder? "collide" ist für mich ein Verb und kein Ausdruck für einen Zustand.

Finde den Namen schon passend. Hier macht das Component ja auch etwa, hinter der Methode liegt ja ein kleines Verhaltens-"Skript"

**Comment by cagix** [comment]
> > Edit: Oh. Jetzt. Lange Leitung. Dann sollte das aber trotzdem anders heissen, oder? "collide" ist für mich ein Verb und kein Ausdruck für einen Zustand.
> 
> Finde den Namen schon passend. Hier macht das Component ja auch etwa, hinter der Methode liegt ja ein kleines Verhaltens-"Skript"

Ja, aber die Methode führt keine Kollision herbei (das bedeutet für mich der Name "collide"), sondern sie führt bei Kollision etwas aus ...

Allein die Tatsache, dass ich als "Außenstehender" hier (mittlerweile mehrfach) nachfrage, sollte Dir zeigen, dass der Name nicht passt!

**Comment by AMatutat** [comment]
> Edit: Oh. Jetzt. Lange Leitung. Dann sollte das aber trotzdem anders heissen, oder? "collide" ist für mich ein Verb und kein Ausdruck für einen Zustand.

I c

**Comment by cagix** [comment]
mit "onCollide" kann ich leben :) ... "onCollision" wäre imho noch besser, aber ich bin auch kein native speaker
