### ISSUE TITLE
[GAME] GUI System für Quizfragen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#175]
In #484 ist der Aufbau der `QuizQuestions` beschrieben. 
Für jeden `QuizQuestionType` braucht es in der (noch nicht existierenden) Klasse `UITools` eine `static` Methode, welche das User Interface anzeigt, wenn die Frage gestellt wird. 

Unabhängig vom Fragentyp soll das Spiel pausiert werden, wenn das UI geöffnet wird. 
Das UI ist in drei Bereiche gegliedert.
1. Fragenbereich: Hier steht die Frage
2. Antwortbereich: Hier werden die Antworten angezeigt/eingegeben
3. Bestätigen Knopf

![image](https://user-images.githubusercontent.com/32962412/226305643-75b3ef05-9d25-4c29-a685-505d435e0d00.png)

Für die Typen gilt dann im speziellen: 
SingleChoice
    - Antworten werden als Buttons angezeigt
    - Ausgewählte Antwort wird farblich hinterlegt
    - Ich kann nur eine Antwort auswählen
    - Einmal drücken wählt aus
    - Neuauswahl hebt die alte Auswahl auf
MultipleChoice
    - Antworten werden als Buttons angezeigt
    - Ausgewählte Antworten werden farblich hinterlegt
    - Ich kann mehrere Antworten auswählen
    - Einmal klicken wählt aus, zweimal wählt ab and repeat
LückenText:
    - Antwort ist ein Texteingabefeld

Wenn der "Bestätigen" Button gedrückt wird, soll sich das UI schließen, das Spiel weiterlaufen und im Logger die Ausgewählten bzw eingegebenen Antworten geloggt werden. 

#Time:15

**Comment by cagix** [comment]
Eine GUI ist (nur) ein möglicher Weg. 

Aber es gibt doch so viele Möglichkeiten, hier Spielelemente zu nutzen. Statt eine Frage in einer aufpoppenden GUI zu bearbeiten könnte man doch die Frage über die üblichen Hinweise oder von einem Ghost gestellt bekommen und dann im Dungeon gezielt Dinge aufsammeln, besuchen oder interagieren müssen? Im ShPD muss man beispielsweise irgendwann mit einer Axt, die man von einem Schmied bekommt, Gold von den Wänden abhacken und dann dem Schmied bringen ...

Es wäre gut, hier eine Modellierung zu finden, die die Fragen und Antworten unabhängig von der konkreten Umsetzung repräsentieren kann. Zusätzlich hat man dann eine Modellierung der Darstellung im Spiel, und dann kann die DSL zufällig im konkreten Spiel eine dieser Darstellungen auswählen. Das wäre dann auch sehr gut auf neue Darstellungsformen erweiterbar.

**Comment by AMatutat** [comment]
> Eine GUI ist (nur) ein möglicher Weg.

Genau. Es ist EIN Weg. Nicht der einzige.

**Comment by cagix** [comment]
> > Eine GUI ist (nur) ein möglicher Weg.
> 
> 
> 
> Genau. Es ist EIN Weg. Nicht der einzige. 

OK, dann habe ich den Sinn des Tickets nicht erfasst. Gibt es auch Tickets für die anderen Wege? Ich glaube, die sollten **jetzt** mitgedacht werden, damit das System nicht "vernagelt" wird.

**Comment by AMatutat** [comment]
Tickets gibts noch nicht, aber im [Ziel](https://github.com/Programmiermethoden/Dungeon/wiki/Ziel:-Quizfragen) ist genau das festgehalten.

**Comment by cagix** [comment]
> Tickets gibts noch nicht, aber im [Ziel](https://github.com/Programmiermethoden/Dungeon/wiki/Ziel:-Quizfragen) ist genau das festgehalten. 

aye - bitte in der ticketbeschreibung dann immer einen link ins wiki mit rein. (ob das die repo-merge-aktion überlebt? sind ja letztlich lokale links?)

**Comment by AMatutat** [comment]
> Tickets gibts noch nicht, aber im [Ziel](https://github.com/Programmiermethoden/Dungeon/wiki/Ziel:-Quizfragen) ist genau das festgehalten.

Anmerkung: In den Issues für die einzelnen Aufgabentypen steht es sogar drinne

**Comment by malt-r** [comment]
> Eine GUI ist (nur) ein möglicher Weg.
> 
> Aber es gibt doch so viele Möglichkeiten, hier Spielelemente zu nutzen. Statt eine Frage in einer aufpoppenden GUI zu bearbeiten könnte man doch die Frage über die üblichen Hinweise oder von einem Ghost gestellt bekommen und dann im Dungeon gezielt Dinge aufsammeln, besuchen oder interagieren müssen? Im ShPD muss man beispielsweise irgendwann mit einer Axt, die man von einem Schmied bekommt, Gold von den Wänden abhacken und dann dem Schmied bringen ...
> 
> Es wäre gut, hier eine Modellierung zu finden, die die Fragen und Antworten unabhängig von der konkreten Umsetzung repräsentieren kann. Zusätzlich hat man dann eine Modellierung der Darstellung im Spiel, und dann kann die DSL zufällig im konkreten Spiel eine dieser Darstellungen auswählen. Das wäre dann auch sehr gut auf neue Darstellungsformen erweiterbar.

Einfach nur, damit es hier steht und verbunden ist: Unsere Idee für die Entkopplung von Aufgabenbeschreibung und Umsetzung im Dungeon sind 'Task-Builder-Methoden' (vgl. https://github.com/Programmiermethoden/Dungeon/issues/197#issuecomment-1412144121)

**Comment by cagix** [comment]
> > Eine GUI ist (nur) ein möglicher Weg.
> > Aber es gibt doch so viele Möglichkeiten, hier Spielelemente zu nutzen. Statt eine Frage in einer aufpoppenden GUI zu bearbeiten könnte man doch die Frage über die üblichen Hinweise oder von einem Ghost gestellt bekommen und dann im Dungeon gezielt Dinge aufsammeln, besuchen oder interagieren müssen? Im ShPD muss man beispielsweise irgendwann mit einer Axt, die man von einem Schmied bekommt, Gold von den Wänden abhacken und dann dem Schmied bringen ...
> > Es wäre gut, hier eine Modellierung zu finden, die die Fragen und Antworten unabhängig von der konkreten Umsetzung repräsentieren kann. Zusätzlich hat man dann eine Modellierung der Darstellung im Spiel, und dann kann die DSL zufällig im konkreten Spiel eine dieser Darstellungen auswählen. Das wäre dann auch sehr gut auf neue Darstellungsformen erweiterbar.
> 
> Einfach nur, damit es hier steht und verbunden ist: Unsere Idee für die Entkopplung von Aufgabenbeschreibung und Umsetzung im Dungeon sind 'Task-Builder-Methoden' (vgl. [#197 (comment)](https://github.com/Programmiermethoden/Dungeon/issues/197#issuecomment-1412144121))

Danke für die Verlinkung! Soweit ich das sehe, ist das die technische Umsetzung/Basis. Sind irgendwo noch die Ideen für die Ausgestaltung (s.o.: Quests, Gegenstände haben bzw. droppen, ...) gesammelt/formuliert? Irgendwie gibt es gefühlt 100 Issues, die sich mit Einzelheiten beschäftigen und dieses Thema berühren, aber ich hab noch nix gefunden, wo diese Spielideen mal gesammelt werden? (Aber vielleicht hab ich mich auch wieder nur verlaufen?)
