### ISSUE TITLE
[GAME] Quizfragen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#176]
Die Quizfragen müssen in Java-Code gegossen werden, welche dann in der DSL erstellt und von dort eingeladen werden. 

Grob gedacht komm ich auf sowas:  

<img width="543" alt="image" src="https://user-images.githubusercontent.com/32962412/215270117-c8171925-8e75-44de-af03-7ea4a8f97ad0.png">

Damit lassen sich so ziemlich alle Fragen abbilden, ich bin mir nur noch nicht sicher, wie ich den Input gescheit generalisiere.
Ich denke für die Anbindung an die DSL wäre ein `Answer-Bulder` sinnvoll. 
#Time:8

**Comment by cagix** [comment]
Ich denke, die Schnittstelle zur Question wird schon String sein. Ich kann mir grad keinen Mechanismus im Spiel vorstellen, der sich inhaltlich nicht auf String reduziert. Selbst ein Button liefert bei Aktivierung einen String, oder?

**Comment by cagix** [comment]
Irgendwie irritiert mich das Diagramm, bin nicht sicher, warum.

**Comment by AMatutat** [comment]
> Auf der anderen Seite hast Du die ButtonAnswer, die eher eine Repräsentation im Spiel ist und eher nicht mit dem Prüfen einer Eingabe zu tun hat.

ButtonAnswer ist einfach in doofer name. VorgefertigteAntwort oderso. Also etwas, was ich auswähle aber nicht selber schreibe.

**Comment by cagix** [comment]
> > Auf der anderen Seite hast Du die ButtonAnswer, die eher eine Repräsentation im Spiel ist und eher nicht mit dem Prüfen einer Eingabe zu tun hat.
> 
> 
> 
> ButtonAnswer ist einfach in doofer name. VorgefertigteAntwort oderso. Also etwas, was ich auswähle aber nicht selber schreibe. 
> 
> 

Macht Sinn. Aber den Boolean brauchst Du dann nicht, oder? Das wird ja über die Methode plus Input berechnet.

**Comment by AMatutat** [comment]
> Macht Sinn. Aber den Boolean brauchst Du dann nicht, oder? Das wird ja über die Methode plus Input berechnet.

Bin mir noch nicht so sicher mit Struktur, könnte mir aber vorstellen, dass die Answers eher Antwort Möglichkeiten sind. Bei vorgefertigen Antworten würde die Antwort wissen ob sie korrekt ist, bei Lückentextaufgaben dann ein Regex oderso.

**Comment by cagix** [comment]
> > Macht Sinn. Aber den Boolean brauchst Du dann nicht, oder? Das wird ja über die Methode plus Input berechnet.
> 
> 
> 
> Bin mir noch nicht so sicher mit Struktur, könnte mir aber vorstellen, dass die Answers eher Antwort Möglichkeiten sind. Bei vorgefertigen Antworten würde die Antwort wissen ob sie korrekt ist, bei Lückentextaufgaben dann ein Regex oderso.

ah. das muss ich als user definieren können, richtig. 

hmmm. soll eine antwort sich selbst evaluieren können (das suggeriert die methode im interface)? oder gibt es ein (externes) "system", welches user-input und vordefinierte antworten vergleicht?

**Comment by AMatutat** [comment]
Nach Gespräch mit Malte.
Quizfragen werden aus dem Fragenkatalog eingelesen (DSL input) und vom Interpreter in Java-Objekte gewandelt. 
Aus was genau eine Frage besteht steht im wiki (jetzt noch nicht, aber malte trägt es ein). 
Die Java-Objekte müssen nicht wissen, was die richtige Antwort ist. Sie übergeben die Auswahl an eine, in der DSL Frage definierten, Funktion. Diese Wertet das Ergebniss aus und  macht dann sachen.

**Comment by AMatutat** [comment]
@malt-r Nochmal ins unreine Gesprochen, aber eigentlich brauch ich gar keine Quizfragen Objekte im Dungen, oder?

Wenn ich unsere Diskussion richtig im Kopf habe, sind Quizfragen immer mit Entitäten verbunden und irgendwie ne Form von Callback-Funktion (#97). 
Bei Auslösen erzeugt die Callback-Function dann (per native Funktion) z.B die GUI (#175  oder #191).
Und selbst wenn das Rätsel dann irgendwas mit "Sammel X Items" ist, ist das im Grunde auch nur Callback, richtig?


Was das Dungeon macht um die Quest in das Level zu bekommen ist doch:
1. Input Lesen
2. Erkennen dass da eine `Task`definition steht
3. Das Ding mithilfe  von #197 "verarbeiten" und eine Liste an Entitäten zurückbekommen
4. Entitäten in das Spiel werfen 

Ich bin mir grade nur nicht 100% sicher, wie/wo die Callback-Funktion für die gegebene Antwort steht. 


Einlesen tue ich das ganze dann wieder über die `QuestConfig`(#195)?

**Comment by malt-r** [comment]
Prinzipiell kann ich mich da bis Punkt 4 anschließen. Die Frage ist dann nur, wie wir eine Aufgabe als abgeschlossen kennzeichnen, bzw. einen Antwortversuch loggen. Die Verantwortung sehe ich da irgendwie beim Dungeon, ich sehe das irgendwie eher als "Framework-Funktionalität". 

In https://github.com/Programmiermethoden/Dungeon/issues/197#issuecomment-1412144121 ist das im ersten Fallbeispiel in dem `collide`-Eventhandler als `dungeon.log_correct_answer()` skizziert, da könnte man noch drüber nachdenken, da auch das `Task`-Objekt mit reinzureichen, sodass das zuzuordnen ist. Im zweiten Fallbeispiel würde das in den `interact_correct` und `interact_incorrect` Handlern passieren (nur durch Kommentare angedeutet).
`dungeon` wäre dann sowas wie ein zentraler Einstiegspunkt fur die DSL->Dungeon API, über die dann auch andere native Funktionen (GUI-Aufrufe, Print, etc.) aufgerufen werden können.

Das Logging würde in den beiden Beispielen also nicht über eine fixe Callback-Funktion des `Task`-Objekts passieren, sondern in spezifischer auf die Aufgabe angepasste Handlerfunktionen der einzelnen Entitäten. Das setzt voraus, dass das `Task`-Objekt in dem Propertybag (vgl. #172 ) der jeweiligen Entitäten gespeichert wird, damit das im Kontext der Handlerfunktionen verfügbar ist. Ich denke, dass das etwas flexibler ist, als das über eine Callback-Funktion des `Task`-Objekts zu realisieren.

Und Einlesen passiert dann irgendwie über `QuestConfig` oder `LevelConfig` oder wie das dann nachher auch heißen mag.

**Comment by AMatutat** [comment]
Potenziell duplicate with #484 jedoch fehlt in dem Ticket die Antwort auf die Frage "Wie mit Antworten umgehen", daher mach ich hier noch nicht dicht.

**Comment by AMatutat** [comment]
Dieses Issue stammt noch aus der Konzeptzeit und erfüllt in meinen Augen keinen Zweck mehr. Hat fast etwas Sammel-Issue-Charakter.

Die Konzeptergebnisse lassen sich in https://github.com/Programmiermethoden/Dungeon/blob/master/doc/control_mechanisms/tasks.md nachlesen.
