### ISSUE TITLE
Konzept: Immutable Objekte nutzen - Record-Klassen?

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#179]
Aus https://github.com/Programmiermethoden/Dungeon/pull/177#issuecomment-1407661787:

> > Warum ist die Component eigentlich mutable? Wäre es nicht einfacher, das Ding wie ein Record zu behandeln und bei Bedarf ein neues Objekt mit anderen Werten anzulegen? Dann könnte man auch auf die vielen Getter/Setter verzichten? 
> 
> 
> 
> Kurz: Um Konsistent mit den anderen Components zu sein. Die Werte verändern sich ja (die Systeme lesen und setzen) die Daten. 
> 
> 

Ja, aber die Frage, warum hier mit mutable Strukturen gearbeitet wird, ist noch nicht beantwortet. Auch gerade in Java geht der Trend zu immutable Strukturen - und dann brauchst Du die obige Unterscheidung nämlich nicht. Die Component hätte dann eine bestimmte (feste) Velocity, und wenn Du eine andere willst, kannst Du aus der alten plus dem Änderungsvektor über einen Ctor oder Builder eine neue Velocity erzeugen. Keine doppelten Werte, die erklärt werden müssen, kein veränderbarer Zustand, keine zig-hundert Getter/Setter :) 

> Components sollen auch möglichst wenig Verhalten implementieren. Sie speichern Daten. 

Das klingt direkt nach Record-Klassen.

**Comment by AMatutat** [comment]
> Die Component hätte dann eine bestimmte (feste) Velocity, und wenn Du eine andere willst, kannst Du aus der alten plus dem Änderungsvektor über einen Ctor oder Builder eine neue Velocity erzeugen.


Das klingt sinnvoll für Situationen in denen das nicht häufig vorkommt aber hier passiert das ja mehrfachs pro Sekunde.

**Comment by cagix** [comment]
> > Die Component hätte dann eine bestimmte (feste) Velocity, und wenn Du eine andere willst, kannst Du aus der alten plus dem Änderungsvektor über einen Ctor oder Builder eine neue Velocity erzeugen.
> 
> Das klingt sinnvoll für Situationen in denen das nicht häufig vorkommt aber hier passiert das ja mehrfachs pro Sekunde.
> 
> Edit: Zusätzlich bedeutet ein Component löschen und neu anlegen im ECS: -> altes Component aus der Entität löschen, neues Component erstellen, neues Component in der Entität hinterlegen. Wobei der letzte Schritt automatisch passiert.

Hmmm. In Haskell würde das genau so gemacht und funktioniert auch mit hoher Last, aber vielleicht ist da der Compiler einfach deutlich schlauer. Will Dir jetzt auch kein Kind in den Bauch reden ;)


> 
> > Keine doppelten Werte, die erklärt werden müssen
> 
> Das Problem hast du ja immer noch. Du musst einmal den Wert speichern, mit dem sich die Entität bewegen KANN und einmal den Wert mit dem es sich jetzt grade bewegt. Und nach ECS Prinzip gehört beides in das Component.

Ja, mag sein :) ... Vermutlich war mein Ausgangspunkt für die Überlegung aber auch, dass es zwei fast identisch benannte Attribute gab, die auch in der Doku nicht wirklich zu unterscheiden waren und dass der Wert des einen Attributs irgendwie durch einen Methodenaufruf plus den Wert des anderen Attributs abhing (wenn ich das richtig in Erinnerung habe). Da kam ich drauf, dass man eigentlich nur einen Satz von Attributen braucht und nicht beide. Aber wenn ihr wirklich beide Attribut-Sätze braucht ... 


> > keine zig-hundert Getter/Setter :)
> 
> Das ist ein Punkt. Obwohl ich die Anzahl der Getter/Setter pro Component noch überschaubar finde.

Überschaubar ja, lesbar und wartbar eher nein. Die eigentliche Funktionalität geht in dem ganzen Getter-/Setter-Geblubber für mich ziemlich unter. Ich bin froh, dass sich Java da auch endlich von wegbewegt (wobei die Entwickler offenbar wesentlich träger sind).

**Comment by AMatutat** [comment]
> Ich bin froh, dass sich Java da auch endlich von wegbewegt (wobei die Entwickler offenbar wesentlich träger sind).

Öyy ^^


Ich denke ich mach hier erstmal zu.
Die Pro und Cons sind aus meiner Sicht genannt und ich würde hier erstmal die Entscheidung treffen, keine Records zu verwenden

**Comment by cagix** [comment]
@AMatutat Der Punkt mit den "doppelten" Attributen ist hinreichend geklärt - hier muss halt im Code entsprechend umgebaut (naja, umbenannt) und dokumentiert werden. Ob das erfolgt ist, weiss ich nicht. Und ob es passende Tickets gibt, falls es nicht bereits umgesetzt ist, weiss ich auch nicht - zumindest wurde hier nix verlinkt, oder?

Die Geschichte mit "traditionellem OO"-Ansatz vs. "modernerem FP"-Ansatz würde ich aber schon gern nochmal aufgreifen irgendwann. Vermutlich nicht mehr in diesem Projekt, aber das könnte mal im Rahmen einer Hausarbeit o.ä. passieren: Diskussion, Refactoring, praktischer Vergleich. Dazu würde ich das Ticket eigentlich gern als Merkhilfe offen lassen. Hast Du ein passendes Label, so dass es offen bleiben kann und Dich aber auch nicht im Tagesgeschäft stört?

**Comment by AMatutat** [comment]
@cagix mein vorschlag wäre dann, ein eigenes Issue "Funktional statt OO" mit dem "thesis" label zu erstellen. 
In dem Issue können wir dann auf dieses (geschlossene) Issue verlinken. Scheint mir irgendwie dem Zweck mehr entgegen zu kommen.

**Comment by cagix** [comment]
Ja, mach. Mir ist nur wichtig, dass die Diskussion nicht untergeht/verloren geht und dass wir einen passenden Marker haben :)
