### ISSUE TITLE
[Diskussion] Aufgaben: Verteilung an die Studis

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#181]
Bisher haben wir immer nur über Quizzes (SC, MC, Lücke) gesprochen und dass wir die Fragen+Antworten in der DSL formulieren können wollen und dass daraus ein fertiges Spiel generiert wird, welches an die Studis verteilt wird. Und dass es zu jedem Fragentyp jeweils mehrere verschiedene Umsetzungen im Spiel geben soll.

Fragen:

- Wie wird das Spiel verteilt? Ein (großes) JAR, welches die Frage enthält?
- Wie gehen wir mit mehreren Fragen zu einem Thema um?
    - Je Frage ein JAR?
    - Ein JAR mit allen Fragen? 
    - Ein JAR, und die Fragen werden aus einer separaten Konfig eingelesen? (Schnieke, aber die Antworten??)

Vermutlich müssen die Fragen (und Antworten) ins JAR gebacken werden. Dann sollte jede Frage auf einem neuen Level präsentiert werden. Die möglichen Übergänge zwischen den Fragen/Leveln werden über ein Petrinetz von den Lehrenden definiert: Wo kann man von einer richtig beantworteten Frage hinkommen, wo von einer nicht/falsch beantworteten Frage? Also wo gibt es Leitern in ein tieferes Level, wann sind sie frei? Auch sollte es die Möglichkeit geben, ein Level wiederholen zu können (selbe Frage, andere Spielumsetzung, andere Werte).

Oder die Fragen werden als eine Art Quest realisiert?

@bcg7 Was denkst Du?

**Comment by bcg7** [comment]
Wir müssten erst einmal wissen, wie groß ein JAR-File mit einer Frage wird. Aber es wäre nur eine Minimallösung, wenn man mit dem Spiel immer nur eine Aufgabe lösen könnte, auch wenn damit mehrere Level verbunden wären. 
Wir haben vor einiger Zeit schon einmal darüber gesprochen, dass für die Formulierung der Lösungen mancher Aufgabentypen ebenfalls eine DSL nötig wäre. Das wäre dann eine zweite Konfig. Die Bewertung meinetwegen in Prozent der bearbeiteten Aufgaben ist auch noch ein Thema.  Nur 0 % oder 100% ausgeben zu können, ist wahrscheinlich nicht das, was gebraucht wird, es sei denn, für ein Testat. Wie soll das spezifiziert werden? Oder sind wir mit dem bloßen Spiel zufrieden, was ja unter dem Aspekt "self paced learning" auch genügen würde.
Und die Ergebnisse müssen ja auch irgendwie zum Lehrenden gelangen. Die einfachste Lösung wären hier wohl verschlüsselte Dateien, die verschickt werden.

**Comment by cagix** [comment]
ich denke, das jar wird nicht so riesig sein. 

aber trotzdem dürfte es unpraktisch sein, wenn man für jede aufgabe oder eine menge von aufgaben (mehrere level) immer ein neues jar erzeugen muss. außerdem könnte man das relativ einfach dekompilieren und hätte dann die texte...

verschlüsselte konfigurationen (aufgabe, lösung) plus verschlüsselter output wäre eine lösung. eine andere wäre eine kommunikation mit einem server.

**Comment by bcg7** [comment]
Wir haben schon einmal darüber diskutiert, das Ganze als Client-Server-Anwendung zu realisieren. Das sollten wir noch einmal aufgreifen.

**Comment by AMatutat** [comment]
Ich glaube man müsste hier vom Fragetyp unterschieden. 

Quizfragen gehen von der Komplexität in Richtung Karteikarten. Ich könnte mir hier vorstellen eine Art Fragekatalog pro Thema/Modul zu haben. Dieser wird dann von den Studies ausgewählt und die Fragen werden zufällig (wie Karteikarten halt) im Spiel verteilt. 
Hier könnte man natürlich noch mit Algorithmen arbeiten, um oft richtig beantwortete Fragen weniger häufig anzuzeigen etc. 

Für größere Aufgaben müsste man sich ein anderes System ausdenken. Hier sind die Aufgaben ja wirklich eher ein ganzes Level. 
Man könnte sowas wie bei Mario spielen machen, da muss man erst Level 1 schaffen um level 2 freizuschalten usw. Manchmal gibt es dann Abzweigungen... Könnte schon in Richtung Petri Netz gehen

**Comment by AMatutat** [comment]
Ich splitte die Diskussion mal in zwei:

Hier: How to Verteilen
In #184 die Übergänge der Rätsel.

**Comment by cagix** [comment]
> Quizfragen gehen von der Komplexität in Richtung Karteikarten.

Ist richtig. 

Die Frage ist aber, ob wir angesichts der vor uns liegenden Aufgaben hier wirklich Zeit reinstecken sollten und für den ersten Lauf (also dieses Projekt) erstmal Quizzes und "große Aufgaben" einfach gleich behandeln sollten und den Rest für die Zukunft lassen sollten.

@AMatutat Das wäre ein Thema, was wir mal in einem der nächsten Meetings durchdiskutieren sollten. => passendes Label?

**Comment by AMatutat** [comment]
Nach unserer Besprechung ergibt sich folgendes System: 

- Das Spiel (ohne Rätsel) wird als eine Jar verfügbar gemacht
- Die Rätsel (das sind ja eigentlich nur die DSL files) werden als Module  verfügbar (scope: ein Petri Netz = ein Themengebiet) gemacht und eingelesen
  - [ ] [DSL] Aufgaben und Lösungen in unterschiedlichen Dateien speichern
  - [ ] #253 
  - [ ] #194
- Für Prüfungen werden die "gemachten" Lösungen nochmal exportiert
  - [GAME] Logging Ergebnisse Exportieren

**Comment by cagix** [comment]
@AMatutat Schreibst Du das bitte auch nochmal ins Wiki? Im Prinzip kannst Du ja direkt den letzten Kommentar rüberkopieren. (Das Ticket gezielt nochmal wiederzufinden ist ja doch schwierig.)

**Comment by AMatutat** [comment]
mach ich. bekommt nen eigenene Seite und eigenen Milestone

**Comment by cagix** [comment]
> > mach ich. bekommt nen eigenene Seite und eigenen Milestone
> 
> Richtig gut wie ich das gemacht habe.... Bin stolz auf mich (du doofkopf andre)

hmmm?

**Comment by AMatutat** [comment]
https://github.com/Programmiermethoden/Dungeon/wiki/Verbreitung:-Themen-Module
