### ISSUE TITLE
Quizfragen: Level-Übergänge

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#184]
Wir müssen uns Überlegen, wie die Aufgaben im Spiel ausgewählt werden. 

Ich glaube man müsste hier vom Fragetyp unterschieden. 

Quizfragen gehen von der Komplexität in Richtung Karteikarten. Ich könnte mir hier vorstellen eine Art Fragekatalog pro Thema/Modul zu haben. Dieser wird dann von den Studies ausgewählt und die Fragen werden zufällig (wie Karteikarten halt) im Spiel verteilt. 
Hier könnte man natürlich noch mit Algorithmen arbeiten, um oft richtig beantwortete Fragen weniger häufig anzuzeigen etc. 

Für größere Aufgaben: #189

**Comment by cagix** [comment]
Finde ich nicht schlecht, denke aber, dass für den aktuellen Lauf eine vorgegebene Reihenfolge (Petrinetz) oder eine zufällige Auswahl+Reihenfolge bei SC/MC reicht und genug Energie bindet.

@AMatutat Das wäre mal ein Ticket, wo wir alle im Meeting drüber sprechen sollten. => passendes Label?

**Comment by AMatutat** [comment]
Wie am 03.02 besprochen: Due Übergänge werden per Petri-Netz beschrieben. 
Ab jetzt geht es in #121 weiter
