### ISSUE TITLE
[API] Starke Abhängigkeit der Attributsnamen zwischen Dungeon und DSL

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#186]
Wenn Attribute im Dungeon umbenannt werden (Refactoring), dann müssen die Namen auch im DSL-Input geändert werden.
Das ist doof. Aktuell geht das vielleicht noch, aber wenn wir später mehrere (und größere) Inputs haben...

@malt-r Kann ich bei den Attributen, analog zu den Klassen, auch einen Namen in der Annotation festlegen? Dann könnte ich das Attribut im Code umbenennt, in der DSL bleibt es aber unter dem alten Namen bekannt. 

#Time:2

**Comment by AMatutat** [comment]
Diskussions Ergebnis: Ja.
@AMatutat umsetzen.

**Comment by cagix** [comment]
> Diskussions Ergebnis: Ja.

Ich bin gespannt: Was ist die Lösung? Ich könnte mir vorstellen, dass es eine Konfig-Datei gibt, die die DSL-Komponente einliest und daraus dann die Packages erfährt. Das würde auch die Annotationen sparen?

**Comment by AMatutat** [comment]
> Ich bin gespannt: Was ist die Lösung? 

Das da: 

> @malt-r Kann ich bei den Attributen, analog zu den Klassen, auch einen Namen in der Annotation festlegen? Dann könnte ich das Attribut im Code umbenennt, in der DSL bleibt es aber unter dem alten Namen bekannt.


Im Code sieht das dann so aus (exemplarisch): 

```
@DSLType(name="velocity_component")
public class VelocityComponent extends Component {
    private @DSLTypeMember(name="x_velocity") float ichHabMirHierEinenNeuenTollenNamenAusgedacht;
    private @DSLTypeMember(name="y_velocity") float yVelocity;
...
```

**Comment by cagix** [comment]
Das klingt nach "Eierlegendewollmilchsau" :)

Aus Sicht des Interpreters bzw. Frameworks ist das vermutlich eine coole Lösung. Ich bin nicht so sicher, ob das auch aus Nutzersicht eine gute Lösung ist: Ich muss dann in ganz vielen Klassen nachschauen, was ich (wie) nutzen darf, oder? D.h. man muss dann parallel ein zentrales Dokument aufsetzen mit allen Optionen und immer dran denken, dieses bei Änderungen auf Code-Level mitzuziehen. Wäre es denkbar, ein solches Dokument dann in Richtung Interpreter/Framework als Konfiguration/Definition zu nutzen? Dann müsste man nur eine Sache pflegen ...

**Comment by AMatutat** [comment]
> Ich bin nicht so sicher, ob das auch aus Nutzersicht eine gute Lösung ist: Ich muss dann in ganz vielen Klassen nachschauen, was ich (wie) nutzen darf, oder?

Definiere Nutzer. Du als Rätselschreiber? Du brauchst ja eh ne DSL-Dokumentation als Anleitung wie du was erstellst. 
In den "Java"-Code musst du eigentlich nicht gucken.

> D.h. man muss dann parallel ein zentrales Dokument aufsetzen mit allen Optionen und immer dran denken, dieses bei Änderungen auf Code-Level mitzuziehen

Du meinst wenn ein neues Feature (im Sinne eines Features dass über die DSL nutzbar ist) im Dungeon implementiert wird? Dann ja. Aber wenn nur der Code Refactort wird, dann nein. 

> Wäre es denkbar, ein solches Dokument dann in Richtung Interpreter/Framework als Konfiguration/Definition zu nutzen? Dann müsste man nur eine Sache pflegen ...

Das versteh ich grade nicht..

**Comment by cagix** [comment]
> > Ich bin nicht so sicher, ob das auch aus Nutzersicht eine gute Lösung ist: Ich muss dann in ganz vielen Klassen nachschauen, was ich (wie) nutzen darf, oder?
> 
> Definiere Nutzer. Du als Rätselschreiber? 

Welche Art Nutzer siehst Du sonst noch? 

> Du brauchst ja eh ne DSL-Dokumentation als Anleitung wie du was erstellst. In den "Java"-Code musst du eigentlich nicht gucken.

Genau. Es gibt Code, wo über Annotationen Dinge mit der DSL verbunden werden. Diese Sachen müssen dann parallel so dokumentiert werden, dass ich als Nutzer einen Überblick habe und auch im Detail weiss, wie ich das einsetzen kann. Ich muss nicht in den Code schauen, vorausgesetzt die Doku gibt das eben her.



> > D.h. man muss dann parallel ein zentrales Dokument aufsetzen mit allen Optionen und immer dran denken, dieses bei Änderungen auf Code-Level mitzuziehen
> 
> Du meinst wenn ein neues Feature (im Sinne eines Features dass über die DSL nutzbar ist) im Dungeon implementiert wird? Dann ja. Aber wenn nur der Code Refactort wird, dann nein.

Und wenn sich eine Zuordnung ändert? Wenn im Zuge von Refactoring oder was auch immer die Namen Richtung DSL/User geändert werden?

Klar, wenn es was neu gibt, muss es eben auch neu dokumentiert werden.


> > Wäre es denkbar, ein solches Dokument dann in Richtung Interpreter/Framework als Konfiguration/Definition zu nutzen? Dann müsste man nur eine Sache pflegen ...
> 
> Das versteh ich grade nicht..

*Seufz*. 

Statt der Zuordnung von Dungeon-Klassen/-Methoden/-Attributen zur DSL über Annotationen könnte man über eine Art Ini-Datei nachdenken, wo an einer zentralen Stelle diese ganzen Verknüpfungen definiert werden. Die DSL bzw. der Interpreter kann diese Datei lesen und die Zuordnungen dann nutzen (statt der Annotationen) zum Erzeugen von Objekten und was auch immer. Und der User kann das gleichzeitig als Dokumentation lesen.

Erstmal so ins Unreine geschrieben, ist nicht weiter durchdacht. Mir kommt nur grad das Konzept mit den Annotationen ziemlich aufwändig und auch zerbrechlich vor. Aber vermutlich habt ihr irgendwann über einfachere Formen diskutiert, aber das nicht an uns kommuniziert. Oder ich war in dem Meeting Kreide holen?
