### ISSUE TITLE
[GAME] Basisspiel Inhalte definieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#188]
Erstellen einer Liste (eher Issues) über alle Spielelemente die wir für das Basisspiel brauchen. 

Das sind zum einen fehlende Strukturen (z.B Inventar) aber auch konkrete Implementierungen (z.B Feuerball) 

#Time:8

**Comment by AMatutat** [comment]
Issues sind angelegt. Vermutlich werden ab und an noch neue Ideen aufkommen, aber der große rund um schlag sollte erledigt sein

**Comment by cagix** [comment]
> Issues sind angelegt. Vermutlich werden ab und an noch neue Ideen aufkommen, aber der große rund um schlag sollte erledigt sein

@AMatutat Legst Du auch eine passende Struktur in der Doku an, damit man bei der Umsetzung der Issues das gleich vernünftig dokumentieren kann und man so einen schnellen Überblick über die vorhandenen Spielelemente und deren Nutzung bekommt?

**Comment by cagix** [comment]
@AMatutat Verstehe ich das richtig, dass dieses Ticket hier das Basisticket für die restlichen Spielelemente ist? Könntest Du die (Sub-) Tickets bitte noch verlinken?

**Comment by AMatutat** [comment]
> Verstehe ich das richtig, dass dieses Ticket hier das Basisticket für die restlichen Spielelemente ist?

Eigentlich ist das eher das Ticket für mich gewesen, damit ich nicht vergesse die ganzen issues anzulegen. 

> Könntest Du die (Sub-) Tickets bitte noch verlinken?

Ich glaub dabei werde ich verrückt. Der Meilenstein Dungeon Spiele beinhaltet all die erzeugten issues

**Comment by cagix** [comment]
> > Könntest Du die (Sub-) Tickets bitte noch verlinken?
> 
> Ich glaub dabei werde ich verrückt. Der Meilenstein Dungeon Spiele beinhaltet all die erzeugten issues

ja gut. dann ein link auf den meilenstein (im ersten kommentar)?
