### ISSUE TITLE
[GAME] Fragenkatalog einlesen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#193]
In der DSL werden verschiedene Fragenkatalog mit Quizfragen erstellt. Diese werden (irgendwo) abgespeichert.
Diese Kataloge sollen eingelesen werden und die DSL-Fragen nach Java-Fragen geparsed werden (mithilfe des Interpreters) 
Es brauche nur Fragen geparsed werden, die zum Ausgewählten Katalog(e) gehören. 
Siehe auch #194

**Comment by cagix** [comment]
Thema: Verschlüsselung? Die Fragen plus Antworten sollten verschlüsselt in das System reinkommen, die Bewertungen sollten verschlüsselt wieder rauskommen. Bzw. es sollte zumindest mitgedacht werden per API nach innen (so als Datenprovider/Datensenke, und von außen kann man da dann ein Modul zum Ver-/Entschlüsseln anstöpseln oder eine REST-Kommunikation)?

**Comment by AMatutat** [comment]
Wir hatten schon ein paar mal davon gesprochen und sind von diesem "Karteikarten" Gedanken abgekommen und haben über feste Reihenfolgen gesprochen (Petri Netze). 
Daher pack ich hier mal ein later dran, mir gefällt die Idee nämlich immer noch sehr gut.

**Comment by cagix** [comment]
Kann nicht auch ein Petrinetz "Karteikarten" abbilden? Das wären dann lauter Aufgaben, die parallel bearbeitbar sind?

**Comment by AMatutat** [comment]
Das wäre denkbar. 
So könntest du zumindest innerhalb eines Themenblocks Karteikarten umsetzten. 

In meinen Kopf würde ich gerne einen Schritt weitergehen: 
Ich (als Studi) hab irgendwo eine Liste mit allen Fragen aus allen Modulen und die werden mir einfach zufällig nacheinander im Spiel gestellt. 
Am besten kann ich das ganze noch konfigurieren, damit ich einen Tag für ADS und am nächsten Tag für KI lernen kann.
Noch ein Schritt weiter: Das Spiel merkt sich, wie gut ich welche Fragen beantworte und stellt mir die Fragen dann häufiger bzw. weniger häufig.

Mit allem drum und dran könnte das "thesis" sein.

**Comment by AMatutat** [comment]
@cagix ping

Das Ding würde ich gerne irgendwie an pinnen. Die Idee find ich immernoch gut.
Richtig "thesis" ist das aber nicht.... Das ist eher "Idee für Folgeanträge"

**Comment by cagix** [comment]
> @cagix ping
> 
> Das Ding würde ich gerne irgendwie an pinnen. Die Idee find ich immernoch gut. Richtig "thesis" ist das aber nicht.... Das ist eher "Idee für Folgeanträge". Soll ich dafür ein label erstellen oder sammelst du das anders?

hmmm. mach doch beides. "thesis" muss ja nicht unbedingt alleine für eine arbeit reichen, aber es könnte einen baustein sein oder den startpunkt bilden?

**Comment by cagix** [comment]
@AMatutat brauchen wir noch ein "antrag"-label? ;)

**Comment by AMatutat** [comment]
> @AMatutat brauchen wir noch ein "antrag"-label? ;)

genau an sowas hatte ich gedacht. Dann kann man einige Issues damit markieren und ggf. bei gelegenheit mal in den Antrags-Mixer werfen.  Ich leg eins an.

**Comment by AMatutat** [comment]
Könnte sich gut mit https://github.com/Programmiermethoden/Dungeon/issues/340 kombinieren lassen. 
Ich kriege Aufgaben basierend auf meinen Fachlichenskill und in der Auführung basierend auf meine Spielerischen Vorlieben.

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
