### ISSUE TITLE
[GAME] DSL-Startpunkte im Meü auswählbar machen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#194]
Im Hauptmenü (#192) soll es einen Punkt "Themengebiet" geben, dort sollen die verschiedenen eingelesen DSL-Startpunkte auswählbar sein.
Wenn ein Startpunkt ausgewählt wird, soll ein Callback `Consumer<EntryPoint>` ausgelöst werden, welcher den Startpunkt von der DSL interpretieren lässt und den weiteren Flow anstößt.

**Comment by cagix** [comment]
Brauchen wir das wirklich? Nach meinem Verständnis werden Fragen mit dem Spiel ausgeliefert und werden durch die Studierenden in einer Reihenfolge durchlaufen. Ggf. gibt es Auswahlmöglichkeiten an den Knoten - na gut, dass läuft dann vermutlich auf ein Menü hinaus.

Aber so in großem Stil sehe ich da noch keinen Bedarf für eine Fragenauswahl?

**Comment by cagix** [comment]
@AMatutat Hatten wir das nicht im letzten Meeting als "obsolet" diskutiert? Die Lösung heisst Petrinetze?

**Comment by AMatutat** [comment]
> @AMatutat Hatten wir das nicht im letzten Meeting als "obsolet" diskutiert? Die Lösung heisst Petrinetze?

> Edit: So richtig obsolet ist es nicht - das sollte über verschiedene Monster erfolgen: Je Themengebiet wird ein spezielles Monster beim Start angeboten.

Zu beidem ne. Ein Petri-Netz "ist ein" Themengebiet. Aber irgendwo musst du schon sagen, welches Themengebiet du jetzt machen willst.

Ich glaub du hast grade noch das auswählen der Fragenkataloge im Kopf (mein Ursprünglicher Gedanke). 
Hab das Issue recycelt, da es nah bei einander lag.

**Comment by cagix** [comment]
Ja, die Issues klingen alle recht ähnlich ...

Aber trotzdem: Ich meine mich zu erinnern, dass wir am Ende eigentlich die Idee mit den verschiedenen Helden, die je ein Thema (= Petrinetz) repräsentieren, "eingeloggt" hatten, oder?

**Comment by AMatutat** [comment]
> Aber trotzdem: Ich meine mich zu erinnern, dass wir am Ende eigentlich die Idee mit den verschiedenen Helden, die je ein Thema (= Petrinetz) repräsentieren, "eingeloggt" hatten, oder?

Hatte das mehr als "könnte eine coole Idee sein" aufgefasst. Aber können wir gerne einloggen. 


Problem bleibt das gleiche. Irgendwo musst du schon sagen was du willst. 
Wie wählst du die Helden aus? Ich pass die Beschreibung an um das ganze dann deutlich zu machen
