### ISSUE TITLE
[API] Quest-Config Objekt überdenken

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#195]
Das Quest-Config-Objekt nutzen wir aktuell als Einstiegspunkt für die DSL. 
Damals war der Gedanke, dass eine Aufgabe = ein Level ist. 

Macht das noch Sinn? 

#Time:4

**Comment by cagix** [comment]
Eine Aufgabe = ein Level ist schon sinnvoll, zumindest fällt mir grad kein Argument dagegen ein.

Die Frage ist nur, wie komme ich von einer Aufgabe zur nächsten? Was ist überhaupt die nächste Aufgabe (=> Petrinetz). Was machen wir mit "Wiedervorlage" (also Aufgabe nicht korrekt gelöst)?

**Comment by AMatutat** [comment]
>  Eine Aufgabe = ein Level ist schon sinnvoll, zumindest fällt mir grad kein Argument dagegen ein.


Dagegen würde sprechen, dass in einem Level auch mehrere Aufgaben sein könnten. Grade bei dem Quizfragen wäre das ja durchaus denkbar. 


> Die Frage ist nur, wie komme ich von einer Aufgabe zur nächsten? Was ist überhaupt die nächste Aufgabe (=> Petrinetz). Was machen wir mit "Wiedervorlage" (also Aufgabe nicht korrekt gelöst)?

Dafür siehe besser #189

**Comment by cagix** [comment]
> > Eine Aufgabe = ein Level ist schon sinnvoll, zumindest fällt mir grad kein Argument dagegen ein.
> 
> Dagegen würde sprechen, dass in einem Level auch mehrere Aufgaben sein könnten. Grade bei dem Quizfragen wäre das ja durchaus denkbar.

Ja, das wäre denkbar. Aber macht uns das nicht die Sache viel zu kompliziert? Ich hätte gedacht, für den Moment reicht "1 Level = 1 Aufgabe" (dann ist es halt ein kleines Level)? Mehrere Fragen pro Level wären für mich Inhalt der nächsten Iteration oder für wenn Zeit ist?


> 
> > Die Frage ist nur, wie komme ich von einer Aufgabe zur nächsten? Was ist überhaupt die nächste Aufgabe (=> Petrinetz). Was machen wir mit "Wiedervorlage" (also Aufgabe nicht korrekt gelöst)?
> 
> Dafür siehe besser #189

IC. Irgendwie verlaufe ich mich im Ticket-Wald *seufz*

**Comment by AMatutat** [comment]
> Ja, das wäre denkbar. Aber macht uns das nicht die Sache viel zu kompliziert? Ich hätte gedacht, für den Moment reicht "1 Level = 1 Aufgabe" (dann ist es halt ein kleines Level)? Mehrere Fragen pro Level wären für mich Inhalt der nächsten Iteration oder für wenn Zeit ist?

Nach den aktuellen Stand glaub ich, das gibt sich nicht wirklich was, ist eher ne Design-Entscheidung. @malt-r meinung?

**Comment by cagix** [comment]
Ja, okay - wenn es keine Arbeit bindet, die woanders dringender gebraucht wird, dann los.

**Comment by AMatutat** [comment]
@malt-r 

Brauchen wir für die Petri-Netzte noch eine Schicht über das Quest-Config Objekt? 
In meinem Kopf hätten wir das Netz als Graph, bestehend aus Knoten. 
Die Knoten haben dann jeweils ein eigenes Quest-Config Objekt. Da stehen dann die Entitäten, ggf. der Levelgraph usw. dinnen. 
Hab nur noch keine Idee, wie bestimmt wird, welches Level das nächste Level ist. 
Entweder die Quest-Config kennt das Petri Netz und weiß, welcher Knoten bei welcher Lösung der nächste ist, oder die Qust-Config muss dem Petri Netz irgendwie die gemachte Lösung zurückgeben....

**Comment by malt-r** [comment]
Ich denke, dass eine übergeordnete Schicht da sinnvoll ist. Falls wir dem "Mario-Overworld"-Gedanken folgen wollen, dann wäre das Petrinetz für mich die oberste Instanz, die festlegt, welche Level für den Spieler begehbar sind. Für jedes Level gibt es dann eine `LevelConfig`/`QuestConfig`, was sich immer auf ein einzelnes Level bezieht.

Die Logik für die Freischaltung der nächsten Level würde ich eher im Petri-Netz sehen. Für jeden Level-Knoten im Petrinetz könnte festgehalten werden, wie viele Aufgaben bereits in diesem Level erfolgreich gelöst wurden (das muss dann irgendwie mit dem Logging vereint werden). Diesen Zustand könnte das Petri-Netz ja abfragen und für Überprüfung der Bedingungen nutzen. Das so als Braindump grade..

**Comment by cagix** [comment]
Diskussion aus https://github.com/Programmiermethoden/Dungeon/pull/401#pullrequestreview-1322343340:

Die `api/src/quest/Quest.java` wirkt auf mich nicht ganz klar: Ich instantiiere das Ding mit einer `QuestConfig`, die ich auch intern halte. Aber warum packe ich die Werte in diesem Konfigurationsobjekt zusätzlich noch aus? Und die Methode `getGenerator()` liefert ein nicht initialisiertes Attribut zurück? ... Ich sehe das Ding eher als Record, wo ich für die abstrakten Methoden bereits Callbacks (Lambdas, Methodenreferenzen) übergebe und die im Record in den jetzt abstrakten Methoden einfach aufrufe. So hätte man eine Questklasse, die man nicht zwingend ableiten müsste (außer man will wirklich zusätzliche Zustände und Methoden implementieren)?

**Comment by AMatutat** [comment]
Nach Besprechung:

- umbenenne in `DungeonConfig`
- speichert `String name, und Graph<Task>`
