### ISSUE TITLE
[API] Einlesen und verwenden der Task-Builder-Methoden

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#197]
Es wurde Besprochen (wiki eintragt folgt), dass in der DSL sogenannte Task-Builder definiert werden. 
Das Dungeon übergibt diesen Buildern ein Task und bekommt dafür eine Liste an Entitäten zurück. 
Das Dungeon verteilt dann diese Entitäten im Level. Vorerst nur in einen Raum, später dann vielleicht auch in mehreren (Siehe dafür #196).

Die Entitäten sind dann die im Spiel integrierte Quest (durch call-back-funktionen)

**Comment by malt-r** [comment]
Ziel dieser Idee ist es, die Definition der Aufgabe (im einfachsten Fall als Kombination von Fragetext und Antwortmöglichkeiten) von der Realisierung (oder "Manifestation") im Dungeon zu entkoppeln. Über die Task-Builder Funktion (die in der DSL definiert wird) könnte dann aus der Aufgabenbeschreibung (als `Task`-Object in der DSL definiert) alle nötigen Entitäten erzeugt und wieder an das Dungeon zurückgegeben werden.

Mit diesem Ansatz wäre es möglich, mit zwei unterschiedlichen Task-Builder Funktionen auch zwei Unterschiedliche Szenarien für bspw. eine Single-Choice Aufgabe zu erstellen. Beispiel für die Aufgabendefinition (Syntax erstmal nur als Idee):

```
task my_task {
	text: "Hallo, ich bin eine Frage",
	answers: {
		A: "eins",
		B: "zwei",
		C: "drei"
	}, 
	correct: answers.A,
	type: SINGLE_CHOICE
}
```

#### Szenario 1: Monster stellt die Frage bei Kollision mit Spieler*in

```
// Definition einer Monster-Entität als DSL Typ
game_object monster {
    // andere Komponenten (Animation etc.),
    combat_component {},
    hitbox_component {},
    properties: {
        task my_task // definiert eine property im propertyBag der Entität
    }
}

// Funktion, die bestimmt, ob die korrekte Antwort ausgewählt wurde
fn check_answer(task t, String answer) -> bool {
    if (t.correct == answer) {
        return true;
    } else {
        return false;
    }
}

// Definition einer Handler-Funktion für die Kollision einer Hitbox mit einer anderen
// Note: die Signatur von solchen Handler-Funktionen muss für jedes Event genau dokumentiert sein
// this: die Entität, die "Besitzer" der Hitbox-Komponente ist, für die die Handler-Funktion aufgerufen wird
// other: die Entität, mit deren Hitbox wir kollidiert sind
fn collide(game_object this, game_object other) {
    // check: mit Helden kollidiert? -> dafür other checken
    // nein: abbruch
    // ja: siehe folgende

    // frage "laden" -> aus dem Propertybag des monsters holen
    task = this.properties.my_task;

    // frage "anzeigen" -> GUI über Dungeon gekapselt, hier kommt dann die ausgewählte Antwort zurück
    let answer = dungeon.show_task(task);

    if (check_answer(task, answer)) 
        // richtige Antwort loggen
        dungeon.log_correct_answer();

        // das monster stirbt, wenn Held*in die richtige Antwort gibt
        this.combat_component.die();
    } else {
        // falsche antwort loggen
        dungeon.log_incorrect_answer();

        // das monster greift Held*in an, wenn die falsche Antwort gegeben wird
        this.combat_component.hit_player();
    }
}

// task-builder funktion für das Quest Monster
fn build_question_monster(task t) -> game_object[] {
    objects = game_object[];
    
    // instanz vom "monster" DSL Typ erstellen
    question_monster = monster;

    // die übergebene Aufgabe im Propertybag des Monsters speichern
    question_monster.properties.my_task = t;

    // event handler für "collide" event der hitbox-Komponente des monsters setzen
    question_monster.hitbox_component.on_collide = collide;
    
    objects.add(question_monster);
    return objects;
}

level_config config {
    // task-builder Funktion registrieren, sodass sie vom Dungeon aufgerufen werden kann
    task_builder_functions: [build_question_monster]
}
```

#### Szenario 2: Schatzkisten-Rätsel (TODO)

**Comment by malt-r** [comment]
Gedanken zu den nächsten Schritten hierzu (im Sinne der Transparenz):
next steps für Taskbuilder-Methoden:
1. Verbindung zwischen Event-Handlers (Strategy-Pattern) und Nutzerdefinierten Funktionen herstellen
2. Erstellung eines (oder mehrerer) `Room`-Objekte und hinzufügen von Entitäten
3. Entitäten Funktionsreferenzen zuweisen (per Member-Accessoperator)

## Was erfordert 1.:
- Handler-Funktion muss irgendwie als Member in Datentyp integriert werden (Markierung per Annotation)
- Funktionsrefernz muss als Wert übergeben werden können
- Was passiert, wenn dann tatsächlich die Funktion als EventHandler aufgerufen wird?
	- Irgendwie muss das Interpreter-Ökosystem dadrum gebaut werden, als Kontext
		- Parameter müssen in DSL-Datentypen übersetzt werden
		- MemorySpaces und Values müssen passend geladen werden
- Member-Zugriff (mit Punkt-Operator) ermöglichen

- Beispiel für Component mit Strategy-Pattern, bei dem man das mal ausprobieren kann: CollideComponent -> ICollide `iCollideEnter`

Erster Schritt (nicht zu viel wollen): 
```
fn onCollide(entity a, entity b, tile_direction td) {
  print("Hello, World!");
}
```
- einfach nur die Funktion aufrufen
- Parameter richtig übergeben und an Values binden
	- wie sieht jetzt die Repräsentation von `Entity` in der DSL aus?
		- aktuell ist `game_object` auf Entity verlinkt
		- eigentlich sollte das einfach in `entity` umbenannt werden, um eine 1:1 entsprechung zu der Java Welt zu haben
		- Das setzt allerdings voraus, dass `game_object`, also die Prototyp-Definition in `entity_type` oder `prototype` umbenannt wird, das also aufgetrennt wird
		- Dann muss auch die Instanziierung davon umstrukturiert werden
	- Wie realisieren wir hier den Member-Zugriff auf Komponenten? -> aktuell sind alle Components als Set in der Entity-Klasse gespeichert
- Print-Funktion aufrufen

Irgendwie muss der Entity-DSL Datentyp mit pseudo-Memberfunktionen (also Memberfunktionen, die die analoge Java-Klasse gar nicht hat) ergänzt werden, z.B. `entity.components("component_name")`

## Was erfordert 2.:
- Explizite Instanziierung von Entitäten
- Array-Sprach Erweiterung

## Was erfordert 3.:
- Member-Access Spracherweiterung
- Funktionsreferenz als Wert

**Comment by AMatutat** [comment]
In #1030 hab ich mir bereits ein Dummy für den TaskBuilder gebaut. Den muss (und den aufruf) muss man dann noch durch die richtigen austauschen
