### ISSUE TITLE
[API] DSLTypeMember Annotation für "unbekannte" Typen verfügbar machen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#207]
Aktuell kann die Annoation `DSLTypeMember` nur verwendet werden, wenn die DSL den Typen des Attributs auch "versteht". 
Im aktuellen Status sorgt das dafür, dass einige Components und Members noch nicht "angeschlossen" werden können. Die Annotation also noch nicht an die Member geschrieben werden kann, da sonst der Interpreter(?) crasht.
In der Praxis kommentiere ich die Annotationen daher erstmal aus (vgl. `AIComponent`) aber so richtig glücklich macht mich das nicht.

Wär es, mit wenig Aufwand, möglich, das zu fixen?

**Comment by malt-r** [comment]
@AMatutat die Issue hier kann zu gemacht werden, oder?
