### ISSUE TITLE
[Game] Modern Java: mehr funktional wagen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#208]
Das Dungeon setzt zwar auf ein ECS, nutzt aber noch die Java typischen OO Strukturen. 
Eine Untersuchung, ob, wo und wie das Dungeon (vollständig oder teilweise) in Richtung des funktionalen Programmierparadigmas geschoben werden kann, könnte sich als Sinnvoll erweisen. 

Edit: Es geht nicht um funktionale Programmierung an sich, sondern um den Einsatz von "modernem Java". Dazu gehören tatsächlich Anleihen aus der FP, aber es bleibt immer noch objektorientierte Programmierung. Ein interessantes Konzept dabei ist der Einsatz von immutable Strukturen, etwa Record-Klassen (und der Verzicht auf die dann überflüssigen Getter/Setter). Gerade bei den kleinen Component-Klassen hat man gefühlt 10 Getter/Setter und eine Nutzmethode.

Siehe auch #179

**Comment by cagix** [comment]
@AMatutat Vielleicht haben wir aneinander vorbeigeredet. Mir geht es nicht darum, den Dungeon "funktional" zu programmieren. Mir geht es darum, modernes Java einzusetzen.
