### ISSUE TITLE
[GAME] IIdle: RadiusWalk

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#21]
Es soll eine konkrete Implementierung des `IIdle` Interfaces geschrieben werden.
Beim `RadiusWalk` soll sich die (von der AI) gesteuerte Entität ein betretbares `Tile` im vorher definierten Radius suchen (Mittelpunkt ist dabei die aktuelle Position der Entiät), dann dort hin gehen, dort kurz warten und sich dann ein neues Ziel suchen.

**Comment by AMatutat** [comment]
@Lena241 lass uns das Mal in unsere heutige Tagesliste aufnehmen.

**Comment by cagix** [comment]
@AMatutat  Die Issues dienen auch der Projektdokumentation. Bitte schreibe deutlich präziser, was hier umgesetzt werden soll - also nicht "Ähnlich sollen Monster von der KI gesteuert werden.", sondern lass uns teilhaben, was ihr euch überlegt habt und wie das hier umgesetzt werden soll. 

Da darf auch sehr gern ein UML-Diagramm in den ersten Kommentar (also die Ticketbeschreibung). Und bitte mache klar, welchen Umfang dieses Ticket hat: Wieviele Klassen sind anzufassen, wieviel muss geändert werden, wie lange ist die Umsetzung ca. geplant.
