### ISSUE TITLE
[API] Annotations überdenken

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#212]
> > Ich bin nicht so sicher, ob das auch aus Nutzersicht eine gute Lösung ist: Ich muss dann in ganz vielen Klassen nachschauen, was ich (wie) nutzen darf, oder?
> 
> Definiere Nutzer. Du als Rätselschreiber? 

Welche Art Nutzer siehst Du sonst noch? 

> Du brauchst ja eh ne DSL-Dokumentation als Anleitung wie du was erstellst. In den "Java"-Code musst du eigentlich nicht gucken.

Genau. Es gibt Code, wo über Annotationen Dinge mit der DSL verbunden werden. Diese Sachen müssen dann parallel so dokumentiert werden, dass ich als Nutzer einen Überblick habe und auch im Detail weiss, wie ich das einsetzen kann. Ich muss nicht in den Code schauen, vorausgesetzt die Doku gibt das eben her.

> > D.h. man muss dann parallel ein zentrales Dokument aufsetzen mit allen Optionen und immer dran denken, dieses bei Änderungen auf Code-Level mitzuziehen
> 
> Du meinst wenn ein neues Feature (im Sinne eines Features dass über die DSL nutzbar ist) im Dungeon implementiert wird? Dann ja. Aber wenn nur der Code Refactort wird, dann nein.

Und wenn sich eine Zuordnung ändert? Wenn im Zuge von Refactoring oder was auch immer die Namen Richtung DSL/User geändert werden?

Klar, wenn es was neu gibt, muss es eben auch neu dokumentiert werden.

> > Wäre es denkbar, ein solches Dokument dann in Richtung Interpreter/Framework als Konfiguration/Definition zu nutzen? Dann müsste man nur eine Sache pflegen ...
> 
> Das versteh ich grade nicht..

*Seufz*. 

Statt der Zuordnung von Dungeon-Klassen/-Methoden/-Attributen zur DSL über Annotationen könnte man über eine Art Ini-Datei nachdenken, wo an einer zentralen Stelle diese ganzen Verknüpfungen definiert werden. Die DSL bzw. der Interpreter kann diese Datei lesen und die Zuordnungen dann nutzen (statt der Annotationen) zum Erzeugen von Objekten und was auch immer. Und der User kann das gleichzeitig als Dokumentation lesen.

Erstmal so ins Unreine geschrieben, ist nicht weiter durchdacht. Mir kommt nur grad das Konzept mit den Annotationen ziemlich aufwändig und auch zerbrechlich vor. Aber vermutlich habt ihr irgendwann über einfachere Formen diskutiert, aber das nicht an uns kommuniziert. Oder ich war in dem Meeting Kreide holen?

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/issues/186#issuecomment-1412182584_

**Comment by malt-r** [comment]
Der Kerngedanke hinter den Annotationen ist, dass wir als Entwickler möglichst einfach die Verbindung zwischen DSL und Dungeon herstellen können und dort, wo der Java-Datentyp definiert wird auch direkt alles, was (und mit welchem Namen) über die DSL verfügbar gemacht werden soll, mitdefiniert wird (über die Annotations). Damit sind alle Information für die Definition eines DSL Datenteypen auf für einen Blick erfassbar und nicht über mehrere Dateien verteilt.

Ich bin von Anfang an davon ausgegangen, dass wir den Endnutzern (=Rätselschreibern) auch eine Dokumentation zur Verfügung stellen, in der jede Komponente etc. dokumentiert ist, damit man sich als Endnutzer die Informationen nicht aus java-Dateien oder ini Dateien zusammensuchen muss. Das war dann vielleicht ein Fehler von mir, mich da selbst nicht zu hinterfragen und das einfach anzunehmen. Damit das jetzt aber nicht im Rauschen untergeht, habe ich ein Issue dafür angelegt: #219 

Ich persönlich sehe das nicht, dass wir das über eine `.ini`-Datei (bzw. vergleichbares) lösen, die dann vom Nutzer editierbar und löschbar ist. Diese Fehlerquelle würde ich gerne von vornherein ausschließen. Ich finde das persönlich auch etwas dürftig als Endnutzer-Dokumentation.

Außerdem vereinfacht so eine `.ini`-Dateienlösung eigentlich ein Verhalten, was wir (meiner Meinung nach) dringend vermeiden wollen, nämlich, dass sich das Typsystem ändert. Als Typsystem nehme ich jetzt hier alle Komponenten mit allen Membernamen an, die eben über diese Annotationen über die DSL verwendbar sind. Bei jeder Änderung des Typsystems riskieren wir, dass bereits bestehende DSL-Programme kaputt gehen. Daher sollte das sowieso die absolute Ausnahme sein. Über das `name`-Attribut in den Annotationen erkaufen wir uns da eigentlich ein bisschen Freiheit, weil der Name "nach außen" im DSL Datentyp vom Namen in der Java-Implementierung unabhängig ist. Damit muss nicht jedes Mal, wenn sich der Name des Java-Members ändert, auch die Endnutzer-Doku und die `.ini` angepasst werden.

(Aus https://github.com/Programmiermethoden/Dungeon/issues/186#issuecomment-1411963847):
> D.h. man muss dann parallel ein zentrales Dokument aufsetzen mit allen Optionen und immer dran denken, dieses bei Änderungen auf Code-Level mitzuziehen. Wäre es denkbar, ein solches Dokument dann in Richtung Interpreter/Framework als Konfiguration/Definition zu nutzen? Dann müsste man nur eine Sache pflegen ...

Wir haben uns ja jetzt in #161 darauf geeinigt, dass bei inhaltlichen Änderungen auch immer die Dokumentation mit angepasst wird. Das sollte dann konsequenterweise auch für die (noch nicht bestehende) Endnutzer-Dokumentation der Komponenten etc. so gelten, sodass das aus meiner Sicht eigentlich kein Problem darstellt.

> Aber vermutlich habt ihr irgendwann über einfachere Formen diskutiert, aber das nicht an uns kommuniziert. Oder ich war in dem Meeting Kreide holen?

Das haben wir im Meeting 15 besprochen (https://github.com/Programmiermethoden/2022-freiraum-dungeon/blob/master/06_meetings/protokoll_015.md#malte)

**Comment by cagix** [comment]
> Ich bin von Anfang an davon ausgegangen, dass wir den Endnutzern (=Rätselschreibern) auch eine Dokumentation zur Verfügung stellen, in der jede Komponente etc. dokumentiert ist, damit man sich als Endnutzer die Informationen nicht aus java-Dateien oder ini Dateien zusammensuchen muss. Das war dann vielleicht ein Fehler von mir, mich da selbst nicht zu hinterfragen und das einfach anzunehmen. Damit das jetzt aber nicht im Rauschen untergeht, habe ich ein Issue dafür angelegt: #219

das war nicht als finger-pointing gemeint, und wir hatten ja diskutiert, dass in möglichst naher zukunft jede code-änderung automatisch die nötigen anpassungen in der doku nach sich ziehen.

ich habe vermutlich einen lehre-jetlag und komme erst jetzt allmählich dazu, mir die sachen genauer anzuschauen und zu hinterfragen. zu dem zeitpunkt, als du uns dein konzept mit den annotationen vorgestellt hattest, erschien mir das durchaus sinnvoll und ich will das jetzt auch gar nicht wieder abreissen oder so. je mehr ich mich nun mit dem thema beschäftige beschleicht mich das gefühl, dass die konstruktion im breiten einsatz ziemlich fragil und irgendwie auch umständlich und vielleicht auch zu groß sein könnte; und ich schreibe einfach meine gedanken (wirr und unsortiert) auf ;)  ich bin ziemlich sicher, dass eine ini-datei nicht die richtige lösung ist. aber vielleicht etwas, was an einer zentralen stelle steht und vom interpreter mit eingelesen wird und dann über die etablierten reflection-mechanismen genutzt wird?
 

> Außerdem vereinfacht so eine `.ini`-Dateienlösung eigentlich ein Verhalten, was wir (meiner Meinung nach) dringend vermeiden wollen, nämlich, dass sich das DSL-Typsystem ändert. Als DSL-Typsystem nehme ich jetzt hier alle Komponenten mit allen Membernamen an, die eben über diese Annotationen über die DSL verwendbar sind. Bei jeder Änderung des Typsystems riskieren wir, dass bereits bestehende DSL-Programme kaputt gehen. 

bin grad nicht sicher, ob ich das verstehe. 

> Über das `name`-Attribut in den Annotationen erkaufen wir uns da eigentlich ein bisschen Freiheit, weil der Name "nach außen" im DSL Datentyp vom Namen in der Java-Implementierung unabhängig ist. Damit muss nicht jedes Mal, wenn sich der Name des Java-Members ändert, auch die Endnutzer-Doku und die `.ini` angepasst werden.

freiheit, ja. und die nutzer brauchen ihre rätsel bei änderungen der java-api nicht anpassen, was auch ein positiver aspekt ist.

andererseits habe ich das muster schon ein paar mal in variationen gesehen, und das hat eigentlich nie so richtig funktioniert auf dauer. dieses breite verteilte zuordnen und dann noch über strings (also nix, was in einem refactoring mitgeht) geht irgendwann richtig schief.

die frage ist: muss der rätselschreiber auf die java-api durchgreifen können, wollen/müssen wir die wirklich exponieren? sollte man dem rätselschreiber andere abstraktionen anbieten (dsl), die dann vom interpreter in die java-api übersetzt werden? sollte der interpreter nicht "neben" der java-api des frameworks liegen, sondern eher wie eine "shell" drüber/drumherum (also muss das framework wirklich vom interpreter wissen)? 

 
> > Aber vermutlich habt ihr irgendwann über einfachere Formen diskutiert, aber das nicht an uns kommuniziert. Oder ich war in dem Meeting Kreide holen?
> 
> Das haben wir im Meeting 15 besprochen (https://github.com/Programmiermethoden/2022-freiraum-dungeon/blob/master/06_meetings/protokoll_015.md#malte)

ich kann mich daran erinnern, dass wir über die umsetzung mit den annotationen gesprochen haben. kann mich aber grad nicht lebhaft an das diskutieren verschiedener alternativer konzepte und deren vor-/nachteile erinnern, dokumentiert ist es auch nicht? aber vielleicht habe ich das auch erfolgreich verdrängt ;)

**Comment by malt-r** [comment]
> das war nicht als finger-pointing gemeint, und wir hatten ja diskutiert, dass in möglichst naher zukunft jede code-änderung automatisch die nötigen anpassungen in der doku nach sich ziehen.

Ist nicht so angekommen :)

> > Außerdem vereinfacht so eine `.ini`-Dateienlösung eigentlich ein Verhalten, was wir (meiner Meinung nach) dringend vermeiden wollen, nämlich, dass sich das DSL-Typsystem ändert. Als DSL-Typsystem nehme ich jetzt hier alle Komponenten mit allen Membernamen an, die eben über diese Annotationen über die DSL verwendbar sind. Bei jeder Änderung des Typsystems riskieren wir, dass bereits bestehende DSL-Programme kaputt gehen.
> 
> bin grad nicht sicher, ob ich das verstehe.

Mein Gedanke war, dass das suggeriert, dass man "mal eben" und "einfach" was in dieser `.ini`-Datei (oder eben an der einen zentralen Stelle) ändern kann, was aber eigentlich relativ weitreichende Folgen nach sich zieht. Und dass wir das daher eben nicht so einfach an zentraler Stelle zugänglich machen sollten, um diesem Gefühl entgegenzuwirken. War so ein Bauchgefühl und ist vielleicht auch leicht philosophisch angehaucht.

> die frage ist: muss der rätselschreiber auf die java-api durchgreifen können, wollen/müssen wir die wirklich exponieren? sollte man dem rätselschreiber andere abstraktionen anbieten (dsl), die dann vom interpreter in die java-api übersetzt werden? soll der interpreter wirklich "neben" der java-api des frameworks liegen (also beide kennen sich gegenseitig), oder könnte der interpreter eher wie eine "shell" drüber/drumherum liegen (d.h. das framework muss nicht vom interpreter wissen)?

Der Rätselschreiber greift ja nicht direkt auf die Java-Api durch. Mit der Annotation und dem `name`-Attribut wird dem `TypeBuilder` kommuniziert, welche Java-Member in dem DSL Datentyp abgebildet sein sollen und wie diese Abbildung in dem DSL Datentyp heißen sollen. Der `TypeBuilder` ließt das (zu Beginn des Programms) ein, erstellt einen DSL Datentyp (in Form eines `AggregateType`) und merkt sich, welcher Name im diesem DSL Datentyp auf welchen Member in der Java Klasse gemappt wird.
Der tatsächliche Zugriff auf einen Member einer Java-Klasse, der dann per Reflection passiert, ist komplett vom Nutzer abgekapselt. Das was der `TypeBuilder` erstellt und was vom Interpreter genutzt wird ist bereits eine Zwischenschicht. Die Erstellung dieser Zwischenschicht wird nur über die Annotations halbwegs automatisiert.

**Falls** wir per DSL Entitäten im Dungeon definieren lassen wollen, dann **müssen** wir eine Verbindung zwischen den DSL Datentypen und den Komponenten-Klassen, die sie auf der Seite vom Dungeon widerspiegeln, herstellen. Ansonsten bekommen wir ja von der DSL keine Informationen in geordneter Form in das Dungeon rein und andersherum.
Der Annotation-Ansatz ist da ehrlich gesagt noch die einfachste Form, die ich mir vorstellen kann. Die Alternative zu den Annotations ist, dass wir diese Zwischenschicht manuell (also für *alle* Komponenten, die in der DSL verfügbar sein sollen) anlegen. Was meines Empfindens nach deutlich fragiler und zerbrechlicher ist, als der Annotation-Ansatz.

Dass die DSL Entitäten definieren kann, heißt dann nicht automatisch, dass jeder Nutzer das machen muss. Sondern, dass von uns häufig verwendete Entitäten (Monster, Items, etc.) in einer Standardbibliothek (in der DSL geschrieben) enthalten sind, die dann vom Endnutzer nur noch minimal konfiguriert werden müssen. Aber die DSL sollte das können. Damit man als Endnutzer theoretisch die Chance hat, möglichst alle wichtigen Teile, die für eine Aufgabe nötig sind, selbst zu verstehen und anpassen zu können. Und das komplett im DSL-Land, ohne große magische Blackboxen, weil die (für mich) genau dem Gedanken hinter der DSL entgegenstehen.

**Comment by malt-r** [comment]
@cagix wenn ich mich richtig erinnere, haben wir hier die Entscheidung getroffen, dass das so drin bleibt, oder?

**Comment by cagix** [comment]
> @cagix wenn ich mich richtig erinnere, haben wir hier die Entscheidung getroffen, dass das so drin bleibt, oder?

@malt-r Das Ticket oder die Annotations? Das Ticket sollte offen bleiben, aber ich sehe keine realistische Chance, mittelfristig von den Annotationen wegzukommen. Also "later", oder?
