### ISSUE TITLE
[GAME] Junit Testfälle @Before überdenken/reduzieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#213]
> * Präfix "test" entfernt

@AMatutat Ich freue mich, dass Du Dich um die Tests kümmerst! Aber wann hattest Du uns diese  Style-Änderung vorgeschlagen und wir haben diese besprochen/beschlossen? Warum auf einmal den Präfix weg?

> * Einheitliche Bennung von `setup`
> * Mockito verwendet wo sinnvoll

Wir hatten das im PM-Dungeon schon mal ausführlich diskutiert, ist vielleicht wieder in Vergessenheit geraten: Ich möchte in den Tests bitte auf ein `setup` verzichten. Die Idee ist, dass jede Testmethode in sich geschlossen ist und funktioniert und man auf Anhieb erkennt, was dort mit welchen Objekten auf welchen Werten passiert. Dafür nimmt man hier ausnahmsweise Code-Duplizierung in Kauf. Ist eine Erfahrung/Best Practice aus "Software Engineering at Google". 

Ähnliches gilt für Mockito. Eigentlich lieber gar nicht einsetzen. Wir wollen nicht interne Strukturen testen, sondern von außen beobachtbares Verhalten.

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/issues/209#issuecomment-1412164769_

**Comment by AHeinisch** [comment]
Was ich aber jetzt z.b. bei dem Erstellen des Items gemerkt habe, die Tests können unnötig aufgeblasen werden, da wir ja einige statische Sachen nutzen und ich der Meinung bin das Schreiben des Aufräumens der statischen Sachen gehört nicht wirklich in den Test. Alles, was wirklich zum eigentlichen Test gehört, finde, ich muss auch in den Test.

Beispiel, ein Item trägt die fallengelassene Entität im ECS ein. Das ECS ist statisch, somit kann nicht eine Instanz für jeden Test erstellt werden. Somit haben wir Interferenzen, um diese zu beheben, muss das ECS bzw. der für die Tests relevante Teil in den Tests zurückgesetzt werden. Dieses Zurücksetzen hat mit dem eigentlichen Test nichts zu tun und macht möglicherweise es schwerer später zu verstehen, was ein bestimmter Test machen soll.

**Comment by AMatutat** [comment]
Ich hatte beim schreiben der Tests für das HealthComponent ein ähnliches Gefühl.

**Comment by cagix** [comment]
@AHeinisch Die Idee aus dem Buch ist, dass in einer Testmethode nach Möglichkeit alles dabei ist, was zu diesem Test gehört: Setup, Testschritte, Prüfung/Assessment - so dass man sieht, was ein Testfall wirklich macht. Die dabei entstehende Code-Duplizierung nimmt man für die Kapselung der Testfälle in Kauf (also bewusste Abkehr von DRY).

Wenn Du jetzt in einem Testfall irgendwo Klassenattribute veränderst (muss das wirklich sein?), muss man nochmal drüber nachdenken. 

Ist das "Zurücksetzen" nach einem Test tatsächlich ein Reset _nach_ einem Test oder ist es eher die _Vorbereitung_ für den (nächsten) Test?
- Als Vorbereitung würde ich das wohl eher in den Testfall selbst schreiben.
- Als Aufräumen könnte ich mir eine `@after` vorstellen, denn da hat es mit dem Test nicht mehr zu tun.

Ich weiss nicht genau, was ihr vorhabt. Aber von hier (ohne Blick in den Code) sieht es für mich erstmal nach Vorbereitung aus.

**Comment by AHeinisch** [comment]
Für die Doku, einmal nochmal hier ein paar Beispiele, damit es vielleicht erkenntlicher ist, wo das Problem liegt und warum ich denke das before an manchen stellen sinnvoll wäre.

- In jedem Systemtest muss der statische SystemController neu erstellt werden also `Game.systems = new SystemController()`. Dies liegt daran, dass jedes System sich immer in diesem einträgt und man hier keine Möglichkeit hat dies zu unterdrücken außer massiv zu mocken.
- In jedem Test wo Entitäten eine Rolle spielen z.b. Systemtests oder Komponententests muss die Liste alles Entitäten im Spiel zurückgesetzt werden `Game.entities.clear()`. Dieses liegt ebenfalls daran, dass z.b. alle Entitäten sich automatisch auch in dieser eintragen. Ebenfalls nur vermeidbar mit massiven mocken.

Beim Zurücksetzen dieser Klassenattribute kann natürlich auch der after genutzt werden. Vergisst dies nur irgendwann wer haben wir Tests die nicht funktionieren, weil sie nicht auf den aufgeräumten Zustand garantiert sind. Außerdem rede ich hier nicht von z.b. ein Level mit einem bestimmten Layout zu erstellen, sondern nur für mich aktuell für das Verstehen der Tests irrelevante Abhängigkeiten vorzubereiten bzw. aufzuräumen.

**Comment by AMatutat** [comment]
Aus dem Meeting-Protokoll 037: Die im Issue aufgeführten Argumente wurden nochmals angesprochen, und es wurde sich darauf geeinigt, dass Setup-/Cleanup-Methoden mit @Before und @After usw. verwendet werden. Das Ticket bleibt mit dem Label "later" bestehen, da mit komplexeren/größeren Testfällen die Diskussion nochmals Sinn ergeben könnte.

**Comment by AMatutat** [comment]
@AHeinisch @fwatermann @Lena241 @dkirshner @JudiTeller Bitte zur Kenntnis nehmen. 

> Aus dem Meeting-Protokoll 037: Die im Issue aufgeführten Argumente wurden nochmals angesprochen, und es wurde sich darauf geeinigt, dass Setup-/Cleanup-Methoden mit @before und @after usw. verwendet werden. Das Ticket bleibt mit dem Label "later" bestehen, da mit komplexeren/größeren Testfällen die Diskussion nochmals Sinn ergeben könnte.

**Comment by cagix** [comment]
> Ich bin mal so gemein und frage immer oder eher nur für allgemeine Vorbereitungen. Zumindest Setup → before 
> 
> Da aufräumen ohne @after glaube ich problematisch ist. (Tests die Fehlschlagen laufen eigentlich nicht durch) und eigentlich ja immer nur zum Aufräumen benutzt wird.
> 
> somit zur Kenntniss genommen.

@AHeinisch ich denke immer noch, die best-practices aus dem buch ergeben einigen sinn. aber wir haben hier ne ziemliche menge statischen kram, so dass man nach jedem tf komplett neu aufräumen/initialisieren muss. deshalb die entscheidung, erstmal überhaupt testcases zu implementieren und bei bedarf vorerst auf das alte vorgehen zu setzen. ich muss mir mal die teststrategie und die existierenden unittests bei gelegenheit  genauer anschauen ...

**Comment by cagix** [comment]
@AMatutat bei der gelegenheit: der ganze viele `static` kram ist ja historisch gewachsen. mal einen schritt zurückgetreten: brauchen wir das überhaupt noch so? muss das `Game` noch singleton sein? eigentlich nicht, oder? und dann würde sich einiges von dem setup/cleanup-problem, was @AHeinisch oben angesprochen hat, in luft auflösen.

**Comment by AMatutat** [comment]
> @AMatutat bei der gelegenheit: der ganze viele `static` kram ist ja historisch gewachsen. mal einen schritt zurückgetreten: brauchen wir das überhaupt noch so? muss das `Game` noch singleton sein? eigentlich nicht, oder? und dann würde sich einiges von dem setup/cleanup-problem, was @AHeinisch oben angesprochen hat, in luft auflösen.

#746 aber `later`. Ich fände den Gedanken durchaus nochmal interessant aber irgendwann müssen wir (leider) mit dem strukturellen Refactoring aufhören
