### ISSUE TITLE
[GAME] 9-Slicing-Sprites für HUD Backgrounds

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#215]
Wir wollen Texte, Buttons und Eingabefelder in der GUI anzeigen, um den Spieler die Quizfragen zu stellen bzw. Questtexte anzuzeigen. 
Die Funktionalitäten dafür haben wir dank des PM-Dungeon-Frameworks schon.

Bisher werden die Texte ohne Hintergrund (siehe unten) auf das HUD geschrieben. Das macht es weder schön noch besonders leserlich.

<img width="341" alt="image" src="https://user-images.githubusercontent.com/32962412/216196095-5d55b4fa-ea62-41ad-beb4-e2c11e59294b.png">

Daher sollen Hintergrundboxen eingefügt werden (nächstes Bild, wenn auch etwas unschön da per Hand geklöppelt)

<img width="370" alt="image" src="https://user-images.githubusercontent.com/32962412/216196488-ca3ea2d1-3d48-415b-99b3-6d6f58d1f580.png">

Diese Boxen sollen so implementiert werden, dass sie sich der Größe des Inhaltes (also des Textes, des Button etc.) anpassen. 

Die gängige Praxis hierfür scheinen [9-slicing Sprites](https://docs.unity3d.com/Manual/9SliceSprites.html) zu sein.
Die Idee ist, das ein Image in 9 Felder geteilt wird, 8 Randstücke und ein Mittelfeld. Das Mittelfeld wird entsprechend der größe des Inhaltes (z.B des Textes) skaliert. 
Wir werden vermutlich nicht ein Sprite (also ein File) in unserem Dungeon aufschneiden können, aber vielleicht reicht es ja, wenn wir uns 9 Files anlegen und zusammensetzen. 

Am Ende soll eine Wrapper-Klasse dabei rauskommen, die sowohl den Background (vermutlich als `ScreenImage` oder `ScreenImage [9]` (oder eigene Klasse?)) als auch den Content (`ScreenText`, `ScreenButton` etc.) speichert. 
Die Klasse (gerne auch eine Helfer-Klasse, wenn besser) berechnet dann automatisch die Größe und Position des Hintergrunds, bei Instanzierung eines Objektes. 

<img width="603" alt="image" src="https://user-images.githubusercontent.com/32962412/216194505-635871e5-20b1-4af0-a4e3-0fe16035a1fb.png">

Die `draw` Methode soll das ganze dem (static) `ScreenController`(muss noch angelegt werden) des `ECS` hinzufügen.
`remove` entfernt das ganze wieder.

*Anmerkung: Die im UML dargestellten Konstruktoren sind vereinfacht. Ein `ScreenButton` braucht z.B noch einen Listener (callback funktion). Diese wird dann auch im cTor übergeben. Faustregel für die ganzen Konfigurationssachen ist: So viel wie nötig, so wenig wie möglich. Ich möchte mit so wenig Aufwand und Input wie möglich, meine Texte/Buttons auf das HUD bekommen.*

Ein Blick in den halbfertigen [UI-Quickstart](https://github.com/Programmiermethoden/PM-Dungeon/blob/quickstart_ui/documentation/quickstart_de.md#head-up-display-hud) unseres Frameworks könnte ggf. helfen. 

#Time:17

**Comment by AHeinisch** [comment]
https://libgdx.com/wiki/graphics/2d/ninepatches weis nicht ob das hier hilft

**Comment by AMatutat** [comment]
@Lena241 @dkirshner Als ersten Schritt mal etwas Recherchieren, was man da machen kann/muss. Wie komplex das ist etc. Alex hat  ja auch schon was gepostet was man sich anschauen sollte. 
Geht mir noch nicht darum das umzusetzen, sondern erstmal ne Idee zu bekommen, was man machen muss.
