### ISSUE TITLE
[GAME] Skill Cooldown

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#221]
Jeder Skill soll einen Cooldown bekommen. 
Der Cooldown wird in Sekunden beim erstellen des Skills übergeben und dann Framebasiert abgespeichert (`cooldownInSec * Constants.FRAMERATE`). 

Ein Skill kann nur ausgeführt werden, wenn der `currentCooldown` 0 ist. Der Cooldown geht jeden Frame um 1 runter. 

Meine Idee ist, das ganze über die execute Methode zu machen. Die wird ja eh jeden Frame aufgerufen (oder?). 

#Time: 1

**Comment by AMatutat** [comment]
Ist mir grade eingfallen:
In #365 haben wir uns darauf verständigt, das ein Skill zu mehren Entitäten gehören kann. 
Der Cooldown eines Skills ist aber von der Entität die ihn benutzen soll/will abhängig.

Mir fallen drei Möglichkeiten ein:

A) Wir überdenken die Entscheidung, dass ein Skill zu mehreren Entitäten gehören kann. Wenn ein Skill nur zu einer Entiät gehört, dann könnte dort auch der Cooldown gespeichert werden. Bedeutet aber auch, das wir viele Redundante Objekte anlegen und speichern müssen.

B) Das `SkillComponent` speichert den Cooldown. Das Component gehört eh zu nur einer Entität. Ich würde aus `killSet = new HashSet<>();` ein `killSet = new HashMap<Skill,Integer>();` machen. Key der Hashmap ist der Skill, Value der Cooldown.
Dann braucht das Component noch eine `void reduceCooldowns` Methode, die den Value jedes Eintrags in der HashMao auf. `Math.min(0,value--)` setzt. `Math.min`, damit wir ein Underflow vermeiden. 
Diese Methode müsste jeden Frame im System getriggert werden. 
Zusätzlich braucht es dann noch eine `setOnCooldown(Skill skill)` Methode im Component, die den Value des Skills in der HashMap des Components auf den Cooldown des Skills setzt (dafür braucht der Skill eine `int getCooldown`).

Hätte den Semantischen Vorteil, dass ein Skill im Grunde garkeinen `currentCooldown` hat. Die Entität hat einen `currentCooldown` für einen Skill und damit wäre das im Component gut aufgehoben. 

C) Theoretisch könnte auch der Skill eine HashSet (vgl B) mit SkillComponents haben, zu den er gehört. Dann müsste man beim `execute` immer prüfen, von welchem Component es ausgeführt wird. Finde ich absolut doof und liste ich nur der Vollständigkeithalber auf.




@Lena241 was denkst du? Ich finde B am schönsten.

**Comment by cagix** [comment]
> Meine Idee ist, das ganze über die execute Methode zu machen. Die wird ja eh jeden Frame aufgerufen (oder?).

was wären denn alternativen? was wären die vor-/nachteile?

> Hätte den Semantischen Vorteil, dass ein Skill im Grunde garkeinen currentCooldown hat. Die Entität hat einen currentCooldown für einen Skill und damit wäre das im Component gut aufgehoben.

finde ich ziemlich fast nachvollziehbar. wenn ich das von "außen" betrachte: eine component gehört zu genau einer entität - d.h. eine konkrete instanz eines skills gehört zu genau einem npc oder helden. und dort gibt es dann in bezug auf die skill-component einen cool-down (oder auch nicht - hängt vielleicht von der art der entität ab). d.h. der cool-down sollte eine eigenschaft des skills sein und nicht der entität. und eine konkrete skill-instanz sollte nicht mehrere entitäten kennen, das würde doch direkt den sonstigen umgang mit components brechen? und wenn man keinen cool-down braucht, kann man den zähler einfach auf den integer 0 setzen.

**Comment by cagix** [comment]
@AMatutat Kannst Du bitte das Ergebnis der obigen Diskussion hier noch mit reinpacken? Irgendwie wirkt das seltsam beim Lesen: Frage aufgeworfen, Optionen aufgelistet, Nachfrage ... aber keine Entscheidung/Ergebnis? Was wurde denn nun (und warum) konkret gemacht?

**Comment by AMatutat** [comment]
True (kommt auch nochmal in die Dokumentation):
- Eine Skill-Instanz gehört zu genau einer Entität und wird im `SkillComponent` der Entiät gespeichert
- Cool Down des Skills wird im `Skill` gespeichert
- `SkillSystem` reduziert den Cool Down (#394)
-  Das `Keyboard` bzw jetzt `PlayerSystem` aktiviert die Skills
- Die AI implementiert in der jeweiligen `IFightAI` Implementierung, wann welcher Skill aufgerufen wird
- Konsistenz mit unseren anderen Verhaltensweise ähnlicher Art (z.B KI). Da speichert auch jede Entität sein Verhaltens-Instanz
Vorteil:
- Wir können einen Skill einen Ursprung zuordnen (der Held hat den Feuerball geworfen => Held verbrennt sich nicht selbst) 
- Viele Parameter des Skills sind vom Ursprung abhängig (von wo flieg ich los, wie weit flieg ich, wie schnell flieg ich (kann ja von den Spielerstatistiken abhängig sein)).
- Zuordnung zwischen Skill und Cooldown pro Entität ist klar und einfach. Der Cooldown wird im Skill gespeichert und es muss keine extra Map geführt werden

Nachteil:
- Speichern der selben Klassen-Instanzen mit überwiegend den selben Werten für mehrere Entitäten
