### ISSUE TITLE
[GAME] Skill aktivieren Spieler

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#222]
Der Spieler muss seine Skills ausführen können.
Ich würden den Spieler Aktive-Skill-Slots zur Verfügung stellen. 
Jeder Skill-Slot hat einen Skill und liegt auf einer Taste (ich bin für Q und E, da komm ich gut ran). Wird die Taste gedrückt, dann wird der Skill auf den Slot ausgeführt. 

Der Spieler braucht dann noch eine Möglichkeit, die Skills in den Slot zu wechseln. 
Für eine erste Implementierung würde ich vorschlagen, dass es für jeden Slot, noch einen "NextSkill" Key gibt, der dann über die Skills des Spielers iteriert, und auf den Slot den ersten, nicht auf einen Slot gelegten, Skill legt.

Frage ist: Wie markiert man einen Skill als "ist auf einen Slot"? 
In meinen ersten Gedanken war der Slot keine eigene Klasse, aber vielleicht doch? 

Um das per GUI zu machen, gibt es ein eigenes Issue (#223). 

#Time:3

**Comment by AMatutat** [comment]
Thema Skill Slots:
Nach dem letzen meeting und dem heutigen gespräch mit @Lena241.
YAGNI. Jeder Skill hat einen festen Knopf und wir müssen nicht wechseln können. Dafür haben wir noch nicht den Bedarf an Skills.
Falls wir das brauchen, kann der Vorschlag wieder augenommen werden.

**Comment by cagix** [comment]
> Thema Skill Slots:
> Nach dem letzen meeting und dem heutigen gespräch mit @Lena241.
> YAGNI. Jeder Skill hat einen festen Knopf und wir müssen nicht wechseln können. Dafür haben wir noch nicht den Bedarf an Skills.
> Falls wir das brauchen, kann der Vorschlag wieder augenommen werden.

@AMatutat @Lena241  Dokumentiert ihr diese Sachen bitte auch in der Projekt-Doku? Das Ticket findet man später kaum noch wieder; erst recht nicht den Kommentar ...

**Comment by AMatutat** [comment]
Fixed in #469
