### ISSUE TITLE
[GAME] Skill Slots über GUI zuordnen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#223]
IN #222 haben wir Skill-Slots besprochen.
Dafür soll es nun auch ein UI geben. 
Per Maus soll der Spieler ein Skill-Icon auf ein Slot ziehen können und ihn so ausrüsten. 

@AMatutat mal doch noch ein Bild dafür

#Time:10

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
