### ISSUE TITLE
[GAME] Zielen mit den Skill 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#224]
Fernkampfskills werden in eine Richtung geschossen. Wie kontrolliert der Spieler die Richtung? Wie die AI? 
Die AI soll eigentlich immer auf den Spieler Zielen.  

Hier bin ich noch ziemlich Ratlos. Offen für Ideen. 

#Time:4

**Comment by cagix** [comment]
Spieler: Klick mit der Maus in ein Feld.
Spieler: Taste für "Feuer", Richtung ist die Blickrichtung 

NPC: Zufälliges Feld per Normalperteilung, wobei Medium in Blickrichtung.

**Comment by AMatutat** [comment]
Das mit der Maus find ich sexy. Irgendwie hab ich das Spiel immer als Keyboard only im Kopf, aber stimmt ja gar nicht. 

Zufälliges Feld für npcs find ich doof. Soll ja schon auf den Spieler geschossen werden. 

Aber im Grunde braucht es dann nur ne Funktion die von der Position der schießenden Entität den Winkel zum Ziel (Mausposition, Heldenposition) berechnet und dann ein Projektil anfeuert. 


Blickrichtung ist natürlich naheliegend, aber aktuell haben wir kein System dafür. Aber ich mach Mal ein Issue dafür auf, ich hab das Gefühl das könnte nochmal nützlich werden

**Comment by cagix** [comment]
npc: naja, das miss passend zum spieler sein. wenn der spieler unabhängig von seiner blickrichtung gezielt auf ein sichtbares feld zielen darf, sollte das auch der npc können. wenn der spieler in sein blickrichtung feuert (tastatur!), dann sollte das beim npc auch so sein.

und hast du mal einen blick auf die verteilung geworfen? wenn medisn=blickrichtung, dann zielt der (je nach parametern) schon überwiegend in blickrichtung. aber es gibt auch die (kleine) chance für "daneben" oder querdchläger, was es interessanter macht.

**Comment by AMatutat** [comment]
Ich hab eben was testen wollen und dabei mehr oder minder hierfür schon was gebastelt (ist nirgends gepusht, eher als inspiration zu verstehen)

```
    private static Vector2 getVelcoity(){

        Vector3 mousePosition=ECS.dungeoncamera.unproject(new Vector3(Gdx.input.getX(), Gdx.input.getY(), 0));

        Point pc = ((PositionComponent) ECS.hero.getComponent(PositionComponent.name)).getPosition();
        float x1= pc.x;
        float y1= pc.y;
        float x2 = mousePosition.x;
        float y2= mousePosition.y;

        float dx = x2 - x1;
        float dy = y2 - y1;
        float distance = (float) Math.sqrt(dx * dx + dy * dy);
        float speed = 0.1f;
        float velocityX = dx / distance * speed;
        float velocityY = dy / distance * speed;
        return new Vector2(velocityX,velocityY);

    }
```
Kurz aufgesplittet:
`        Vector3 mousePosition=ECS.dungeoncamera.unproject(new Vector3(Gdx.input.getX(), Gdx.input.getY(), 0));`normalisiert die Positon der Maus in das Tile-Based Coordinaten System Die Dungeoncamera muss im ECS noch angelegt und gesetzt werden. 


```
float dx = x2 - x1;
float dy = y2 - y1;
float distance = (float) Math.sqrt(dx * dx + dy * dy);
float speed = 0.1f;
float velocityX = dx / distance * speed;
float velocityY = dy / distance * speed;
```

Das berechnet den Winkel und die sich daraus ergebene Velocity von Position A (hier der Held) nach Position B (hier die Maus) 

`return new Vector2(velocityX,velocityY);` Wenn jetzt ein Projektil mit VelocityX und VelocityY erstellt wird, fliegt es in die Richtung des Mousecoursers. 

Das ganze kann refacotrt werden
