### ISSUE TITLE
[GAME] Skilltree

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#229]
Für die freischaltbaren Skills soll ein typischer Skill Tree implementiert werden.
Über Levelaufstiege sammelt der Spieler Skill-Punkte, dieser kann er dann im Skill-Tree ausgeben.
Das Ganze soll auch visualisiert und mit der Maus gesteuert werden können (#354). 

- Es soll ein dynamischer Skill-Tree gebaut werden. Ich will also nicht eine hardkodierte Liste an Skills, sondern mit den Skill-Tree selber (per Code) zusammenbauen. 
[Beispiel](https://creately.com/static/assets/landing/templates/block-diagram-skill-tree-ddmW9a3aC2q-thumb.svg)

---
## Bounty

Die GUI für den Skill-Tree ist ein eigenes Bounty.

--- 

#Time:17

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
