### ISSUE TITLE
[GAME] Inventory System, braucht es das?

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#233]
Klassischer Weise haben wir für jedes Component auch ein eigenes System. Daher kommt natürlich der Gedanke auf, auch ein System für die Inventory Component (#25) anzufertigen.
Ich hab nur keine Ahnung was das machen soll. 

- Das aufsammeln und benutzen von Items wird wohl nicht von diesem System gesteuert. 
- #234 würde ich nicht als System beschreiben. 

@Lena241 @AHeinisch bitte denkt beide einmal über mögliche Funktionalitäten eines Inventar-Systems nach und wenn euch was einfällt, können wir darüber sprechen. Ansonsten machen wir hier zu.

#Time:1

**Comment by AHeinisch** [comment]
Ich habe mir hier beim Erstellen Gedanken gemacht und keinen wirklichen nutzen gefunden außer man würde darüber eine Art Schnittstelle bauen, womit aufgenommene Gegenstände ins Heldeninventar gepackt werden. 

Es wird ja, glaube ich, nie Gegenstände geben, die irgendwie sich über die Zeit ändern sollen. Beispielsweise ein Gegenstand der Haltbarkeit mit der Zeit verliert, da er z.b. die Zeit verlangsamt oder sowas.

**Comment by AMatutat** [comment]
@AHeinisch du hasst dich ja noch etwas mit dem Inventory beschäftigt, wenn du immer noch sagst: "Braucht es nicht", dann würde ich zu mache.

**Comment by AHeinisch** [comment]
Nach yagni kann zu. Ich sehe da immer noch keinen Nutzen für.
