### ISSUE TITLE
[GAME] Inventar GUI

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#234]
Für das Inventar (#25 #233) soll eine interaktive GUI erstellt werden.

- Jeder Platz im Inventar soll ein Slot in der UI sein, das muss auch mitskalieren für unterschiedlich große Inventare.
  - Hier gibt es ja den Trick, immer eine Reihe mit Slots voll zu machen und alle, die zu viel sind "unusable" zu machen und grau darzustellen.
- Der Spieler soll Items per Drag&Drop bewegen und auf andere Slots schieben können
-  Der Spieler soll Items per Drag&Drop bewegen und auf den Boden werfen können
- Der Spieler soll mit der Maus über ein Item hovern und dann den Namen und Beschreibungstext lesen können
- Der Spieler soll so aktivierbare Items im Inventar aktivieren können (per Linksklick und einen Button "Benutzen" oder so)
- GUI soll auf Knopfdruck aufgehen (Spiel kann pausiert werden)
- GUI soll auf Knopfdruck zu gehen (Spiel geht weiter)
- Wenn ich mit der Maus über ein Item gehe, soll die Item Beschreibung angezeigt werden

Optische Inspirationen: 
[Klick](https://noplatform.files.wordpress.com/2015/05/deus-ex-human-revolution-inventory.jpg)
[Klick](https://64.media.tumblr.com/3ffc8cd1d66aedaa2496423eea9ea3bd/tumblr_inline_njz7blSP2T1r2xhmf.png)
 [Klick](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0Hap41IAguBYxKFnqWlFhvAsw3fYBOrrygsqhQfPDsDNLbqRRDAHuxBQF8SGwv-ajZZw&usqp=CAU)

Bitte fertigt vorher eine Skizze an und sprecht diese mit mir ab. 

Edit: Das Ganze sollte mit #512 und #329 und #327 zusammen diskutiert werden

#Time:17

**Comment by AHeinisch** [comment]
Ich hatte die letzten Tage kein Internet daher gibt es heute erst den Besprechungs inhalt



Das Inventar UI weis wie groß theoretisch das Inventar werden kann und sperrt noch nicht freigeschaltete Plätze. Wir tendieren auch eher dazu, dass alle Items genau einen Slot belegen und nicht jedes Item theoretisch eine unterschiedliche Größe im Inventar hat. Die Items liegen auf dem Overlay als eigene Elemente und können nur auf bestimmten Slots fallen gelassen werden dafür gibt es bei libgdx bereits eine Klasse, die dabei helfen kann https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/utils/DragAndDrop.java.

Für auf den Boden werfen gibt es zwei Optionen. Entweder man hat einen, Slot, welche den Gegenstand auf den Boden fallen lässt oder falls es möglich ist, kann auch einfach außerhalb des Inventars ziehen.
 Zum Aktivieren von Items muss kontrolliert werden, wie es sich genau verhält, wenn ziehen von Items aktiviert ist und ob ein einfaches rechts klicken auf ein Item vielleicht auch schon reicht. 

Da es relevant war zu entscheiden, ob Items stapelbar sind, hatten wir uns gedacht es ist einfacher und auch aktuell meines Wissens vorgesehen das die Items sich nicht stapeln. Daher würden wir dies auch im UI nicht erlauben.

- GUI soll auf Knopfdruck aufgehen (Spiel kann pausiert werden)
- GUI soll auf Knopfdruck zu gehen (Spiel geht weiter)
wäre bereits das normale verhalten von der "Screens und HUD" Besprechung.


Nachforschungen für 
- Der Spieler soll mit der Maus über ein Item hovern und dann den Namen und Beschreibungstext lesen können
- Wenn ich mit der Maus über ein Item gehe, soll die Item Beschreibung angezeigt werden
werden noch gemacht.

Der Spieler soll so aktivierbare Items im Inventar aktivieren können (per Linksklick und einen Button "Benutzen" oder so)
Wenn ein Tooltip möglich ist, geht es wahrscheinlich auch eine Art Kontextmenü zu erstellen.


Ein Inventar könnte also simple gesagt wie folgt aussehen: 
![image](https://user-images.githubusercontent.com/32952411/234060701-5fb9ee1d-1b62-4659-b15d-c5007757efcb.png)
1. Das Inventar kann jederzeit geschlossen werden
2. Es gibt für die Items Slots in denen sie liegen
3. Slots, die noch nicht verfügbar sind, werden als gesperrt (grau hinterlegt angezeigt)
4. Hier, mit dem Beispiel auf der UI gibt es einen Fallenlassen-Slot

@Lena241 ich hoffe, ich habe hier nichts vergessen bin mir aber sicher wir hatten es so besprochen

**Comment by AMatutat** [comment]
Das klingt gut.
Grade das Slot-Schiebe Ding hatte mir bei der Idee Angst gemacht, gut dass es da wohl was gibt.
Frage: Wie verhält sich das mit #491? Könnte man einfach zwei Inventare Anzeigen und dann über die Slots die Items verschieben?

**Comment by AMatutat** [comment]
Warte damit noch etwas.
Aktuell will ich erst die strukturellen Baustellen zu machen, bevor wir "was neues" Anfangen.

**Comment by AMatutat** [comment]
@dkirshner vielleicht kannst du hierfür schonmal ein paar Experimente machen?
Lässt sich das so umsetzten? Was brauchen wir dafür noch?
