### ISSUE TITLE
[GAME] Aktive Items bauen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#237]
Es sollen eine Handvoll aktiver Items (#235)  gebaut werden.

Zu jedem Item gehören:
- Texturen/ Animationen (bitte achtet auf die Lizenzen) 
- Verhaltens Logik

Ich hätte gerne 10 solcher Items: 
- 3 Heiltränke verschiedener Stärke (auch optisch unterschiedlich darstellen)
- 3 Zauberspruchrollen 
- Ideen ??

---
## Bounty

Dieses Bounty kann von mehreren Teams bearbeitet werden. Die Items müssen sich aber von den bereits eingereichten Items unterscheiden. 
Für das Bounty müssen nur 5 Items umgesetzt werden. 
Um die maximalen Punkte zu erreichen, müssen sich die Items in Ihrer Funktionalität stark unterscheiden. 3 unterschiedliche Heiltränke sind nicht erlaubt.
Dieses Bounty kann mit #242  kombiniert werden (2 von hier, 3 von dort o. ä.)

Jedes Team kann nur einmal die Punkte für diese Bountys bekommen.

--- 

#Time: 17

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
