### ISSUE TITLE
[GAME] Ausrüstung bauen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#242]
Es sollen eine Handvoll passiver Items (#236) gebaut werden.

Zu jedem Item gehört:
- Textur/Animation (auf Lizenzen achten)
- Logik 

Ich möchte mindestens 10 Items, darunter:
- 2x Helme
- 2x Rüstung 
- 2x Schwert
- 3x unnützer Krempel
-  Ideen? 

---
## Bounty

Dieses Bounty kann von mehreren Teams bearbeitet werden. Die Items müssen sich aber von den bereits eingereichten Items unterscheiden. 
Für das Bounty müssen nur 5 Items umgesetzt werden. 
Um die maximalen Punkte zu erreichen, müssen sich die Items in Ihrer Funktionalität stark unterscheiden. 3 unterschiedliche Heiltränke sind nicht erlaubt.
Dieses Bounty kann mit #237 kombiniert werden (2 von hier, 3 von dort o. ä.)

Jedes Team kann nur einmal die Punkte für diese Bountys bekommen.

--- 

#Time:17

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
