### ISSUE TITLE
[GAME] Aufrufe von Entity#addComponent entfernen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#243]
Jetzt bin ich über meine eigene Anpassung gestolpert:
Beim erstellen eines Components, fügt dieses sich automatisch der Entität hinzu.
```
    public Component(Entity entity, String name) {
        this.entity = entity;
        entity.addComponent(name, this);
    }
```

Das ist super und kann auch so bleiben. Aber damit sind alle anderen Stellen an den `Entity#addComponent` aufgerufen wird, überflüssig und können entfernt werden.
*Anmerkung: Es verursacht kein Fehler. Da das Component beim Aufruf von `Entity#addComponent` quasi aus der Entität löscht und neu hinzufügt. Es ist einfach nur unnötig.*
Die Dokumentation ist hier dann auch Fehlerhaft.

**Comment by AMatutat** [comment]
wurde in #250 behoben

**Comment by cagix** [comment]
> wurde in #250 behoben

@AMatutat Dort wurde nur der **Code** gefixt, aber nicht die Dokumentation. Oben im ersten Kommentar hast Du geschrieben: "Die Dokumentation ist hier dann auch Fehlerhaft." ... 

Reopening to fix documentation.
