### ISSUE TITLE
[GAME] Ranking der Systeme

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#244]
Teilweise agieren die Systeme auf die gleichen Components, daher ist die Reihenfolge in der die Systeme ausgeführt werden entscheidend. 

Ich würde vorschlagen jedem System bei Erzeugung eine ID zuzuweisen (mit Hilfe einen statischen Zählers) und je geringer die ID desto höher die Priorität und desto früher wird das System ausgeführt. 

Praktisch heißt das: Das erste erzeugte System ist das wichtigste usw.

Man sollte nochmal gucken, wie der `SystemController` damit umgeht. Das ding führt die Systeme aus, erbt aber aus dem Framework vom `AbstractController`. Stellt sicher, dass die Priorität beim iterieren über die Einträge beachtet wird.

**Comment by cagix** [comment]
Hier sollte eine Priorität o.ä. definiert werden. Zähler klingen erstmal einfach, lösen aber das Problem nicht wirklich.
