### ISSUE TITLE
[GAME] HealthSystem Entität erst nach Animations-ende löschen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#246]
Im HealthSystem aus Programmiermethoden/PM-Dungeon#245 wird die Entität gelöscht, wenn die Lebenspunkte auf 0 fallen.
Zuerst sollte aber die die Animation zuende abgespielt werden.
Dafür brauchen wir noch eine [Anpassung im Framework](https://github.com/Programmiermethoden/Dungeon/issues/307)

**Comment by fwatermann** [comment]
Wurde meiner Meinung nach nicht gefixt. Entites werden trotz Animation immer noch sofort gelöscht, daher: #554
