### ISSUE TITLE
[GAME] Interaktionssystem

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#252]
Das System für #251.
Eigentlich muss das System nicht viel machen, vielleicht kann man das auch im `KeyboardSystem` implementieren.
Wenn der Interaktionsknopf gedrückt wird, soll für die Entität in Range `onInteraction getriggerd werden. 
Wenn mehre Entitäten (mit dem InteractionComponent) in Reichweite sind, dann soll mit der Entität die am nähsten zum Helden steht "interagiert" werden. 

Bitte auch an Tests denken. 

#Time: 2

**Comment by cagix** [comment]
Was'n mit "Interaktionssystem" gemeint?

**Comment by AMatutat** [comment]
Aktuell haben wir Systeme um Sachen zu hauen und in Sachen reinzulaufen. Ich weiß, in Berlin deckt das schon 95% der Interaktion ab, aber im Dungeon hätte ich gerne noch etwas mehr. 

Ernst: Drücke "Taste X" um mit Entität Y zu interagieren (Kiste aufmachen, Item aufheben, Leute ansprechen).

**Comment by cagix** [comment]
> Systeme um Sachen zu hauen und in Sachen reinzulaufen. Ich weiß, in Berlin deckt das schon 95% der Interaktion ab

Hmmm, reicht doch, oder? ;)

> Drücke "Taste X" um mit Entität Y zu interagieren (Kiste aufmachen, Item aufheben, Leute ansprechen).

Für "hauen" haben wir ein eigenes System. Für "reinlaufen" haben wir ein eigenes System. Das Konzept "Interaktion" scheint deutlich mehr zu umfassen: Kisten öffnen, Items aufheben, NPC ansprechen. Deshalb nochmal meine Frage, etwas präziser formuliert: Was genau macht das Interaktionssystem? Soll es wirklich diese vielen Dinge in _einem_ System lösen? Oder andersherum: Warum nehmen wir dann nicht das System für "hauen" und ergänzen das?

**Comment by AMatutat** [comment]
> Das Konzept "Interaktion" scheint deutlich mehr zu umfassen: Kisten öffnen, Items aufheben, NPC ansprechen. Deshalb nochmal meine Frage, etwas präziser formuliert: Was genau macht das Interaktionssystem? Soll es wirklich diese vielen Dinge in einem System lösen?

Jop. Prinzip ist im Grunde wie unseren anderen Systeme. Das Interaktionscomponent macht eine Entiät "interagierbar". Das WAS wird dann wieder per Strategy-Pattern implementiert. 


> Oder andersherum: Warum nehmen wir dann nicht das System für "hauen" und ergänzen das?

Bist wieder zu nah am Pixel Dungeon. Unser hau-system ist "Erzeuge eine unsichtbare Entität vor dir, die anderen Schaden macht". Wir klicken nix an. 

PS: Das Issue muss noch gefüllt werden, wie Beschreibung und Label das auch andeuten.

**Comment by AMatutat** [comment]
@AHeinisch  Wenn du hier fertig bist, kann du auch gleich einmal rebasen und dann in `doc/ecs/components` und `doc/ecs/systems` deine neue Schöpfung sowohl in den Tabellen eintragen als auch eine entsprechende Datei + Dokumentation anlegen und füllen.
