### ISSUE TITLE
[GAME] StatsSystem, braucht es das?

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#26]
Klassischer Weise haben wir für jedes Component auch ein eigenes System. Daher kommt natürlich der Gedanke auf, auch ein System für #232  anzufertigen.
Ich hab nur keine Ahnung was das machen soll.

@Lena241 @AHeinisch bitte denkt beide einmal über mögliche Funktionalitäten eines Stats-Systems nach und wenn euch was einfällt, können wir darüber sprechen. Ansonsten machen wir hier zu.

#Time:1

**Comment by AMatutat** [comment]
@Lena241 bitte in dieser Woche bearbeiten.

**Comment by AHeinisch** [comment]
Also mir würde nur bei einem Statsystem so was einfallen wie.
Hat der Spieler X stamina regeneriert er y hp alle z ticks
Hat der Spieler X beweglichkeit berechnet sich die Geschwindigkeit alle z ticks neu
etc. 

Aber ja, wenn dies beides keine gewünschten Funktionalitäten sind, wie es ja bisher immer klang, ist es hier irgendwie nicht notwendig ein System zu haben, da die Stats keine andauernde Aktualisierungen machen.

**Comment by AMatutat** [comment]
Ich mag die Vorschläge, klingt für mich aber auch erstmal nach YAGNI.

**Comment by cagix** [comment]
@AMatutat Was ist das Ziel dieses Tickets? Es ist mit "current week" gekennzeichnet, gleichzeitig aber auch mit "question" - d.h. es soll umgesetzt werden, muss aber noch diskutiert werden? Und Deine obige Antwort "yagni" deutet darauf hin, dass dieses Ticket obsolet ist?

**Comment by AMatutat** [comment]
> @AMatutat Was ist das Ziel dieses Tickets? Es ist mit "current week" gekennzeichnet, gleichzeitig aber auch mit "question" - d.h. es soll umgesetzt werden, muss aber noch diskutiert werden? Und Deine obige Antwort "yagni" deutet darauf hin, dass dieses Ticket obsolet ist?

Ja wir hatten das im Meeting heute besprochen. Habs nicht zu gemacht.
