### ISSUE TITLE
[DSL] Instancing of `AggregateTypeAdapter`

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#268]
The `TypeInstantiator` currently only supports the instantiation of adapted types which require a single parameter to instantiate. This needs to be extended in order to support the instantiation of `AggregateTypeAdapter`s, which requires multiple parameters for instantiation.

#### Requirements
- extend `TypeInstantiator::instantiate` to pass parameters correctly from passed `IMemorySpace` to the builder methods
- Tests
- Extend documentation

#Time:5

**Comment by cagix** [comment]
@AMatutat @malt-r Was ist hier der Stand? Am 06.02. wurde das auf "current week" gesetzt. Warum ist das noch nicht gelöst? Warum hängt es noch auf "current week"?
