### ISSUE TITLE
Wo legen wir die Issues ab?

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#271]
@AMatutat Ich schreibs mal als Issue auf: Bisher sind die Tickets aus dem Projekt über mehrere Repos verstreut: Tickets zum Dungeon im Dungeon-Repo, Tickets zu Paper im Freiraum-Repo, Tickets zu D2A im PM-Lecture-Repo. 

Im Prinzip finde ich das auch richtig.

Dein Tooling (Berechnung der Aufwände) läuft aber nur über ein Repo, oder? Außerdem sind die Meilensteine für die Planung nur in einem Repo (hier). Meine Befürchtung ist, dass wir uns damit komplett verzetteln - beispielsweise habe ich keinen Meilenstein für D2A gefunden.

Vorschlag: Alle Issues, die im Rahmen vom Dungeon-Projekt entstehen und zu bearbeiten sind, werden hier in diesem Dungeon-Repo gesammelt/gepflegt. Immer.

(Die PR für die Paper/Einreichungen bleiben im Freiraum-Repo und können ja auf die jeweiligen Tickets hier verweisen. Die Tickets für D2A werden ohnehin nicht im Lecture-Repo bearbeitet, da können sie genausogut auch hier liegen.)

**Comment by AMatutat** [comment]
Gut das du es ansprichst, beim D2A bin ich nämlich auch darüber gestolpert. 
Finde deinen Vorschlag gut, sollten wir so umsetzen.

**Comment by AMatutat** [comment]
Ich glaub das haben wir jetzt geklärt, oder?

**Comment by cagix** [comment]
Geklärt ja - umgesetzt nein. Die Paper-Sachen liegen iirc noch im Freiraum-Repo, oder?

**Comment by AMatutat** [comment]
my bad, hab gelesen das PRs. und Tickets im Freiraum Repo liegen. 
Dann müssen wir die Publikations Issues noch transferieren

**Comment by cagix** [comment]
> my bad, hab gelesen das PRs. und Tickets im Freiraum Repo liegen. Dann müssen wir die Publikations Issues noch transferieren
> 
> Edit: Yikes ich (vielleicht darfst du das) darf keine Issues aus Privaten in Public Repos transferieren

@AMatutat Ich darf das auch nicht, habe jetzt aber einen Umweg genommen: Habe die Issues alle in ein privates Repo transferiert, dieses dann public gemacht und dann die Issues von dort hierher geschoben. Sorry, sind jetzt viele "neue" Issues - und die sind teilweise nicht gelabelt bzw. nicht mehr erkennbar.

**Comment by AMatutat** [comment]
Ich wühl mich schon durch. 
Ich mach hier dann als "erledigt" zu.
