### ISSUE TITLE
[DSL] Logging in der DSL definieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#274]
In der DSL soll angegeben werden können, was wann und wie geloggt wird.
Dafür kann der Logger aus dem Dungeon mithilfe einer nativen Funktion aufgerufen werden.

**Comment by AMatutat** [comment]
Besprechung 08.02: 
Das Logging wird über native Funktionen aus der DSL aufgerufen. 
Siehe auch https://github.com/Programmiermethoden/Dungeon/issues/197#issuecomment-1412144121

- Seperatse Logbuch für Aufgaben und System-Logging

**Comment by malt-r** [comment]
Primär wird auch dieses Issue erstmal als native Funktion umgesetzt (siehe #1059 )
