### ISSUE TITLE
[GAME] Log verschlüsselt exportieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#275]
Das Logbuch soll verschlüsselt exportiert werden können. damit es später als Lösung abgegeben werden kann. 
Fragen: Wie wird der Log verschlüsselt? Wo liegen die Keys?

In Kombination mit https://github.com/Programmiermethoden/Dungeon/issues/276

**Comment by cagix** [comment]
Idee: Public Key kann im JAR integriert werden - die Lehrenden haben den passenden Private Key zum Entschlüsseln. Ggf. kriegt man das sogar so hin, dass man das auswählen kann.
