### ISSUE TITLE
[Feature] Ergebnisse aus Log automatisch auswerten

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#276]
Im Dungeon-Projekt werden die abgegebenen Antworten, erreichten Punkte usw. in eine separates Logdatei geschrieben. Für eine Anwendung wie eine Prüfung ist es erforderlich, dass das Logfile verschlüsselt exportiert wird, um sicherzustellen, dass die Studierenden die Abgabe nicht manipulieren können.

Zusätzlich sollte ein Tool zur automatischen Auswertung der Logeinträge entwickelt werden. In einem ersten Schritt sammelt dieses Tool nur die erreichten Punkte ein. Es wäre jedoch auch denkbar, die gegebenen Antworten zu sammeln und so eine Art Semesterübersicht zu erstellen. Damit könnten Lehrende feststellen, welche Themen bei den Studierenden gut bzw. weniger gut verstanden wurden.

**Comment by AMatutat** [comment]
Besprechung 08.02
- Wir sollten ein kleines Beispiel bauen und gucken in welche Probleme wir rennen, da ohne konkreten Anwendungsfall es schwer ist, abzuschätzen was man braucht

**Comment by AKirsch1** [comment]
@AMatutat Könnte das hier ein Teil von D2A sein bzw. im Rahmen von D2A gelöst werden? In beiden Fällen wollen wir die Lösung automatisiert auswerten. Siehe #620 (Metrik Dungeon).

**Comment by cagix** [comment]
@AKirsch1 Hmmm, ursprünglich ging es um die Logs, die beim Lösen der Rätsel entstehen (sollen). Aber tatsächlich könnte das quasi ein Bewertungsplugin bei D2A sein :)

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
