### ISSUE TITLE
[GAME] Fallen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#28]
Ausgelöst durch eine Aktion des Spielers oder Questfortschritt
Schaden an Spielern (oder und zusätzlich an Gegnern)
Rollender Fels:
Fällt von oben in den Dungeon und rollt in eine festgelegte Anfangsrichtung
Ändert bei Kontakt mit Wänden die Richtung
Zerfällt nach Anzahl zurückgelegter Tiles und oder Anzahl der Wandkontakte
Pfeilschuss Anlage:
Schießt einen oder mehrere Pfeile in eine festgelegte Himmelsrichtung
Stachelfalle:
Fährt Stacheln aus dem Boden aus
Variante A: regelmäßiges ein- und ausfahren
Variante B: ausgelöst durch eine Aktion oder Quest (vorher unsichtbar)

**Comment by malt-r** [comment]
So dann?
![indiana_jones](https://user-images.githubusercontent.com/37513253/207307623-1f5bfafc-1889-4c3c-8fba-a69a203b8a57.gif)

**Comment by AMatutat** [comment]
wird über DSL definiert
