### ISSUE TITLE
[GAME] Kapselung und Zugriff über Getter und Setter, ist das noch ECS? 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#285]
> > Öhmmm. Ja. Schöner Nebeneffekt :/
> > Sollte das nicht eher sowas wie hpComponent.clearDamages() sein?
> 
> Ehrlich gesagt, keine Ahnung was hier der beste style ist. Ich weiß das Spotless jegliches Call by Reference Verhalten doof findet und am liebsten nur kopien von Listen rausgeben will, auf der anderen Seite ist das ganze Konzept von ECS, dass die Systeme die Werte verändern, warum also nicht so? 

Gute Frage. 

Ich sehe hier einen Nebeneffekt - sowas ist immer hässlich. Du siehst ja, ich bin auch beim Lesen drüber gestolpert. 

Das Rausgeben der Liste an sich ist nicht das Problem, aber das Verändern von Werten im Objekt über die herausgegebene Liste ist das Unschöne hier - dafür hast Du doch extra Getter und Setter und sonstige Methoden. Das bricht Dir die Kapselung.

> Mit der Argumentation könnte ich aber auch gleich alles public machen und das will nun wirklich keiner.....

Ist tatsächlich aber die Frage, ob das nicht eine konsequente Folge von ECS ist. Im ShPD war auch fast alles `public`, wenn ich mich richtig erinnere.

Und letztlich stellt sich die Frage: Warum willst Du Dinge kapseln und verstecken (`private`), wenn Du Dir dann Getter bastelst und damit exakt die interne Repräsentation rausgibts und dann obendrein noch die Veränderung des Objektzustands darüber erlaubst? Dann kannst Du auch konsequent sein und direkt auf den Attributen des Objekts arbeiten, das macht dann keinen Unterschied mehr.

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/245#discussion_r1099829988_

**Comment by cagix** [comment]
Das Ticket verfolgt 2 Probleme:

1. Ist der Zugriff über Getter und Setter tatsächlich "ECS"? Im ShPD ist mehr oder weniger alles `public`.
2. Nebeneffekte wie das Ändern von Objektzuständen über herausgegebene Referenzen sollten unabhängig davon auf alle Fälle vermieden werden. Objekte sollten nur über ihre Methoden abgefragt und geändert werden. (Kapselung)

**Comment by AMatutat** [comment]
Ich hab mich mal ein wenig umgeschaut (es gibt ja kein richtiges "THIS IS ECS") und tatsächlich scheint es da zwei Fraktionen zu geben.
- public und mach halt was du willst
- getter und setter

Vielleicht spricht da der Java OOP Entwickler aus mir, aber ich wäre auch für getter und setter, dann aber konsequent. 


> Nebeneffekte wie das Ändern von Objektzuständen über herausgegebene Referenzen sollten unabhängig davon auf alle Fälle vermieden werden. Objekte sollten nur über ihre Methoden abgefragt und geändert werden. (Kapselung)

Ja. Ich würde mich aber ungerne Spotbugs beugen und nur Kopien von Objekten rausgeben. Das macht so viele Probleme.

**Comment by cagix** [comment]
> Ich hab mich mal ein wenig umgeschaut (es gibt ja kein richtiges "THIS IS ECS") und tatsächlich scheint es da zwei Fraktionen zu geben.
> 
> * public und mach halt was du willst
> * getter und setter
> 
> Vielleicht spricht da der Java OOP Entwickler aus mir, aber ich wäre auch für getter und setter, dann aber konsequent.

Bin ich dabei. So lange es konsequent ist :)

> 
> > Nebeneffekte wie das Ändern von Objektzuständen über herausgegebene Referenzen sollten unabhängig davon auf alle Fälle vermieden werden. Objekte sollten nur über ihre Methoden abgefragt und geändert werden. (Kapselung)
> 
> Ja. Ich würde mich aber ungerne Spotbugs beugen und nur Kopien von Objekten rausgeben. Das macht so viele Probleme.

Spotbugs zeigt aber letztlich nur auf das Problem: Man gibt den internen Zustand heraus und erlaubt den Nutzern, darüber den Objektzustand zu ändern (aka Seiteneffekt). Für mich hat das nicht so sehr mit "ich beuge mich Spotbugs" zu tun, sondern eher mit (un-) sauberem OO-Design - hier gibt es einen Designflaw: Man möchte etwas (außerhalb des Objekts) tun, was eigentlich das Objekt selbst erledigen sollte (Methoden). Das hat auch einen Namen: "Feature Neid" (https://github.com/Programmiermethoden/PM-Lecture/blob/master/markdown/coding/smells.md#code-smells-feature-neid) ...

**Comment by AMatutat** [comment]
@AHeinisch kannst du mir dies bezüglich eine grobe Einschätzung aus deiner ECS Erfahrung geben?

**Comment by AMatutat** [comment]
Dieses Issue lag jetzt lange rum ohne beachtet zu werden und die Praxis hat einen weg gefunden.+
Wir verwenden getter/setter für so ziemlich alles und geben nur Kopien von internen Zuständen.

Praktisch möchte ich nochmal über alles gucken und überprüfen ob das wirklich so ist oder wir an einigen stellen den short cut genommen haben. 

Ziel ist: Zugriff auf Attribute über getter/setter und nur rausgeben von Kopien interner zustände. 
Für mich geht das dann auch hand in hand mit #660

**Comment by AMatutat** [comment]
Für die bessere Übersicht und Aufteilung sowie einen besseren Workflow ist dieses Issue gemerged in #1025 und #178.

Je Klasse 1 PR
