### ISSUE TITLE
[Feature] Itch.io Support

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#300]
Auf https://itch.io/ finden regelmäßig verschiedene GameJams statt.
Das sind Hackathons nur für Spiele.

Für die meisten GameJams ist es Voraussetzung, dass diese dann auch auf itch.io gespielt werden können.
Es gibt wohl auch support für Java applets: https://itch.io/updates/support-for-java-applets-added

Wenn wir unser Framework kompatibel damit machen, könnten die Studis mit dem Framework/ ihrem Dungeon an solchen GameJams Teilnehmen und müssten nicht erst eine andere Engine lernen. 

Als erstes müssen wir herausfinden, welche Änderungen am Framework nötig wären.
Dann müssen wir abwägen, ob sich der Aufwand lohnt bzw. es zu nicht tolerierbaren Einschränkungen kommen würde (ich denke an das libGDX HTML target zurück).

Edit: Es gibt zumindest "native" libGDX Spiele https://itch.io/games/made-with-libgdx

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
