### ISSUE TITLE
[GAME] TextureHandler.getInstance().getTexturePaths() findet Texturen doppelt.

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#306]
`extureHandler.getInstance().getTexturePaths($REGEX$)` soll eigentlich jede Textur, auf die der regex passt, in einer Liste zurückgeben. Scheinbar werden Texturen auch doppelt "gefunden".

#Time:2

**Comment by tgrothe** [comment]
@AMatutat Hat dieses Ticket einen Bezug zu #311 ?

Ist mit "doppelt" gemeint, dass zum Beispiel hierbei Pfade in `build` und auch in `game` gefunden werden?

```java
    protected void setup() {
        List<String> paths = TextureHandler.getInstance().getTexturePaths("knight/runLeft");
        for (int i = 0; i < paths.size(); i++) {
            System.out.println((i + 1) + " " + paths.get(i));
        }
        System.out.println();

```

```
> Task :run
operating system 'Windows 11'
1 C:/<…>/Dungeon/build/resources/main/character/knight/runLeft/knight_m_run_anim_mirrored_f0.png
2 C:/<…>/Dungeon/build/resources/main/character/knight/runLeft/knight_m_run_anim_mirrored_f1.png
3 C:/<…>/Dungeon/build/resources/main/character/knight/runLeft/knight_m_run_anim_mirrored_f2.png
4 C:/<…>/Dungeon/build/resources/main/character/knight/runLeft/knight_m_run_anim_mirrored_f3.png
5 C:/<…>/Dungeon/game/assets/character/knight/runLeft/knight_m_run_anim_mirrored_f0.png
6 C:/<…>/Dungeon/game/assets/character/knight/runLeft/knight_m_run_anim_mirrored_f1.png
7 C:/<…>/Dungeon/game/assets/character/knight/runLeft/knight_m_run_anim_mirrored_f2.png
8 C:/<…>/Dungeon/game/assets/character/knight/runLeft/knight_m_run_anim_mirrored_f3.png

```

Es sollen aber nur Pfade aus `build` zurückgegeben werden, oder?

**Comment by cagix** [comment]
@tgrothe Danke für den Beitrag. Versuche bitte in Zukunft, nicht unbedingt die Bounty-Sachen zu lösen 😀

@AHeinisch Ich verstehe ehrlich gesagt nicht, was @AMatutat hier genau gefixt haben will bzw. worin konkret das Problem besteht. Bitte nicht mergen, bevor nicht @AMatutat was dazu gesagt hat.

@AMatutat Ein bisschen mehr Kontext wäre schon hilfreich... Das Ticket hier ist klassisches Selbst-Murmeln!

**Comment by tgrothe** [comment]
Danke, werde ich in Zukunft nicht mehr machen, ich hatte mir das nur herausgepickt, weil ich wohl als Letztes daran beteiligt war, und uns da (damals) etwas nicht aufgefallen war oder aus einem Grund nun nicht mehr wie erwartet funktioniert. => Weiteres im PR #560

**Comment by AHeinisch** [comment]
> @AHeinisch Ich verstehe ehrlich gesagt nicht, was @AMatutat hier genau gefixt haben will bzw. worin konkret das Problem besteht. Bitte nicht mergen, bevor nicht @AMatutat was dazu gesagt hat.

DAs Problem darin liegt das z.b. die MissingTexture bis zu 3 mal von dem TextureHandler gefunden wird. Dies soll nicht mehr der Fall sein.


Beim Entwickeln heißt der Ressourcenordner Assets.
Nach dem Build existiert ein weiterer Order Ressources.
Und nach dem jar existiert ein dritter Ordner.
Die 2 automatisch generierten Ordner kopieren alle Dateien. (Alle Bilder, Klassen etc.) Dadurch findet der TextureHandler bei MissingTexture.png (welche im git nur einmal liegt) bis zu 3 Dateien anstelle von exakt einer. Außerdem findet z.b. "Hero" auch Hero.java und Hero.class.

Hier noch einmal, damit es nochmal komplett vorhanden ist:
Das Problem liegt daran, dass rekursiv durch alle Ordner gelaufen wird und jede Datei in die pathmap eingetragen wird. Dies sorgt beim debuggen mit der IDE dazu, dass alle Grafiken mehrmals gefunden werden. Um dies zu lösen, muss das eintragen in die pathmap gefixt werden, da dort über 1000 Filehandles liegen, welche nie genutzt werden. (z.b. alle git dateien, IDE dateien)

Gemerged wird so oder so erst, sobald alle noch einmal rübergeschaut haben und auch Test vorhanden sind.

**Comment by cagix** [comment]
Hmmm, den Fall mit dem JAR könnte man erstmal ausklammern, oder? Wenn ich das JAR habe/nutze, dann habe ich den Rest nicht.

Assets vs. Build scheint ein Konfigurationsproblem zu sein? Ich meine, dass nach dem Build die Texturen genau wie die .class-Dateien aus dem Build-Ordner genommen werden sollten, also nicht aus den Sourcen ("assets/").

**Comment by cagix** [comment]
> Danke, werde ich in Zukunft nicht mehr machen, ich hatte mir das nur herausgepickt, weil ich wohl als Letztes daran beteiligt war, und uns da (damals) etwas nicht aufgefallen war oder aus einem Grund nun nicht mehr wie erwartet funktioniert. => Weiteres im PR #560 

@tgrothe so war das nicht gemeint 😀 du kannst gern issues fixen, und auch die bounty-sachen können natürlich gemacht werden. allerdings sind letztere vor allem an die studis gerichtet, weshalb wir da etwas zurückhaltender sein sollten. also nicht alle bounties wegfixen, so lange es noch anderes zu tun gibt (außer ein bounty "juckt" wirklich furchtbar).

**Comment by tgrothe** [comment]
> Hier noch einmal, damit es nochmal komplett vorhanden ist:
> Das Problem liegt daran, dass rekursiv durch alle Ordner gelaufen wird und jede Datei in die pathmap eingetragen wird. Dies sorgt beim debuggen mit der IDE dazu, dass alle Grafiken mehrmals gefunden werden.

Ja, siehe auch hier https://github.com/Programmiermethoden/Dungeon/pull/560#issuecomment-1509869172

**Comment by tgrothe** [comment]
Vorher hatten wir ja zwei Repos (+ jar), es war also sinnvoll, alle Assets in das `build` zu kopieren. Jetzt wäre das doch eigentlich nicht mehr notwendig, weil alle Assets in `game` (neben `src`) liegen.
