### ISSUE TITLE
[GAME] Animation Freeze

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#307]
Eine `Animation` loopt immer automatisch.
Die Klasse sollte so erweitert werden, dass auch eine non-loop Animation möglich ist.
In diesen Fall läuft die Animation wie gewohnt durch, bleibt aber am letzten Frame stehen und springt nicht zurück auf den ersten Frame. 

Eingestellt kann das per cTor Parameter. Default sollte `loop=true` sein. 

Daher brauchen wir:
- neuen Konstrukten mit weiteren boolean `loop` Parameter
- der aktuelle cTor wird beibehalten => ruft dann den neuen mit `loop=true` auf
-`Animation#getNextAnimationTexturePath()`  entsprechend anpassen. (Könnte ein Stumpfes if else sein, oder?) 
- Tests und Dokumentation anpassen. 

@Lena241 Klar was zu tun ist? Bei Fragen/Unklarheiten melden. 

#Time:1

**Comment by AHeinisch** [comment]
@dkirshner hast du hier schon angefangen?
