### ISSUE TITLE
[GAME] ScreenInput behält Fokus trotz wegklicken

### ISSUE THREAD

**Issue by AHeinisch** [Programmiermethoden/Dungeon#309]
Der `ScreenInput` hat ein Problem mit dem Fokus. Und zwar behält es den Fokus so lange, bis ein anderer `ScreenInput` angeklickt wurde. Dies schränkt keinen Button oder Ähnliches ein, sondern sorgt nur dafür, dass in dem `ScreenInput` immer weiter geschrieben wird. Drücken eines Buttons, Labels oder Image nimmt den Fokus nicht weg.

Lösung dafür (die ich finden konnte, welche problematisch sein kann) ist einen riesigen Button auf der tiefsten Ebene anzulegen. 
Mir sind dabei aber bereits mögliche Probleme aufgefallen:
- eigener Button liegt vor dem Fokus Button und somit wird der Fokus nicht gelöscht
- Ein Image liegt vor dem Fokus Button und somit kann es sein, dass das Event nicht ausgelöst wird
- Text ähnlich wie beim Image

#Time:4

**Comment by AMatutat** [comment]
Problem durch das neue UI-Konzept hinfällig
