### ISSUE TITLE
[Tooling] Mavencentral abschalten/Account löschen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#313]
Für mavencentral muss der Key alle2 Jahre geupdated werden. Kann man das automatisieren? Kann man ein geplantes Issue anlegen, was früh genug bescheid sagt? 

@Tobias321 kannst du nochmal spezifizieren welcher Key genau das war? Hab mir das natürlich nicht notiert.

**Comment by AMatutat** [comment]
@cagix wir haben uns doch jetzt mehr oder weniger von Mavencentral verabschiedet, richtig?

**Comment by cagix** [comment]
> @cagix wir haben uns doch jetzt mehr oder weniger von Mavencentral verabschiedet, richtig?

Ja, aber wir haben noch keine richtige Strategie:

- Wollen wir "für immer" weg? Wollen wir später vielleicht doch nochmal wieder hin?
- Sollten wir auf MC aufräumen: Account und Artefakte löschen? (Unabhängig von "für immer" oder "nur mal kurz": Das Repo ist ja weg...)
- Geht Github-Packages als Ersatz in Gradle?

**Comment by AMatutat** [comment]
ich pack mal meeting dran, geht vermutlich schneller das verbal zu besprechen

**Comment by cagix** [comment]
@AMatutat Wir haben das besprochen. Was war das Ergebnis? Warum gibts hier keinen Kommentar dazu? Kann das Ticket zu? Oder sollten wir es als "Reminder" aufheben?

Siehe auch #314

**Comment by AMatutat** [comment]
Wir hatten uns stillschweigend darauf geeinigt, Mavencentral nicht erneut zu nutzen. Allerdings haben wir noch keinen endgültigen Entschluss gefasst. Die Frage ist, ob wir den Account einfach abschalten oder zuvor löschen sollten. 
Auch GitHub Packages sind für uns nicht unbedingt notwendig, da wir uns nicht mehr ausschließlich auf den Framework-Gedanken fokussieren, sondern uns eher als Softwareprojekt bzw. Code-Basis verstehen. Die PM-Studierenden arbeiten direkt mit Forks im Code. 
Für unser Projekt haben wir uns entschieden, mit `.jar`-Dateien zu arbeiten, wie hier näher beschrieben: https://github.com/Programmiermethoden/Dungeon/wiki/Verbreitung:-Themen-Module

@cagix, die finale Entscheidung liegt bei dir.

Das betrifft #314 #313

**Comment by cagix** [comment]
lass uns den maven-central-account abschalten/löschen, danach kann hier zu (#313). 

oder spricht für dich noch irgendwas für ein weiterbetreiben des accounts?

**Comment by AMatutat** [comment]
> oder spricht für dich noch irgendwas für ein weiterbetreiben des accounts?

Falls irgendwelche Menschen mit dem alten Ding noch aktiv rumrennen, schneiden wir die Verbindung ab. Ist dann doof für die aber die könnten sich die lib dann aus dem alten Repo ziehen...

Dann darf ich jetzt mal rausfinden wie man in Mavencentral sein Konto löscht.

**Comment by tgrothe** [comment]
📬 email sollte jetzt da sein

**Comment by tgrothe** [comment]
Hat es geklappt? @AMatutat

**Comment by AMatutat** [comment]
@tgrothe hab die Daten bekommen, danke ^^


@cagix Habe den Support jetzt eine E-Mail geschrieben. Mal gucken ob und wann die antworten.

**Comment by AMatutat** [comment]
Es geht voran, auch wenn es etwas an Passierschein A38 ran kommt.

**Comment by cagix** [comment]
Mail am 10.05.: 

> Joel Orlina kommentiert am MVNCENTRAL-8065:
> -----------------------------------------
> 
> While we can delete your accounts and remove your access, Sonatype policy prohibits the removal or any other modification of artifacts after they've been released.  For details on this long-standing policy, have a look here:


@AMatutat Scheint so zu sein, dass wir die Releases nicht mehr loswerden. Sowas habe ich auch schon bei ORCA erlebt - einmal draußen, immer draußen. Sollen wir das mit dem Account weiter verfolgen oder einfach das PW ein letztes Mal auf einen zufälligen Wert ändern und dann den Wert/das PW wegwerfen und damit die Sache ruhen lassen?

**Comment by tgrothe** [comment]
Ich bekam diese E-Mail auch... Was würde denn mit "Zombie-Accounts" bei mvncentral passieren?

**Comment by cagix** [comment]
> Ich bekam diese E-Mail auch... Was würde denn mit "Zombie-Accounts" bei mvncentral passieren?

was weiss ich? vermutlich nix.

**Comment by AMatutat** [comment]
Hab das Passwort geändert, damit sollte die Sache abgehackt sein.

@cagix willst du das Passwort irgendwie behalten oder soll ich es unwiederruflich verbrennen?

**Comment by cagix** [comment]
> Hab das Passwort geändert, damit sollte die Sache abgehackt sein.
> 
> @cagix willst du das Passwort irgendwie behalten oder soll ich es unwiederruflich verbrennen?

@AMatutat schicke es mir mal zusammen mit dem user-namen als interne mail. man weiss ja nie.
