### ISSUE TITLE
[ORG] GitHub-Package anstelle von mavencentral?

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#314]
Früher haben wir Maven Central verwendet, um das Framework an die Studierenden zu verteilen.
Vorteil: Die Studierenden mussten sich nicht das Projekt-Repository forken, sondern konnten auf einem eigenen (sauberen) Repository arbeiten.
Auch konnten sie keine Änderungen an den Vorgaben vornehmen. Das war in der Praxis sowohl ein Vorteil, da man so einfacher Bugfixes ausliefern konnte, und die Ergebnisse der Studierenden einfacher in das Framework zu integrieren waren. Allerdings war es für einige Studierende auch eine Hürde, da sie gerne an den Vorgaben herumgeschraubt hätten.

Können wir GitHub Packages verwenden und Maven Central dafür ausschließen?
Welche Vor- und Nachteile haben die beiden Varianten?

**Comment by AMatutat** [comment]
Ich zieh dieses Ticket mal aus den aktiven Projekt Milestones raus. 
Das ist eher Lecture und PM

**Comment by cagix** [comment]
das ticket kommt aus der pm-ecke, aber das könnte sehr wohl auch relevant für den einsatz und die verbreitung der dsl bzw. der generierten rätsel sein?!

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
