### ISSUE TITLE
[FEATURE] Raspberry Pi Support

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#315]
Das Framework ist auf dem aktuellen Raspberry Pi Geräten nicht lauffähig. Ursache hierfür, wird vermutlich libGDX selbst sein. 

PIs erlauben uns mehr Flexibilität in der Strukturierung des Praktikums und sind zeitgleich eine gute Fallback-Ebene, falls andere Betriebssysteme streiken sollten.

**Comment by cagix** [comment]
@AMatutat der letzte sinnvolle kommentar deutet darauf hin, dass das game auf dem pi läuft. kann das ticket zu?

**Comment by AMatutat** [comment]
@tgrothe danke fürs ausprobieren und dokumentieren. Wie ich sehe steht aus auch im Wiki.
