### ISSUE TITLE
[FEATURE] Testabdeckung

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#319]
Unsere mangelnde Testabdeckung fällt uns langsam auf die Füße. 
Jede Klasse sollte nochmal genau analysiert und getestet werten.

1. Klassen Sammeln (@Lena241)
2. Teststrategie Diskutieren (@AMatutat , @cagix) 

- [ ] `ClassName1`
 - [ ] `ClassName2` 
- [ ] ...

**Comment by cagix** [comment]
duplicate of #318
