### ISSUE TITLE
[GAME] HUD und Screens Besprechen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#327]
Wir sollten uns einmal über ein gemeinsames Konzept für die GUI austauschen.
Ich denke da an so Sachen wie Inventar Screen, Stats Screen, Ausrüstung Screen etc.

Das hat direkten Einfluss auf #234 #229 etc.

**Comment by AHeinisch** [comment]
Für den alten Ansatz spricht es bleibt in der Entwicklungsumgebung und nutzt keine weiteren Tools. 
Für den neuen Ansatz für den Infodialog #543 spricht, dass es vielleicht einfacher zu verstehen ist, wo welche Elemente platziert sind, wenn es visuell direkt beobachtet werden kann. (Durch externes Tool)

Beides klingt recht schön und persönlich denke ich das vielleicht, dass mit dem externen Tool für Layout Erstellung einmal gründlich durchgeschaut werden sollte.

**Comment by cagix** [comment]
d.h. es spricht alles für den kompletten wechsel hin zu den systems, weg von den controllern, richtig?

**Comment by AMatutat** [comment]
Das haben wir gemacht und umgesetzt.
