### ISSUE TITLE
[GAME] CC-0 Fonts suchen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#330]
Für den ganzen HUD Kram brauchen wir ein paar schöne Fonts. Als Open Source Projekt können wir natürlich nicht irgendwelche Fonts aus dem Internet nehmen, daher soll gezielt nach passenden Fonts unter CC-0 Lizenz gesucht werden.

Sucht bitte Fonts raus, die optisch in das Dungeon passen (am besten schreibt ihr direkt dran, wofür ihr die verwenden wollen würdet).
Wir brauchen Fonts für Menüs, Dialoge, Spielanzeigen etc. 

**Die Fonts bitte nicht einfach in einen PR hochladen, sondern erst hier verlinken und abnicken lassen (inclusive "beweis" dass es CC-0 ist bzw. man es einfach so verwenden darf** 

#Time:3

**Comment by cagix** [comment]
Am besten wäre es, wenn man die Fonts dynamisch per Link zur Compile- oder noch besser Laufzeit laden könnte und gar nicht erst hier im Repo ablegen muss.

**Comment by AMatutat** [comment]
Wir haben unsere eigene Font, daher ist dieses Issue eher nice to have.
