### ISSUE TITLE
[D2A] Checkliste für Aufgaben

### ISSUE THREAD

**Issue by jposselt** [Programmiermethoden/Dungeon#334]
Vielleicht wäre es gut bei den einzelnen Aufgaben immer eine kurze Checkliste dabei zu haben, die die wichtigsten Punkte wiedergibt. Damit würde man die Studenten (und die Tutoren ebenso) auch noch mal an die wiederkehrenden Aufgaben erinnern. Zum Beispiel könnte man sagen "Tasks: Pattern implementieren, JavaDoc, JUnit Test, Logging". Was haltet ihr davon?

Edit: Wird eventuell obsolet durch https://github.com/PM-Dungeon/PM-Lecture/issues/465

**Comment by AMatutat** [comment]
@cagix Ist da Ticket noch aktuell? 
Die Konzeptaufgaben werden/sollen von der D2G Toolchain bewertet werden, dafür braucht es dann keine Abnahme und daher keine Checkliste mehr.
Die Dungeonaufgaben sind sehr frei in der Gestaltung und Umsetzung, dafür lässt sich nur sehr schwer (und sehr grob) eine Checkliste erstellen.

**Comment by cagix** [comment]
im prinzip ist das ticket überflüssig.

aber: ich sehe in diesem semester d2a nicht mehr realistisch eingebunden. es sind noch fünf wochen bis zum start - und weder steht die toolchain noch die aufgaben noch existiert ein umsetzungszeitplan. 

d.h. wir brauchen da was. und auch wenn es für die dungeonaufgaben schwieriger ist, eine liste zu erstellen: hilfreich ist sie trotzdem für die tutoren.

**Comment by AKirsch1** [comment]
Closed as not planned in favor of #620.
