### ISSUE TITLE
[D2G] Aufbereitung der Reports

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#335]
Im CI läuft Spotless, Checkstyle, SpotBugs und JUnit. Alle erzeugen Reports. Für Deploy-to-Abgabe wäre es hilfreich, wenn wir diese Reports per Skript o.ä. zu einem einzigen übersichtlichen Report automatisiert zusammenfassen lassen könnten.

https://github.com/PM-Dungeon/dungeon-starter/pull/99#issuecomment-1114486477

**Comment by AKirsch1** [comment]
Closed, weil Duplikat von Kombination aus #409 und #632.
