### ISSUE TITLE
[D2A] Alternative Testmethoden

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#337]
Neben den klassischen JUnit Tests, könnten sich auch alternative Testmethoden als nützlich erweisen.

## Die Nelson-Methode

Die Idee dieser Methode ist es, nicht die konkrete Implementierung zu prüfen, sondern die Ergebnisse zu testen. Dafür wird ein (für die Studierenden unbekannter?) Input-Datensatz durch die definierte Schnittstelle (die Aufgaben müssen entsprechend gestellt sein) eingelesen und von der Studierenden-Lösung verarbeite. Das Ergebnis wird vom Studierenden-Programm ebenfalls exportiert. Das ausgespuckte Ergebnis wird nun mit der Musterlösung verglichen. 

Das Visitor-Pattern könnte eine gute erste Experiment-Aufgabe sein. Der Input ist die Reihenfolge der Spielkarten die in den Baum geladen werden. Die beiden Outputs wären die Ausgabe Inorder und Postorder. 

## JGrade

> A library for grading Java assignments

https://github.com/espertus/jgrade

---
@cagix Ich hatte in Compilerbau schonmal ein Dummy dafür gebaut, existiert das Repository noch? Habe keinen Zugriff mehr auf die Organisation,

**Comment by AKirsch1** [comment]
Ich schließe dieses Issue, da ich die Metriken ab jetzt zentral in #620 sammeln möchte.
