### ISSUE TITLE
[Thesis] Player Analysis

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#340]
Bestimmung der Spielertypen (mit AI?) über kleine Aufgaben, Adaption im Spiel

**Comment by AMatutat** [comment]
Könnte sich gut mit https://github.com/Programmiermethoden/Dungeon/issues/193 kombinieren lassen. 
Ich kriege Aufgaben basierend auf meinen Fachlichenskill und in der Auführung basierend auf meine Spielerischen Vorlieben.
