### ISSUE TITLE
[GAME] Dokumentation Spielelemente Basisspiel

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#342]
Es soll eine grundlegende Dokumentationsstruktur angelegt werden unterhalb von [`doc/`](https://github.com/Programmiermethoden/Dungeon/tree/master/doc), damit in den Issues zum Erstellen der einzelnen fehlenden Spielelemente diese direkt bei der Erstellung mit dokumentiert werden können.

Ziele:
- Überblick über die vorhandenen Spielelemente
- Kurze Einführung in die Nutzung der vorhandenen Spielelemente

Bereits umgesetzte Elemente müssen nachträglich dokumentiert werden - dazu bitte passende Issues erstellen und hier verlinken.

Siehe auch #188

**Comment by AMatutat** [comment]
Für die Nachträgliche Dokumentation habe ich die SHKs beauftragt. Nach dem Prinzip: Wer es als erstes anpackt muss es Dokumentieren.

**Comment by AMatutat** [comment]
> Überblick über die vorhandenen Spielelemente

gibt es:
Die wohl wichtigsten: 
https://github.com/Programmiermethoden/Dungeon/tree/master/doc/ecs/components
https://github.com/Programmiermethoden/Dungeon/tree/master/doc/ecs/systems

Das updaten gehört zu 

https://github.com/Programmiermethoden/Dungeon/issues/1024

> Kurze Einführung in die Nutzung der vorhandenen Spielelemente

#178 und #1025. spliiten das Issue in `core` und `contrib` Javadoc.


Ich mach hier mal zu als "not planned", da "done" etwas weit gegriffen wäre
