### ISSUE TITLE
[GAME] Setter für Strategy-Pattern Methoden?

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#353]
Diese Methode ist konzeptionell fragwürdig: Sollte der Callback nicht beim Erstellen der Component fest sein (und bleiben)? Gibt es einen Use-Case für das Ändern des Callbacks in der HealthComponent zu einem späteren Zeitpunkt? Im Code habe ich nur einen Test gefunden, sonst wird die Methode nicht verwendet.

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/245#discussion_r1106714153_

Anmerkung André: Fragestellung kann auf alle Strategy-Pattern Methoden übertragen werden.

**Comment by AMatutat** [comment]
Um die möglichen Optionen festzuhalten:

1. Es bei setter Methoden belassen
2. Setter erst bei bedarf einfügen (YAGNI), aber das widerspricht etwas dem Framework Gedanken
3. Regel: Wenn ich die Strategy Pattern Methoden verändern möchte, dann muss ich mir halt ein neues Component anlegen und das alte löschen. Hier müssen dann aber alle anderen Daten übertragbar sein.

**Comment by cagix** [comment]
Framework ist ein Punkt. 

Andererseits kann man irgendwie nicht alle Interaktionsmöglichkeiten vorhersehen - das spricht für mich definitiv für YAGNI. Zumal im Moment eigentlich unklar ist, welche Aufgaben wir mit dem Framework (und wie) umsetzen möchten.

Mein Vorschlag wäre, entweder die Kunden das selbst implementieren zu lassen (die können ja gern die vorhandenen Framework-Components ableiten und erweitern) oder eben bei Bedarf die konkrete Component in einen Copy-Ctor zu stecken und damit ein neues Objekt zu erzeugen. (Meine Vermutung ist, wer diese Möglichkeit wirklich braucht, muss ohnehin auch das jeweilige System anpassen bzw. ableiten und erweitern.) Oder eben die ganzen Möglichkeiten dann nachzupflegen, wenn wir wissen, dass wir sie brauchen.

**Comment by AMatutat** [comment]
> Andererseits kann man irgendwie nicht alle Interaktionsmöglichkeiten vorhersehen - das spricht für mich definitiv für YAGNI. Zumal im Moment eigentlich unklar ist, welche Aufgaben wir mit dem Framework (und wie) umsetzen möchten.

Da bin ich bei dir. 

> Mein Vorschlag wäre, entweder die Kunden das selbst implementieren zu lassen (die können ja gern die vorhandenen Framework-Components ableiten und erweitern) 

Dann müssten man nur alle Attribute "protected" setzen. Find ich aber auch gut. Hatte ich irgendwann mal im PM-Dungeon auch vorgeschlagen.

**Comment by cagix** [comment]
> Dann müssten man nur alle Attribute "protected" setzen. Find ich aber auch gut. Hatte ich irgendwann mal im PM-Dungeon auch vorgeschlagen.

Passt vielleicht auch eher zum Framework-Gedanken - einerseits haben wir ne API, die direkt genutzt werden kann, andererseits sollte/darf es auch Strukturen geben, die man ableiten und erweitern kann. Und `protected` ist halt der Weg des Java (zugegeben etwas häßlich - aber was soll's).

**Comment by AMatutat** [comment]
Duplicate #850
