### ISSUE TITLE
[GAME] Skilltree Menü 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#354]
Eine GUI für #229 

[Beispiel](https://creately.com/static/assets/landing/templates/block-diagram-skill-tree-ddmW9a3aC2q-thumb.svg)

---
## Bounty

Für dieses Bounty muss erst #229 gelöst sein. 
Zu diesem Bounty gehören die Erarbeitung eines Konzeptes und die Umsetzung. 

--- 

#Time:17

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
