### ISSUE TITLE
[GAME] Skills erstellen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#355]
Ein paar konkrete Implementierungen für Skills (dafür braucht es #125  #24 #126):

- `Heal` stellt ein paar Trefferpunkte wieder her
- `Firewall` schießt einen Feuerball, macht beim Auftreten Fire Damage
- `Iceball` schießt einen Eisball und verlangsamt getroffene Gegner für eine gewisse Zeit
- `NahkampfHieb` schlägt vor sich und macht Schaden 
- `Sprint` erhöht kurzeitig die Bewegungsgeschwindigkeit der Entität

Dazu gehören dann auch nette Animationen

---
## Bounty

Dieses Bounty kann von mehreren Teams bearbeitet werden. Die Skills müssen sich aber von den bereits eingereichten Skills unterscheiden. Jedes Team kann nur einmal die Punkte für dieses Bounty bekommen.

--- 

#Time:10

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
