### ISSUE TITLE
Repo Struktur Finalisieren (Projekte richtig nebeneinander legen)

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#358]
Die aktuell noch getrennten Projekte `pm-dungeon` und `game` (das ist da ecs) sollen gemerged werden.
Konkrete Implementierungen in `game` sollen in ein Einges Projekt extrahiert werden. 

Am Ende sollen vier Projekte im Repo liegen
- `game` (das ist das Framework (ECS))
- `dsl`
- `dslToDubgeon`
- `dungeon` (das sind die Projektspezifischen Implementierungen) 

#Time:2

**Comment by cagix** [comment]
@AMatutat Macht es Sinn, `dungeon` und `game` in ein Projekt zu legen? 

Wir werden hier in diesem Projekt immer mit `game` arbeiten, und die Studis in PM wohl auch, oder?

**Comment by AMatutat** [comment]
Könnte man auch machen.

**Comment by cagix** [comment]
> Könnte man auch machen.

Hmmm. Dann anders gefragt: Was wären potentielle Nachteile? Gibt es potentielle Vorteile, die beiden Projekte weiterhin separat zu lassen? ...

**Comment by AMatutat** [comment]
Aus meiner Sicht: 

Vorteil:
- Übersichtlichere Projektstruktur
- Keine "Kommt Feature X lieber in `game` oder `dungeon`"

Nachteil:
- aufgeblähteres Framework für die Studierenden

**Comment by cagix** [comment]
Ein weiterer Vorteil könnte sein, dass man die Dokumentation für die Studis und für uns schlanker halten kann. 

Das "Aufblähen" sehe ich auch, aber das ist vermutlich relativ - das Framework ist eh "groß" und die Studis müssen sich da einlesen und nutzen am Ende vermutlich nur einen Teil davon. Ich glaube, bei einem Merge müssen sie nur andere Dinge lesen - der Fokus geht von den vielen Controllern weg und hin zu Systemen+Components. Vielleicht brauchen sie die Controller und so gar nicht mehr? 

Vielleicht brauchen auch wir die alte Architektur (Controller über alles) gar nicht mehr und könnten die dann bei einem Merge mal rauswerfen? Das wäre sogar ein Vorteil.

Ich stelle mir zusätzlich die Frage, was die Studis konkret machen (können), wo schon so viel da ist - Health war ja mal ne Aufgabe und ist jetzt quasi da. Aber auch ohne Merge sehen die Studis die ECS-Sachen und könnten die einfach nutzen.

Die Vorteile sprechen deutlich für ein Zusammenlegen. 

Also zusammenlegen?
