### ISSUE TITLE
[GAME] Minimap

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#36]
Anzeigen der Levels als Minimap auf dem UI.

https://github.com/Programmiermethoden/Dungeon/discussions/39#discussioncomment-3923241

**Comment by AMatutat** [comment]
- shaperenderer?

**Comment by AMatutat** [comment]
- Bäume
    - beliebig viele Kinder pro Knoten (Schwellwert nach Darstellungsmöglichkeit)
    - Tiefe nach Darstellungsmöglichkeit

- Graphen
    -  nur planare Graphen 
    - maximal anzahl an knoten und kanten nach Darstellungsmöglichkeit
 
Other:
- Kanten sollten Farbig werden und Türen haben dann die Farbe der Kante
- Im HUD minimap ausschnitt (aktueller raum + nachbarn)
- Per Tastentdruck Karte öffnen, ganzen Graphen

**Comment by AMatutat** [comment]
@AHeinisch hilft das?

**Comment by AHeinisch** [comment]
Ja, das klingt nach ausreichenden Informationen

**Comment by AMatutat** [comment]
[Planasierungsalgorithmen](https://www.researchgate.net/publication/321058412_Konflikte_vermeiden_Planarisierungsalgorithmen_fur_Graphen_im_Praxistest)

**Comment by AMatutat** [comment]
@AHeinisch Nach discussion: Bitte einmal die Rechercheergebnisse hier festhalten.

**Comment by AHeinisch** [comment]
Hier mal ein paar Erkenntnisse zu den Graphen Baum Planar darstellen.
ForceDirected Graph Darstellungen für Graphen:
Eades und FruchtermanReingold können Graphen erstellen, die nicht immer planar sind dafür brauchen diese Keine extra Algorithmen für feste Knoten.
Tutte brauch damit es planar ist feste Knoten und dazwischen wird ein Netz gespannt.
Der Walker Algorithmus wäre für das Zeichnen von Bäumen besser, da er dafür entwickelt worden ist. Das Problem ist, dass der Original-Algorithmus nicht mehr aufzufinden. Sondern nur noch, wie der verbesserte Walker Algorithmus den grundlegenden optimiert. 

Für Demonstrationszwecke werde ich den Tutte Algorithmus implementieren.

Dieser hat aber bereits bekannte Schwächen. Z.b. können bei schlecht gewählten festen Koordinaten die Knoten übereinander liegen. Bzw. planare Eigenschaft nicht gegeben. Oder dass überhaupt vom Graphen Knoten mit Koordinaten versehen werden müssen, damit der Graph überhaupt gespannt wird.

Damit die Minimap auch später beliebige Symbole für die Räume haben kann, würde es sich dafür anzubieten eine Art Raum Renderer anzubieten z.b. Buchstabenraum oder Symbolraum welche dann auf der Minimap im Graphen an der richtigen Stelle ein Zeichen setzen.
