### ISSUE TITLE
Alte Wiki Einträge überarbeiten und eintragen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#361]
Das Wiki aus dem PM-Dungeon beinhaltet einige wichtige Einträge, diese sollten in das aktuelle Wiki übertragen werden. 

#Time:2

**Comment by cagix** [comment]
@AMatutat Wenn Du beschreiben würdest, was das genau ist und wo das hin soll, könnte das ein SHK-Label bekommen.

**Comment by AMatutat** [comment]
Ich will die Einträge aber erst sichten und filtern was überhaupt noch gebraucht wird. Daher mach ich das lieber selber

**Comment by AMatutat** [comment]
War einfacher als Gedacht. Ein Teil war schlichtweg unnütz für das neue Projekt und den anderen Teil konnte ich nahezu 1 zu 1 übernehmen. 
Ist erledigt
