### ISSUE TITLE
[API] Signatur-Informationen in `FunctionType` für Event-Handler Funktionen festhalten

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#366]
#97 fordert, dass Event-Handler Funktionen per DSL definiert werden können, welche vom Dungeon aufgerufen werden, wenn für eine `Entity` ein bestimmtes Event auftritt. Ein Beispiel hierfür ist die Methode `ICollide::onCollision`, welche vom `HitboxComponent` aufgerufen wird, falls die hitbox mit einem anderen `HitboxComponent` kollidiert. Eine Skizze, die die Verwendung solcher Event-Handler Funktionen im Kontext eines größeren DSL-Programs andeutet, ist [hier](https://github.com/Programmiermethoden/Dungeon/issues/197#issuecomment-1412144121) zu finden.

Damit eine DSL Funktion als Event Handler in einer Komponente registriert werden kann, muss die Signatur der DSL Funktion mit der auf der Dungeon erwarteten Signatur übereinstimmen. Für `ICollide::onCollision` wäre das die folgende:
```java 
    void onCollision(Entity a, Entity b, Tile.Direction from)
```

Im Rahmen der semantischen Analyse muss überprüft werden, ob diese geforderte Signaturübereinstimmung zutrifft (Anmerkung: das wird dann mal Teil des Typecheckings, das es **aktuell noch nicht gibt**). Dafür ist auch zu bedenken, dass im obigen Beispiel `Entity` und `Tile.Direction` auf DSL-Typen gemappt werden müssen (analog zu [Doku: Typebuilding](https://github.com/Programmiermethoden/Dungeon/blob/master/doc/dsl/typebuilding.md)).

#364 fügt einen `FunctionType`-Typ hinzu, in dem Signatur-Informationen festgehalten werden. Es sollte ein Mechanismus geschaffen werden, um aus der Java-Definition der Funktion so eine `FunctionType`-Instanz zu generieren. Intuitiv denke ich da an Annotations. Das sollten wir allerdings im nächsten Meeting besprechen.

#Time: 3

**Comment by malt-r** [comment]
@cagix @AMatutat @bcg7 hier würde ich gleich im Meeting gerne drüber sprechen.

**Comment by cagix** [comment]
@malt-r Und? Was kam im Meeting raus? Warum aktualisierst Du Dein Ticket nicht?

**Comment by malt-r** [comment]
Wie im Meeting besprochen, kann hierfür der Annotation-basierte Ansatz verfolgt werden, da das mit den bereits vorhandenen Mechanismen zum Typebuilding (bspw. `@DSLType`-Annotation) konsistent ist.
