### ISSUE TITLE
KI Aufgabentyp finden 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#369]
Für diesen Aufgabentypen brauchen wir eine Aufgabe aus dem Modul KI.
Wir müssen einen Aufgabentypen aus den Modul finden und eine passende Umsetzung als Spielquest konzeptionieren. 
Daraus leiten sich dann die weiteren Issues ab.

**Comment by cagix** [comment]
@AMatutat @malt-r Ich bin mir nicht so richtig sicher, vermutlich habe ich im Meeting was gesagt und mein Mikro war aus oder so. Ich kann mich deutlich erinnern, dass ich was mit "KI würde die Themen Suche und CSP hergeben" gesagt habe. Meint ihr das mit "freies Modul"?

**Comment by AMatutat** [comment]
> Ich bin mir nicht so richtig sicher, vermutlich habe ich im Meeting was gesagt und mein Mikro war aus oder so. Ich kann mich deutlich erinnern, dass ich was mit "KI würde die Themen Suche und CSP hergeben" gesagt habe. Meint ihr das mit "freies Modul"?

Ich habe das als Vorschlag aufgenommen, um mal in die Richtung zu gucken nicht als "das will ich haben". Anders als BC, die sich dort klar ausgedrückt hat.

> Ich bin mir nicht so richtig sicher, vermutlich habe ich im Meeting was gesagt und mein Mikro war aus oder so. Ich kann mich deutlich erinnern, dass ich was mit "KI würde die Themen Suche und CSP hergeben" gesagt habe. Meint ihr das mit "freies Modul"?

Interpretiere ich das falsch oder ist das passiv Aggressiv?

**Comment by cagix** [comment]
> > Ich bin mir nicht so richtig sicher, vermutlich habe ich im Meeting was gesagt und mein Mikro war aus oder so. Ich kann mich deutlich erinnern, dass ich was mit "KI würde die Themen Suche und CSP hergeben" gesagt habe. Meint ihr das mit "freies Modul"?
> 
> Ich habe das als Vorschlag aufgenommen, um mal in die Richtung zu gucken nicht als "das will ich haben". Anders als BC, die sich dort klar ausgedrückt hat.

naja, dann kam das wohl falsch an. ich meinte schon, dass das geeignete kandidaten sind. klarer krieg ich das grad nicht gesagt :)

**Comment by AMatutat** [comment]
@malt-r kannst du einmal durch die Issues im milestone gehen und aus"Aufgabentyp #3" ein "KI Aufgabentyp" machen?

**Comment by malt-r** [comment]
gemacht

**Comment by AMatutat** [comment]
duplicated with #390
