### ISSUE TITLE
[AUFGABEN] Kombinieren:  Bewertung definieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#374]
Wie werden die Lösungen des Spielers für den Aufgabentypen "Kombinieren" ausgelesen?
Wie werden diese BewerteT?

**Comment by malt-r** [comment]
Ich setze hier mal den Assignee auf @AMatutat , da wir die Bewertung (wie in #1059 angesprochen) erstmal als native Funktion im Dungeon umsetzen.

**Comment by malt-r** [comment]
"Kombinieren" wurde mit "Ersetzen" zusammen gelegt (https://github.com/Programmiermethoden/Dungeon/issues/507)
