### ISSUE TITLE
[AUFGABEN] Kombinieren:  API definieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#375]
Welche Anforderungen an die API gibt es für den Aufgabentypen "Kombinieren". 
Welche Informationen müssen von der DSL in. das Spiel?
Welche Informationen müssen als dem Spiel in die DSL?
Welche nativen Funktionen erden benötigt?

**Comment by malt-r** [comment]
"Kombinieren" wurde mit "Zuordnen" zusammen gelegt (https://github.com/Programmiermethoden/Dungeon/issues/507)
