### ISSUE TITLE
[AUFGABEN] Positionieren: DSL Eingabe definieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#377]
Wie sieht die DSL Eingabe für den  Aufgabentyp „Positionieren“ aus? 
Wie wird die Aufgabenstellung angegeben?
Wie wird die Lösung angegeben? 
Gibt es Callback Methoden, wenn ja welche und wofür?

**Comment by malt-r** [comment]
"Positionieren" gibt es als Aufgabentyp nicht mehr und wurde mit "Zuordnen" zusammengelegt.
