### ISSUE TITLE
[AUFGABEN] Positionieren: API definieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#379]
Welche Anforderungen an die API gibt es für den Aufgabentypen Positionieren? 
Welche Informationen müssen von der DSL in. das Spiel?
Welche Informationen müssen als dem Spiel in die DSL?
Welche nativen Funktionen erden benötigt?

**Comment by malt-r** [comment]
"Positionieren" gibt es als Aufgabentyp nicht mehr und wurde mit "Zuordnen" zusammengelegt.
