### ISSUE TITLE
[AUFGABEN|  Kombinieren: DSL Eingabe Definieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#380]
Wie sieht die DSL Eingabe für den  Aufgabentyp „Kombinieren“ aus? 
Wie wird die Aufgabenstellung angegeben?
Wie wird die Lösung angegeben? 
Gibt es Callback Methoden, wenn ja welche und wofür?

**Comment by malt-r** [comment]
Duplikat von #380
