### ISSUE TITLE
[AUFGABEN] Ersetzen: DSL Eingabe Definieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#382]
Wie sieht die DSL Eingabe für den  Aufgabentyp „Ersetzen“ aus? 
Wie wird die Aufgabenstellung angegeben?
Wie wird die Lösung angegeben? 
Gibt es Callback Methoden, wenn ja welche und wofür?

**Comment by malt-r** [comment]
DSL-Eingabe für Aufgabendefinition aus der Diskussion am 23.03.:

```
01: replacement_task t {
02:     elements: [elem1, elem2, elem3,...]
03:     rules: graph {
04:         n1[elements=[elements.0 , elements[1],elem3], order_relevant=true/false]
05:         n2[elements=[elem4,elem5]]
06:         n3[elements=[elem6]
07:         n4[elements=[elem7]
08:
09:         n1 -> n2 [name=ersetzung1]
10:         n2 -> n3 [name=ersetzung2]
11:         n2 -> n4 [name=ersetzung3]
12:
13:     }
14:     sequence: [rules.ersetzung1, rules.ersetzung2]
15: }
```

Erläuterung:
- Zeile 02: Definition aller Elemente, die Teil der Aufgabe sind
- Zeile 04 - 07: Definition der Elementmengen, welche für die Ersetzungsregeln verwendet werden sollen
  - Attribut elements: Liste der Elemente in der Menge, Syntax für Referenzierung der Elemente aus der Definition in Zeile 02 noch unklar
  - Attribut order_relevant: ist die Reihenfolge der Elemente wichtig?
- Zeile 09 - 11: Definition der Ersetzungsregeln: `n1 -> n2 [name=ersetzung1]` bedeutet "Menge n1 (Zeile 04) kann durch Menge n2 (Zeile 05) ersetzt werden, die Regel heißt 'ersetzung1'"
- Zeile 14: Angabe der Reihenfolge, in der die Regeln angewandt werden sollen, das ist nützlich um algorithmisches Verständnis zu überprüfen, da deterministische Algorithmen solche Regeln immer nach der gleichen Reihenfolge anwenden werden

**Comment by malt-r** [comment]
Duplikat von #801
