### ISSUE TITLE
[AUFGABEN] Ersetzen: Bewertung definieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#383]
Wie werden die Lösungen des Spielers für den Aufgabentypen "Ersetzen" ausgelesen?
Wie werden diese BewerteT?

**Comment by malt-r** [comment]
Ich setze hier mal den Assignee auf @AMatutat , da wir die Bewertung (wie in https://github.com/Programmiermethoden/Dungeon/issues/1059 angesprochen) erstmal als native Funktion im Dungeon umsetzen.

**Comment by AMatutat** [comment]
Ursprünglich hatten wir den Gedanken, Teilpunkte für die einzelnen Schritte im Ersetzungsprozess zu vergeben.
Da wird die BEwertungsfunktionen nun nicht mehr über die DSL definieren lassen, können wir nicht festlegen welche Teilschritte überhaupt Punkte geben sollen, und welche Teilschritte zum falschen Weg gehören. 


tldr: Ersetzungsaufgaben werden vorerst wie folgt bewertet: Für jedes Item das der Spieler besitzt/abgibt welches zur Lösungsmenge gehört, gibt es Punkte.

Gibt der Spieler falsche Antworten ab, werden keine Punkte abgezogen. EIn falsch gecratetes Item (also falsche Ersetzung durchgeführt) impliziert das ich ein richtiges Item nicht mehr bekommen kann.

Siehe auch https://github.com/Programmiermethoden/Dungeon/pull/1097
