### ISSUE TITLE
[AUFGABEN] Ersetzen: API definieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#384]
Welche Anforderungen an die API gibt es für den Aufgabentypen Ersetzen. 
Welche Informationen müssen von der DSL in. das Spiel?
Welche Informationen müssen als dem Spiel in die DSL?
Welche nativen Funktionen erden benötigt?

**Comment by malt-r** [comment]
Wird im Wesentlichen durch #801 abgebildet.
