### ISSUE TITLE
[GAME] YAGNI Analyse

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#385]
Wir haben viele Components und Systeme mit Funktionen versehen, die unter "vielleicht brauchen wir das mal", "vielleicht wollen wir ja mal xyz machen". 
Nach dem Motto YAGNI soll jetzt einmal durch alle Components und Systeme durchgeschaut werden und geprüft werden, ob wie wirklich alle Funktionen davon brauchen.
Besonders die seiter und getter könnten in vielen Components unter YAGNI fallen. 
IntelliJ gibt einen auch den Hinweis, ob eine Funktion nie aufgerufen wird. Das ist schonmal ein Indikator. 
Auch haben wir viele Animationen eingeplant, die wir eigentlich nicht haben (z.B sterben Animation)  

Hier soll dann eine Liste mit allen Inhalten erstellt werden die unter YAGNI fallen, mit einer kurzen Begründung warum. 

Danach sprechen wir darüber und entfernen alles, was wir mit mehr wollen. 

#Time: 6

**Comment by cagix** [comment]
@AMatutat Bitte diese Sachen und Entscheidungen unbedingt auch in der Projekt-Doku aufschreiben (wenigstens stichpunktartig). Die Tickets findet man später kaum noch wieder ...

**Comment by cagix** [comment]
Ein zweiter Gedanke: Das Projekt weiss noch gar nicht, was genau benötigt wird. Meine Empfehlung wäre, mit dem Entfernen von existierenden Features zu warten, bis Meilenstein [Quests: Auswahl und Präzisierung der Fragen (-typen)](https://github.com/Programmiermethoden/Dungeon/milestone/23) und insbesondere Ticket https://github.com/Programmiermethoden/Dungeon/issues/393 abgeschlossen sind.

**Comment by JudiTeller** [comment]
Hier mal der Auszug aus unseren YAGNI-Funden zum Diskutieren:

---------------------
|Package: dslToGame |
---------------------
Klasse: TestComponet (leere nicht verwendete Klasse)


------------------------------------
|Package: ecs->componets->ai->fight|
-----------------------------------
Klasse: MeleeAI (selbst nicht verwendet)
Zeile 25 Constructor dieser Klasse (keine Verwendung)


------------------------------------
|Package: ecs->componets->ai->idle|
-----------------------------------
Klasse: PatrouilleWalk (selbst nicht verwendet)
Zeile 52 Constructor dieser Klasse (keine Verwendung)

Klasse: StaticRadiusWalk (selbst nicht verwendet)
Zeile 29 Constructor dieser Klasse (keine Verwendung)


------------------------------------
|Package: ecs->componets->ai->transition|
-----------------------------------
Klasse: AITools
Zeile 186, 207, 208 (fehlende Parameter Beschreibung)

Methode: (wird nirgends verwendet)
public static GraphPath<Tile> calculatePathToHero(Entity entity) {return calculatePath(entity, ECS.hero);}


---------------------------------
|Package: ecs->components->skill|
---------------------------------
Klasse: Skill
45: getAnimation (aktuell nicht funktional genutzt, wird in SkillTest in PR #395 aufgegriffen)


--------------------------
|Package: ecs->components|
--------------------------
Klasse: HitboxComponent
102: getCollideMethod (keine Nutzung)

Klasse: VelocityComponent
47: constructor ungenutzt


------------------------
|Package: ecs->entities|
------------------------
Klasse: Hero
Methoden:
41: heroCollision (aktuell nicht genutzt, fällt stark in "wird vielleicht in naher Zukunft benötigt")

-----------------
|Package: items |
-----------------
Abstrakte Klasse: Item

Methoden: (werden nicht verwendet)
Zeile 83 void setItemType(ItemType itemType) {this.itemType = itemType;}
Zeile 91 void setInventoryTexture(Animation inventoryTexture) {this.inventoryTexture = inventoryTexture;}
Zeile 99 void setWorldTexture(Animation worldTexture) {this.worldTexture = worldTexture;}
Zeile 107 void setItemName(String itemName) {this.itemName = itemName;}
Zeile 115 public void setDescription(String description) {this.description = description;}


-------------------------
|Package: ecs-> systems |
-------------------------
Klasse: CollisionSystem

Zeile 87-88 und Zeile 101-102(fehlende Parameter Beschreibung)
@param hitbox1
@param hitbox2


-----------------
|Package: graph |
-----------------
Klasse: Edge
Methode: (wird nicht verwendet)
Zeile 31 getEdgeType() 

Klasse: Node
Methode:
Zeile 46 public boolean addEdge(Edge edge) {return this.edges.add(edge);} (keine Verwendung des Rückgabewertes)

Klasse: PropertyBag
Methode (keine Verwendung des Rückgabewertes)
Zeile 21 boolean addProperty(String name, Property attr)...


---------------------
|Package: levelgraph|
---------------------
Klasse: GraphLevelGenerator (wird nicht verwendet)?! Möglicherweise Attribute die verwendet werden auslagern
 
Methoden: (werden nicht verwendet)
Zeile 59 getNodeToLevelNode()
Zeile 63 getLevelNodeToNode()
 
--------------------
|Package: mydungeon|
-------------------
Klasse:ECS
Zeile 98-102 if-Anweisung kann vereinfacht werden (bereits erledigt)


----------------
|Package: quest| wird noch benötigt
----------------
Package enthällt nur Prototypen (alle hier enthaltenen Klassen und Methoden sind unvollständig und werden nirgends verwendet)
Interface: Evaluateable 

Abstrakte Klasse: Quest 

Klasse: QuestFactory 


----------------
|Package: room |
----------------
Interface: IRoom
Zeile 16
getLevelNode(); (Methode getLevelNode() wird nirgends verwendet)

Klasse: Room
Zeile 22
Room(Tile[][] layout) {super(layout);} (Constructor 'Room' wird nirgends verwendet)
Zeile 41
addElement(DungeonElement dungeonElement) {elements.add(dungeonElement);} (Methode 'addElement' wird nirgends verwendet)
Zeile 45
public void removeElement(DungeonElement dungeonElement) {elements.remove(dungeonElement);} (Methode 'removeElement' wird nirgends verwendet)

Klasse: RoomGenerator 
Zeile 169
boolean symmetrical = random.nextFloat() < SYMMETRICAL; (Variable "symmetrical" wird nirgends verwendet)
Zeile 581 - 598 
Methode: => Kontrollausgaben mit System.out
printLayout(level.tools.LevelElement[][], level.tools.LevelSize)

**Comment by AMatutat** [comment]
Für die bessere Übersicht und Aufteilung sowie einen besseren Workflow ist dieses Issue gemerged in #1025 und #178.

Je Klasse 1 PR
