### ISSUE TITLE
[GAME] Iteration über Entitäten in der Basisklasse ECS_System implementieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#386]
Aktuell muss jedes System noch eigenständig über die Entitäten iterieren. 
Kann man das in die Basisklasse auslagern?        

> Echt jetzt? Das muss jedes System nochmal selber machen? 
Die Iteration gehört für mich in die Basisklasse, und dort dann ein Aufruf einer abstrakten Methoden, die jedes neue System dann implementieren muss.

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/211#discussion_r1095831674_
           

Passt gut zu #270. 
Hier bitte vorher nochmal genau schauen, ob das in Kombination mit #270 Sinn ergibt. 
Tests müssten dann auch entsprechend geändert werden. 

---

Edit (@cagix): Aus meiner Sicht müsste man vor allem prüfen, ob das mit dem Iterieren wirklich immer so trivial gestaltet ist, also ob man nur eine einfache Iteration hat und dabei einen einfachen Callback (Lambda, Methodenreferenz) aufruft oder ob das deutlich komplexer werden kann. Und es hat für mich nicht unbedingt was mit "funktionalem Handling" zu tun, sondern mit klass. OO-Pattern ("Template-Method"): In der Basisklasse die Hauptschleife zu machen und dabei eine abstrakte Methode aufzurufen, die dann in den ableitenden Klassen entsprechend implementiert wird.

Edit: siehe auch #517, müsste danach vielleicht komplett weggeschmissen werden.

#Time:2

**Comment by cagix** [comment]
@Lena241 @AKirsch1 @AMatutat dieses ticket ist seit zwei wochen assigned, aber unbearbeitet. wo klemmt es und warum?
