### ISSUE TITLE
[Quests] Sammlung der Aufgaben, Darstellung mit konkretem Beispiel

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#391]
Erstellung einer Übersicht: Was ist die Aufgabe, wie sieht ein Beispiel aus?

---

siehe https://github.com/Programmiermethoden/Dungeon/issues/391#issuecomment-1446094494:

> Dieses Ticket hier (https://github.com/Programmiermethoden/Dungeon/issues/391) sollte dann der Sammlung der gefundenen Aufgaben dienen. Dabei muss jede Aufgabe möglichst präzise dargestellt werden, dazu gehört auch ein Beispiel mit konkreten Zahlen/Werten/..., damit man auch in drei Jahren noch weiss, was gemeint war -> Erstellung einer Übersicht.

**Comment by AMatutat** [comment]
## Sortieralgorithmen im Dungeon 

Für das Modul ADS möchte @bcg7 verschiedene Sortieralgorithmen im Spiel abfragen können. 
Das bedeutet der Spieler bekommt eine Menge an Dungeon-Objekten die in die richtige Reihenfolge gebracht werden müssen. 
Bei Sortieralgorithmen können wir nicht das Endergebnis prüfen (dieses ist für jeden Algorithmus gleich), sondern müssen einen oder mehrere Zwischenschritte prüfen, um sicherzustellen, dass der richtige Sortieralgorithmus verwendet wird. 

### DSL Eingabe
@malt-r, die genaue Eingabe kannst du sicherlich besser modellieren als ich, daher führe ich hier nur die Anforderungsliste auf:
- Eingabe einer unsortierten Zahlenmenge
- Eingabe des Aufgabentextes, aus dem sich der zu verwenden Sortieralgorithmus ableitet
- Eingabe der/(aller ?) Zwischenschritte + Finale Lösung.
=> Der Sortieralgorithmus soll nicht im Dungeon/DSL implementiert werden. 

### Ablauf im Spiel (was macht der Spieler)

Für die Umsetzung im Dungeon fallen mir aktuell zwei Szenarien ein. 
Für beide Szenarien wird die abstrakte Zahlenmenge aus der DSL in Dungeon-Elemente umgewandelt. 
Dem Spieler muss aufgezeigt werden, welches Dungeon-Element größer und welches kleiner ist.
Dafür fallen mir zwei Möglichkeiten ein: 

1. Farbkodierung: Jedes Element wird in einer bestimmten Farbe eingefärbt. Per Textbox wird dem Spieler erklärt, das Gelb>Rot>Grün>Lila…. Gilt.
		
  Vorteil: Nachdem die Kodierung gelernt wurde, ist sie auf den ersten Blick erkenntlich. 
		  
  Nachteil: - Kodierung ist „Zufällig“ (Warum ist Rot>Grün?), das macht es schwer sich die Sache zu merken - Beim Einsatz von Farben müssen Faktoren wie Sichtbarkeit und Farbenblindheit beachtet werden, das ist aufwendig und als Außenstehender auch nur schwer einzuschätzen - die Dungeon Elemente müssen in verschiedenen Farben vorliegen, das kostet Zeit

2. Textboxen: Mit jedem Dungeon-Element kann lesend interagiert werden. Der Spieler geht auf das Element zu, drückt einen Knopf und bekommt dann eine Textbox mit dem Zahlenwert des Dungeon-Elementes zu sehen. 
		
  Vorteil: Easy to use, es gibt keine versteckten Stolpersteine 
		  
  Nachteil: Nicht besonders kreativ/immersiv. - Zahlenwerte sind nicht auf den ersten Blick zu erkennen, der Spieler muss erst (oder immer wieder, wenn er ein schwaches Gedächtnis hat) mit den Elementen interagieren, um die Werte zu sehen. 


Wie die Aufgabenstellung dem Spieler angezeigt wird, muss noch geklärt werden, aber dem Spieler wird (irgendwie) der Aufgabentext aus der DSL angezeigt. 

#### Szenario A: Schieberätsel

Der Spieler befindet sich in einem Raum mit verschiedenen Statuen/Blöcken. Dem Spieler wird der Aufgabentext angezeigt. 
Der Spieler muss die Statuen so verschieben, dass sie in der gewünschten Reihenfolge sortiert sind (z. B. dritter Schritt nach Bubble-Sort) 
Welcher Schritt gewünscht ist, wird zufällig bestimmt.

Die Statuen müssen auf speziell markierte Felder geschoben werden. Die Felder repräsentieren die Felder eines Arrays, so kann geprüft werden, welche Statue auf welchen. Feld steht. 
Wenn der Spieler die Statuen verschoben hat, muss er seine Eingabe einloggen. Dafür befindet sich im Raum ein Schalter, mit dem interagiert werden kann. 
Wenn der Spieler mit dem Schalter interagiert, wird er darauf hingewiesen (per Textfenster), dass er damit seine Lösung einloggt und soll dieses nochmal bestätigen (per Button). 

Ist die Lösung richtig, wird der Spieler belohnt und/oder der Weg zum nächsten Level/Raum geöffnet. 
Ist die Lösung falsch, wird der Spieler bestraft und muss seine Lösung verbessern. 

Das Verschieben von Blöcken kostet dem Spieler Zeit. Er muss erst zum Block hinlaufen und diesen dann zum Ziel schieben (für gewöhnlich bewegen diese sich dann auch relativ langsam).
Daher sollten Schieberätsel nicht zu viele Statuen haben (ich denke 4-6 sind noch okay, alles darüber wird nur nervig.) 
Damit der Spieler die Statuen nicht in eine Ecke schieben kann und diese dann dort feststecken, müssen Statuen auch gezogen werden können. 
Daher sollten Schieberätsel auch nur genutzt werden, um **einen** Zwischenstand abzufragen, nicht mehrere. 




Benötigte Features: 
- [ ] Statuen/Blöcke zum Schieben und Ziehen
- [ ] Felder zum Platzieren der Statuen
- [ ] Hebel zum Einloggen der Eingabe
- [ ] Textboxen
- [ ] Bewertungsfunktion (Erkennen der Spielereingabe, interpretieren des Ergebnisses, Belohnen/Bestrafen des Spielers) 
- [ ] Übergeordnetes Objekt zum Verbinden der Aufgabe mit den Elementen, der Bewertungsfunktion und der Belohnung/Bestrafung. 

#### Szenario B: Schalterrätsel 

Der Spieler befindet sich in einem Raum mit verschiedenen Schaltern. Dem Spieler wird der Aufgabentext angezeigt. 
Der Spieler muss die Schalter in der richtigen Reihenfolge bedienen. Die richtige Reihenfolge ergibt sich aus dem erwünschten Sortieralgorithmus.
Die Startreihenfolge ergibt sich aus der Anordnung der Schalter. Um Verwirrung auszuschließen, wird dem Spieler per Textbox auch beschrieben, wie die initiale Reihenfolge ist. 
Der Spieler muss durch das Betätigen der Schalten den gesamten Sortieralgorithmus durchspielen. Damit das ganze nicht zu viel wird, müssen nur die Schritte, bei denen sich etwas ändert durchgeführt werden. 
Bei der Zahlenreihenfolge „4,3,7,2“ nach BubbleSort müssen also die Schalter in der Reihenfolge:
3,4,7,2,
3,4,2,7,
3,2,4,7,
2,3,4,7

Betätigt werden. 
Einen Schalter zum Einloggen oder zurücksetzten der Eingabe braucht es nicht. Sobald der Spieler einen falschen Schalter umlegt, kann er bestraft werden und das Rätsel setzt  sich automatisch zurück. 

Ist die Lösung richtig, wird der Spieler belohnt und/oder der Weg zum nächsten Level/Raum geöffnet. 
Ist die Lösung falsch, wird der Spieler bestraft und muss seine Lösung verbessern. 

Das Schalterrästel ermöglicht es uns, alle Schritte eines Sortieralgorithmus zu prüfen. 
Die Visualisierung der getätigten Schritte erfolgt über die Position der Schalter (ich stelle mir das wie Hebel vor). Am Anfang sind alle Schalter unten, wenn der Spieler mit den Schaltern interagiert, wechseln diese Ihre Position. 
Am Anfang von Schritt zwei sind dann alle Schalter oben, am Anfang von Schritt 3 dann wieder unten usw. 
Wenn ein falscher Hebel umgelegt wird, springen alle Schalter wieder auf die Ursprungssituation.


Benötigte Features: 
- [ ] Schalter/Hebel
- [ ] Textboxen
- [ ] Bewertungsfunktion (Erkennen der Spielereingabe, interpretieren des Ergebnisses, Belohnen/Bestrafen des Spielers) 
- [ ] Übergeordnetes Objekt zum Verbinden der Aufgabe mit den Elementen, der Bewertungsfunktion und der Belohnung/Bestrafung.

**Comment by AMatutat** [comment]
@cagix Ich bin mir nicht 100% sicher ob ich deine Issue Ideen richtig verstanden habe. Ich würde in #390 nach Aufgabentypen suchen und hier (#391) dann Ideen/Beispiele zur Umsetung als Quest Sammeln über die wir dann Diskutieren/Abstimmen. 
#392 #393 wären für mich dann dran, wenn wir uns auf Aufgaben festgelegt haben.

**Comment by cagix** [comment]
Hmmm, jetzt bin ich da auch reingerannt :) ... Zu kleinteilige Issues plus nicht so wahnsinnig gute Formulierung der Aufgabe.

Meine Idee war, dass wir einmal nach möglichen Aufgaben in möglichst vielen Gebieten recherchieren (#390). 

Dieses Ticket hier (#391) sollte dann der Sammlung der gefundenen Aufgaben dienen. Dabei muss jede Aufgabe möglichst präzise dargestellt werden, dazu gehört auch ein Beispiel mit konkreten Zahlen/Werten/..., damit man auch in drei Jahren noch weiss, was gemeint war -> Erstellung einer Übersicht. 

Damit kann man in #392 dann hingehen und die Aufgaben analysieren: Was brauche ich da für die Umsetzung (also in der DSL, welche Spielmechaniken/-elemente könnten relevant sein), was haben wir und was brauchen wir noch. Das wäre auch die Stelle, wo wir entscheiden sollten, welche Aufgaben aus der Sammlung wir in diesem Projekt noch umsetzen wollen/können.

Und in #393 sollte dann konkret festgelegt werden, wie die ausgewählten Aufgaben dann konkret realisiert werden sollen. Ich denke, je Aufgabe sollte es drei Spielmechaniken/-situationen geben, damit es abwechslungsreich genug wird. Vielleicht wird es bei manchen Aufgaben nur zwei sinnvolle Umsetzungen geben, vielleicht wird es bei anderen Aufgaben vier mögliche Umsetzungsvarianten geben - im Mittel sollten es drei pro Aufgabe sein :)

**Comment by AMatutat** [comment]
## Zuordnungsaufgaben für PM

Beschreibung der Idee, siehe: https://github.com/Programmiermethoden/Dungeon/issues/390#issuecomment-1447974543

**Setup** 
Im Level sind mehrere Texttafeln (`n` viele) platziert. Wenn der Spieler mit den Texttafeln interagiert, wird ihm ein bestimmter Text angezeigt (siehe Beispiele). Im Level sind `x` viele (`x>=n`) Schatzkisten mit Lösungs-Items versteckt. Auf jedem dieser Items ist auch ein Text zu finden. Der Spieler muss jetzt das richtige Item an der richtigen Texttafel verwenden/einfügen. 


*Ich mache jetzt immer das Beispiel für eine Texttafel, sonst wird das hier unübersichtlich* 

### Beispiel 1: Bad Smells 

Auf der Texttafel seht:


"Das ist meine Code und mein Code ist schön, oder?"
```java
public class CreditsCalculator {
    public ECTS calculateEcts(Student s) {
        int semester = s.getSemester();
        int workload = s.getCurrentWorkload();
        int nrModuls = s.getNumberOfModuls();
        int total = Math.min(30, workload);
        int extra = Math.max(0, total - 30);
        if (semester < 5) {
             extra = extra * nrModuls;
        }
        return new ECTS(total + extra);
    }
}
```

Auf den Items die der Spieler finden kann steht
- "Das ist ein schöner Code"
- "Feature Neid"
- "Dead Code"
- "Lava Code"
- "Poltergeist" 


## Beispiel 2: Pattern erkennen

Auf der Texttafel im Dungeon ist ein 
![UML](https://github.com/Programmiermethoden/PM-Lecture/blob/master/markdown/pattern/images/command.png)
 zu sehen.
Es gilt das Pattern zu erkennen und zu nennen. 

Auf den Items steht:
- "Command Pattern"
- "Visitor Pattern"
- "Das ist gar kein Pattern"
- "Observer Pattern"

### Bewertung
Zum Bewerten könnte man schauen, wie oft der Spieler versucht hat, ein falsches Item zu verwenden. 


### Anmerkungen
- Texttafeln Varianten können gemischt werden 
  - Eine Tafel mit Text, Code und Bild
  - Mehrere Tafel im gleichen Level mit verschiedenen Typen (Text,Code,Bild)
- Auf Items können auch Code oder Bilder (oder beides) zu sehen sein.  
- Zu einer Tafel können auch mehrere Antworten gehören
- ggf. löschen wir das Item nicht aus dem Inventar, wenn es benutzt wurde. So kann man nicht per ausschlussverfahren vorgehen.

**Comment by AMatutat** [comment]
## CSP und KI

Beschreibung der Idee siehe https://github.com/Programmiermethoden/Dungeon/issues/390#issuecomment-1447930933

### Beispiel Color problem 

**Setup** 
In einen Raum im Level ist ein NPC mit dem man reden kann. Er zeigt einen die
![Landkarte](https://github.com/Artificial-Intelligence-FHB-TDU/KI-Vorlesung/blob/master/markdown/csp/images/map_graph.png) (PS: Wäre richtig cool, wenn das die Level-Karte wäre, aber das ist wohl ehr Sache des Dozenten bei der DSL eingabe)
Für jeden Sektor auf der Landkarte ist eine Schatzkiste im Raum aufgestellt. 

Der NPC sagt, dass er gerne die Karte einfärben möchte und der Sektor C die Farbe Grün bekommen sollen.
*Es folgt eine Erklärung des Color problems* 
(Alternative: Man könnte die Farben und die Bedingung C=Grün auch in CSP "Sprache" formulieren, dann muss der Studi das lesen können)  
Der Spieler bekommt vom NPC ein Item pro Farbe die verwendet werden darf. Die Items kann er beliebig oft verwenden. 

Der NPC sagt: "Verwenden Backtreesearch und zeige mir alle Möglichkeiten für den nächsten Schritt"
Der Spieler muss jetzt in jede Schatzkiste das/die Item(s) legen, welche der Sektor auf der Karte annehmen darf. 

Wenn das erledigt ist, geht er wieder zum NPC und dieser sagt
- "Gut gemacht. Mach jetzt weiter mit D="Blau"
- "Das stimmt nicht du narr, mach es nochmal"

repeat until done 

### Bewertung

Anzahl der falschen Versuche Zählen und dafür Punkte abziehen. 

### Benötigte Dungeon-Elemente

- [ ] NPC
- [ ] "Dialog"-System
- [ ] Schaztzkisten
- [ ] Items
- [ ] Funktion um Items in Schatzkiste zu legen
- [ ] Möglichkeit Bilder anzuzeigen
- [ ] Übergeordnetes Objekt zum logischen Verbinden der Rätsel-Objekte

**Comment by cagix** [comment]
> Das Sortieren mit Farben halte ich für schwierig. Es können auch Buchstaben sein oder n-Ecke, die nach Anzahl der Ecken sortiert werden müssen. Oder irgendwelche Symbole statt Zahlen, also acht Kringel oder Balken auf einem Element.

Ich glaube, "Farben" ist hier nur ein Platzhalter für einen sortierbaren Datentyp, oder?
