### ISSUE TITLE
[GAME] IJ Warnings fixen 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#397]
IntelliJ gibt einen gerne einige Hinweise, wie man seinen Code nochmal optimieren kann.
Daher einmal in jede Klasse gehen und schauen was IJ so Anzumerken hat und ob das sinnvoll ist.
Wenn ja, umsetzten, wenn nicht: Begründen. 
Die #385 fällt da bestimmt auch mit rein. 
WICHTIG: Das soll kein "Alles klar wenn IJ das sagt, dann machen wir das so" werden. Es geht um sinnvolle Verbesserungen, 
Zum einarbeiten in das Dungeon scheint mir das eine gute Übung zu sein.

**Comment by cagix** [comment]
> IntelliJ gibt einen gerne einige Hinweise, wie man seinen Code nochmal optimieren kann.
> Daher einmal in jede Klasse gehen und schauen was IJ so Anzumerken hat und ob das sinnvoll ist.
> Wenn ja, umsetzten, wenn nicht: Begründen.
> Die #385 fällt da bestimmt auch mit rein.
> WICHTIG: Das soll kein "Alles klar wenn IJ das sagt, dann machen wir das so" werden. Es geht um sinnvolle Verbesserungen,
> Zum einarbeiten in das Dungeon scheint mir das eine gute Übung zu sein.

@AMatutat Könntest Du hier zwei Beispiele geben, wo Du eine IJ-Anmerkung sinnvoll findest und wo nicht, damit @dkirshner ein besseres Gefühl für die Aufgabe bekommt?

**Comment by AMatutat** [comment]
Gute Idee

Also (fast immer) sinnvoll finde ich: 
- `Field XYZ may be final`
- Vereinfachung von Statements oder verwenden von Lambda Ausdrücken
- Missing JavaDoc
- Typos sowieso

Genau angucken muss man sich
- ` XYZ is never used`, das ist im Grunde #385 
- `Raw use of parameterized class XYZ`

Er meckert auch gerne über den Namen `ECS_System`, das würde ich aber so stehen lassen. `ECSSystem` liest sich doof, `EcsSystem` find ich auch und `System` geht ja eh nit, weil Java System.

**Comment by cagix** [comment]
> Raw use of parameterized class XYZ

Hast Du hier ein Beispiel, wo das nicht sinnvoll war bzw. man sich das nochmal genau anschauen sollte? In meiner Erfahrung sollte man generische Klassen niemals nie direkt "raw" einsetzen ...

**Comment by AMatutat** [comment]
Wir haben z.B sowas

```java
public class LevelNode<T extends IRoom> ....

    public boolean connect(LevelNode other) {
        Collections.shuffle(toTry);
        for (DoorDirection direction : toTry) {
            if (tryConnect(other, direction)) return true;
        }
        return false;
    }
```

IJ hätte dann gerne
`public boolean connect(LevelNode<?> other)` 

Bin innerlich Zwiegestalten und hab da keine so richtig feste Meinung zu.

**Comment by cagix** [comment]
Hmmm. Für mich wäre das definitiv mit Typ-Parameter, also das, was IJ da auch vorschlägt. Generische Typen sollten immer als solche erkennbar sein aus meiner Sicht.

Wobei das interessant ist: IJ sagt ja `LevelNode<?>` statt `LevelNode<T extends IRoom>`, d.h. es würde hier in der Methode einen beliebig parametrisierten `LevelNode` akzeptieren. Allerdings darf es lt. Klassendefinition nur `LevelNode` mit von `IRoom` abgeleiteten Typ-Parametern geben. Vermutlich ist das stärker als das `?` in der Methode, dennoch irgendwie unschön.

**Comment by AMatutat** [comment]
@AMatutat du musst eine, dann für alle gültige Konfiguration, erstellen/angeben

**Comment by cagix** [comment]
@AMatutat wieso ist hier "meeting" dran?

**Comment by cagix** [comment]
@AMatutat intellij hat in der aktuellen version wahnsinnig viele "bugs" (anmerkungen). wir sollten hier tatsächlich eine bestimmte auswahl festlegen. 

anschließend muss das einfach mit behoben werden, wenn eine klasse angefasst wird. wie auch die ergänzung des javadoc.

**Comment by AMatutat** [comment]
Wäre jetzt für mich duplicate mit #605
