### ISSUE TITLE
[GAME] Fix DungeonCamera Tests

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#403]
Die Tests in `graphic/DungeonCameraTest` schlagen fehl (obwohl die Funktionalität gegeben zu sein scheint). 
In den Tests wird Mockito und PowerMock verwendet. Vielleicht liegt hier das Problem. 

Es muss sich jemand die Tests anschauen und reparieren. Wenn dabei PowerMock und/oder Mockito rausfliegen, um so besser.

#Time:3

**Comment by cagix** [comment]
**PowerMock sollte definitiv rausfliegen**. Das wird nicht im Gegensatz zu Mockito mehr vernünftig maintained im Moment.

Den Einsatz von Mockito sollten wir aber auch nach Möglichkeit in Grenzen halten.
