### ISSUE TITLE
Dungeon-Aufgaben: Lösungsskizzen erstellen

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#406]
Für die Dungeon-Aufgaben sollte es eine Art Lösungsskizze geben: Was muss gemacht werden, wie könnte man das angehen, worauf muss man achten?

**Comment by AMatutat** [comment]
Da wir (noch) keine festen Aufgaben (mehr) haben, kann man auch keine Lösung erstellen.
