### ISSUE TITLE
[D2A] Unit-Tests für die Beispiel Tasks

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#408]
Für die beiden Beispiel Tasks gibt es noch keine Tests.

- [x] Programmiermethoden/Homework-Solutions#49
- [x] Programmiermethoden/Homework-Solutions#50

**Comment by AKirsch1** [comment]
Da beide hier genannten Issues gelöst sind, würde ich das hier schließen.
