### ISSUE TITLE
[PITCH] DSL Eingabe grob-Skizzieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#41]
Dokumentieren in https://github.com/Programmiermethoden/Dungeon/discussions/39

**Comment by malt-r** [comment]
Siehe https://github.com/Programmiermethoden/Dungeon/discussions/39#discussioncomment-3927309

**Comment by AMatutat** [comment]
siehe https://github.com/Programmiermethoden/Dungeon/discussions/39#discussioncomment-3927309
