### ISSUE TITLE
[D2A] Weitere Metriken

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#410]
Aktuell haben wir folgende Bewertungskriterien bestimmt
- JUnit
- Format (Checkstyle)
- Metriken (Spotbugs)
- Test ala Nelson
- [JPlag](https://github.com/Programmiermethoden/Dungeon/issues/410#issue-1605102226)

Gibt es weitere? Welche Aspekte der Programmierung decken diese ab? Wie integrieren wir diese in unsere bestehende Toolchain?

**Dieses Issue ist als Sammelbecken für Ideen zu verstehen.**

**Comment by cagix** [comment]
@AKirsch1 Du kannst ja in diesem Ticket die Ideen sammeln. Wenn Du einen Rat haben willst: Packe die Erkenntnisse immer wieder in den ersten Kommentar ganz oben (via "edit"). Nur so behältst Du eine Übersicht :)

**Comment by AKirsch1** [comment]
Ja, zum Sammeln hatte ich es hier auch rein geschrieben. Habe es jetzt auch oben ergänzt

**Comment by AKirsch1** [comment]
Ich schließe dieses Issue, da ich die Metriken ab jetzt zentral in #620 sammeln möchte.

**Comment by AKirsch1** [comment]
... als Duplicate

**Comment by AKirsch1** [comment]
... als Duplicate
