### ISSUE TITLE
[D2A] Observer: Ordnerstruktur

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#414]
Wir sollten die Erstellung der Tests und das Aufbauen des Deploy-to-Abgabe gleich für eine Restrukturierung der Aufgaben nutzen.

Am Beispiel Observer: Wir haben derzeit diese Struktur:

```
.
|____vorgabe/
| |____test/
| | |____EinzelhandelTest.java
| | |____GrosshandelTest.java
| | |____AuftragTest.java
| |____src/
| | |____WarenTyp.java
| | |____Grosshandel.java
| | |____Einzelhandel.java
| | |____Main.java
| | |____Auftrag.java
|____loesung/
| |____test/
| | |____EinzelhandelTest.java
| | |____GrosshandelTest.java
| | |____AuftragTest.java
| |____src/
| | |____WarenTyp.java
| | |____Grosshandel.java
| | |____Einzelhandel.java
| | |____IObserver.java
| | |____Main.java
| | |____IObserveable.java
| | |____Auftrag.java
|____aufgabe.md
```

Dabei ist problematisch, dass aus dem Ordner `vorgabe/` mindestens die Tests und Teile des Vorgabecodes nach `loesung/` kopiert werden. Zusätzlich ist problematisch, dass direkt im Vorgabecode editiert wird. 

Besser wäre eine Trennung in `test/`, `vorgabe/` und `loesung/`. Dabei wären die Tests und die Vorgaben quasi schreibgeschützt, d.h. hier dürfen die Studis keine Änderungen machen. Die Implementierung der Studis erfolgt dann im Lösungsordner. Für Gradle müsste man dann sowohl `vorgabe/` als auch `loesung/` als Source-Ordner und `test/` als Test-Ordner deklarieren und kann alles gemeinsam kompilieren.

Das würde bedeuten, dass man die Vorgaben einem Refactoring unterziehen müsste und diese als Schnittstellen oder abstrakte Klassen bereit stellt, auf die sich die Lösung dann bezieht.

Ggf. dann noch mit einem `src/`-Unterordner oder der typischen Maven-Struktur.

**Comment by AKirsch1** [comment]
Closed as not planned in favour of #622.
