### ISSUE TITLE
[D2A] Command Line Argument für Target-Repo location 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#422]
Aktuell ist sowohl Name als auch Pfad zum Target-Repo (das wo die Lösungen liegen) hardcoded.
Für die Action ist das kein Problem, da wir hier unsere eigene Orderstruktur erstellen können, auch für Programmiermethoden/Dungeon#416 ist das okay.
Aber für Programmiermethoden/Dungeon#415 nicht, damit wollen die Studierenden ihr Repo "testen" und dafür sollten sie nicht gezwungen sein den Namen ihres Workingdirs zu ändern.

tldr: Das Python-Skript soll um ein Command-Line-Argument für den Pfad zum Target-Repo ergänzt werden.

**Comment by AKirsch1** [comment]
Da das hier Kleinkram beim Python-Skript ist, das in der Form wahrscheinlich eh nicht weiter verwendet wird, schließe ich dieses Issue als Not planned.
