### ISSUE TITLE
[D2G] Ausgabe der Ergebnisse 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#423]
Folgende Ergebnisse sollen in der Action nach ablau des Skriptes ausgegeben werden.

- [ ] Studi-Punkte: Eine Tabelle mit Mail des Studis, Task, Erreichte Punkte, Gesamt Punkte
- [ ] Für jeden Task die erzeugten `.xml` -Files
  - [ ] JUnit
  - [ ] Spotbugs
  - [ ] Checkstyle
  - [ ] Spotless

**Comment by AKirsch1** [comment]
Wird ersetzt durch #631.
