### ISSUE TITLE
Gradle-Konfiguration refactoren

### ISSUE THREAD

**Issue by tgrothe** [Programmiermethoden/Dungeon#426]
Wir sollten:

- "-verwenden, wo möglich
- `id "com.diffplug.spotless" version "6.+"` verwenden
- NotNull-Annotationen hinzufügen
- gradle.properties richtig formatieren
- sourceSets vereinfachen

**Comment by AMatutat** [comment]
Dat sieht irgendwie sehr outdated aus. 
Und @NotNull haben wir schon mehrfach gekillt. 
Ich mach zu

**Comment by tgrothe** [comment]
👀 wurde per 📫 benachrichtigt

**Comment by AMatutat** [comment]
> 👀 wurde per 📫 benachrichtigt

@tgrothe okay jetzt musste ich lachen ^^ Könnte heut noch ein paar mal vorkommen. Ich mach grade Frühjahrs Putz

**Comment by tgrothe** [comment]
> > 👀 wurde per 📫 benachrichtigt
> 
> @tgrothe okay jetzt musste ich lachen ^^ Könnte heut noch ein paar mal vorkommen. Ich mach grade Frühjahrs Putz

@AMatutat ok, kein Ding und gutes Gelingen dabei ;)
