### ISSUE TITLE
[D2A] Alle relevanten Dokumente in den Vorgabe-Ordner duplizieren, damit die Studis diesen mit ausgeliefert bekommen.

### ISSUE THREAD

**Issue by AHeinisch** [Programmiermethoden/Dungeon#427]
Damit beim git subtree alle relevanten Dokumente mit zur Studi-Vorgabe transferiert werden, müssen diese in den vorgabe Ordner kopiert werden. Nicht verschoben, da beim Verschieben sie nicht mehr für dieses Repo greifen.

- [x] .gitignore
- [x] .gitattributes
- [x] .editorconfig
- [ ] license 
- [ ] README.md <- Studi Repo Beschreibung

**Comment by cagix** [comment]
@AMatutat was ist mit diesem ticket? das ist doch längst gelöst, oder?

**Comment by cagix** [comment]
ist das d2a?
