### ISSUE TITLE
[D2A] Testen, ob die .editorconfig auch bei Subprojekten in den IDEs greifen

### ISSUE THREAD

**Issue by AHeinisch** [Programmiermethoden/Dungeon#428]
Da IDEs aus jeden Subprojekt ein Modul machen muss einmal kontrolliert werden, ob die .editorconfig vom rootprojekt greift oder ob jedes Subprojekt diese Datei benötigt.

**Comment by AMatutat** [comment]
Bezieht sich auf die Sturktur im Homework-Solution Repo

**Comment by cagix** [comment]
> Bezieht sich auf die Sturktur im Homework-Solution Repo

Sollten wir ein Label für die Ziel-Repos einführen?

**Comment by AMatutat** [comment]
> Sollten wir ein Label für die Ziel-Repos einführen?

Das klingt so falsch. 
Das kann halt wirklich nicht der weg sein, aber außer "guck halt auf die Transfer History" hab ich nix besseres.

**Comment by cagix** [comment]
> > Sollten wir ein Label für die Ziel-Repos einführen?
> 
> Das klingt so falsch. Das kann halt wirklich nicht der weg sein, aber außer "guck halt auf die Transfer History" hab ich nix besseres.

Ja, fühlt sich falsch an. Ist aber letztlich die Folge, dass wir die Tickets und Milestones nur in einem Repo pflegen wollen (was irgendwie auch wieder sinnvoll ist).

**Comment by cagix** [comment]
@AMatutat was ist mit diesem ticket? warum ist das immer noch offen?

**Comment by AMatutat** [comment]
Das Issue hängt mit der D2G zusammen. 
Die Idee war damals, dass jede Aufgabe ein eigenes Sub-Projekt ist. 
Es gibt also das große "Homework"-Project und da liegen die ganzen Aufgaben drinnen.

**Comment by AKirsch1** [comment]
Laut [editorconfig-Dokumentation](https://editorconfig.org/) wird im Verzeichnis der zu formatierenden Datei und dessen Parent-Verzeichnissen nach einer `.editorconfig` gesucht. Die Suche wird gestoppt, wenn eine `.editorconfig` mit dem Inhalt `root = true` gefunden wurde oder das `root`-Verzeichnis erreicht wurde.

In unserem Fall bedeutet das, dass die `.editorconfig` im Homework-Solutions-Repository aktuell für alle Unterprojekte greift. Im Falle des Dungeon-Projekts klappt dies nicht mehr. Ich vermute, dass das damit zusammenhängt, dass hier Gradle konfiguriert ist und somit da `root`-Verzeichnis gegeben ist. Die IntelliJ-Einstellung [`editor.config.stop.at.project.root`](https://youtrack.jetbrains.com/issue/IDEA-148199) hat bei mir da auch keinen Unterschied gemacht. Es funktioniert aber, wenn ich den darüber liegenden Ordner öffne.

Fazit: Nach meinen Tests müsste in jeden Aufgabenordner eine eigene `.editorconfig`.

**Comment by cagix** [comment]
> Fazit: Nach meinen Tests müsste in jeden Aufgabenordner eine eigene .editorconfig.

blöd, aber damit kann ich gut leben. das ist nur eine kleine textdatei, die auch nie angepasst werden muss ...

**Comment by AKirsch1** [comment]
Da die Frage geklärt ist, schließe ich das hier jetzt.

**Comment by cagix** [comment]
> Da die Frage geklärt ist, schließe ich das hier jetzt.

Du hast es ja auch bereits bei der Diskussion des Task-Layouts berücksichtigt, wenn ich das richtig in Erinnerung habe, oder?

**Comment by AKirsch1** [comment]
> Du hast es ja auch bereits bei der Diskussion des Task-Layouts berücksichtigt, wenn ich das richtig in Erinnerung habe, oder?

Ja, `.editorconfig` liegt auch dort im Task-Ordner. (Hatte ich vorher schon so drin.)
