### ISSUE TITLE
[D2A] Mappen der Toolchain-Ergebnisse auf Punkte

### ISSUE THREAD

**Issue by AHeinisch** [Programmiermethoden/Dungeon#429]
Fragen, die beim Einlesen im Abgabe Skript entstanden sind.

Welche Art vom Mapping der Ergebnisse der Tools werden benötigt?
 - Schwellwert oder Linear 
 - Alle Punkte an einem Tool verlieren oder nur bis zu bestimmten Punkten
 - Für alle Task identisch oder pro Task ein eigenes Mapping oder ein überschreibbares Mapping
 - Wie soll die Struktur für diese Konfiguration aussehen

Durch die neue Tabelle von https://github.com/Programmiermethoden/Homework-Solutions/pull/65#issuecomment-1225279752 muss noch geguckt werden, wie die User, die an einem Task beteiligt waren am Ende beim Export zur Verfügung gestellt werden.

**Comment by AKirsch1** [comment]
Ich schließe hier, da die Definition der Punktevergabe jetzt Teil von #623 ist.
