### ISSUE TITLE
[Game] Gradle Plugins und libs stärker beschränken

### ISSUE THREAD

**Issue by AHeinisch** [Programmiermethoden/Dungeon#430]
Da spotless uns im PM-Dungeon bereits einen Fehler wirft, sollte vielleicht nochmal alle libs die wir nutzen stärker eingeschränkt werden, damit nicht solche Fehler kommen, sobald mal ein Update von diesen im Semester kommen und alle in Panik gehen. Bzw. wenn die Auswertung gemacht wird.

Aktuell wurden folgende Plugins wie folgt beschränkt:
    id "com.diffplug.spotless" version "6.+"
    id "com.github.spotbugs" version "5.+"
Und libs wie folgt:
        // https://mvnrepository.com/artifact/org.jetbrains/annotations
        implementation "org.jetbrains:annotations:23.0.0"
        // https://mvnrepository.com/artifact/junit/junit
        testImplementation "junit:junit:4.13.2"

        // https://mvnrepository.com/artifact/org.powermock/powermock-module-junit4
        testImplementation "org.powermock:powermock-module-junit4:2.+"
        // https://mvnrepository.com/artifact/org.powermock/powermock-api-mockito2
        testImplementation "org.powermock:powermock-api-mockito2:2.+"

spotless hat zwei Abhängigkeiten, und zwar spotless-lib und spotless-lib-extra. for spotless 6.11 werden die libs in Version 2.30 benötigt, welches aktuell nicht existiert. Darum muss einmal zurückgegangen werden zu 6.10.+, damit keine Abhängigkeitsfehler existieren.

Edit: Im aktuellen Build-Skript steht
```
    id "com.github.spotbugs" version "5.0.+"
    id "com.diffplug.spotless" version "6.5.+"
```

Um hier zu zu machen, einmal die neusten Versionen von Spotbugs und Spotless raussuchen, inclusive. der letzten Versionsnummer Eintragen und Testen (denkt daran temporäre Files zu löschen). 

#Time:1

**Comment by cagix** [comment]
@AMatutat Ist das gelöst?

**Comment by AMatutat** [comment]
@AHeinisch kannst du das nochmal aufgreifen? 
Klingt nach etwas das einfach gemacht werden muss.
