### ISSUE TITLE
[D2A] Github-Teachers-Forum Einträge sichten 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#433]
https://github.com/espertus/jgrade
https://github.com/codefreak/codefreak

**Comment by AKirsch1** [comment]
Die Diskussion hier hat wenig mit dem eigentlichen Titel zu tun. Was davon ist jetzt das Problem, das das Issue ansprechen soll?

**Comment by AMatutat** [comment]
@AKirsch1 die Diskussion gehört auch garnicht in das Issue. Da ist GitHub beim Transferieren der Issues von einem Repo in das andere wohl etwas durcheinander gekommen und hat Diskussionen in die falschen Tickets geschrieben.


@cagix hatte mir vor Ewigkeiten mal diese GitHub Teacgers Forum Dinger geschickt, ich hab aber noch nie richtig reingeguckt. Gedanke war: Einfach mal gucken was die so machen,

**Comment by cagix** [comment]
@AKirsch1 siehe die Antwort von @AMatutat obendrüber - eigentlich ging es hier darum, weitere Auto-Grading-Tools zu sammeln und zu evaluieren (siehe erster Kommentar).

Vielleicht ist es nicht verkehrt, dieses Issue als "not planned" zu schließen und für das Sammeln von Auto-Grading-Tools ein neues Ticket aufzumachen und die beiden Links aus dem ersten Kommentar mit rüberzunehmen.

**Comment by AKirsch1** [comment]
Die Liste wird jetzt in #598 weiter geführt.
