### ISSUE TITLE
[D2A] Repo Struktur 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#434]
> > Ähm, das Repo haben wir bereits: [Programmiermethoden/Homework-Solutions](https://github.com/Programmiermethoden/Homework-Solutions).
> 
> 
> 
> Bin ehrlich, hab ich damals auch schonmal gesagt, ich verstehe nicht, warum wir die "Musterlösungen" und die Toolchain in einem Repo führen. 

ich meine, es gab gründe. einer war vermutlich, dass die toolchain mit den aufgaben ausgeliefert werden sollte und dafür entsprechend im repo mit den aufgaben als unterordner verankert sein muss. ein anderer war, dass es einfacher aufzubauen ist, wenn alles strukturell zunächst zusammen ist. und ein dritter grund könnte sein, dass wir nie richtig über github-actions und -workflows nachgedacht haben.

> Die Toolchain sollen Open Source und "Aufgaben unabhängig" sein. 
> 
> Die Aufgaben und Tests sind im Grunde nur die Konfigurationsparameter für die D2A-Toolchain. 

ja.

das bringt dann tatsächlich aber nochmal ne neue ebene rein: wie willst du die auszuführenden dinge spezifizieren? also die toolchain ist unabhängig, und in der aufgabe muss es dann neben der zu implementierenden schnittstelle und den tests eine config geben, die konkret spezifiziert, was die d2a-toolchain für diese aufgabe genau machen soll. das könnte ein gradle-skript sein - aber das steckt im vorgabeordner der aufgaben, wird von der (externen/separaten) d2a-action ausgeführt und stützt sich auf dingen ab, die in der action installiert/verfügbar sein müssen.  das macht mir etwas bauchschmerzen.

> Grob drüber Nachgedacht gäbs dann:
> 
> - D2A-Toolchain Repo
> 
>   - Hier wird die "generische" Toolchain entwickelt

ja.

und je länger ich drüber nachdenke: die toolchain sollte als [github-docker-action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) realisiert werden. damit ist sie unabhängig und kann extrem einfach in den workflows eingebunden werden. und da es am ende ein docker ist, kriegen wir das (mit anpassungen im workflow) auch auf gitlab an den start.

> 
> - Homework-Solution
> 
>   - privates Repo
> 
>   - Entwicklung der Aufgaben, Vorgaben, Tests und Lösungen

ja. 

zusätzlich wird hier die toolchain als workflow eingebunden, um vorgabe+tests+lösung zusammen mit der toolchain testen zu können.

und die konfiguration muss auch hier bereits drin sein.

eventuell sollte man hier nochmal darüber nachdenken, ob es ein reines aufgaben-/vorgabe-repo geben sollte und wir die lösungen separat (wie die studis) in einem privaten fork pflegen. das würde vieles einfacher machen: ordnerstruktur einfacher, kein git subtree push, skripte einfacher ... aber eine änderung der vorgaben würde (wie bei den studis) einen pull bedeuten und damit "rauten" im lösungsrepo oder einen rebase produzieren. wäre aber akzeptabel für mich. (und man könnte im lösungsrepo die lösung in einem separaten branch pflegen, der auf dem "master" aufsetzt - so kann der "master" durch einen pull jederzeit auf den stand der vorgaben gezogen werden (ohne rauten) und der lösungsbranch wird per rebase wieder auf die spitze des masters gesetzt.)

> 
> - Vorgabe-Repo
> 
>   - Einbindung der D2A-Toolchain (Subtree?)
> 
>   - Einbinden der Aufgaben, Vorgaben und Tests aus dem Homework-Solution Repo (Subtree?) 
> 
>   - Konfigurationsdatei für die D2A (Punkte, Abgabedaten etc.) 

klares jain 😀

das vorgabe-repo enthält per "git subtree push" aus dem privaten solutions-repo die vorgaben, die tests und die config-dateien für die toolchain.

die toolchain selbst ist als github-workflow im repo definiert (das geht leider nur per copy).

das vorgabe-repo ist in diesem szenario nur ein temporäres wegwerf-repo. (alternativ: dauerhaftes public vorgabe-repo und separat ein privates lösungsrepo als "fork" des vorgabe-repos.)

> 
> - Studi-Repo 
> 
>   - (manueller) Fork des Vorgabe-Repos

ja.

> 
> Die Demo bestände dann aus Demo-Vorgabe und Demo-Studi-Repo

ja. wobei ich hier definitiv nur dinge ausprobieren würde; die eigentlichen commits und tickets wären für mich im d2a-repo.

---

edit: ich würde nach der erfahrung im sommer in pm und der erfahrung jetzt im winter in sp das homework-solutions definitiv in einen dauerhaften public vorgabeteil und einen privaten "fork" für die lösung aufteilen. das macht die config deutlich einfacher und die strukturen sind identisch zu denen der studis - wir können also sicher sein, dass das bei den studis auch läuft.

edit: allerdings wird dann das erstellen neuer vorgaben+lösungen fies komplexer. ich würde vermutlich eine neue aufgabe dann zunächst komplett in einem hilfsbranch im lösungsrepo erstellen (damit die ide klarkommt) und anschließend den vorgabeteil manuell in das vorgaberepo kopieren+committen, im lösungsrepo einen pull machen und dann den lösungsteil hier committen. das klingt nach albtraum. hmmm, aber es macht diese ganzen stunts mit den pfaden weg und simuliert zudem die arbeitsweise der studis (also das ergebnis).

_Originally posted by @cagix in https://github.com/Programmiermethoden/D2A_demo_vorgabe/issues/18#issuecomment-1370968598_

**Comment by cagix** [comment]
> Bin ehrlich, hab ich damals auch schonmal gesagt, ich verstehe nicht, warum wir die "Musterlösungen" und die Toolchain in einem Repo führen. Die Toolchain sollen Open Source und "Aufgaben unabhängig" sein. Die Aufgaben und Tests sind im Grunde nur die Konfigurationsparameter für die D2A-Toolchain.

Das war der alte Ansatz: Alles ist in einem Repo, und man kann für die Studis einfach Teile (Unterordner) per `git subtree push` in ein neues Repo auslagern.

Aber wir hatten ja bereits darüber gesprochen: Für das Tooling halte ich eine GH-Action (entweder als Docker-Action oder als Composite-Action) für sinnvoll. Der Code kommt in ein anderes Repo, und die GH-Action wird dort als Workflow eingebunden. 

Im Prinzip finde ich eine Composite-Action besser. Das setzt aber voraus, dass das Installieren der nötigen Software auf dem Runner nicht so ewig lange dauert. Für die Docker-Action spräche, dass man das für GitLab einfacher wiederverwenden kann. Sonst müsste man für GitLab nochmal nen eigenen Workflow+Action basteln.



> Grob drüber Nachgedacht gäbs dann:
> 
> * D2A-Toolchain Repo
>   
>   * Hier wird die "generische" Toolchain entwickelt

Ja. Siehe oben: Als Github-Action (https://docs.github.com/en/actions/creating-actions).

> * Homework-Solution
>   
>   * privates Repo
>   * Entwicklung der Aufgaben, Vorgaben, Tests und Lösungen

Jupp.

> * Vorgabe-Repo
>   
>   * Einbindung der D2A-Toolchain (Subtree?)
>   * Einbinden der Aufgaben, Vorgaben und Tests aus dem Homework-Solution Repo (Subtree?)
>   * Konfigurationsdatei für die D2A (Punkte, Abgabedaten etc.)

Toolchain als Github-Workflow. Aufgaben+Vorgaben+Tests als Git-Subtree aus dem HW-Solution-Repo. Konfiguration direkt (vermutlich).


> * Studi-Repo
>   
>   * (manueller) Fork des Vorgabe-Repos

Genau - damit sollten sie dann auch den Workflow "erben" und in ihrem Repo ausführen können. 


> Die Demo bestände dann aus Demo-Vorgabe und Demo-Studi-Repo

👍

**Comment by AKirsch1** [comment]
Ich wollte eigentlich gar keine Antwort darauf :D. Das ist eine alte Antwort von Andre, die ich aus dem einen Issue gezogen habe, das ich gestern geschlossen hatte. Ich wollte die hier nur der Vollständigkeit halber ergänzen

**Comment by AKirsch1** [comment]
> Für die Docker-Action spräche, dass man das für GitLab einfacher wiederverwenden kann. Sonst müsste man für GitLab nochmal nen eigenen Workflow+Action basteln.

Ist das in unserem Fall relevant oder läuft alles über GitHub? "Früher (also zu meiner Zeit)" war ja alles über GitLab, meine ich.

**Comment by AKirsch1** [comment]
Closed as not planned in favour of #621.
