### ISSUE TITLE
[Plan] Projektplan aktualisieren und verfeinern

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#439]
aus https://github.com/Programmiermethoden/Dungeon/issues/438:

> Wie sieht eigentlich aktuell der Projektplan aus? Ihr hattet ja mal etwas aufgeschrieben, was vom Antrag abgeleitet war. Ist das noch aktuell? Sollten wir mal einen neuen Projektplan aufstellen für die restliche Laufzeit mit einer Feinplanung für die nächsten Wochen?

* Plan für die restliche Laufzeit anpassen und Meilensteine definieren
* Feinplanung der nächsten Wochen/des nächsten Meilensteins erstellen

@AMatutat @malt-r @bcg7 @cagix

**Comment by AMatutat** [comment]
Ich bin grade etwas stuck wie wir hier am besten weitermachen. 

In meinen Kopf scheint es mir jetzt Sinnvoll zu sein, die einzelnen Issues in Meilenstein-Pakete zu packen. 
Dabei ist darauf zu achten, dass die Pakete nicht wieder "Mach fertig" sind, sondern klare und sinnige Teilschritte. 
Die Meilenstein-Pakete kann mann dann in Verhältnis zueinander setzten. 
Also A muss vor B gemacht werden und C vor D, die beiden sind aber "unabhängig" von A und B. 
Und dann kann hoffentlich zusammen mit den #Time Markierungen in den Beschreibungen, ein Zeitplan generiert werden. 


Klingt das logisch? 


In meinen Kopf entwickelt sich daraus ein Graph der irgendwie so aussehen könnte: 
Dabei ist jeder Knoten ein Meilenstein. Damit ein Meilenstein bearbeitet werden kann, müssen alle Meilensteine die eine Kante zum entsprechenden Meilenstein haben vorher gelöst sein. 
![graphviz-2](https://user-images.githubusercontent.com/32962412/226839558-57dbf522-8ec0-4ea3-ac10-61049edf7ac4.png)


Als Dot
```dot
digraph G {

Start -> TypeBuilder
Start -> Quizfragen_Struktur
Quizfragen_Struktur->Quizfragen_GUI
Quizfragen_Struktur -> DemoQuizfragenOhneGUI
Steuermechanismen -> DemoQuizfragenOhneGUI
InventarGUI -> DemoQuizfragen
Quizfragen_GUI -> DemoQuizfragenGUI
Steuermechanismen -> DemoQuizfragenGUI
TypeBuilder -> Steuermechanismen

Start -> Inventar -> InventarGUI -> PositionierenDemo
Steuermechanismen ->PositionierenDemo

Inventar -> Crafting -> CraftingGUI
CraftingGUI-> DemoKombinieren
Steuermechanismen -> DemoKombinieren

Steuermechanismen -> BewertungsKonzeptErarbeiten
BewertungsKonzeptErarbeiten -> BewertungsKonzeptUmsetzten
DemoQuizfragenGUI -> BewertungsKonzeptUmsetzten
DemoKombinieren -> BewertungsKonzeptUmsetzten
PositionierenDemo -> BewertungsKonzeptUmsetzten


Start -> DeployToGradingCleanUP
DeployToGradingCleanUP -> RepoStrukturErarbeiten
DeployToGradingCleanUP -> SkripteFixen
SkripteFixen -> UmsetzungAlsAction
UmsetzungAlsAction -> D2GDemo
RepoStrukturErarbeiten -> D2GDemo
D2GDemo -> AufgabenUmgestalten

Start -> HighscoreKonzeptErarbeiten
HighscoreKonzeptErarbeiten -> HighscorePoC
HighscorePoC -> AnbindungIlias
HighscorePoC -> AnbindungDungeon
AnbindungDungeon -> HighscoreDemo
AnbindungIlias -> HighscoreDemo

Start -> PetriNetzeKonzeptionieren
PetriNetzeKonzeptionieren -> PetriNetzeEinlesen

PetriNetzeEinlesen -> PetriNetzeVerwenden
Steuermechanismen -> PetriNetzeVerwenden
BewertungsKonzeptUmsetzten -> PetriNetzeVerwenden

PetriNetzeVerwenden -> AbschlussDemo
HighscoreDemo -> AbschlussDemo


}
```

**Comment by AMatutat** [comment]
@AMatutat ergänz das Diagramm mal grob und führ color Coding für die Zuständigkeit: WiMi Work, SHK-Work, Wimi+SHK Work

**Comment by malt-r** [comment]
"TypeBuilder" umbenennen in  "TaskBuilder"

**Comment by cagix** [comment]
@AMatutat Wir hatten bei der Diskussion über den Projektplan oben neulich über das Builder-Pattern gesprochen: https://www.digitalocean.com/community/tutorials/builder-design-pattern-in-java

**Comment by AMatutat** [comment]
ist mit #585 erledigt.
