### ISSUE TITLE
[GAME] Verhalten in Components, warum?

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#446]
> Unter dem Package AI sehe ich aber lauter Klassen, nicht scheinbar nicht Components sind? game/src/ecs/components/ai/AITools.java, game/src/ecs/components/ai/fight/CollideAI.java und game/src/ecs/components/ai/fight/MeleeAI.java sollen ja im PR hinzugefügt werden unter game/src/ecs/components/? Dito game/src/ecs/components/ai/idle/PatrouilleWalk.java ...

Sind quasi Helper-Klassen die zum Component gehören. 

> Edit: Hmmm, noch nicht genug Kaffee. D.h. die im PR hinzukommenden Sachen unter AI sind nicht die Components für "AI", sondern Verhalten, welches per Definition nicht in die Components darf und aber auch nicht zu einem System gehört?

In diesen PR kommt doch nix unter AI hinzu.

> sondern Verhalten, welches per Definition nicht in die Components darf und aber auch nicht zu einem System gehört?

Herzlich willkommen in der Welt der ECS. Wo alles entweder E oder C oder S ist oder irgendwas dazwischen was es aber nicht geben darf. Aber ja, das beschreibt es recht gut. Unity und co lösen sowas über kleine Skripte die man in den Components reinstecken kann. Wir haben das mit unserem Strategy-Pattern Ansatz kopiert. 
Wenn man richtig hardcore ECS sein wollen würde, müsste man vermutlich für jede Verhaltensweise ein eigenes Component erstellen und das System würde dann Anhand der Kombination. die Logik implementieren und ausführen. Macht man mit anderen Components ja auch....

Ich merke grade: Das ist Thema für eine andere Diskussion

**Comment by cagix** [comment]
siehe https://github.com/Programmiermethoden/Dungeon/pull/401#issuecomment-1453164146:

> > > Edit: Hmmm, noch nicht genug Kaffee. D.h. die im PR hinzukommenden Sachen unter AI sind nicht die Components für "AI", sondern Verhalten, welches per Definition nicht in die Components darf und aber auch nicht zu einem System gehört?
> > 
> > 
> > In diesen PR kommt doch nix unter AI hinzu.
> 
> Stimmt, sind nur geändert (Packagenamen).
> 
> > > sondern Verhalten, welches per Definition nicht in die Components darf und aber auch nicht zu einem System gehört?
> > 
> > 
> > Herzlich willkommen in der Welt der ECS. Wo alles entweder E oder C oder S ist oder irgendwas dazwischen was es aber nicht geben darf. Aber ja, das beschreibt es recht gut. Unity und co lösen sowas über kleine Skripte die man in den Components reinstecken kann. Wir haben das mit unserem Strategy-Pattern Ansatz kopiert.
> 
> Ich überlege nur, ob man das irgendwie in ein gemeinsames Package `helper` (?) auslagern sollte und das neben den E- und C- und S-Packages hinlegt. Aktuell verwirrt es irgendwie, andererseits hat man eine räumliche Nähe zu den Components.
> 
> Wenn es tatsächlich nur Hilfsklassen sind, die in bestimmten Components genutzt werden: Wären verschachtelte Klassen ein Ansatz zur Strukturierung? D.h. die AI-Hilfsklassen wären verschachtelte Klassen der AIComponent? Aber das ist auch irgendwie hässlich, ziehe ich sofort wieder zurück.

**Comment by AMatutat** [comment]
Dieses Ticket wurde von der Realität überholt.


> Ich überlege nur, ob man das irgendwie in ein gemeinsames Package helper (?) auslagern sollte und das neben den E- und C- und S-Packages hinlegt. Aktuell verwirrt es irgendwie, andererseits hat man eine räumliche Nähe zu den Components.

Haben wir durch die neue Struktur #583 erreicht. Hilfsmethoden wurden in ein `utils` package extrahiert. 

> Wenn es tatsächlich nur Hilfsklassen sind, die in bestimmten Components genutzt werden: Wären verschachtelte Klassen ein Ansatz zur Strukturierung? D.h. die AI-Hilfsklassen wären verschachtelte Klassen der AIComponent? Aber das ist auch irgendwie hässlich, ziehe ich sofort wieder zurück.

Haben wir durch #694 erreicht, indem wir auf `Consumer` o.ä umgestellt haben, das erspart uns das Strategy-Pattern mit eigenen Interfaces. 
Toolklassen und konkrete Implementierungen liegen in `utils`
