### ISSUE TITLE
[GAME] Items innerhalb der ECS-Struktur überdenken

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#447]
Aktuell sind Items weder Entität noch Component noch System. 
Könnte die aktuelle Klasse `Item` ein Component sein?

#Time:2

**Comment by AHeinisch** [comment]
Also soweit ich das sehe kann das hier Probleme machen aktuell liegen alle Entitäten immer im Game.entities aber wenn wir Entitäten erstellen welche nicht immer im Game.entities liegen wird es Problematisch.

Eine Item-Komponente klingt auch erst gut bis auf, dass dies ja bedeuten würde, dass diese einen Lifecycle hat, also von einem gleichnamigen System angesteuert werden oder dass sie jeden Frame aktualisiert werden müssen. Aktuell klingt dies eher nach, wir bauen uns da was Komisches ein und werden damit nicht glücklich.

Also andere lösen es meist auf eine Weise, wo es leicht verständlich ist.
- Die Items sind Entitäten und haben ihre "Eltern" z.b. der Spieler, die Welt etc. Also gibt es eine Hierarchie zwischen den Entitäten
- Die Items sind, da sie keinen eigenen Lebenskreislauf haben, unabhängig vom ECS

Selbst in Unity gibt es für beide Ansätze beliebte Lösungen. Größtenteils entscheidet man sich für eine Lösung, weil man irgendwas Spezielles damit machen möchte. Die es als Entität erstellen haben vorwiegend den Vorteil, wenn bei 100 Items z.b. das auf den Boden fallen gemacht wird, sie einfach nur vom Spieler-Inventar auf die Welt um verlinkt werden müssen, anstelle von erst Entitäten erstellen und diese komplett neu hinzufügen. Bei der Lösung, dass sie unabhängig davon sind, ist der Vorteil sie liegen nicht in dem ECS, falls der Spieler sie z.b. aufbraucht und somit werden sie gelöscht, muss das ECS nicht die Entität aus einer vielleicht optimierten Struktur entfernen.

**Comment by dkirshner** [comment]
Als Item verstehe ich eine Entität ohne Komponenten (gehört somit zu Game.entities).
Bezüglich "Die Items sind Entitäten und haben ihre "Eltern" z.B. der Spieler, die Welt etc. Also gibt es eine Hierarchie 
zwischen den Entitäten".
Man kann doch eigentlich eine Map<Integer (item Id), Integer (Anzahl)> als eine neue Komponente dem Besitzer Objekt  (Hero, Dungeon, Monster) hinzufügen um eine Hierarchie zu vermeiden.

**Comment by AMatutat** [comment]
> Man kann doch eigentlich eine Map<Integer (item Id), Integer (Anzahl)> als eine neue Komponente dem Besitzer Objekt (Hero, Dungeon, Monster) hinzufügen um eine Hierarchie zu vermeide

Haben wir das nicht mit unserem `InventoryComponent`? 


Hmm mir fällt es grade sehr schwer eine Entscheidung zu treffen. @AHeinisch was sagt dein Bauchgefühl?

**Comment by cagix** [comment]
> Außerdem würde eine Item-Komponente bedeuten sie kann auch dem Helden zugewiesen werden, wodurch dieser aber nur ein Item besitzen kann und nicht z.b. 8 Items da wir aktuell nur eine Komponente jeder Klasse erlauben.

Ja gut, das könnte man ja auflösen.


> Also andere lösen es meist auf eine Weise, wo es leicht verständlich ist.
> 
> Die Items sind Entitäten und haben ihre "Eltern" z.b. der Spieler, die Welt etc. Also gibt es eine Hierarchie zwischen den Entitäten
> Die Items sind, da sie keinen eigenen Lebenskreislauf haben, unabhängig vom ECS

Mir gefällt die Idee eines "Entitäten-Trees" oder auch "Component-Trees". 

Konzeptionell verstehe ich nicht, warum ein Item eben keine Entität ist und anders behandelt wird. Einerseits wird damit das ECS-Pattern quasi verletzt/ausgehebelt. Andererseits könnte ein Item aus meiner Sicht durchaus einen Lebenszyklus haben, und wenn man das nicht braucht - dann könnte man dem Ding einen "statischen Lebenszyklus" klöppeln? Und die Beschränkung, dass der Held nur ein Item haben kann, die kommt ja von uns und könnte aufgehoben werden.

**Comment by AMatutat** [comment]
Ich hab grade versucht eine Antwort auf deine Frage zu schreiben und die war so lang, dass irgendwo ein konzeptioneller Fehler liegt. 


Eigentlich ist ja die Frage: Wann ist eine Entität ein Item?

**Comment by cagix** [comment]
> Ich hab grade versucht eine Antwort auf deine Frage zu schreiben und die war so lang, dass irgendwo ein konzeptioneller Fehler liegt.

Genau das ist mein Gefühl die ganze Zeit.

> Eigentlich ist ja die Frage: Wann ist eine Entität ein Item?

Oder anderherum: Was ist der Unterschied? 

Oder nochmal anders: Wann ist ein Item eine Entität?


Ich denke, Items sind einfach spezielle Entitäten. Vielleicht haben sie einen anderen Lebenslauf als andere Entitäten, vielleicht interagieren sie anders als andere. Aber ist das nicht irgendwie immer so?

**Comment by malt-r** [comment]
Für mich fühlt sich die Trennung von Item und Entität danach an, dass wir bewusst ein System umgehen und einen "Spezialfall" einführen. Das kann uns nachher noch richtig auf die Füße fallen. Die Idee hinter dem ECS-Gedanken ist ja, das *alle "Objekte"* im Dungeon Entitäten sind, das ECS erhebt also schon konzeptionell alleinigen Herrschaftsanspruch :) Wenn wir jetzt ein Parallelsystem dazu aufmachen, laden wir uns damit vermutlich ziemlich viel Arbeit auf, da beide Systeme miteinander interagieren müssen. Gerade wenn es um die Verwaltung von allen "Dingen" im Dungeon geht, sollten wir ein durchgängiges und in sich konsistentes System verwenden.

@AHeinisch 
> Außerdem würde eine Item-Komponente bedeuten sie kann auch dem Helden zugewiesen werden, wodurch dieser aber nur ein Item besitzen kann und nicht z.b. 8 Items da wir aktuell nur eine Komponente jeder Klasse erlauben.

Das ist konzeptionell aus meiner Sicht falsch. Ich würde die Zuweisung eines `ItemComponent` zu einer Entität so verstehen, dass damit "diese Entität ist ein Item" abgebildet wird, und nicht "diese Entität hat ein Item". Hierfür haben wir das `InventoryComponent`.

> Ich denke, Items sind einfach spezielle Entitäten. Vielleicht haben sie einen anderen Lebenslauf als andere Entitäten, vielleicht interagieren sie anders als andere. Aber ist das nicht irgendwie immer so?

Ich denke auch, dass das andere Verhalten konzeptionell im ECS-Gedanken enthalten ist und kein separates System voraussetzt.

**Unabhängig von allen Aspekten auf der Dungeon-Seite** macht das auch Probleme in der DSL. Ich habe mich da relativ stark drauf verlassen, dass alles, was im Dungeon kreucht und fleucht, über das ECS abgebildet werden kann. Das ist essentiell für die Übersetzung einer abstrakten Aufgabenbeschreibung in ein konkretes Spielszenario.

**Comment by AHeinisch** [comment]
Im Dungeon ist es bereits eine Entität. Im Inventar eben nicht. Warum dies so ist -> hat es ein Leben außerhalb des Inventars, nein.
Um ein Item immer eine Entität sein zu lassen:
- Inventar muss überarbeitet werden
- Aktive Item und passive Item müssen von vererbende Klassen auf eigenständige Komponenten abgeändert werden
- Je muss ein eigenes System gebaut werden (Hier mit der nicht puren ECS Variante also mit Verhalten des spezifischen aktiven oder passiven Item beim Komponente)
- Ein Item brauch entweder ein Indikator im Inventar oder muss aus dem ECS.entities entnommen werden, sobald es aufgenommen wurde. (darf nicht mehr angezeigt werden oder interagiert werden)
- ItemVorlagen müssen erstellt werden, damit z.b. die Kiste ein zufälliges Item erstellen kann.


Wenn man es zu 100% richtig machen will:
- Interaktion darf nur über ItemSystem stattfinden (nicht über InteraktionSystem/KeyboardSystem)
- Aktive und Passive Item müssen je eigenes System bekommen 
  - Jedes Aktive Item brauch an sich ein eigenes System
  - Jedes Passive Item brauch an sich ein eigenes System
- Beziehungen zwischen Entitäten müssen ermöglicht werden (Held)-interagiert mit->(Kiste), (Held)-interagiert mit->(Item)


Ich schätze, hier handelt es sich, um mehr Arbeit als vielleicht aktuell zu erkennen.

**Comment by cagix** [comment]
@AHeinisch @AMatutat @malt-r Könnt ihr das bitte nochmal genauer als Konzepte formulieren: Items wie bisher vs. Items als Entitäten. Was hat es jeweils für Folgen, wo liegen Probleme und wo Vorteile, wie sehen die relevanten Strukturen aus. Dann sollten wir das nochmal in der Runde mit @bcg7 diskutieren und eine Entscheidung treffen.

Mein Verständnis ist, dass wir die Items zwar als Entitäten an sich auffassen, aber eben die anderen Mechanismen aus dem ECS nicht dafür formuliert haben und quasi eine Abkürzung genommen haben. Das fühlt sich nicht gut an, gerade mit Blick auf die Verknüpfung mit der DSL. 

Eine andere Sache ist, dass Items ja durchaus einen eigenen Lebenszyklus im Inventar haben können: Wenn ich in eine Feuerfalle trete, kann es passieren, dass mir dadurch Scrolls verbrennen. Dito wenn ich eine Frostfalle (oder Frost-Potion) aktiviere, dann kann mir eine andere Potion in meinem Inventar kaputt gehen. Das wären Dinge, die von außen über ein System erledigt werden müssten.

Vielleicht braucht es tatsächlich ein Inventar-System oder Item-System? Damit könnte ich zwar versuchen, mit einen Troll oder so in meinen Rucksack zu stopfen, aber das System würde das nicht erlauben. Aber vielleicht ist es auch eine Spielidee, Trolle in den Rucksack stopfen zu können? 

Die nächste Frage ist, ob man aktive und passive Entitäten explizit formulieren muss oder ob sich das über die Eigenschaften und System entsprechend ergibt?

**Comment by malt-r** [comment]
Zwei mögliche Lösungen, beide nutzen ein `ItemComponent`, um die relevanten Daten über das Item zu speichern:

![2023_03_21_item](https://user-images.githubusercontent.com/37513253/226618722-a79afe32-9fcb-476c-b669-253e5d831128.png)

Linke Seite: Wenn ein Item in die Welt gedropped wird, wird es in einen ItemContainer verpackt, der nur ein Item (als Entität) speichert. Wird es aufgehoben, wird dieser Container gelöscht und das Item wird (als Entität) in dem `InventoryComponent` der `Hero`-Entität gespeichert.

Rechte Seite: wenn ein Item in die Welt gedropped wird, werden die `PositionComponent`, `AnimationComponent` und `HitboxComponent`s aktiviert. Wenn das Item aufgehoben wird, werden diese Componenten deaktiviert (sodass sie nicht mehr von den entsprechenden Systemen beachtet werden, orientiert sich an einem [ähnlichen Mechanismus](https://docs.unity3d.com/ScriptReference/Behaviour-enabled.html) in Unity. Dann wird die Entität mit dem `ItemComponent` in dem `InventoryComponent` der `Hero`-Entität gespeichert.

**Comment by AMatutat** [comment]
Das Notiz Diagram aus unserer heutige (bestimmt nicht zu langen) Diskussion.
Morgen früh mach ich daraus ein gescheites Klassen + Sequenzdiagramm, jetzt erstmal umkommentiert hier abgelegt, damit ihr nochmal gucken könnt falls mich morgen der Bus erwischt... 

![image](https://user-images.githubusercontent.com/32962412/226676658-f4f0d5d7-1afb-42e3-be2b-175b3242bf7e.png)
