### ISSUE TITLE
[GAME] Feuerball Textur

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#453]
Für unseren Feuerball Skill braucht es eine Textur/Animation.

Gespeichert soll es unter `game/assets/skills/fireball/... ` werden. 

@dkirshner dein tool spuckt doch bestimmt neben `.png` auch eine Tool-Spezifische Datei aus, die gerne auch hochladen. 

#Time: ?

**Comment by dkirshner** [comment]
Mit dem Tool (Piskel) hat man folgende Möglichkeiten:
- Sprite in ein animiertes GIF umwandeln
- Spritesheet erstellen (.png)
- Spritesheet mit Jason-Metadaten
- C-Datei mit als Array gerendertem Frame 

sonst schaue ich mich auch nach anderen Tool um, falls dieses nicht ausreichen sollte

**Comment by AMatutat** [comment]
fixed in #477
