### ISSUE TITLE
[GAME] Dokumentation Basics

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#454]
Für den ECS Anteil gibt es bereits einiges an Dokumentation (noch nicht genug) aber für den "hinteren Teil", also das was früher das `PM-Dungeon-Framework` war.

Ich habe dafür bereits eine Struktur und ein paar Bullet-Points angelegt, das ist ein guter Startpunkt. 
Ziel der Dokumentation ist es, den Studis im zweiten Semester aber auch uns einen guten Überblick und Verständnis über Struktur, Funktionalität und Gedanken zu liefern. Es ist (erstmal) nicht der Anspruch, ein 1 zu 1 Tutorial zu schreiben. 

Vermutlich kann man auch mal im alten Quickstart schauen und recyceln: https://github.com/Programmiermethoden/__pm-dungeon/tree/quickstart

#Time: 10

**Comment by AMatutat** [comment]
@cagix vielleicht kannst du nochmal beschreiben was du alles für deinen QuickStart haben willst.

- Struktur des Codes
- Welche Klasse macht was
- Woran muss ich ziehen um XYZ einzubauen (dafür gibt es auch schon das "addOwnContent.md")

**Comment by cagix** [comment]
> @cagix vielleicht kannst du nochmal beschreiben was du alles für deinen QuickStart haben willst.
> 
> * Struktur des Codes
> * Welche Klasse macht was
> * Woran muss ich ziehen um XYZ einzubauen (dafür gibt es auch schon das "addOwnContent.md")

So richtig habe ich mir da noch gar keine Gedanken gemacht :) 

Meine Idee war, den Studis grob die Struktur des Repos und der Packages/Klassen zu erklären und dann analog zum alten Quickstart-Guide hinzugehen und das Repo clonen, in IJ einbinden, bauen und dann schrittweise einen Helden reinsetzen, bewegen (wasd) und hüpfen lassen. 

Dabei würde ich nicht auf alle Klassen oder so eingehen (wollen), aber so die grundsätzlichen Dinge, mit denen die Studis in Berührung kommen und die Grobstruktur (wo finde ich was).

Hilft das schon? Sonst muss ich flink nochmal denken :)

**Comment by cagix** [comment]
Im Ticket für die "Vorlesung" (naja, eigentlich wird das ein Tutorial) steht aber auch noch nicht wirklich viel: https://github.com/Programmiermethoden/PM-Lecture/issues/476

**Comment by AMatutat** [comment]
Um hier mal etwas Dampf zu machen: 
Zu Dienstag Abend: 
- Stichpunktartige Struktur um die zentralen Fragen zu beantworten
    - Wie sieht die Struktur aus?
    - Welche Infos müssen eingebaut werden? 
    - Wo liegen diese? 
    - Ergebniss: Files, Kapitelüberschriften und Inhalte grob skizziert (Stichpunkte) 
- Mittwoch : Feedback abwarten und umsetzen
- Bis Freitag: Alle nötigen Diagramme erstellen und einflegen
- Bis Montag: Inhalte verfeinern/fertigstellen, 
- Reviewprozess

@Lena241 @dkirshner das ding ist jetzt wirklich HIGH HIGH HIGH Prio.
