### ISSUE TITLE
[ORG] Abkürzen der Review-Überarbeiten-Review-Schleife

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#456]
Bisher werden Änderungen per PR vorgeschlagen, die dann von mind. einer anderen Person einem Review unterzogen werden. Dann geht es zur ersten Person zur Überarbeitung zurück und dann wieder zum Review ... 

Die Erwartung war, dass im Laufe der Zeit alle Beteiligten ein besseres Gespür für die von ihnen erwarteten Dinge entwickeln und damit der Prozess relativ schnell geht. 

Die Praxis ist im Moment, dass nach einem aufwändigen Review die Hälfte der Vorschläge/Kommentare/... "übersehen" wird und oft eine zweite und dritte Schleife notwendig werden. Das kostet viel Zeit (und betrifft alle Tarifstufen).

Angeregt durch die Diskussion in https://github.com/Programmiermethoden/2022-freiraum-dungeon/pull/107#discussion_r1127640575 sollten wir darüber nachdenken, ob wir diesen Prozess vereinfachen können.

**Comment by cagix** [comment]
> Wir sind doch bestimmt nicht die Einzigen mit diesem Problem. Wie wird das denn woanders gehandhat?

Naja, das regelt normalerweise der Markt. Du kriegst eine gewisse Zeit einen Vertrauensvorschuss, aber wenn Du danach immer noch "super zäh" bist und keine Anzeichen für Verbesserung erkennen lässt, spielt entweder keiner mehr mit Dir (in Open-Source-Projekten) oder Du fliegst halt (Firma).

**Comment by cagix** [comment]
@AMatutat was ist der stand? wir hatten das besprochen im meeting. warum ist das ticket noch offen und nicht kommentiert?

**Comment by AMatutat** [comment]
Im [Meeting](https://github.com/Programmiermethoden/2022-freiraum-dungeon/blob/master/06_meetings/protokoll_025.md) beschlossen und umgesetzt:


- Verwendung von GitHub Codeowners zur klaren Zuordnung von Zuständigkeitsbereichen. Weitere Details finden Sie unter: https://github.com/Programmiermethoden/Dungeon/pull/482.
- Deaktivierung der GitHub-Einstellung, die es dem letzten Committer untersagt, ein (für einen Merge gültiges) Review zu erstellen. Dadurch können kleine Änderungen an PRs der SHKs von den WiMIs selbst durchgeführt werden.
- Sonderregel für @malt-r's PRs: @cagix oder @bcg7 reviewen oder der PR wird nach 2 Tagen "blind" gemerged.
