### ISSUE TITLE
[Feature] Test Infrastruktur

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#457]
Viele der Unit-Tests und die verwendeten Strukturen sind "historisch" gewachsen und es fehlt ein übergeordnetes klares und durchgängiges Testkonzept. Im Rahmen einer Bachelorarbeit könnte das einmal "richtig" und neu gedacht werden.

**Comment by AMatutat** [comment]
Aus meiner Sicht rennen wir aktuell irgendwie mit den Tests los ohne klare Vorgaben des Was und Wie. 
Strukturell unterscheiden sich die Tests auch (sieh hierzu auch die Diskussion in #213). 
Wir haben auch kein klares Konzept, ob und wie wir Mockito einsetzten wollen (cagix ist eher dagegen). 
Ein Überblick über die Testabdeckung haben wir auch nicht.

**Comment by AMatutat** [comment]
dup #604
