### ISSUE TITLE
[Game] Pathfinding Indexe werden falsch gelöscht oder hinzugefügt

### ISSUE THREAD

**Issue by AHeinisch** [Programmiermethoden/Dungeon#461]
Libgdx pathfinding nutzt eine Verbesserung des A* welche alle Elemente in einem Array verwaltet. Dabei benötigt also jeder Knoten einen Index sowie benötigt der Graph(Level) eine Anzahl von Knoten. Wiederum wurde beim Löschen eines Tiles die Gesamtzahl der Knoten reduziert und dabei nicht sichergestellt, dass Tile wirklich das letzte Element war. Dies führt dazu, dass beim Pfadfinden der Algorithmus nicht mehr funktioniert. Da z.b. Index 8 nicht mehr existiert und Index 11 zwar existiert, aber das Level nur noch 10 Knoten angibt.

Hierfür muss geschaut werden, was sich mehr anbietet die Knotenanzahl nicht verändern oder eine Liste mit freien Indizes zu erstellen, welche dann bei Bedarf neu zugewiesen werden können und sobald diese Leer ist dann darf erhöht werden oder wenn der Liste wirklich der letzte Index(`TileLevel.nodecount == (index + 1)`) zugewiesen wurde verkleinern.

**Comment by AHeinisch** [comment]
Vermutung für die Bearbeitungszeit etwa 2 Stunden da hierfür auch Tests benötigt werden und ich schätze diese kompliziert werden damit sie alle derzeit bekannten Fälle abfangen.

**Comment by AMatutat** [comment]
Wie im Meeting besprochen: Beim löschen eines Tiles wird die Lücke in der Liste geleert. Das ist von der Laufzeit zwar nicht optimal, sollte aber die lesbarste Umsetzung sein. Außerdem werden in der Regel nur selten und nur wenige Tiles im Level gelöscht.
