### ISSUE TITLE
[GAME] Dokumentation Skill

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#466]
Dokumentation für die Skills und die Systeme dahinter. 

_Originally posted by @AMatutat in https://github.com/Programmiermethoden/Dungeon/pull/394#issuecomment-1469522545_

**Comment by cagix** [comment]
@Lena241 @AMatutat @AKirsch1 das ticket ist seit zwei wochen assigned. warum gibt es keinen fortschritt?!
