### ISSUE TITLE
[GAME] Fireball Animation

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#470]
Im #469 wurde ein Feuerball Skill hinzugefügt. Dafür fehlen uns aber noch passende Texturen/Animationen. 

- texturen erstellen
- Texturen für Feuerball einsetzen 

#Time:2

**Comment by dkirshner** [comment]
Die sind auch fertig, lade den Feuerball gleich hoch.

**Comment by AMatutat** [comment]
uh super

**Comment by AMatutat** [comment]
duplicate mit #453
