### ISSUE TITLE
[ORG] Label für die Zuordnung der Tickets zu den Modulen überdenken

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#483]
Wir haben mal die Label "KI", "PM", "ADS" und "Quizfragen" eingeführt. 
Die Idee dahinter war, das wir für jedes Modul einen bestimmten Aufgaben-Typen entwickeln. 
Die von uns gewählten  Aufgaben-Typen zeichnen sich aber auch dadurch aus, dass sie in verschiedenen Modulen eingesetzt werden können. 

In meinen Augen ergibt das Label "Quizfragen" (als Sammelbegriff für SC,MC und Lückentext) daher deutlich mehr Sinn als die Label "PM", "ADS", "KI". 

Das selbe gilt eingentlich für die Issues. Ich hab damals mal für jedes Modul eine Reihe an Issues angelegt (Aufgabe ausdenken, Anforderungsanalyse, API Definition etc.) [Beispiel](https://github.com/Programmiermethoden/Dungeon/issues?q=is%3Aopen+is%3Aissue+label%3AKI+-label%3AADS)

Aus meiner Sicht müssten wir von der "Modul-Sicht" (vielleicht hatte auch nur ich die) zur "Aufgaben-Typen-Sicht" wechseln.
Das würde für mich bedeuten:
- Label "ADS","PM" und "KI" entfernen
- Issues als "won't fix" closen
- Label für die Aufgaben-Typen einführen
   - Quizfragen (haben wir ja schon)
   - Positionieren
   - Ersetzen
   - Kombinieren

Zusätzlich wird es wohl für jeden Aufgaben-Typen einige "Meta"-Issues brauchen
- Definition der DSL eingabe
- Definition des Bewertungsverfahren
- Analysieren der Mechaniken => ableiten kleinerer Issues

Für unsere Szenarien sollte es dann jeweils ein Issue (incl. konkreter Aufgabe) geben. Das sind ja quasi unsere Showcases

 - NPC stellt Frage
 - Monster greift mit Frage an
 - Truhe ist mit Frage verschlossen
 - Mehrere Truhen aber nicht alle sind richtig
 - Crafting: Items in Crafting-Container reinwerfen
 - Items müssen in Briefkasten gepackt werden

**Comment by cagix** [comment]
@AMatutat Brauchen wir wirklich so detaillierte Label? Wir sollten in die Tickets Meilensteinen zuordnen, um eine zeitliche Komponente/Planung zu sehen. Für die inhaltliche Einordnung würde mir ehrlich gesagt _ein_ Sammel-Label reichen.

**Comment by AMatutat** [comment]
Hmm?
So detailliert sind die Label doch nicht. 

> Quizfragen (haben wir ja schon)
Positionieren
Ersetzen
Kombinieren

Irgendeine form von Zuordnung von Issue zu anderen Issues (so ein Aufgabentyp wird ja nicht nur in einem Issue bearbeitete) und von Issue zu Aufgaben-Typ brauchen wir ja schon. Machen wir mit "KI", "PM", "ADS". ja auch. Nur sind die. Label (mittlerweile) semantisch falsch. 


>  Wir sollten in die Tickets Meilensteinen zuordnen, um eine zeitliche Komponente/Planung zu sehen. 

Klar. Aber das hat erstmal nix mit der Thematischen Einordnung zu tun. 


> Edit: Das kann man dann ja je nach Bedarf mit "DSL" oder "ECS" oder "Game" kombinieren.

Sowieso.

**Comment by malt-r** [comment]
Ich habe da auch nochmal drüber nachgedacht. Diese kursbezogenen "PM", "ADS"... Label sind vermutlich überholt, daher können die entsprechenden Issues geclosed werden.

Der Einführung von Labels für die einzelnen Aufgabentypen stehe ich etwas kritisch gegenüber. Vermutlich werden die ja auch nur sehr sporadisch eingesetzt. Ich stelle mir das etwas "ergonomischer" vor, für die einzelnen Aufgaben ein Sammel-Issue zu haben und die thematische Einordnung bzgl. Aufgabentyp über die Verlinkung zu diesem Issue zu machen, aber das ist eher ein Bauchgefühl. Ich habe da aber keine wirklich starke Meinung zu.. wichtig wäre nur, dass wir das dann auch im Workflow im Wiki festhalten.

**Comment by AMatutat** [comment]
Jetzt hat er das böse Wort "Sammel-Issues" erwähnt.
Eigentlich sind die ja auch genau dafür da, aber in der Praxis sind die eklig. Die werden nicht gepflegt, die liegen nur rum und fangen an zu stinken.

**Comment by cagix** [comment]
@AMatutat Ich glaube, @malt-r meint nicht "Sammel-Issue", sondern "Sammel-Label". Das war ja auch mein Vorschlag, die Label nicht so super spezifisch zu machen, sondern etwas allegemeiner zu lassen. Wir erschlagen uns sonst ...

**Comment by AMatutat** [comment]
> die Label nicht so super spezifisch zu machen, sondern etwas allegemeiner zu lassen. Wir erschlagen uns sonst ...

Ich versteh nicht ganz warum `KI` allgemein ist aber `Kombinieren` nicht. 
Ich bin ja bei euch. Die Label sollen nicht zu Issue Beschreibungen werden. 

> Bitte nicht die Issues einfach zumachen, sondern entsprechend umwidmen. Die alten Issues sind nach meinem Verständnis ja nicht falsch, oder?

Falsch nicht, aber outdated. Ich habe beim umwidmen von Issues immer ein mieses Bauchgefühl. Manchmal bietet es sich an, weil der Kern eines Issues noch identisch bleibt. Aber bei größeren "Änderungen" finde ich das immer ein wenig mäh. Ich muss ja kein Issue-Papier sparren. 
Wir haben ja so Issues wie (KI Aufgabentyp Bewertung definieren #374). Ich könnte daraus jetzt ("Bewertung für Aufgabentyp Kombinieren definieren") machen, aber irgendwie fühlt sich das falsch an.  
Liegt vielleicht aber auch nur an mir.

**Comment by cagix** [comment]
@AMatutat 

Issues: Ja klar, wenn es wirklich outdated ist, dann bitte einen Kommentar sein (warum outdated, ggf. welches Issue ersetzt das) und zu damit. 

Ich hatte nur eben das Gefühl, ihr wollt erstmal alles zumachen und dann neue Sachen wieder aufmachen und hatte das Gefühl, dass einige der Dinge vielleicht nur leicht umgewidmet werden müssten.

Label: Mein Vorschlag wäre, ein gemeinsames Label für die Aufgabensachen zu machen. Bei "ECS" haben wir ja auch nur ein Label und unterscheiden nicht noch weiter nach "Component X" und so. So findest Du in der Issue-Flut alle Issues schnell wieder, die irgendwas mit "Aufgaben" zu tun haben. Den Rest muss dann die Summary klären.

**Comment by cagix** [comment]
> > Label: Mein Vorschlag wäre, ein gemeinsames Label für die Aufgabensachen zu machen. Bei "ECS" haben wir ja auch nur ein Label und unterscheiden nicht noch weiter nach "Component X" und so. So findest Du in der Issue-Flut alle Issues schnell wieder, die irgendwas mit "Aufgaben" zu tun haben. Den Rest muss dann die Summary klären.
> 
> Ich finde der vergleich mit dem ECS hingt ein wenig. Das ECS ist eigentlich nur Tool. 

Aber das ECS setzt sich aus vielen kleinen Bestandteilen zusammen - man könnte hier auch nach "Component", "System", ... filtern wollen? Und doch reicht hier "ECS".


> danach filtern möchte, was für den Aufgabentyp "Kombinieren" noch zu tun ist. 

Aber müsste man hier nicht nach den Grundbausteinen (Mechanik) fragen, und nach den Szenarien und Steuermechanismen? Und liegen die nicht alle "quer", d.h. sind auch für andere Aufgabentypen relevant?

So richtig sehe ich den Bedarf nicht. Aber ich muss es auch nicht machen/umsetzen :) ... Wenn also für Dich ein Label "Kombinieren" wirklich notwendig ist, dann mache es halt.

**Comment by AMatutat** [comment]
> So richtig sehe ich den Bedarf nicht. Aber ich muss es auch nicht machen/umsetzen :) ... Wenn also für Dich ein Label "Kombinieren" wirklich notwendig ist, dann mache es halt.

Gut, hab wohl genug gequengelt und darf jetzt das Ü-Ei an der Kasse mitnehmen ^^

**Comment by cagix** [comment]
> > So richtig sehe ich den Bedarf nicht. Aber ich muss es auch nicht machen/umsetzen :) ... Wenn also für Dich ein Label "Kombinieren" wirklich notwendig ist, dann mache es halt.
> 
> Gut, hab wohl genug gequengelt und darf jetzt das Ü-Ei an der Kasse mitnehmen ^^

In der Tat. Mach es Dir bitte nur nicht zu filigran und komplex - wir haben neben Issues und Labels ja auch noch Projekte und Meilensteine. Das sollte alles sinnvoll ineinander greifen und möglichst einfach sein. Die Erfahrung bisher war: Je feiner, um so kaputter.

**Comment by AMatutat** [comment]
Nochmal um meine Gedanken festzuhalten (und potenzielle Gehirnaussetzer zu vermeiden)

- Project-Boards sind für die "echten" Projekte. Damit ordnen wir Issues den Projekten zu. (PM-Dungeon, Dungeon, Lehre, und was da noch alles kommt) 
- Präfixe ([GAME], [DSL] etc.) ordnen Issues einen bestimmten Bereich zu, dienen aber nur der Übersicht und doppeln sich mit den label. 
- Label ordnen die Issues in verschiedene Bereichen ein 
    - Projektziel (deploy-to-grading, highscore, Quizfragen, Aufgabentyp: Kombinieren, Petri netze, ..."
    - Aufgabenbereich Einordnung  (Dungeon, DSL, API ...) 
    - Zuständigkeit (SHK, WIMi-DSL; WiMi-Dungeon) 
    - Inhalt (bug, dokumentation,gui,...)
    - Sonderlabels (meeting) 
- Milestones sind für die Zeitliche Einordnung der Issues. Geben aber keine Auskunft über den Inhalt.

**Comment by cagix** [comment]
Klingt inhaltlich sinnvoll.

> Edit: Mittlerweile gefällt mir das "current_week" label nicht mehr, ist ja eigentlich ein Mini-Milestone. Aber jetzt ist egal, hin und her macht Taschen leer.

Naja, Du wolltest eine direkte Möglichkeit zum Auszeichnen der aktuellen Woche. Meilensteine gehen nicht, da man ein Issue immer nur einem Meilenstein zuordnen kann und die wöchentlichen Sachen keine "Meilensteine", sondern "Sprints" sind. Man könnte auch ohne Label auskommen, wenn die Assignees sinnvoll gesetzt sind.

**Comment by AMatutat** [comment]
Hab meine Labels erstellt und die Isseus angepasst. 
Bin erstmal glücklich
