### ISSUE TITLE
[GAME] Item aus Spielerinventar in ein anderes Inventar legen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#491]
Der Spieler soll aus seinem Inventar Items in das Inventar von anderen Entitäten legen können. 
Das Ganze soll über die GUI #234 gemacht werden können.

Ich habe noch keine klare Vorstellung, wie genau das aussehen könnte.

Einsatz: Die Items repräsentieren eine mögliche Lösung für die Aufgabenstellung. Der Spieler muss das Item in den richtigen Container legen, um die Antwort "abzugeben". 

Das Ganze braucht es auch in mehreren Geschmacksrichtungen:
- Ich kann ein item abgeben und wieder zurücknehmen (z.B Kiste)
- Ich gebe das Item ab und komme nicht wieder dran (z.B NPC)

---
## Bounty

Dieses Bounty kann erst bearbeitet werden, wenn eine entsprechende GUI (#234) vorliegt. 

--- 

#Time:15

**Comment by AMatutat** [comment]
@fwatermann ich glaub das gehört stark zur GUI

**Comment by fwatermann** [comment]
Items können via Drag&Drop von einem in ein anderes Inventar verschieben. Dies wurde in PR #934 implementiert.
