### ISSUE TITLE
[GAME] AnimationBuilder als static Methode in Animation verschieben

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#498]
Der `AnimationBuilder` kann rausgeworfen werden und `Animation` um eine `static build` Methode mit der selben Funktionalität erweitert werden. 

@malt-r aus DSL-Anschluss Sicht ist dir das egal, oder?

Ich Frage deshalb:
```
    @DSLTypeAdapter(t = Animation.class)
    public static Animation buildAnimation(String path) {
        return new Animation(TextureHandler.getInstance().getTexturePaths(path), frameTime);
    }
```

Time:#1

**Comment by AMatutat** [comment]
überflüssig durch #348

**Comment by cagix** [comment]
> überflüssig durch #348

Naja, nicht ganz: Die statische Methode `build()` aus dem initialen Kommentar könnte tatsächlich Sinn machen - siehe Vorschlag in https://github.com/Programmiermethoden/Dungeon/issues/348#issuecomment-1555043292 (dort heisst die Methode passend zum restlichen JDK `of()`).

**Comment by AMatutat** [comment]
den gibts gar nit mehr. problem hat sich von selbst gelöst

**Comment by AMatutat** [comment]
> > überflüssig durch #348
> 
> Naja, nicht ganz: Die statische Methode `build()` aus dem initialen Kommentar könnte tatsächlich Sinn machen - siehe Vorschlag in [#348 (comment)](https://github.com/Programmiermethoden/Dungeon/issues/348#issuecomment-1555043292) (dort heisst die Methode passend zum restlichen JDK `of()`).

das haben wir ja
