### ISSUE TITLE
[Config] code Verzeichnis "auflösen"

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#50]
Siehe https://github.com/Programmiermethoden/Dungeon/pull/45#issuecomment-1293059433

`assets` nach -> `game/`

PM-Dungeon übernehmen

**Comment by cagix** [comment]
Naja, das war erstmal nur ne Frage :) ... Wenn wir wirklich sonst noch viel auf Top-Level haben, würde `code/` schon sinnvoll sein in meinen Augen. Auch wenn wir mehr als vier..fünf Gradle-Subprojekte haben, würde ein `code/`-Ordner eine schöne Klammer bilden. 

Aber wenn wir hier `code/` rausnehmen, sollten wir das dann ggf. "drüben" im PM-Duneon auch tun?

**Comment by cagix** [comment]
aus https://github.com/Programmiermethoden/Dungeon/pull/45#issuecomment-1293581797:

> Wollen wir da morgen nochmal kurz drüber sprechen? 

ja, lass uns nochmal direkt drüber sprechen. 

es gibt möglicherweise auch gründe, einen bestimmten aufbau zu nutzen. aber das sollten wir dann gemeinsam diskutieren und hinterher dokumentieren (warum weichen wir vom standard-layout ab).

für meinen geschmack sind die beiden ebenen `src/main/` für unsere kleinen projekte eher überflüssig und hinderlich. vermutlich ist es deshalb "drüben" im pm-dungeon auch anders gemacht. andererseits muss man nicht so viel konfigurieren (und erklären/dokumentieren), wenn man einfach den standard nimmt.


> 
> > Die Maven-Struktur sieht afaik vor, dass in jedem Subprojekt die Ordner `src/main/java/` und `src/test/java/` bzw. statt "java" entsprechende Unterordner für andere Sprachen existieren (etwa `src/main/cpp/`). Entsprechend würde ich `src/main/antlr/` erwarten (wie Du oben geschrieben hattest, ist dies eine Forderung vom Gradle-Plugin), auch wenn ich die Grammatik eher unter einem Resource-Ordner suchen würde. D.h. eigentlich müsste jetzt die Grammatik unter `<project>/code/dsl/src/main/antlr/` liegen und der Code für den Interpreter unter `<project>/code/dsl/src/main/java/`?

hierzu als quelle noch https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html - die schlagen tatsächlich `src/main/antlr` für antlr vor. also nix mit `src/main/resources/` für antlr :)
