### ISSUE TITLE
[GAME] Controller ersetzen?

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#500]
Können die Controller aus dem ECS entfernt werden?
Eigentlich sollten Systeme ganz oben in der Hierarchie sein.

**Comment by cagix** [comment]
@AMatutat Das Ding hat seit Ewigkeiten "current week" dran? Was ist der Status, warum tut sich hier nix?

**Comment by cagix** [comment]
Duplikat von #550
