### ISSUE TITLE
[DOC] Grafik um den Zusammenhang aller Projekt-Bausteine zu visualisieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#501]
Uns fehlt irgendwie eine Einstiegsgrafik, um das Projekt und die Projektbausteine zu visualisieren.  
Ich hätte gerne noch eine Grafik die alle Bausteine des Projektes und deren Bezug zueinander aufzeigen.
sprich:
- DSL
- Game
- Highscore System
- Deploy to Grading

Das soll auch wirklich nur ganz grob sein, nur damit der Betrachter zumindest alle Bausteine mal gesehen hat. 
Da kann man bestimmt auch ein wenig von unseren bestehenden Abbildungen für die Publikationen recyceln. 

#Time:2

**Comment by malt-r** [comment]
![taskbuilder_petri](https://user-images.githubusercontent.com/37513253/227265766-3e44f227-5b72-4c9d-8f00-c50f0dae89f4.png)

Erklärung / aufgeräumtes Diagram folgt!

**Comment by AMatutat** [comment]
@Lena241 mist, hab ich ganz vergessen. Kannst du das bitte auch aufbereiten (die Skizze in schön machen).
Vermutlich sollten wir uns dafür zusammen setzen, oder? Du baust die Grafik und ich erkläre was dort passiert ist.
