### ISSUE TITLE
[DSL] Petri Netze für verschachtelte Aufgaben

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#503]
Wir hatten mal darüber gesprochen Petri Netze nicht nur als Levelübergang #121 sondern auch zur verschachteln von Aufgaben zu nutzen. 

Wie könnte das genau aussehen? 
Was braucht es dafür?
Ist das nicht einfach #121.nur im selben Level?

**Comment by malt-r** [comment]
Wir sollten hier nochmal die Anforderungen klären, die wir an den Use Case von Petri-Netzen haben.

Für mich ist noch nicht genau geklärt, was **genau** wir durch Petri-Netzen abbilden wollen. Wie stehen die Stellen und Transitionen mit dem restlichen System in Verbindung?

Im Meeting mit @AMatutat am 28.03.23 haben wir eine Stelle mit einem Token als "aktive Aufgabe" interpretiert (vgl. auch #520). Das ist wahrscheinlich zu kurz gedacht. Zumindest, wenn wir tatsächlich den Zustand der Aufgaben mit Petri-Netzen modellieren wollen.

### Beispiel für den Ablauf der Bearbeitung einer verschachtelten Aufgabe (auch mit Betrachtung der GUI für die aktiven Quests):

Aufgabenverschachtelung:
- t1 (Oberaufgabe) hat zwei Unteraufgaben und zusätzlich einen eigenen Lösungsteil, ist also nicht direkt beendet, wenn die Unteraufgaben abgeschlossen sind
  - t2 (Unteraufgabe), erforderlich für t1
  - t3 (Unteraufgabe), erforderlich für t1

Wir haben auch schonmal darüber diskutiert, dass wir die Bearbeitung einer Oberaufgabe blockieren müssen, wenn die Unteraufgaben noch nicht abgegeben wurden.

### Zustand 0: Startzustand

**Questlog**

- Das Questlog ist leer

**Zustände pro Aufgabe**

- t1: inaktiv
- t2: inaktiv
- t3: inaktiv

***Event***: Spielcharakter spricht Questgeber von t1 an.

### Zustand 1

**Questlog**
- Im Questlog wird der **Aufgabentitel** von t1 angezeigt. Der **Aufgabentitel** müsste sich hier von der Aufgabenbeschreibung unterscheiden, da die Aufgabenbeschreibung den eigenen Lösungsteil von t1 beschreibt ("tue dies, löse das")
- t2 und t3 werden als Unteraufgaben von t1 angezeigt
  - Frage hierzu: Werden hier direkt die Aufgabenbeschreibungen von t2 und t3 angezeigt, ohne, dass der Spielcharakter bei den Questgebern dieser Aufgabe war? Eine Möglichkeit hierzu wäre eine "Dummy"-Aufgabe vor t2 und t3 zu schalten, die nicht in die Bewertung eingeht und deren Beschreibung lediglich "Finde den Zauberer, der dir t2 erklärt" ist. Wird dann dieser Zauberer angesprochen, wird die eigentliche Aufgabe t2 aktiv

**Zustände pro Aufgabe**

- t1: aktiv im Questlog, eigener Lösungsanteil noch nicht freigeschaltet
- t2: aktiv im Questlog, Lösungsanteil ist freigeschaltet
- t3: aktiv im Questlog, Lösungsanteil ist freigeschaltet 

***Event***: Spielcharakter gibt Antwort für t2 ab.

### Zustand 2

**Questlog**

- Im Questlog wird der **Aufgabentitel** von t1 angezeigt
- t2 wird entweder als erledigt (durchgestrichen, mit grünem Haken dahinter, etc.) dargestellt oder verschwindet ganz aus dem Questlog
- t3 wird als Unteraufgabe von t1 angezeigt

**Zustände pro Aufgabe**

- t1: aktiv im Questlog, eigener Lösungsanteil noch nicht freigeschaltet
- t2: aktiv oder inaktiv im Questlog, Bearbeitung abgeschlossen
- t3: aktiv im Questlog, Lösungsanteil ist freigeschaltet

***Event***: Spielcharakter gibt Antwort für t3 ab.

### Zustand 3

**Questlog**

- Im Questlog wird die Aufgabenbeschreibung von t1 angezeigt, also die Beschreibung, was noch zur Lösung der Aufgabe zu tun ist
- t2 und t3 werden entweder als abgeschlossen angezeigt oder sind aus dem Questlog verschwunden

**Zustände pro Aufgabe**

- t1: aktiv im Questlog, eigener Lösungsanteil ist zur Bearbeitung freigeschaltet
- t2: aktiv oder inaktiv im Questlog, Bearbeitung abgeschlossen
- t3: aktiv oder inaktiv im Questlog, Bearbeitung abgeschlossen

***Event***: Spieler gibt Antwort für t1 ab

### Zustand 4 - Endzustand

**Questlog**

- ist leer, alle Aufgaben abgeschlossen, oder alle Aufgaben werden als abgeschlossen markiert angezeigt

**Zustände pro Aufgabe**

- t1: aktiv oder inaktiv im Questlog, Bearbeitung abgeschlossen
- t2: aktiv oder inaktiv im Questlog, Bearbeitung abgeschlossen
- t3: aktiv oder inaktiv im Questlog, Bearbeitung abgeschlossen

### Aufgabenzustände gesammelt

Aus dem Beispiel gehen für mich folgende Aufgabenzustände hervor, die wir durch Petri-Netze modellieren müssen
1. inaktiv im Questlog, Bearbeitung blockiert
2. aktiv im Questlog, Bearbeitung blockiert
3. aktiv im Questlog, Bearbeitung freigeschaltet
4. aktiv im Questlog, Bearbeitung abgeschlossen 
5. inaktiv im Questlog, Bearbeitung abgeschlossen

**Comment by malt-r** [comment]
Gesammelte Notizen, unsortiert, einfach damit sie hier stehen und nicht verloren gehen (werde ich noch aufbereiten):

![system_petri-1](https://user-images.githubusercontent.com/37513253/230130200-169e9a2a-6575-4e40-a654-d6042bfb2206.png)

![system_petri-3](https://user-images.githubusercontent.com/37513253/230130240-fcf0d1aa-c0b7-4bc0-932a-e5e9661665e8.png)

![system_petri-4](https://user-images.githubusercontent.com/37513253/230130267-d2862c28-cd7f-4d53-a676-d2b8030145bc.png)

![system_petri-5](https://user-images.githubusercontent.com/37513253/230130285-269e255d-20c2-44cc-acc5-5009ef8b4e1f.png)

![system_petri-6](https://user-images.githubusercontent.com/37513253/230130307-a806d5e8-3f3e-47c9-854f-b57654fd8bc9.png)
