### ISSUE TITLE
[Game] Aussehen der Konfigurationsdatei bestimmen und anpassen

### ISSUE THREAD

**Issue by AHeinisch** [Programmiermethoden/Dungeon#505]
Wir haben aktuell kein wirkliches Konzept, wie die Struktur der Konfigurationsdatei aussehen soll.

Aktuell sind alle Tasten im Keyboard Config

```json
{
    "keyboard": {
        "movement": {
            "up": "51",
            "down": "47",
            "left": "29",
            "right": "32"
        },
        "inventory": {
            "open": "37"
        },
        "interact": {
            "world": "33"
        },
        "skill": {
            "first": "45",
            "second": "46"
        },
        "debug": {
            "activate": "30",
            "zoom_in": "39",
            "zoom_out": "40",
            "toggle_levelsize": "54",
            "spawn_monster": "52",
            "teleport_start": "38",
            "teleport_end": "36",
            "teleport_onend": "35",
            "teleport_cursor": "43"
      }
}
```

Dies ist gut, wenn man allgemein im folgenden System vorgeht:
1. -> Alle Tasten Ändern
2. -> Andere Parameter ändern

Die Gefahr ist aber das dadurch das alle Tasten zusammen liegen, die Struktur vereinfacht dargestellt 
```mermaid
graph LR;
   ROOT --> keyboard;
   keyboard --> debug;
   keyboard --> skill;
   keyboard --> inventory;
   keyboard --> interact;
   keyboard --> movement;
   ROOT --> windowConfigs;
```
Dies könnte aktuell bereits auf dieses abgeändert werden. Um vielleicht vom alle Tasten liegen bei Keyboard zu den Tasten werden auf ihre Funktion umverteilt und somit vielleicht auch dann schneller gefunden, da sie neben anderen Parametern liegt z.b. Heldengeschwindigkeit etc…
```mermaid
graph LR;
   ROOT --> Held;
   ROOT --> debug;
   ROOT --> windowConfigs;
   Held--> skill;
   Held--> inventory;
   Held--> interact;
   Held--> movement;
```

**Comment by cagix** [comment]
@AHeinisch @AMatutat ist das eigentlich noch aktuell? brauchen wir das https://github.com/Programmiermethoden/Dungeon/labels/meeting label?

**Comment by cagix** [comment]
> @AHeinisch @AMatutat ist das eigentlich noch aktuell? brauchen wir das [ meeting](https://github.com/Programmiermethoden/Dungeon/labels/meeting) Lets talk about that one label?

.o0( keine Antwort, dann assigne ich mal direkt an @AMatutat )

**Comment by AHeinisch** [comment]
Vollkommen vorbei gegangen. Hier geht es mehr um ein später. Es ist bereits beide Strukturen möglich nur wurde sich noch nicht entschieden.

**Comment by cagix** [comment]
> Vollkommen vorbei gegangen. Hier geht es mehr um ein später. Es ist bereits beide Strukturen möglich nur wurde sich noch nicht entschieden. 

dann "later"? 

ich hatte nur gefragt, weil das ticket seit zeiten das "meeting"-label hat, aber auch nicht im meeting aufpoppt ...
