### ISSUE TITLE
[AUFGABEN] Aufgabentypen "Ersetzen" und "Kombinieren" zusammenlegen?

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#507]
In https://github.com/Programmiermethoden/Dungeon/issues/382#issuecomment-1482820202 ist die DSL-Eingabe für die Definition einer Ersetzungsaufgabe angedeutet. Da die Definition der Mengen per DSL (aktuell) keine Beschränkungen bzgl. Elementanzahl vorgeben , könnte mit dieser Repräsentation sowohl Ersetzung als auch Kombination abgebildet werden (vgl. hierzu auch [PR #444](https://github.com/Programmiermethoden/Dungeon/pull/444/files#diff-205126b6d8f5bc522969cdcae3df7caee09d107f3e8e31c4f95782a1af8250a2R98-R106)). Kombinieren wäre damit eher ein Sonderfall der Ersetzung.

Laut [Protokoll #22](https://github.com/Programmiermethoden/2022-freiraum-dungeon/pull/107/files#diff-6955dcaa47bb6a9f3079ea487144601a45de7585c73d5d6914cb42ea427f3d58R244-R245) stand sowieso im Raum, ob wir die Aufgabentypen nicht zusammenlegen.

Meinungen dazu?

**Comment by malt-r** [comment]
@cagix @bcg7 @AMatutat ping. Hier eine Entscheidung zu treffen ist wichtig, um jetzt #444 auf einen finalen Stand zu bringen.

**Comment by cagix** [comment]
@malt-r Wenn die Konzepte und Strukturen sich sinnvoll vereinigen lassen und quasi durch Konfiguration oder "Injection" von Verhalten (Funktionsreferenzen o.ä.) steuern lassen, sehe ich einen großen Vorteil auf der Implementierungsebene. 

Ob man das dem User (also den Lehrenden, die die DSL bedienen) dann auch so verkauft, steht auf einem anderen Blatt. Es könnte sinnvoll sein, dass auf User-Ebene zu differenzieren (über Sprachkonstrukte der DSL) und dann im Interpreter wieder zu vereinigen und dann entsprechend zu bearbeiten.

**Comment by malt-r** [comment]
Aus dem Meeting mit @AMatutat, @AKirsch1 und @malt-r vom 03.05.23:

Die beiden Aufgabentypen werden zu "Ersetzen" zusammengefasst, da die Abgrenzung der beiden Typen uns unter Berücksichtigung der geplanten Eingabe (in https://github.com/Programmiermethoden/Dungeon/issues/382#issuecomment-1482820202 angedeutet) aktuell nicht mehr sinnvoll erscheint. Wir würden eher den Weg gehen und die unterschiedlichen Anwendungsfälle (ersetze 1 Element durch n Elemente; ersetze n Elemente durch 1 Element; ersetze n durch m Elemente) in der Doku für den Aufgabentyp darzustellen. Falls uns doch nachher auffällt, dass die Trennung sinnvoll ist, schätzen wir den Aufwand, das nachher wieder zu trennen als relativ gering ein.

**Comment by malt-r** [comment]
Wie im Meeting vom 03.05.23 besprochen: "Kombinieren" und "Ersetzen" wird zu "Ersetzen" zusammengelegt und die unterschiedlichen Anwendungsfälle (von denen Kombinieren dann auch einer wird) werden in der Doku zum Aufgabentyp dargestellt.
