### ISSUE TITLE
[AUFGABEN] Nur das Endergebnis oder auch Lösungsweg speichern

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#518]
Notizen aus Diskussion mit @AMatutat am 28.03.23:

Ursprüngliche Frage: Reihenfolge mitloggen oder nur Endergebnis? (siehe [offene Punkte 2 und 3 Brainstorming zu Kontrollmechanismen](https://github.com/Programmiermethoden/2022-freiraum-dungeon/pull/110/files#diff-ad33f375c551e000657be3a9bbe7e5efffebc415e58646460bd05aca89860596R99-R113))

Vorab nochmal zur Klärung: *Reporting* fasst das Erfassen, Bewerten und Speichern von Antworten zusammen

**TL;DR**: Wir präferieren, auch den Lösungsweg zu erfassen. Ein Reporting-System, was so aufgebaut ist, kann relativ einfach so konfiguriert werden, dass es auch nur das Endergebnis speichert.

- Fall 1 - nur Endergebnis:
  - (+) ist einfacher in der Implementierung
  - (+) Studi kann Fehler währender der Zuordnung korrigieren
  - (-) Zuordnung mit relevanter Reihenfolge -> Kette von Zuordnungsaufgaben, die händisch
    von der Lehrperson definiert werden müssen (oder Standardbibliothek?)
  - (?) Bei Fehler in einzelnem Zuordnungsschritt:
    - (-) falls Folgefehler abgebildet werden sollen, müsste jedes Szenario von Lehrperson
      (per Petri-Netz) modelliert werden
    - weitere Möglichkeit wäre aber auch Zurücksetzen von Aufgabenkonfiguration auf den
      Zustand vor dem Zuordnungsschritt mit Fehler
- Fall 2 - Zuordnungschritte einzeln erfasst (und evtl. auch einzeln bewertet, falls so
  konfiguriert) in einer Aufgabe:
  - (+) falls nur das Endergebnis relevant ist, kann das auch relativ einfach hiermit
    abgebildet werden
  - (+) keine händische Verkettung mehrerer Aufgaben für Erfassung von Zuordnungsschritten
    nötig
  - (+) Folgefehler können einfacher über die Bewertung herausgefiltert werden
    - Setzt voraus, dass die Bewertung nicht statisch Elemente vergleicht, sondern als
      Algorithmus implementiert ist
  - (?) Studi kann seine Fehler nicht einfach rückgängig machen -> müsste gesamte Aufgabe
    zurücksetzen
    - Erste Lösungsmöglichkeit: jedes Mal per GUI fragen, ob Studi Zuordnungsschritt machen
      will, aber das ist vermutlich GUI-Overload, führt zum sinnlosen wegklicken von GUI,
      sodass nichts gewonnen wird
    - Zweite Lösungsmöglichkeit: Auch einzelne Zuordnungsschritte rückgängig machen können
      (bspw. über Button im Menü des Quest-Geber-NPC)
      - das könnte eine Konfigurations-Geschichte sein, die optional durch DSL-Definition
        erlaubt werden kann
- **Fazit**: (vgl. untenstehendes Bild) **Fall 2** kann relativ einfach per Konfiguration
  genutzt werden, um **Fall 1** abzubilden, andersherum ist das schwieriger, daher klare
  Favorisierung von Fall 2
  - Bewertung per Algorithmus in DSL als Perspektive, aber erstmal standardmäßig den **Fall
    1** implementieren -> **Frage**: wie die Bewertungsfunktion konfigurierbar machen? Wo
    ist die Schnittstelle dafür?
- Implementierungsdetail:
  - Wahrscheinlich brauchen wir für InventoryComponent EventHandler für addItem(Item) und
    removeItem(Item), um da drin das Reporting (bzw. Erfassung) anzustoßen

![reporting_order](https://user-images.githubusercontent.com/37513253/228274814-c848a40e-782d-4fb9-8305-8c0375436c8c.png)

Das Bild zeigt die Zuordnung der Elemente {a,b,c,d} zu den Elementen {u,v,w,x}. Links (Fall 1) wird nur die Endzuordnung gespeichert, rechts (Fall 2) wird jeder Zuordnungsschritt gespeichert. In Fall 1 fällt die Information über Zuordnungsschritt 2 (b -> w) weg, in Fall 2 bleibt die erhalten.

**Comment by malt-r** [comment]
@AMatutat wollen wir ein Label 'Reporting' für die Issues, die sich damit befassen, einführen?

**Comment by cagix** [comment]
@malt-r Ist das Ticket so gedacht, dass Du und @AMatutat und @AKirsch1 in der WiMi-Runde weiter darüber diskutiert? Oder sollen alle hier gemeinsam im Issue diskutieren? Oder soll das in der nächsten Teamrunde (WiMi, PL) besprochen werden?

**Comment by cagix** [comment]
> Das soll erstmal die Gedanken aus dem Meeting mit @AMatutat sammeln, um dann final in der nächsten Teamrunde eine Entscheidung zu treffen.

@malt-r kannst dann bitte auch erstmal nur die personen assignen, die aktuell hier was zu tun haben? so poppt das ding jetzt nämlich bei mir als todo auf und ich muss wieder erst nachfragen. wenn ihr soweit seid, kannst du mich und bc ja dann wieder reinnehmen und das ding mit "meeting" lablen ...

**Comment by malt-r** [comment]
@AMatutat und ich haben in einem Meeting am 25.09. beschlossen, dass das hier ein `later` wird.

**Comment by cagix** [comment]
> @AMatutat und ich haben in einem Meeting am 25.09. beschlossen, dass das hier ein `later` wird.

@malt-r @AMatutat Das ist ja schön und gut. Aber mir scheint das doch ein zentrales Feature zu sein, d.h. darüber sollten wir im großen Meeting gemeinsam sprechen?
