### ISSUE TITLE
[AUFGABEN] Merge von Aufgabentypen "Positionieren" und "Elemente in der richtigen Reihenfolge wählen"

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#519]
In [PR #110 im 2022er Freiraum repo](https://github.com/Programmiermethoden/2022-freiraum-dungeon/pull/110/files#diff-ad33f375c551e000657be3a9bbe7e5efffebc415e58646460bd05aca89860596R101-R104) hat @cagix angemerkt, dass nach unserer aktuellen Definition bzgl. Datenstrukturen und Reporting kein großer Unterschied zwischen den Aufgabentypen "Positionieren" und "Elemente in der richtigen Reihenfolge wählen" besteht, bzw. dass "Elemente in der richtigen Reihenfolge wählen" durch "Positionieren" abgebildet werden könnte.

Dazu aus dem WiMi Meeting mit @AMatutat vom 28.03.23:

Aufgabentypen mergen?

- (+) Alle Aufgaben, die definiert werden, könnten sich die Szenarien teilen
- (+) "Elemente in der richtigen Reihenfolge auswählen" könnte auf "Positionieren" abgebildet werden, bzw. sind in folgendem Fall äquivalent
  - in einer "Positionieren"-Aufgabe ein Element dem Array-Index 1 zuordnen
  - in einer "Elemente in der richtigen Reihenfolge auswählen"-Aufgabe das erste Elemente wählen
- Abgrenzung ursprünglich:
  - Positionieren -> Alle Elemente sind dem Studi direkt sichtbar
  - Elemente auswählen -> nicht alle Elemente müssen dem Studi sofort sichtbar sein
- (?) konkrete Idee für ein Szenario: Türen in mehreren aufeinanderfolgenden Räumen
  auswählen, um Elemente auszuwählen (Labyrinth)
  - das würde für Positionierung problematisch werden, da (laut unserer Definition) beim
    Positionieren bereits alle verfügbaren Elemente vorher bekannt sein sollen; das geht hier nicht, da Studi nur einen Raum gleichzeitig sieht
  - das konkrete Szenario könnte allerdings auch durch Verkettung von Single Choice Aufgaben
    (für jeden Raum eine) realisiert werden
- Nach welchen Kriterien beurteilen wir, ob zwei Aufgabentypen unterschiedlich sind?
  - Aufgabendefinition ist unterschiedlich
  - Reporting ist unterschiedlich
- Beides (Aufgabendefinition und Reporting) könnte für beide gleich  ähnlich sein, was stark
  darauf hindeutet, dass sie tatsächlich gemerged werden können
- **Fazit**: beide Aufgabentypen zu einem “Zuordnen”-Aufgabentyp mergen
  - Konfigurationsmöglichkeiten für diesen Aufgabentyp:
    - Nur Endergebnis oder auch Lösungsweg bewerten
    - Bewertungsfunktion angeben (evtl. als Algorithmus)
    - Wird nach jedem Zuordnungsschritt bewertet oder erst ganz am Ende
    - Können einzelne Schritte vom Studi rückgängig gemacht werden
  - Btw: Das sind auch alles Konfigurationsmöglichkeiten, die für die Aufgabentypen
    “Ersetzen” und “Kombinieren” relevant sind

**Comment by malt-r** [comment]
Wie #518: Das soll erstmal die Gedanken aus dem Meeting mit @AMatutat sammeln, um dann final in der nächsten Teamrunde eine Entscheidung zu treffen.

**Comment by cagix** [comment]
> Wie #518: Das soll erstmal die Gedanken aus dem Meeting mit @AMatutat sammeln, um dann final in der nächsten Teamrunde eine Entscheidung zu treffen.

@malt-r kannst dann bitte auch erstmal nur die personen assignen, die aktuell hier was zu tun haben? so poppt das ding jetzt nämlich bei mir als todo auf und ich muss wieder erst nachfragen. wenn ihr soweit seid, kannst du mich und bc ja dann wieder reinnehmen und das ding mit "meeting" lablen ...

**Comment by malt-r** [comment]
Ergebnis aus der Diskussion von @AMatutat, @AKirsch1 und @malt-r vom 03.05.23:

Die **Unterscheidung** zwischen diesen beiden Aufgabentypen **bleibt bestehen**, da für die Aufgabentypen unterschiedliche Szenarien vorstellbar sind, die nicht einfach auf den jeweils anderen Aufgabentyp anwendbar sind.
Allerdings wird "Positionieren" in "Zuordnen" umbenannt, da der Begriff für uns klarer beschreibt, was in den Aufgaben passiert.

Wesentlicher Unterschied:
Bei "Zuordnen"-Aufgaben haben Studierende Zugriff auf alle Informationen gleichzeitig, es sind alle Elemente bekannt.
Bei "Elemente in der richtigen Reihenfolge auswählen" muss das nicht so sein, hier kann es auch sein, dass die Elemente den Studierenden nach und nach präsentiert werden.

Ein Beispiel: 
Die richtigen Türen als Antworten auswählen (ein Szenario für "Elemente in der richtigen Reihenfolge auswählen"), wobei sich diese Aufgabe über mehrere Räume erstreckt. 
Hier sind die auszuwählenden Elemente (die Türen) nicht von Anfang an alle bekannt, da ein Teil der Elemente erst beim Betreten eines Raums sichtbar wird.

**Comment by malt-r** [comment]
Wie im Meeting vom 03.05.23 besprochen:

Diese der beiden Aufgabentypen bleibt bestehen (Grund: https://github.com/Programmiermethoden/Dungeon/issues/519#issuecomment-1532933333)
