### ISSUE TITLE
[DOC] Konzept zur Dokumentation überarbeiten

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#539]
Wir hatten die Diskussion schon mal, und durch https://github.com/Programmiermethoden/Dungeon/pull/537#issuecomment-1497204620 bekommt sie für mich eine neue Relevanz.

Aktuell werden in den Java-Klassen alle als `public` gekennzeichneten Strukturen mit einem "aussagekräftigen" Javadoc-Kommentar dokumentiert. Damit folgen wir den üblichen Style-Regeln und Best-Practices.

Parallel pflegen wir unter `doc/` eine Markdown-Doku, die einerseits den Überbau/Hintergrund/... erklärt und eine Art Bedienungsanleitung enthält, und die andererseits für jede Klasse einen eigenen Eintrag hat. 

Das führt dazu, dass man bei Änderungen am Code sowohl die Javadoc als auch die `doc/` nachziehen muss - und weil das seine Zeit kostet, ist man schnell versucht, das zu umgehen (siehe auch https://github.com/Programmiermethoden/Dungeon/pull/537). 

---

Die WiMis sollen zeitnah Vorschläge zum Umgang mit der Situation erarbeiten und in der nächsten PL-Runde zur Diskussion vorstellen.

---

Ich persönlich möchte noch einmal auf die Dokumentation im JDK selbst hinweisen. 

Dort wird in den Java-Klassen ein relativ ausführlicher Javadoc gepflegt inkl. Klassen-Kommentar. Dabei wird im Klassenkommentar kurz erklärt, was die Klasse soll/kann und an kurzen+prägnanten Beispielen, wie man damit umgeht. Die Methoden-Kommentare erklären dann wie immer, was die Methode macht und warum.

Zusätzlich gibt es dann eine extra Dokumentation, die auf das "große" Gesamtbild schaut, ausführlichere Beispiele zum Umgang mit Klassen und Strukturen zeigt, und auch Design-Entscheidungen dokumentiert.

Vorteil: Informationen werden möglichst nicht doppelt dargestellt. 
Nachteil: Im Javadoc kann man keine Bilder einbetten. (Braucht man das wirklich?!)

---

Hängt mit https://github.com/Programmiermethoden/Dungeon/issues/542 zusammen.

**Comment by AMatutat** [comment]
Im Grunde müssen wir ja nur die folgenden Fragen entweder der Javadoc oder der Dokumentation zuordnen

- Wie sieht die Struktur des Projektes aus? 
- Was gibt es alles?
- Wie arbeite ich mit den Projekt? (Installation, Setup, quickstart) etc.
- Wofür ist die Klasse da?
- Was machen die Methoden in der Klasse? 
- Wofür benutze ich die Klasse/ die Methode? 
- Welche Besonderheiten gibt es bei der Verwendung der Klasse/Methode?
- Wie benutzte ich die Klasse/Methode? 
- In welchem Verhältnis stehen die Klassen zueinander?
- Warum ist das so? Designentscheidungen erklärt. 


Ich würde mich @cagix bzw. dem JDK da anschließen 

Das würde die externe Dokumentation massiv verschlanken und deutlich haltbarer machen, da nicht jede Codeänderung dokumentiert werden muss (zumal man auch wissen muss, wo das alles in der Dokumentation steht) und zum anderen habe ich im Code alles was ich brauche um mit den Code zu arbeiten. Ich muss meine IDE nicht verlassen. 



Eine Frage stellt sich dann für mich aber noch: Sehen wir den Code als Teil der Dokumentation? Wir geben unser "Framework" aktuell nicht als `jar` raus, daher haben alle Programmierenden-User auch den Quellcode vor Augen. 
Auf der anderen Seite macht libGDX das auch ganz gerne und es ist schrecklich.....

**Comment by cagix** [comment]
Ich würde mal frech zu Deinen Punkten die folgende Zuordnung treffen:

> * Wie sieht die Struktur des Projektes aus? [**Dokumentation**]
> * Was gibt es alles? [**Dokumentation**]
> * Wie arbeite ich mit den Projekt? (Installation, Setup, quickstart) etc. [**Dokumentation**]
> * Wofür ist die Klasse da? [**Javadoc**] und [Dokumentation]
> * Was machen die Methoden in der Klasse? [**Javadoc**]
> * Wofür benutze ich die Klasse/ die Methode? [**Javadoc**]
> * Welche Besonderheiten gibt es bei der Verwendung der Klasse/Methode? [**Javadoc**]
> * Wie benutzte ich die Klasse/Methode? [**Javadoc**]
> * In welchem Verhältnis stehen die Klassen zueinander? [**Dokumentation**] und [Javadoc]
> * Warum ist das so? Designentscheidungen erklärt. [**Dokumentation**]

---

> Eine Frage stellt sich dann für mich aber noch: Sehen wir den Code als Teil der Dokumentation? 

Würde ganz klar sagen: Ja. 

> Programmierenden-User auch den Quellcode vor Augen. Auf der anderen Seite macht libGDX das auch ganz gerne und es ist schrecklich.....

Ich denke, man kann entweder die Javadoc als eigenes Jar veröffentlichen und irgendwie "dazulinken" (also der IDE sagen, wo die Doku ist) oder beides (Code+Javadoc) in einem gemeinsamen Jar veröffentlichen. Beim JDK klappt das ja auch, dass ich per Mouse Over die Sachen angezeigt kriege?

**Comment by cagix** [comment]
@AMatutat @malt-r @AKirsch1 Status?

**Comment by AMatutat** [comment]
"Das Konzept scheint zu stehen (siehe https://github.com/Programmiermethoden/Dungeon/issues/539#issuecomment-1497567237).
Die Umsetzung wäre jetzt der nächste Schritt. Dabei werden wir vermutlich Feinheiten ausdiskutieren (das geht anhand eines Beispiels besser).
Mein Vorgehen wäre jetzt:
- Konzept ins Wiki aufnehmen
- Hier dichtmachen
- Jeweils einen Draft-PR für eine Java-Klasse und ein Dokument im "doc"-Ordner erstellen und dort das Konzept umsetzen. Dann gucken wir uns nochmal an, ob uns das Konzept auch in der Praxis sinnvoll erscheint, feintunen es ggf. und setzen es dann flächendeckend um."

**Comment by AKirsch1** [comment]
Um das einmal hier zu aktualisieren:

Konzept ist im Wiki: [HOW TO: Dokumentation](https://github.com/Programmiermethoden/Dungeon/wiki/HOW-TO:-Dokumentation)
Und hier ein erstes Sammelissue für ein paar Java-Klassen: [#559](https://github.com/Programmiermethoden/Dungeon)/issues/559

**Comment by cagix** [comment]
> * Konzept ins Wiki aufnehmen
> * Jeweils einen Draft-PR für eine Java-Klasse und ein Dokument im "doc"-Ordner erstellen und dort das Konzept umsetzen. Dann gucken wir uns nochmal an, ob uns das Konzept auch in der Praxis sinnvoll erscheint, feintunen es ggf. und setzen es dann flächendeckend um."
> * Hier dichtmachen

wenn das konzept umsetzbar erscheint, dann macht das vorgehen sinn :)

> Und hier ein erstes Sammelissue für ein paar Java-Klassen: [#559](https://github.com/Programmiermethoden/Dungeon)https://github.com/Programmiermethoden/Dungeon/issues/559

sammel-issues sind in github irgendwie hässlich und verstopfen vor allem den tracker. aber man kann sie gut nutzen, um gezielt viele einzeltickets loszuschiessen. danach dann das sammelticket aber direkt wieder schliessen, bitte.
