### ISSUE TITLE
[AUFGABEN] Konzept für Reporting-Ablauf

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#541]
Gesammelte Notizen, unsortiert, einfach damit sie hier stehen und nicht verloren gehen (werde ich noch aufbereiten):

![reporting-1](https://user-images.githubusercontent.com/37513253/230133141-9ca573e9-2178-46d9-890c-eef05f4922bc.png)

**Comment by malt-r** [comment]
Konzept zur Verknüpfung von Entity mit konkretem Task-Element (bspw. Schriftrolle, die eine Antwort für eine Frage hält). 

![task2entity](https://user-images.githubusercontent.com/37513253/230376189-84948f8d-8ddd-491c-8fdb-111be93d217e.png)

**Comment by cagix** [comment]
@malt-r Warum ist das in einem Ticket und nicht in einem PR?

**Comment by malt-r** [comment]
Ich wollte meine handschriftlichen Notizen nicht in den `doc/` Ordner laden, weil das ja noch nicht final entschieden ist.

**Comment by cagix** [comment]
> Ich wollte meine handschriftlichen Notizen nicht in den `doc/` Ordner laden, weil das ja noch nicht final entschieden ist.

so lange wie noch nicht gemergt ist, macht das doch nix? durch den squash-merge bleibt ja sowieso nur der wirklich zu mergende content.
