### ISSUE TITLE
[DOC] Vereinheitlichung der Namen in der Dokumentation

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#542]
In der Dokumentation `doc/` herrscht üppiger Wildwuchs. 

- Viele Ordnernamen werden komplett klein geschrieben, aber nicht alle: `doc/HUD/` beispielsweise nicht. 
- Die meisten Readme werden komplett klein geschrieben, aber nicht alle, beispielsweise `dsl/README.md`. 
- Die meisten Dateinamen werden klein geschrieben, aber nicht alle. Zusätzlich wird bei manchen CamelCase verwendet, bei anderen Snake-Case.
- Der Ordner für Abbildungen heisst mal `figs/`, mal `img/`. 
- Manche Order wie `ecs/` oder `graphic/` haben noch kein `readme.md`.
- `ecs/gameelements/onDeathDropLoot` ist eine Datei ohne Endung.

**Bitte aufräumen!**

- Alle Ordner und Dateien werden komplett klein geschrieben.
- Falls nötig, nutzen wir Snake-Case.
- Jeder Ordner hat ein `readme.md`.
- Die Abbildungen landen in Ordnern namens `img/`. (Ich komme zwar von LaTeX her und dort bevorzugt man `figs/`, aber so muss nur ein Ordner umbenannt werden.)
- Jede Datei bekommt eine Endung!
- Jede Markdown-Datei hat einen YAML-Header mit dem Element `title: "..."`. Die oberste Gliederungsebene ist dann H2.

--- 

Hängt mit https://github.com/Programmiermethoden/Dungeon/issues/539 zusammen.

**Comment by AMatutat** [comment]
Damit sollten wir aber warten bis der Quickstart #496 gemerged ist. Wenn wir jetzt großflächig die Daten umbenennt, wird @Lena241 richtige Probleme beim Rebasen bekommen. Git mag da so garnicht

**Comment by cagix** [comment]
warten

**Comment by cagix** [comment]
@AMatutat @malt-r In Bezug auf den Snake-Case bin ich auch diskussionsbereit - da müsstet ihr halt ein Konzept erstellen und das dann kurz vorstellen.

**Comment by cagix** [comment]
@AMatutat @malt-r @AKirsch1 ping

**Comment by AMatutat** [comment]
@AKirsch1 @malt-r ich mach das mal grade, mein Hirn braucht grade etwas stupides
