### ISSUE TITLE
[GAME] Vereinfachen von Coordinate und Point

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#547]
Wir nutzen (berechtigt) zwei unterschiedliche Koordinatensysteme. 
Coordinate mit integer Werten für die Tiles im Level und Point mit float werten für Entitäten, 
Das ist als user des „Framework“ echt fuddelig und eigentlich unnötig. 

Lass uns das vereinfachen. 

Mein erster Gedanke wäre, Coordinate nurnoch Level intern zu benutzen und nach außen nur mit Point zu arbeiten. 
Alle Schnittstellen die ein Coordinate bekommen oder zurückgeben müssten auf Point geändert und entsprechend gerundet werden. 

Vielleicht kann man beides auch morgen? Aber ich glaube das wird eklig…

**Comment by cagix** [comment]
Wäre umgedreht nicht besser? Dann würden die Studis in Feldern/Tiles (also Integern) denken/rechnen, und intern ist es dann für libGDX in Float?

**Comment by AMatutat** [comment]
Hmm warum eigentlich nicht, recht hast du ja. 
Eigentlich ist der float Kram dann nur noch für die bewegungsgeschwindigkeit relevant. Das kriegt man erklärt

**Comment by cagix** [comment]
> Hmm warum eigentlich nicht, recht hast du ja. 
> 
> Eigentlich ist der float Kram dann nur noch für die bewegungsgeschwindigkeit relevant. Das kriegt man erklärt

ah. das hstte ich nicht auf dem schirm. aber auch dafür könnte man kachelbasiert arbeiten?

**Comment by cagix** [comment]
🐣🧳🛫🏖️

**Comment by AMatutat** [comment]
> ah. das hatte ich nicht auf dem schirm. aber auch dafür könnte man kachelbasiert arbeiten?

Könnte man auch. Dann würde man immer von Kachel zu Kachel gehen. Wäre im jetzigen. System eine Geschwindigkeit von 1. Aber ich glaube die Option kann man sich offen halten. Ich grübel mal was man da schönes machen kann

**Comment by cagix** [comment]
> > ah. das hatte ich nicht auf dem schirm. aber auch dafür könnte man kachelbasiert arbeiten?
> 
> 
> 
> Könnte man auch. Dann würde man immer von Kachel zu Kachel gehen. Wäre im jetzigen. System eine Geschwindigkeit von 1. Aber ich glaube die Option kann man sich offen halten. Ich grübel mal was man da schönes machen kann

diagonal könnte 1.5 sein, und vielfaches (2 pro zug) könnten ja auch gehen.

aber du hast recht, ich habe das nur aus positionierungs- und hitbox-blickwinkel gesehen. da würde kachelbasiert einiges sehr deutlich vereinfachen. aber geschwindigkeit ist nochmal was anderes. 🤔

**Comment by AMatutat** [comment]
Mein Konzept Vorschlag wäre jetzt folgendes:
- `Coordinate` (integer-basiert) und `Point` (float basiert) bleiben beide vorhanden
- Intern kann auch weiter mit den float werten gearbeitet werden. Grade die Positionierung der Entitäten (also wo stehe ich grade) wird weiter float basiert sein, damit sich Figuren flüssig bewegen können und nicht wie Schachfiguren "springen". 
- In unserer "API" arbeiten wir nur noch mit `Coordinate`, bedeutet: alle Parameter die wir bekommen und rausgeben sind `Coordinate`
- Das `PositionComponent` speichert weiter einen `Point`, intern kann dann über das Component die exakte Position abgefragt werden. Wichtig für das `VelocitySystem`, `DrawSystem` und `HitboxSystem`

Jetzt wo ich das aufgeschrieben habe, wirkt es wieder verwirrend und komplex.

**Comment by AMatutat** [comment]
Gegenthese: Wir schmeißen `Coordinate` raus und überall wo wir das jetzt verwendet haben, runden wir den dann zu verwenden ?Point` auf oder. ab? 
Dann müssen die Studis nicht mehr Tilebasiert denken, sondern nurnoch pixelbasiert.

**Comment by cagix** [comment]
> Mein Konzept Vorschlag wäre jetzt folgendes:
> [...]
> Jetzt wo ich das aufgeschrieben habe, wirkt es wieder verwirrend und komplex.

Finde ich im Prinzip gut: Nach außen hin nur noch `Coordinate`, nach innen `Position`. Allerdings müsste dann in den Bewegungssystemen tatsächlich eine Umrechnung von `Coordinate` nach `Position` stattfinden sowie eine Punkt-weise Bewegungsausführung (also eine Art Mini-Path-Berechnung und dann automatische Ausführung der Bewegung). Damit hätten die Kunden (aka PM-Studis) das deutlich einfacher, sie könnten (wenn sie wollten) auch direkt alles in `Coordinate` machen und würden halt "hüpfen". Wenn sie unsere Systeme nutzen, kriegen sie dann trotzdem die smoothe Ausführung. Und wer hardcore ist, greift eh an der API vorbei und macht seinen eigenen Kram.


> Wir schmeißen Coordinate raus und überall wo wir das jetzt verwendet haben, runden wir den dann zu verwendenden Point auf oder ab?

Wäre auch denkbar. Aber sobald ich ein `Tile` in der Hand habe, bin ich doch wieder auf `Coordinate`? Na gut, das könnte man in der API effizient in einen `Point` (besser `Position`) umrechnen. Aber andersherum - kriege ich eine `Position` effizient in eine `Coordinate` umgerechnet, denn die brauche ich ja für die interne 2D-Matrix?

**Comment by JudiTeller** [comment]
Beim genaueren Überlegen fände ich es fast einfacher mit Variante zwei, überall Positions, mit Konvertierung zu Coordinates, wenn nötig.

@cagix oder gabs bei dir feedback, dass Studis gar nicht mit der Unterscheidung klargekommen sind? Bei mir hatte sich da keiner beschwert.

Bei Variante zwei kann doch einfach ein int-cast genutzt werden, um den Nachkommabereich der Positions abzuhacken und zur nächst niedrigeren "Hauptkoordinate" umzuwandeln?

![image](https://github.com/Programmiermethoden/Dungeon/assets/59529322/983863b5-906b-4099-995f-68ee5fd6b165)

**Comment by AMatutat** [comment]
> Beim genaueren Überlegen fände ich es fast einfacher mit Variante zwei, überall Positions, mit Konvertierung zu Coordinates, wenn nötig.
> 
> @cagix oder gabs bei dir feedback, dass Studis gar nicht mit der Unterscheidung klargekommen sind? Bei mir hatte sich da keiner beschwert.
> 
> Bei Variante zwei kann doch einfach ein int-cast genutzt werden, um den Nachkommabereich der Positions abzuhacken und zur nächst niedrigeren "Hauptkoordinate" umzuwandeln?
> 
> ![image](https://user-images.githubusercontent.com/59529322/252904318-983863b5-906b-4099-995f-68ee5fd6b165.png)

Ist das nicht prinizipiell was wir aktuell tun? Nur mit umwegen über `Point#toCoordinate`?  

Grundsätzlich bin ich aber bei dir: Die Studis arbeiten mit Point bzw Tiles und Coordinate wird nur intern verwendet => Alle Methoden müssen entsprechende Parameter bekommen und zurückgeben. 

Ich hatte die Tage (ich finde es leider grade nicht wieder). mal über 
`Pojnt extends Coordinate` nachgedacht. Dann könnte ich überall wo ich eine Coordinate reinstecken will, auch ein Point verwenden und durch Polymorphie mir entweder den int oder den float ziehen.

Ich muss das Wiederfinden, da bin ich nämlich auf mir unbekanntest java-Verhalten gestoßen.

**Comment by cagix** [comment]
> @cagix oder gabs bei dir feedback, dass Studis gar nicht mit der Unterscheidung klargekommen sind? Bei mir hatte sich da keiner beschwert.

Nein, direktes Feedback gab es nicht. 

Ich denke, wir richten uns mit diesem Framework explizit an die Zweitsemestler und wollen ihnen damit die Arbeit im Unterricht leichter machen. Die Unterscheidung zwischen "kachelbasiert" und "pixelgenau" ist dabei aus meiner Sicht nicht unbedingt förderlich, zumal das ja ziemlich häufig in der API wechselt(e) - mal so, mal so. Ich würde deshalb für eine möglichst einfache Schnittstelle plädieren und aber gleichzeitig den Weg für die Nutzung der Alternative nicht versperren. Für mich wäre das "kachelbasiert" als Default in der an die Studis gerichteten API, intern "pixelgenau" und zusätzliche Methoden in der API, die auch "pixelgenau" anbieten.

> mal über `Pojnt extends Coordinate` nachgedacht.

Das könnte ein interessanter Weg sein. Ich würde einen Typ `Position` vorschlagen, welcher überall in der API genutzt wird. Dieser Typ sollte Zugriffsmethoden haben, mit denen man die Position "kachelbasiert" bekommen und einstellen kann, und weitere, die analog "pixelbasiert" arbeiten. Dann brauche ich nur noch konkrete (Unter-) Typen für "kachelbasiert" (`Coordinate`) und "pixelgenau" (`Point`). Damit kann sich der Kunde selbst aussuchen, womit er arbeiten will.

**Comment by AMatutat** [comment]
`Tile` ist keine Position. `Tile` HAT eine Position (aktuell als `Coordinate`) gespeichert.

**Comment by AMatutat** [comment]
Irgendwie bauen wir uns grade ein großes konstrukt auf,.

Was wäre denn wenn wir nur noch `Point` hätten (könnten wir in `Position` umbenennen.
`Coordinate` fliegt restlos raus. 
In `Point` speichern wir weiter `float x` und `float y`. 
In `Tile` speichern wir die Position dann nicht mehr als `Coordinate` sondern als `Point`(die Werte haben dann zwar immer `.0f`, aber das ist ja egal).
Die einzigen stellen an denen wir aus Float-Werten ein Integer-Wert machen müssten, ist wenn wir das Level-Layout betrachten (das ist schließlich ein Tile[x][y]-array). 
 An diesen stellen könnten wir doch einfach manuell casten
```java
public void tileAt(Point p){
return layout[(int)p.y][(int)p.x];
}
```

Als Studi hab ich dann `Point` und kann da sowohl float als auch integer werte reinstecken, so richtig gedanken muss ich mir da halt nicht mehr machen.

**Comment by cagix** [comment]
> `Tile` ist keine Position. `Tile` HAT eine Position (aktuell als `Coordinate`) gespeichert.

technisch ist das korrekt.

aber als studis möchte ich ein tile wie eine position nutzen können - ich stehe mit meiner figur auf einem tile, da ist die position meiner figur eben das tile.

**Comment by cagix** [comment]
> ```java
>     interface Position {
>         default Pair<Integer> tile() {
>             return new Pair<>(pixel().x().intValue(), pixel().y().intValue());
>         }
> 
>         default Pair<Float> pixel() {
>             return new Pair<>(tile().x().floatValue(), tile().y().floatValue());
>         }
>     }
> 
>     record Pair<T>(T x, T y) {}
> 
>     final class Point implements Position {
>         private final Pair<Float> position;
> 
>         public Point(float x, float y) {
>             position = new Pair<>(x, y);
>         }
> 
>         @Override
>         public Pair<Float> pixel() {
>             return position;
>         }
>     }
> 
>     final class Coordinate implements Position {
>         private final Pair<Integer> position;
> 
>         public Coordinate(int x, int y) {
>             position = new Pair<>(x, y);
>         }
> 
>         @Override
>         public Pair<Integer> tile() {
>             return position;
>         }
>     }
> ```
> 

Die Methoden im Interface deuten auf tilebasiert vs. pixelbasiert hin, das passt. 

Aber die ableitenden Klassen müssten schon jeweils beide Zugriffsmethoden implementieren, sonst muss ich ja doch wieder manuell konvertieren. D.h. im Interface sollte noch eine Defaultimplementierung sein, die sich auf einer abstrakten Methode der ableitenden Klassen abstützt. Damit muss ich als ableitende Klasse nur noch eine Methode implementieren. In Haskell wird das bei der Typklasse `Eq` rekursiv gemacht: Da gibt es `==` und `/=` im Interface, und die Defaultimplementierung ist einfach `x /= y    =  not (x == y)` und `x == y    =  not (x /= y)`. Wenn ich das ableite, muss ich eine der beiden Funktionen mit Leben erfüllen und dann passt alles. Hier bei uns müssten sich beide Methoden dann noch auf einer Zugriffsmethode auf die Daten abstützen, die ich im Interface nicht habe und die dann die implementierenden Klassen implementieren müssen.

Und ich würde wirklich gern von "`Coordinate`" weg und hier ein `Tile` haben (siehe mein letzter Kommentar). Mir ist bewusst, dass ein `Tile` erstmal noch viel mehr ist. Aber es hat eben eine Position - die wird jetzt ein `Pair<Integer>` und dann kann ich es als `Position` verwenden.

**Comment by cagix** [comment]
> Irgendwie bauen wir uns grade ein großes konstrukt auf,.

Da bin ich grad nicht bei Dir. Sobald Du gedanklich akzeptieren kannst, dass ich ein `Tile` als `Position` verwenden kann, wird nach außen alles einfach und übersichtlich. Es gibt dann auch keinen Grund zum manuellen Transformieren oder zum Casten ...


> 
> Was wäre denn wenn wir nur noch `Point` hätten (könnten wir in `Position` umbenennen. `Coordinate` fliegt restlos raus. In `Point` speichern wir weiter `float x` und `float y`. In `Tile` speichern wir die Position dann nicht mehr als `Coordinate` sondern als `Point`(die Werte haben dann zwar immer `.0f`, aber das ist ja egal). Die einzigen stellen an denen wir aus Float-Werten ein Integer-Wert machen müssten, ist wenn wir das Level-Layout betrachten (das ist schließlich ein Tile[y][x]-array). An diesen stellen könnten wir doch einfach manuell casten
> 
> ```java
> public void tileAt(Point p){
> return layout[(int)p.y][(int)p.x];
> }
> ```

Finde ich nicht wirklich elegant. Ich sehe Positionen - da ist mir erstmal egal, ob die int- oder float-basiert sind. Aber ich kann die als Tile (kachelbasiert) oder als Point (pixelgenau) interpretieren und habe ich die passenden Typen dafür:

- Beim Point ist das dann wirklich nur ein `(float, float)`-Tupel und nix weiter.
- Beim Tile ist das ein `(int, int)`-Tupel plus noch Textur und Level-Gedöns. 

Beide kann ich als `Position` verwenden, ich muss nicht casten und auch nicht umrechnen, weil ich mir bei Bedarf einfach die jeweils andere Interpretation geben lassen kann. Das machen die Klassen dann unter sich aus. 

Ggf. braucht das Interface noch Zugriffsmethoden, die das Ding als `Point` bzw. `Tile` zurückliefern. Dann kann ich `Point p; p.tile();` aufrufen und habe wirklich das zu dem Punkt gehörende Tile und andersrum `Tile t; t.point();`, um den Mittelpunkt des Tiles zu bekommen. 



> Für das Path-Finding könnte man dann noch `findPath(Point from, Tile to)` als Hilfsaufruf für `findPath(from, to.position());` anbieten. `findPath(Tile from, Tile to)` und `findPath(Tile from, Point to)` könnte man auch anbieten, aber ich seh den Anwendungsfall grade nicht.

Das sollte schlicht `findPath(Position from, Position to)` sein.

**Comment by cagix** [comment]
Nach der Diskussion hier mein überarbeiteter Vorschlag:

```java
public interface Position {
    // kachelbasierter Zugriff
    Tile tile();
    void tile(Tile);

    // pixelgenauer Zugriff
    Point point();
    void point(Point);
}

public interface Pair<T> {
    T x();
    T y();
}

public class Tile implements Pair<Integer> implements Position {}
public class Point implements Pair<Float> implements Position {}
```

Dabei sind `Tile` die Klasse im Level-Bereich und `Point` ist davon unabhängig.

In `Tile` wäre dann `Tile tile() { return this; }` und `Point point() { return new Point(this.x, this.y); }`.

In `Point ` wäre dann `Tile tile() { return Level.toTile(this); }` und `Point point() { return this; }`.

**Comment by cagix** [comment]
```java
public interface Position<T> {
    // kachelbasierter Zugriff
    Tile tile();
    void tile(Tile);

    // pixelgenauer Zugriff
    Point point();
    void point(Point);

    // direkter Zugriff auf x und y
    T x();
    T y();
}

public class Tile implements Position<Integer> {}
public class Point implements Position<Float> {}

findPath(Position<Number> from, PositionPosition<Number> to) {...}
```

hmmm. etwas besser.

**Comment by cagix** [comment]
@AMatutat Das hier scheint mir die beste Lösung zu sein:

```java
public interface Position {
    // kachelbasierter Zugriff
    Tile tile();
    void tile(Tile);

    // pixelgenauer Zugriff
    Point point();
    void point(Point);
}

public class Tile implements Position {
    // direkter Zugriff auf x und y
    Integer xCoordinate();
    Integer yCoordinate();
}
public class Point implements Position {
    // direkter Zugriff auf x und y
    Float xPixel();
    Float yPixel();
}

findPath(Position from, Position to) {...}
```

**Comment by AMatutat** [comment]
@JudiTeller setz mal https://github.com/Programmiermethoden/Dungeon/issues/547#issuecomment-1632412713 um

**Comment by AMatutat** [comment]
> ich stoße jetzt aber auf Bereiche, in denen jetzt Tile statt dem alten Coordinate instanziiert werden soll, aber nicht geht, weil Tile abstrakt ist.

Kannst du mal so eine stelle zeigen? Brauche was. zum angucken um das Problem zu verstehen

**Comment by JudiTeller** [comment]
```java
    private Tile randomFloor(LevelElement[][] layout) {
        Tile tile =
                new Tile(RANDOM.nextInt(layout[0].length), RANDOM.nextInt(layout.length));
        LevelElement randomTile = layout[tile.y()][tile.x()];
        if (randomTile == LevelElement.FLOOR) {
            return tile;
        } else {
            return randomFloor(layout);
        }
    }
```
ist im RandomWalkGenerator
das war mal Coordinate

**Comment by AMatutat** [comment]
> ```java
>     private Tile randomFloor(LevelElement[][] layout) {
>         Tile tile =
>                 new Tile(RANDOM.nextInt(layout[0].length), RANDOM.nextInt(layout.length));
>         LevelElement randomTile = layout[tile.y()][tile.x()];
>         if (randomTile == LevelElement.FLOOR) {
>             return tile;
>         } else {
>             return randomFloor(layout);
>         }
>     }
> ```
> 
> ist im RandomWalkGenerator das war mal Coordinate

first of all: WTF. Das ist ja ein potenzieller Endlos-loop. 
second of all: WTF das hab ich geschrieben..... Yikes....

Aber um auf das eigentliche Problem einzugehen:
Hier sind wir im Generierungsprozess des Levels, es gibt also noch keine Tiles, daher sollten wir hier auch keine Tiles verwenden.

Ich sehe auf Anhieb zwei Möglichkeiten:

1. Coordinate durch Point ersetzen und dann immer runden.
2. In `private record Coordinate` wie das alte `Coordinate` implementieren. Ist hier ein internes Hilfskonstrukt und aus meiner Sicht the way to go.

**Comment by cagix** [comment]
Im Prinzip geht es darum, dass wir noch kein `Tile` haben, aber die Integer für die Indizes speichern wollen (also die alten `Coordinate`)?

Wenn wir alles richtig machen, sollte ein `Point` hier eigentlich reichen - der kann ja ohne Verlust in ein `Tile` mit einem `x` und `y` Index umgewandelt werden. Ansonsten würde ich dem Ding einfach ein `Tuple<Integer, Integer>` spendieren. Wenn wir ein internes Record `Coordinate` nehmen, kriegt das bestimmt irgendwer noch durcheinander?

**Comment by JudiTeller** [comment]
Mir ging es nicht darum, dass Tile spezifisch an der Stelle nicht instanziiert werden kann (also zum Teil schon).
In meinem Codesnippet wurde ursprünglich ja Coordinate verwendet.

Mir ging es darum, dass sich Tile in der jetzigen Form nicht wirklich dafür eignet, als ein Koordinatenspeicher zu agieren.
Um das zu tun, müsste man ja an jeder Stelle eine spezifische Subclass von Tile instanziieren.

Wenn wir jetzt sagen, dass überall nur noch Point hinkommt, ist das Interface Position aktuell ja auch hinfällig?
Oder sollen wir das als möglichen Punkt zum Anknüpfen für die zukünftigen Studis drinlassen?

Ich refactor auf jeden Fall mal in die Richtung, dass im Rest des Codes nur noch Point verwendet wird und Tile-intern der record ist.

**Comment by AMatutat** [comment]
Aber Coordinate nutzen wir abseits von Tile ja wirklich nur als Hilfsspeicher, oder?

**Comment by AMatutat** [comment]
@JudiTeller hat in #875 bereits eine Lösung vorgestellt.
Ich kann noch nicht den Finger drauf legen, aber mein Bauchgefühl ist noch nicht richtig glücklich damit.
Ich muss mich da nochmal als Zeichenbrett setzen

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
