### ISSUE TITLE
[Game] Sinn der Trennung in Game und zwei andere Starterklassen?

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#549]
In `starter` gibt es drei verschiedene Klassen, die sich gegenseitig referenzieren und aufrufen. Könnte man das nicht mal sauber in eine gemeinsame Klasse verpacken?

Zusätzlich kommt dazu: Die Studis müssen `starter.Game` modifizieren. Das passt nicht zum Framework-Gedanken (den wir ja ziemlich aufgeweicht haben). Es wäre besser, wenn die Studis ihre eigene Klasse mit einer `main()` schreiben würden und darin dann Methoden aus `starter.Game` aufrufen würden (oder sich selbst übergeben würden o.ä.).

**Comment by AMatutat** [comment]
Die Aufteilung liegt zu einem an der alten Hoffnung mehrere Systeme (Desktop, Web) zu bedienen als auch der kapselung von Libgdx. 

Aber das kann man bestimmt merken

**Comment by cagix** [comment]
Wie realistisch ist eine Trennung in Desktop und Web? Wenn das nicht ein Feature ist, was in den nächsten 6..12 Monaten fest geplant ist, dann ist das YAGNI.

Eine andere Sache ist aber, dass die Studis den "Framework"-Code modifizieren sollen und sich nicht einfach "rein-hooken" (Dependency Injection o.ä.).

Ich glaube, man kriegt das schon so hin, dass man mit einer minimalen Anzahl von Startern (N=1) auskommt und sich trotzdem die Option auf Web nicht verbaut.

**Comment by cagix** [comment]
@AMatutat Mein Vorschlag wäre, das so umzubauen:

1. Es existiert ein Desktop-Launcher.
2. Es existiert ein Web-Launcher.
3. Es gibt eine Stelle, wo die Studis ihren Teil für das Setup und die Game-Loop einschieben/ändern können. 

Danach schauen wir weiter. Wenn der Web-Launcher funktioniert, könnte man das drin lassen. Sonst halt weg. 

Der Hook für die Studis könnte ein Interface mit einer Default-Methode sein, welches sie implementieren und die Methode ergänzen bzw. ersetzen und was dann per Injection in den Starter reingepackt wird.

**Comment by AMatutat** [comment]
Unter zwei kommen wir nicht:
Wir brauchen einmal ein `com.badlogic.gdx.Game`(das ist aktuell `LibgdxSetup`) und das zeigt dann einen libGDX `ScreenAdapter` an, das ist unser `starter.Game`
`DesktopLauncher` und `LibgdxSetup` könnte man nach dem YAGNI-Motto zusammenlegen.

**Comment by AMatutat** [comment]
Vorschlag:
- `LibGDXSetup` wird als Nested-Class in `Game` integriert
`DesktopLauncher#run` wird in der Nested-Class integriert

=> `Game` als einzige Starter Klasse.

In #582 zieht man dann noch die `main` aus `Game` raus.
