### ISSUE TITLE
[Game] Welche Controller werden noch gebraucht im ECS?

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#550]
Brauchen wir noch einen `SystemController`? Könnte den Job nicht das `ECS_System` übernehmen?

**Comment by AMatutat** [comment]
Selben Gedanke hatte ich auch. Ich glaube die Controller können entfernt werden und wir arbeiten direkt mit den Systemen.

**Comment by AHeinisch** [comment]
> Die HUD Geschichte scheint mir etwas mehr verknoten zu sein. @AHeinisch da müssten wir vermutlich mal zusammen aufräumen gehen.

Können wir gerne uns dran setzen.

**Comment by AMatutat** [comment]
Die Dinger kommen weg, 
aktiv ergeben sich daraus diese beiden todos.

#303 
#677
