### ISSUE TITLE
[Game] Klassennamen im ECS

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#551]
Im ECS heisst unser Basis-Entität: `ecs.entities.Entity`.

Unsere Basis-Component heisst: `ecs.components.Component`.

Unser Basis-System heisst dagegen: `ecs.systems.ECS_System`.

---

Warum gibt es den (überraschenden) Namensunterschied? Wieso ist das Basis-System nicht einfach auch `ecs.systems.System`?

**Comment by AMatutat** [comment]
Hast wahr. Mir ist das damals um die Ohren geflogen, aber schien an mir gelegen zu haben
