### ISSUE TITLE
[Game] Ableiten von ecs.entities.Entity?

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#552]
Aktuell wird von `ecs.entities.Entity` abgeleitet, um eigene Entitäten zu realisieren (auch im Quick-Start).

Jetzt sind aber Entitäten per Definition nur Hüllen für Components, d.h. ich soll gar keine Eigenschaften haben, die nicht über Components realisiert werden. Wieso wird für den Hero und die Chest eine eigene Klasse von `ecs.entities.Entity` abgeleitet und nicht nur eine Instanz davon erzeugt (mit den "richtigen" Components)?

Edit: Während der `ecs.entities.Hero` außer Hilfsmethoden zum Kapseln hat, zeigt die `ecs.entities.Chest` schon reichlich Verhalten. Darf die das im ECS überhaupt? Ist das nicht Sache der Components+Systems?

**Comment by cagix** [comment]
> Eigentlich doof. Richtig wäre hier wohl das Builder Pattern und Entity als Final

Oder sogar Record. Die Components werden ja schrittweise der internen Sammlung hinzugefügt.

**Comment by AMatutat** [comment]
fixed in #618
