### ISSUE TITLE
[Game] Unsymmetrie von Point und Coordinate (Packages)

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#553]
Während `Coordinate` aus `level.tools` stammt, findet sich `Point` weiter "oben" (in `tools`). 

Sollte das nicht alles im selben Hilfspackage liegen?

Brauchen wir nach außen überhaupt einen `Point`, wäre eine `Coordinate` nicht für alle Beteiligten einfacher zu handeln (siehe #547).

edit: siehe auch #583

**Comment by AMatutat** [comment]
Wenn ich jetzt erstmal #547 außen vorlasse, ist die Asymmetrie tatsächlich "richtig".
`Point` ist ein Tool, das auf der Entity-Ebene relevant ist.
`Coordinate` ist ein Tool, das wirklich nur für die Arbeit auf Level-Ebene wichtig ist, insbesondere bei der Generierung der Level oder dem Pathfinding. Auf der Entity-Ebene arbeite ich nicht mit `Coordinate`.


Wird mit #547 dann auch alles besser.
