### ISSUE TITLE
[Game] Hero ohne PositionComponent führt zu MissingComponentException

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#556]
Wenn man ein Game ohne Hero starten kann, würde ich erwarten, dass ein minimaler Hero auch funktioniert:

```java
public class Hero extends Entity {}
```

Interessanterweise bekommt man dann eine `MissingComponentException`: die `PositionComponent` fehlt. (Macht auch irgendwie Sinn - wo soll der Held denn positioniert werden?)

Ich habe es nicht ausprobiert, aber eine `PositionComponent` scheint im Moment Pflicht für alle Entitäten zu sein? Da wir bei Entitäten erstmal nur über Container für Components sprechen, und Systems Entitäten ohne passende Components normalerweise ignorieren, finde ich das etwas unglücklich modelliert.

Kann man die Anforderung auflösen, d.h. ohne `PositionComponent` wird eine Entität halt von den zugehörigen Systems (und vermutlich vom Spiel insgesamt) ignoriert?

**Comment by AMatutat** [comment]
PositionComponent ist nur für den Helden Pflicht. 
Das steht auch irgendwo…. 
Ich fürchte mal wieder nur in einem PR Kommentar. #526

**Comment by cagix** [comment]
> Haben halt nie ohne Hero geplant.

Macht Sinn, irgendwie. 

Andererseits ist es ECS. Warum soll eine Entität gleicher sein als die anderen? Wenn die Entität die richtigen Components hat, wird sie vom System behandelt, sonst nicht.

Insofern sollte das Verhalten aufgelöst werden. Wenn eine Entität keine `PositionComponent` hat, wird sie halt nicht gezeichnet.

**Comment by AMatutat** [comment]
Ich glaube das explodierte dir garnicht beim zeichnen sondern woanders. 

Die Kamera, die AI der Monster, die Checks ob ein neuesten Level geladen werden muss… all das ist halt teilweise vom Helden abhängig. Der Held ist halt Tatsächlich gleicher. 

Korrekterweise müsste man immer überprüfen ob es den Helden gibt und ob er ein PC hat. Dann sieht der Code aber echt mies aus (weil viele Verschachtelungen) und das alles, um einen echt speziellen Sonderfall abzufangen.


Anders formuliert : Das Spiel braucht einen Helden und wir liefern einen passenden mit. warum prüfen ob der Held ist wie er ist?

**Comment by cagix** [comment]
Vielleicht sollte es ein `CameraSystem` geben, was auf eine `CameraComponent` reagiert - damit könnte man den Fokus auf eine andere "aktive" Entität schieben wie einen Geist oder eine Truhe oder so.
