### ISSUE TITLE
[Game] VelocityComponent hängt implizit von AnimationComponent ab

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#557]
Folgendes Szenario:

```java
public class Hero extends Entity {
    public Hero() {
        super();

        new PositionComponent(this);

        Animation moveRight = AnimationBuilder.buildAnimation(pathToRunRight);
        Animation moveLeft = AnimationBuilder.buildAnimation(pathToRunLeft);
        new VelocityComponent(this, xSpeed, ySpeed, moveLeft, moveRight);
}
```

Interessanterweise bekommt man dann eine `MissingComponentException`: die `AnimationComponent` fehlt.

In der aktuellen Modellierung wird vom `VelocitySystem` die `VelocityComponent` abgefragt, aber auch die `AnimationComponent` geändert. Diese Abhängigkeit ist nicht dokumentiert, zusätzlich finde ich das etwas unglücklich modelliert (siehe auch #348 und https://github.com/Programmiermethoden/Dungeon/pull/245#discussion_r1106896186).

Kann man die Anforderung auflösen, d.h. ohne `VelocityComponent` und `AnimationComponent` wird eine Entität einfach vom `VelocitySystem` ignoriert? 

---

Edit: Das betrifft so ähnlich auch `PlayableComponent`. Ohne `VelocityComponent` gibts eine Exception, weil das `PlayerSystem` scheinbar hier noch mehr machen möchte. Dabei entstehen drei Fragen: 
(a) Sollte das `PlayerSystem` nicht einfach nur die Tasteneingaben in der `PlayableComponent` ablegen, und die anderen Systems dürfen dann ihren Reim draus machen? 
(b) Wenn das `PlayerSystem` sowohl `PlayableComponent` als auch `VelocityComponent` zwingend braucht: Sollte es dann Entitäten nicht einfach ignorieren, wenn eine oder beide Components nicht vorhanden sind? 
(c) Der "Incident", also das `PlayerSystem` hat eine Entität mit `PlayableComponent` aber ohne `VelocityComponent` gefunden und die Entität entsprechend ignoriert, sollte dann geloggt werden.

**Comment by AMatutat** [comment]
Ist dokumentiert (https://github.com/Programmiermethoden/Dungeon/tree/master/doc/ecs/systems) 

Könnte man wie von dir beschrieben auflösen. Jedoch könnte das zu mehr Verwirrung führen. Wenn du jetzt ein VC ohne AC hinzufügst Platz es, aber dir ist klar warum. Wenn man das ignorieren würde, würdest du dich wundern warum es sich nicht wie erwartet verhält.

**Comment by cagix** [comment]
> Ist dokumentiert (https://github.com/Programmiermethoden/Dungeon/tree/master/doc/ecs/systems)

Ah, gut! Im Javadoc der Systems fehlt es noch (da hatte ich geschaut) ;)


> 
> Könnte man wie von dir beschrieben auflösen. Jedoch könnte das zu mehr Verwirrung führen. Wenn du jetzt ein VC ohne AC hinzufügst Platz es, aber dir ist klar warum. Wenn man das ignorieren würde, würdest du dich wundern warum es sich nicht wie erwartet verhält.

Bin nicht sicher, ob es wirklich Verwirrung stiftet. Die Logik ist doch:

- Wenn ein System nur eine Component braucht, dann ignoriert es Entitäten, diese Component nicht haben.

Erweitert auf mehrere Components:

- Wenn ein System mehrere Components braucht und diese nur teilweise vorhanden sind, wäre das Ignorieren plus Loggen imho stringenter als eine Exception.

---

Konsequent weiter gedacht: **Wenn die Entität die richtigen Components hat, wird sie vom System behandelt, sonst nicht.** 

Das Dokumentieren der Abhängigkeiten (`docs/`, Javadoc) ist aber zusätzlich gut und notwendig.

**Comment by AMatutat** [comment]
Wie besprochen:
#517 umsetzten und in `accept` entsprechend loggen.

- Key-Component fehlt => ignorieren
- Key-Component ist da, aber ein anderes wichtiges Component fehlt => Loggen
- Alles ist da => Hinzufügen zum internen Set
