### ISSUE TITLE
[Doc] Dungeon kann nicht mit einem 32-bit JDK verwendet werden

### ISSUE THREAD

**Issue by tgrothe** [Programmiermethoden/Dungeon#558]
Hallo,
offenbar kann das neue Dungeon nicht mit einem 32-bit JDK verwendet werden, da nicht genug Heap Space reserviert werden kann.
Getestet hatte ich mit der 32-bit Version von Azul Zulu JDK 17 (build of OpenJDK 17) version 17.36.15.
Ich denke, das sollte dokumentiert werden.

**Comment by AMatutat** [comment]
Gehört am besten hierzu https://github.com/Programmiermethoden/Dungeon/wiki/JDK-Kompatibilität

**Comment by tgrothe** [comment]
> Gehört am besten hierzu [https://github.com/Programmiermethoden/Dungeon/wiki/JDK-Kompatibilität](https://github.com/Programmiermethoden/Dungeon/wiki/JDK-Kompatibilit%C3%A4t)

Ja 👍🏼 vielleicht einfach eine Anmerkung dazu, nicht mit einem 32-bit JDK auf einem 64-bit OS verwenden

Man könnte auch die Xmx-Option ändern: `2048 * 0.75 = 1536`, aber dann würde `-Xmx1536m` vielleicht mit 32-bit funktionieren, ich wäre dann aber nicht sicher, ob nicht andere Probleme auftreten würden 🤒

**Comment by AMatutat** [comment]
habs eingetragen

**Comment by tgrothe** [comment]
> habs eingetragen

danke dir 🙂 🎚️
