### ISSUE TITLE
[DOC] Sammelissue für JavaDoc von ECS Components

### ISSUE THREAD

**Issue by AKirsch1** [Programmiermethoden/Dungeon#559]
Wie im SHK-Meeting angesprochen, hier eine erste Auswahl an Klassen aus `ecs.components`, die Dokumentation benötigen.

- [ ] #566
- [ ] #568
- [ ] #588
- [ ] #567
- [ ] #564
- [ ] #589
- [ ] #590
- [ ] #591
- [ ] #592
- [ ] #569
- [ ] #593
- [ ] #594
- [ ] #595
- [ ] #565

**Comment by AMatutat** [comment]
Samuel Issue, daher zu
