### ISSUE TITLE
[Game] Dokumentation HitboxComponent

### ISSUE THREAD

**Issue by AHeinisch** [Programmiermethoden/Dungeon#564]
Javadoc für die HitboxComponent erstellen bzw. verbessern wie im Eltern Issue vorgegeben.
Dazu muss Klassendoc/sowie MethodenDoc angepasst werden.

Die Klasse  [ `HitboxComponent` (https://github.com/Programmiermethoden/Dungeon/blob/master/game/src/ecs/components/HitboxComponent.java)]
braucht noch 

- [x] Ausführliche JavaDoc
- [ ] Beschreibung im `doc` Ordner.

**Comment by cagix** [comment]
@AHeinisch Bitte die Summary anpassen. Worum geht es hier?
