### ISSUE TITLE
[Game] Dokumentation VelocityComponent

### ISSUE THREAD

**Issue by Lena241** [Programmiermethoden/Dungeon#565]
Die Klasse  [ `VelocityComponentt` (https://github.com/Programmiermethoden/Dungeon/blob/master/game/src/ecs/components/VelocityComponent.java)]
braucht noch 

- [ ] Ausführliche JavaDoc
- [ ] Beschreibung im `doc` Ordner.

**Comment by cagix** [comment]
@Lena241 Bitte die Summary anpassen. Worum geht es hier?

**Comment by AMatutat** [comment]
@Lena241 ich schnapp mir das einmal, damit ich ein example machen kann. Das Ding eignet sich am besten dafür.
