### ISSUE TITLE
[Game] Dokumentation AnimationComponent

### ISSUE THREAD

**Issue by fwatermann** [Programmiermethoden/Dungeon#566]
Die Klasse [`AnimationComponent`](https://github.com/Programmiermethoden/Dungeon/blob/master/game/src/ecs/components/AnimationComponent.java)

braucht noch 

- [x] Ausführliche JavaDoc
- [x] Beschreibung im `doc` Ordner.

**Comment by cagix** [comment]
@fwatermann Bitte die Summary anpassen. Worum geht es hier?
