### ISSUE TITLE
[Game] Dokumentation HealthComponent

### ISSUE THREAD

**Issue by fwatermann** [Programmiermethoden/Dungeon#567]
Die Klasse  [ `HealthComponent` (https://github.com/Programmiermethoden/Dungeon/blob/master/game/src/ecs/components/HealthComponent.java)]
braucht noch 

- [ ] Ausführliche JavaDoc
- [ ] Beschreibung im `doc` Ordner.

**Comment by cagix** [comment]
@fwatermann Bitte die Summary anpassen. Worum geht es hier?
