### ISSUE TITLE
[Game] Dokumentation Component

### ISSUE THREAD

**Issue by dkirshner** [Programmiermethoden/Dungeon#568]
Die Klasse  [`Component` (https://github.com/Programmiermethoden/Dungeon/blob/master/game/src/ecs/components/Component.java)]
braucht noch 

- [x] Ausführliche JavaDoc
- [x] Beschreibung im `doc` Ordner.

**Comment by cagix** [comment]
@dkirshner Bitte die Summary anpassen. Worum geht es hier?

**Comment by dkirshner** [comment]
Oh sry, habe es nicht gesehen, dass da noch die Beschreibung fehlt. Wird behoben.

**Comment by AMatutat** [comment]
Scheint erledigt zu sein.
