### ISSUE TITLE
[GAME] Dokumentation AI-Component /IIdleAI folgt immer dem Helden

### ISSUE THREAD

**Issue by tgrothe** [Programmiermethoden/Dungeon#570]
Mir ist aufgefallen, dass die `IIdleAI`s immer dem Helden folgen, wenn dieser in der Nähe ist. Ich weiß aber nicht, ob das so beabsichtigt wäre.

Hier ein Beispiel mit Imp und ` new PatrouilleWalk(2, 4, 1000, PatrouilleWalk.MODE.RANDOM)`:

![Animation1](https://user-images.githubusercontent.com/85501570/233368777-3285fc32-dac0-49fe-a1c7-87df1314ab83.gif)

**Comment by tgrothe** [comment]
Danke für die Erklärung @fwatermann.

Ich dachte nur, dass das vielleicht "standardmäßig" anders sein sollte, aber wenn es so gedacht ist, alles super. 🙂

**Comment by fwatermann** [comment]
Es sollte einfach nur besser dokumentiert sein. Werde ich mir mal anschauen.
