### ISSUE TITLE
Test test_findPath_moreThanOnePathPossible() schlägt manchmal fehl

### ISSUE THREAD

**Issue by tgrothe** [Programmiermethoden/Dungeon#571]
https://github.com/Programmiermethoden/Dungeon/blob/d6b2423bd2fd23f44f106f468db2ec046b56e8dd/game/test/level/TileLevelTest.java#L247-L249

Dieser Test schlägt manchmal willkürlich fehl.

**Comment by fwatermann** [comment]
Duplicate zu #563
