### ISSUE TITLE
[Game] Teile der API für AITools gehören eher nach Level

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#573]
Die ganzen Pfad-Sachen gehören konzeptionell ins Level: Das agiert mit Kacheln und Positionen, und das Level wäre die richtige Stelle, um auch mit Pfaden zu arbeiten. Dazu kommt, dass der Pfad-Kram mit "AI" irgendwie so gar nichts zu tun hat.

**Comment by cagix** [comment]
klingt doch sinnvoll. wichtig ist ja, dass diese pfad-sachen eher richtung level kommen, hat ja mit "ai" nicht viel zu tun. und eine util-klasse ist doch super (ich würde sie `LevelUtils` nennen statt `LevelTools`).

**Comment by AMatutat** [comment]
high prio, da einige Issues sich auf diese Methoden beziehen und ich durch ein vorzeites Abarbeiten dieses Issues einen haufen Merge-Konflikte umgehen möchte.
