### ISSUE TITLE
[Game] gurkenlabs/litiengine: Konfiguration Game und Label und Dokumentation als Vorbild

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#576]
~~[gurkenlabs/litiengine](https://github.com/gurkenlabs/litiengine) ist ein 2d-java-framework auf der basis von java und awt(!) und ohne weitere abhängigkeiten. zusätzlich integriert es bereits ecs, level-/tile-funktionalitäten u.v.m. ...~~

~~damit könnten wir die etwas undurchsichtigen abhängigkeiten in libgdx (insb. die plattformabhängigen teile des frameworks, die beim nächsten update evtl. wieder für bauchschmerzen sorgen) ablösen mit einem reinen java-basierten ansatz.~~

~~vermutlich könnten wir auch unser eigenes framework deutlich verschlanken und uns auf die eigentlichen spielelemente fokussieren.~~

=> #303

---

@AMatutat ich finde den einsatz von labels, issues und discussions und auch dokumentation in dem projekt recht interessant. die art, wie das game konfiguriert wird, gefällt mir ebenfalls sehr gut. vielleicht können wir davon lernen? 

https://github.com/gurkenlabs/litiengine-docs

**Comment by AMatutat** [comment]
> @AMatutat ich finde den einsatz von labels, issues und discussions und auch dokumentation in dem projekt recht interessant. 

Ich finde die Ordner-Struktur der Dokumentation irgendwie ganz nett. Aber ansonsten steh ich etwas auf dem Schlauch, was du da jetzt "recht interessant" findest. Sieht für mich recht Basic aus. 
Die Discussions als eine Art Hilfeforum wollte ich ja auch immer haben, aber die Studis wollen ja nit....

> die art, wie das game konfiguriert wird, gefällt mir ebenfalls sehr gut. vielleicht können wir davon lernen?

Das ist ja #582

**Comment by cagix** [comment]
- label: sind wir mittlerweile besser.
- doc: die strukturieren die markdown-doku nicht nach klassen/packages, sondern (vor allem) nach einsatzzweck ("was will ich machen"): level, ecs, configuration, gettingstarted, ... 
- konfiguration: #582

**Comment by cagix** [comment]
also im prinzip ist dieses ticket nur noch für das nachdenken über eine strukturierung der doku bzw. der kapitel dort.
