### ISSUE TITLE
[Game] Einhaltung von Java-Conventionen

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#577]
Die Studis orientieren sich tatsächlich an unserem Code-Style. Wir sollten deshalb unbedingt darauf achten, unsererseits den Java-Codestyle einzuhalten.

Hier bin ich eben in der Abgabe drüber gestolptert:
https://github.com/Programmiermethoden/Dungeon/blob/3cf36135d03a9a212c9bd56d23bfe3b7dc23a21b/game/src/ecs/entities/Chest.java#L16

Lt. https://google.github.io/styleguide/javaguide.html#s5.2-specific-identifier-names sollten in Java Variablen `lowerCamelCase` geschrieben werden und Konstanten (`static final`) `UPPER_SNAKE_CASE`. Das ist zumindest hier nicht der Fall. 

Bitte den Code prüfen und vereinheitlichen.

**Comment by AMatutat** [comment]
Für die bessere Übersicht und Aufteilung sowie einen besseren Workflow ist dieses Issue gemerged in #1025 und #178.

Je Klasse 1 PR
