### ISSUE TITLE
[Game] Definition der Interfaces

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#578]
Wir haben diverse Interfaces definiert, beispielsweise `ISkillFunction`, `ITargetSelection`, `IInteraction`, `IOnDeathFunction` (Liste nicht vollständig).

Diese Interfaces sind alles funktionale Interfaces und dienen ausschließlich dazu, als Typ für einen Lambda-Ausdruck herzuhalten. 

Nun gibt es aber bereits Interfaces im JDK, die genau diese Funktionalität erfüllen: `Consumer<Entity>`, `Supplier<Point>`, `Consumer<Entity>` und `Consumer<Entity>` (in der Reihenfolge wie oben). (siehe https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html)

Diskussion: Brauchen wir diese separaten Interfaces wirklich? Könnten wir nicht direkt die Standards aus dem JDK nehmen?

Vorteil: Die Methodennamen sind "sprechend".
Nachteil: Mehr Dateien im Framework, mehr "künstliche" Namen (Interface, Methode).

**Comment by AMatutat** [comment]
> Diskussion: Brauchen wir diese separaten Interfaces wirklich? Könnten wir nicht direkt die Standards aus dem JDK nehmen?

Ich glaube ja, weg damit. 
Die sprechenden Namen lassen sich ja beibehalten, indem die Consumer in den Collections gescheit genannt gespeichert werden. Aus der Javadoc sollte das dann hervorgehen.
