### ISSUE TITLE
[Doc] Eigene Klasse für den Hero?

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#579]
In der Doku (https://github.com/Programmiermethoden/Dungeon/blob/master/doc/ecs/structure_design_decisions.md#eigene-klasse-für-hero) steht

> Der Held hat eine eigene Klasse bekommen, anstatt nur eine Instanz von Entity zu sein.
> [...]
> Da Vererbung gegen das ECS-Paradigma verstößt, könnte auch ein Builder benutzt werden, der eine Entität erstellt, welche den Helden als `Entity` erstellt.
> So würde zu einem das ECS-Paradigma eingehalten werden, als auch die Lesbarkeit des Codes beibehalten werden, da eine Auslagerung in eine eigene Klasse immer noch möglich ist.
> Zusätzlich würde es `instanceOf Hero`-Abfragen verhindern (es zwingt zu besserem Code).

Zusammengefasst: Wir erklären also, dass wir absichtlich gegen das ECS verstoßen und wie man es "richtig" machen würde.

Frage: Warum machen wir das dann nicht einfach richtig und sparen uns diese umständliche Erklärung?

**Comment by cagix** [comment]
Was ist konzeptionell einfacher und am Ende übersichtlicher? 

(1) würde ja auch die Monster etc. betreffen, d.h. wir würden `Game` nicht unbedingt verbessern.

(2) klingt interessant - das wäre im Prinzip eine praktische Anwendung des Type-Object-Patterns (https://www.hsbi.de/elearning/data/FH-Bielefeld/lm_data/lm_1359639/pattern/type-object.html)

(3) wäre wie jetzt pro Entität eine von `Entity` ableitende Klasse, in der die Eigenschaften gesetzt werden.


Ich glaube, eine Art Fabrikmethode (wie in https://www.hsbi.de/elearning/data/FH-Bielefeld/lm_data/lm_1359639/pattern/type-object.html#fabrikmethode-für-die-type-objects) könnte uns eine Menge Klassen ersparen, die eigentlich nur Konfigurationen hardcoden und setzen.

**Comment by AMatutat** [comment]
Ich hab mal hier #618  versucht die Record Idee + (2) umzusetzen.

Eine Builder Klasse wurde mir dann auch irgendwie zu groß. Ich habe jetzt mal sowohl für Hero als auch Chest einen eigenen Builder gebaut. Damit das ganze noch angenehme zu benutzen ist, gibt es den `EntityBuilder` als bessere Schnittstelle zwischen User und Buildern.
Find ich irgendwie ganz nett.

**Comment by cagix** [comment]
Hmmm. Dann wären wir aber auch wieder bei einer Klasse pro Entität, oder? Nur dass es jetzt ein Builder ist und nicht eine von `Entity` abgeleitete Klasse (was schon mal im Sinne des ECS gut ist).

**Comment by AKirsch1** [comment]
Viele Game Engines arbeiten doch mit Prefabs (Unity, Unreal Engine, etc...), also mit einer Datei, die beschreibt, wie eine Entität aufgebaut ist. Wäre das für den Dungeon auch eine sinnvolle Umsetzung? Im Grunde haben wir das Konzept davon schon in der DSL (siehe [hier](https://github.com/Programmiermethoden/Dungeon/blob/master/doc/dsl/typebuilding.md)). Dann müsste man aus der Definition "nur" noch die Entität erstellen: `EntityBuilder.createEntityFromPrefab("prefabs/hero.prefab");`.

**Comment by cagix** [comment]
Das könnte dann mit JAXB oder sowas laufen, also aus dem JSON direkt die Objekte erzeugen.

**Comment by AMatutat** [comment]
> Das könnte dann mit JAXB oder sowas laufen, also aus dem JSON direkt die Objekte erzeugen.

Nenn mich verrückt, aber wenn unsere DSL das schon kann, warum sollten wir auf JSON wechseln?

**Comment by cagix** [comment]
> Nenn mich verrückt, aber wenn unsere DSL das im Grunde schon kann, warum sollten wir auf JSON wechseln?

hallo herr verrückt :) 

(a) habe ich von unserer dsl bisher nur gehört, aber nur wenig bis nix (konkretes) gesehen.

(b) liegt das für mich nah beisammen. wenn die api vernünftig gestaltet ist, sollte sowohl ein einlesen aus einer json als auch das "einlesen" über die dsl die selbe schnittstelle bedienen.


> Ich glaube aber, dass das nicht im Scope dieses Milestones liegt.

jaxb sicher nicht :) aber nochmal nen schritt zurück treten und das gesamte bild betrachten - ja. die gemeinsame api zu definieren sollte machbar sein.

**Comment by cagix** [comment]
wie vorhin besprochen: den builder von @malt-r könnte man verallgemeinert in das game ziehen. dann könnte die dsl das ding weiter nutzen und wir könnten das auch für die konfiguration benutzen.

**Comment by AMatutat** [comment]
Für eine kurzfristige/mittelfristige Lösung haben wir besprochen, dass wir auf eine Entity-Factory wechseln werden. So lösen wir die Hierarchie in der Entitätsstruktur auf.
