### ISSUE TITLE
[Game] Modellierung der Skills

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#580]
Leider fehlt hier komplett die Dokumentation, auch der Javadoc ist sehr rudimentär.

Wir haben die Klasse `Skill`, mit der ich einen ausführbaren Callback habe und einen Cooldown modelliere. Das kann ich gut nachvollziehen, aber das ist keine `Component` und somit im falschen Package.

Dann aber gibt es eine `SkillComponent`, die alle Skills einer Entität sammelt. Der Aufbau erinnert hier stark an die Modellierung der `Entity` - wir _sammeln_ lediglich alle Skills. Warum ist nicht jeder Skill seine eigene Component, dann könnte man sich diese Zwischenklasse sparen? Tatsächlich wird diese Klasse bisher auch nur in den Tests verwendet?! Im reinen ECS dürfen Components zwar keine Funktionalität haben, aber wir hatten ja sowieso Ausnahmen erlaubt. Das würde hier auch Sinn machen, dann könnte ein Skill (als Component) eben die `execute()`-Methode haben.

Dann gibt es noch die Klasse `DamageProjectileSkill`. Diese ist eine `ISkillFunction` (implementiert das), aber der Klassenname spiegelt das nicht wider: Ein Skill ist eine Fähigkeit, also etwas, was ich _tun_ kann, also ein Verb. Ein Projektil ist ein Objekt, also ein Substantiv und keine Fähigkeit. Ich würde ja auch nicht sagen, ich habe einen `LaptopSkill`?! Außerdem: Wenn das wirklich ein "Skill" sein soll, müsste diese Klasse dann nicht von `Skill` ableiten?! Und noch eine Frage: Ist ein Projektil nicht eher eine Entität, d.h. es hat eine Animation, eine Position, eine Velocity und einen Impact und wird von den Systems bewegt und die Kollision berechnet etc. ... ??? Der zugehörige Skill wäre das _Auslösen_ (oder Werfen oder Schießen ...)? 
Edit: Tatsächlich wird in `execute()` eine neue Entität erzeugt und auf den Weg gebracht. Das erledigt die vorigen beiden Sätze - nur der Klassenname ist echt Mist.
Edit: `DamageProjectileSkill` ist außerdem im falschen Package, es ist keine Component. 

Und schließlich gibt es im Package `skill` eine Component `ProjectileComponent` (falsches Package?). Wie hängt diese Component mit dem `DamageProjectileSkill` zusammen? Da diese Component nur einen Start und ein Ziel speichert: Könnte man die nicht auch für allgemeine Wege-Probleme nutzen, also beispielsweise für ein Monster oder so?

**Comment by AMatutat** [comment]
> Leider fehlt hier komplett die Dokumentation, auch der Javadoc ist sehr rudimentär.

Das lang verschöbene #466. Und leider schiebt sich das jetzt weiter, da ich grade das Ding strukturell umdenke (siehe auch #602)

> Wir haben die Klasse Skill, mit der ich einen ausführbaren Callback habe und einen Cooldown modelliere. Das kann ich gut nachvollziehen, aber das ist keine Component und somit im falschen Package.

> Edit: DamageProjectileSkill ist außerdem im falschen Package, es ist keine Component.

Siehe #583 

> Dann aber gibt es eine SkillComponent, die alle Skills einer Entität sammelt. Der Aufbau erinnert hier stark an die Modellierung der Entity - wir sammeln lediglich alle Skills. Warum ist nicht jeder Skill seine eigene Component, dann könnte man sich diese Zwischenklasse sparen? Tatsächlich wird diese Klasse bisher auch nur in den Tests verwendet?! Im reinen ECS dürfen Components zwar keine Funktionalität haben, aber wir hatten ja sowieso Ausnahmen erlaubt. Das würde hier auch Sinn machen, dann könnte ein Skill (als Component) eben die execute()-Methode haben.

Da hab ich in #602 einen vereinfachten Vorschlag gemacht. Bei dem würde das `SkillComponent` und `SkillSystem` sogar vollständig entfernt werden. 

> Dann gibt es noch die Klasse DamageProjectileSkill 

Name ist doof, Issue wird aufgemacht.


> Und schließlich gibt es im Package skill eine Component ProjectileComponent (falsches Package?). Wie hängt diese Component mit dem DamageProjectileSkill zusammen? Da diese Component nur einen Start und ein Ziel speichert.
- falsches package, ja
- `ProjectileComponent` markiert ein Projektil als solches, das System löscht dann die Entität, wenn das Ziel erreicht wurde. 

>  Könnte man die nicht auch für allgemeine Wege-Probleme nutzen, also beispielsweise für ein Monster oder so?

Hmm... vielleicht. Man könnte daraus ein `PathComponent` (der name ist doof) machen, welches Start und Endziel (vielleicht auch den Pfad?) hat. 
Das kriegt dann zusätzlich eine `IonPathFinished`Funktion, welche dann das Verhalten beim erreichen des Ziels festlegt.
Ein Monster sucht sich ein neues Ziel, ein Projektil verschwindet etc.
Ich weiß nur nicht, wie sich das mit unseren AI-Konstrukt verhält. 
Ich mach mal ein neues Issue auf.

**Comment by AMatutat** [comment]
Da wir für alle angesprochenen Punkt (jetzt) eigene Issues haben, würde ich hier zu machen und kommende Diskussionen dann im konkreten Issue führen wollen.
