### ISSUE TITLE
[Game] Aufräumen der Package-Struktur

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#583]
Bitte räumt die Package-Struktur auf. Es sollte einen Bereich geben, wo die API des Frameworks zu finden ist. Die Umsetzung (etwa konkrete Components o.ä.) gehört in ein eigenes (Ober-) Package.

Arbeitsauftrag: Bitte erstelle bis zum nächsten Meeting ein Konzept und stelle dieses vor.

**Comment by AMatutat** [comment]
> Es sollte einen Bereich geben, wo die API des Frameworks zu finden ist.

Irgendwie stolpere ich in letzter Zeit wieder häufiger über den Begriff Framework, darüber müssen wir nochmal quatschen. 

Trotzdem: Packages aufräumen find ich wichtig.
In den packages `components` and `systems` hätte ich gerne nur noch die Components bzw Systems ohne den ganzen Helfer-Kram. Der wandert in eigenen packages. je mach Gebiet (z.B `skills`, `items`) etc. 
Und dann hätte ich noch gerne ein package `content` indem sich dann die ganzen konkreten Elemente befinden, also der Feuerball, der Heiltrank, die konkreten Implementierungen des Strategy-Pattern etc. 

Für das Game-Projekt kann ich was vorbereiten

**Comment by cagix** [comment]
> > Es sollte einen Bereich geben, wo die API des Frameworks zu finden ist.
> 
> Irgendwie stolpere ich in letzter Zeit wieder häufiger über den Begriff Framework, darüber müssen wir nochmal quatschen.

Ich glaube schon, dass das noch ein Framework ist, auch wenn schon ziemlich viele konkrete Elemente/Implementierungen mitgeliefert werden.

Ich merke bei den Studis, dass die munter und ohne nachzudenken im Dungeon-Code rumwursteln. D.h. bei denen ist der Framework-Gedanke nicht angekommen, und das wird einigen ziemliche Schmerzen bereiten, wenn (und falls) sie ihre Codebasis mal aktualisieren wollen. Aber so wie ich das aktuelle Semester einschätze, wird das nicht passieren (weshalb ich auch kein schlechtes Gewissen für das Aufräumen habe).

> 
> Trotzdem: Packages aufräumen find ich wichtig. In den packages `components` and `systems` hätte ich gerne nur noch die Components bzw Systems ohne den ganzen Helfer-Kram. Der wandert in eigene packages. je nach Gebiet (z.B `skills`, `items`) etc. Und dann hätte ich noch gerne ein package `content` indem sich dann die ganzen konkreten Elemente befinden, also der Feuerball, der Heiltrank, die konkreten Implementierungen des Strategy-Pattern etc.

Genau das ist die Idee: Die API (System, Component, Entity, ...) unter ein gemeinsames Package, darunter dann wie jetzt "ecs.system...." und so. Die fertigen konkreten Elemente sollten ein anderes Oberpackage bekommen, darunter könnte es dann aber die selbe Struktur wie im API-Package haben und dort sortieren sich dann fertige Components und Systeme und Entitäten ein. Und der ganze Helferkram geht nach `tool` oder so?

Im Prinzip könnten wir auch gemeinsam drüber schauen, aber im Moment kann ich keine Verabredungen machen :/

**Comment by AMatutat** [comment]
Nach der Besprechung:

`game/src` aufteilen in 
- `api`
     - `Component.java`
     - `System.java`
     - `Entity.java`
     - `LevelManager.java` (ehemals `LevelAPI`)
     - `/components`
     - `/systems` 
     - `/hud`
     - `/level` 
     - `/utils`
     - 
- `content`
     - `/components`
     - `/systems` 
     -  `/utils`
- `starter`  
    - #549

**Comment by AMatutat** [comment]
@Quezacotel kannst du hier deinen Vorschlag nochmal beschreiben?

**Comment by cagix** [comment]
Die Aufteilung in `common`, `client`, `server` finde ich auf den ersten Blick nicht verkehrt. Darunter dann jeweils (nach Bedarf) die Unterpackages.

Ich würde würde aber nochmal genau nachdenken, was genau wo sein soll. Beispielsweise ist für mich `configuration` eher `common.configuration` und nicht `client.configuration`. Dito wäre `logging` unterhalb von `utils`.

Nicht glücklich bin ich, dass es im `src`-Ordner des Projekts `game` dann nicht mit Packages weitergeht, sondern irgendwo tiefer unten jeweils nochmal `src`-Ordner kommen. Ich würde also `game/src/assets/` sehen und `game/src/client/ecs/` und `game/src/common/ecs/` etc.

**Comment by Quezacotel** [comment]
- Die Unterpackages von client, server und common müsste man sich nochmal genauen anschauen aber Dinge wie configuration und assets könnten meiner Meinung nach Sinn beim Client und Server machen, da bspw. manche Assets und Konfigurationen nur client oder nur serverspezifisch sind und ich diese daher nicht in common packen würde. Die Unterpackages hatte ich nur grob einmal dargestellt, mir gings im Wesentlichen erstmal drum, die Grundidee rüberzubringen).

- "Was ein Server macht oder was ein Client macht, ist ja im Wesentlichen durch die Aufrufe in der jeweiligen main() definiert. "
Kann dir da grad nicht ganz folgen aber ich vermute dass du das in Hinblick auf die Verwendung für die Studis meinst und das dann schwierig ist in eine API zu verpacken? Meiner Vorstellung nach, kriegt man die Logiken durch so eine Struktur recht gut und intuitiv gekapselt (hat sich zumindest auch bisher bei anderen Projekten bewert). Aus meinem Blickwinkel ist aber der ausschlaggebenste Vorteil dass man unabhängig von Single oder Multiplayer-Mode eine konsistente Spiellogik hat - in beiden Fällen übernimmt der Server die Spiellogik, weshalb das dann unter Umständen auch besser angepasst werden könnte (?).

- Zu deinem Vorschlag, ein Package Multiplayer zu machen: so haben Tim und ich das aktuell umgesetzt - mit einer MultiplayerAPI, über welche die Studis dann Multiplayersitzungen starten/joinen können. Ist in gewissem Maße auch nett aber man merkt ständig die Vermischung von Single- und Multiplayerlogik (vielleicht ja auch weil unsere Struktur nicht ganz sauber ist, wer weiß :D ) und hat kein einheitliches Handling für Single und Multiplayer.

**Comment by cagix** [comment]
> aber Dinge wie configuration und assets könnten meiner Meinung nach Sinn beim Client und Server machen, da bspw. manche Assets und Konfigurationen nur client oder nur serverspezifisch sind und ich diese daher nicht in common packen würde

Bin ich bei dir, wenn es wirklich exklusive Assets oder Konfigurationen sind. Aber sobald das zwar für den Client oder den Server gedacht ist, aber von beiden genutzt werden kann, ist das für mich sowas wie "common". (Wobei ich eher davon absehen würde, so ein Package einzurichten, siehe den Edit oben.)

> > "Was ein Server macht oder was ein Client macht, ist ja im Wesentlichen durch die Aufrufe in der jeweiligen main() definiert. "
> Kann dir da grad nicht ganz folgen aber ich vermute dass du das in Hinblick auf die Verwendung für die Studis meinst und das dann schwierig ist in eine API zu verpacken?

Du hast irgendwelche Klassen und Interfaces, die Du für irgendwas nutzt. Die kannst Du zur besseren Gliederung nach Einsatzzweck in Packages sperren - genau das ist ja die Idee hinter diesem Ticket. 

Irgendwo wirst Du nun noch eine Klasse mit einem `main()` haben und dort den Client instantiieren, konfigurieren und starten. Dito mit dem Server. Diese letzten beiden Klassen und alles, was irgendwie mit dem verteilten Arbeiten zu tun hat, gehören nach `multiplayer`. Aber der Rest sollte neutral bleiben. 

Aber warum sollte ich Systeme nach `server` schieben, wenn ich die auch für ein Singleplayer-Spiel brauche und dort gar keinen Server habe? Das ist doch nix Server-spezifisches? Und am Ende verwirrt es die Studis in PM nur.

> Ist in gewissem Maße auch nett aber man merkt ständig die Vermischung von Single- und Multiplayerlogik (vielleicht ja auch weil unsere Struktur nicht ganz sauber ist, wer weiß :D ) und man hat kein einheitliches Handling für Single und Multiplayer.

Da bin ich erstmal ratlos :) Was genau vermischt ihr da? Ihr baut doch irgendwo ein System zusammen, was den Server spielt, d.h. es gibt eine extra `main()` und es werden Klassen instantiiert etc. Was vermischt ihr da?

**Comment by cagix** [comment]
> in beiden Fällen übernimmt der Server die Spiellogik

@Quezacotel Ich glaube, das ist der Punkt: Es gibt keinen Server oder Client bei uns. D.h. die Studis starten ein Spiel, welches beide Aspekte in einem Programm vereint - aus deren Sicht ist eine Trennung von Klassen komplett nicht nachvollziehbar. Ihr dagegen setzt da ne Schicht obendrüber und sagt, der eine Teil wird nur im Server genutzt und ein anderer Teil des Codes nur im Client - und deshalb wäre es für euch eine gute Trennung. Aber eben nicht für das Gesamtprojekt.

Oder wir müssten die gesamte Spielarchitektur so umbauen, dass es _immer_ einen Server und einen Client gibt. Aber da sind wir nicht, und da sehe ich uns in diesem Projekt auch nicht (mehr).

**Comment by Quezacotel** [comment]
> Irgendwo wirst Du nun noch eine Klasse mit einem main() haben und dort den Client instantiieren, konfigurieren und starten. Dito mit dem Server. Diese letzten beiden Klassen und alles, was irgendwie mit dem verteilten Arbeiten zu tun hat, gehören nach multiplayer. Aber der Rest sollte neutral bleiben.

In der aktuellen Version von Tim und mir haben wir das auch so gemacht. Wir starten aktuell den Server nur im Multiplayer-Mode. Dadurch hat man aber automatisch keine konsistente Spiellogik in Single und Multiplayer-Mode. Man fängt an zu differenzieren ob es der Host- oder "andere" Client ist, mit dem der Server gerade spricht. Nur der Hostclient soll sich um die Logik für Monsterbewegungen und so kümmern und die anderen Clients zeigen diese nur an, usw..
Darauf zielte die Struktur mit Client, Server und Common ab. Ziel wäre es, dass der Server auch im Singleplayer läuft, wodurch die gesamte Logik einheitlich ist und im Multiplayer Mode werden nur die Ports für andere geöffnet. 

> @Quezacotel Ich glaube, das ist der Punkt: Es gibt keinen Server oder Client bei uns. D.h. die Studis starten ein Spiel, welches beide Aspekte in einem Programm vereint - aus deren Sicht ist eine Trennung von Klassen komplett nicht nachvollziehbar. Ihr dagegen setzt da ne Schicht obendrüber und sagt, der eine Teil wird nur im Server genutzt und ein anderer Teil des Codes nur im Client - und deshalb wäre es für euch eine gute Trennung. Aber eben nicht für das Gesamtprojekt.
Oder wir müssten die gesamte Spielarchitektur so umbauen, dass es immer einen Server und einen Client gibt. Aber da sind wir nicht, und da sehe ich uns in diesem Projekt auch nicht (mehr).

Den Punkt kann ich gut nachvollziehen. Eventuell ist es mit der vorgeschlagenen Struktur aufwändiger eine API zu machen, welche intuitiv für 2. Semester-Studis ist. Hinzu kommt wohl auch, dass der Multiplayer-Mode für den Dungeon ja auch kein Hauptbestandteil des Moduls bzw. Lerninhalte wird, sondern wohl eher Spielerei für besonders motivierte Studis (?) :D  
Tim und ich würden dann mit der Variante weiterfahren, dass wir ein Multiplayer-Package bereitstellen, welches auf höchster Ebene eine MultiplayerAPI/MultiplayerManager bereitstellt.

**Comment by cagix** [comment]
@Quezacotel Ich hatte gestern mit @AMatutat darüber gesprochen. Wir würden jetzt erstmal mit unserem Vorschlag weitermachen und den etwas verfeinern. Nach der Umsetzung könnt ihr euch dann auf die neuen Strukturen rebasen und gern weitere Packages dazu bauen. Wenn dann alles fertig ist, machen wir uns nochmal neu Gedanken und ob es bei `multiplayer` bleibt oder ob man das nochmal weiter schieben sollte ...

**Comment by Quezacotel** [comment]
alles klar
