### ISSUE TITLE
[Github] Tickets aufräumen 

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#584]
Das Ticketsystem sieht aus wie Sau. Bitte aufräumen und längst bearbeitete oder mittlerweile obsolete Tickets schließen. Duplikate und Tracking-Issues bitte auch.

siehe auch #586

**Comment by cagix** [comment]
so, jetzt habe ich selbst drei stunden investiert und zumindest die summaries, label, assignees etwas gerade gerückt und teilweise die leute angepingt.

dennoch: da sind gefühlt tausend issues offen, von denen gefühlt 1/3 mittlerweile obsolet sind bzw. die sich möglicherweise überschneiden bzw. doppeln. bitte wirklich dringend aufräumen. so nutzt uns das ticketsystem nämlich fast nichts.

und bitte auch diese "tracking-issues" mal schließen - was nutzen die dinger, wenn es dazu bereits einzelne issues gibt? ds verstopft nur das system :/

**Comment by cagix** [comment]
so, jetzt habe ich selbst drei stunden investiert und zumindest die summaries, label, assignees etwas gerade gerückt und teilweise die leute angepingt.

dennoch: da sind gefühlt tausend issues offen, von denen gefühlt 1/3 mittlerweile obsolet sind bzw. die sich möglicherweise überschneiden bzw. doppeln. bitte wirklich dringend aufräumen. so nutzt uns das ticketsystem nämlich fast nichts.

und bitte auch diese "tracking-issues" mal schließen - was nutzen die dinger, wenn es dazu bereits einzelne issues gibt? das verstopft nur das system :/

**Comment by AMatutat** [comment]
Ich glaube das ist etwas, dass sich jetzt über die nächsten Wochen ziehen wird.

Was ich heute schonmal gemacht habe
- Samuel Issues geschlossen
- Gelöste bzw. veraltete Issues geschlossen


Um kurz die Problematik zu erläutern:
Einige Konzepte in manchen Issues sind nicht mehr ganz aktuell bzw. wir sind grade dabei zu diskutieren diese Konzepte zu kippen. Erst wenn die neuen Konzepte durchgewinkt sind, machte ich veraltete Issues zu machen (solange sind sie in meinen Augen nämlich nicht veraltet).

**Comment by AMatutat** [comment]
Ich hab noch ein paar Tickets gefunden und geschlossen.
Die meisten sind aber immer noch aktuell bzw. erst dann irrelevant, wenn andere Konzepte beschlossen/umgesetzt sind.

**Comment by AMatutat** [comment]
ich glaub das ist im großen ganzen jetzt erledigt. 
Gibt bestimmt noch ein paar Dinger die rumliegen, aber aktuell sehe ich nichts

**Comment by cagix** [comment]
danke dir!
