### ISSUE TITLE
[Github] Milestones aufräumen und Update der Planung/Milestones

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#585]
Es gibt aktuell nur zwei Milestones. Der "April April Dungeon SHK" ist nur zu 25% gelöst, obwohl der April fast vorbei ist. Es fehlen Meilensteine für die weitere Projektplanung, sowohl in Bezug auf Game, DSL als auch D2A. Was ist hier los?

Arbeitsauftrag an alle wiss. MA: Bitte erstellt einen Plan für die nächsten zwei Monate inkl. Meilensteine bis zum nächsten Meeting.

Edit: Könnte mit dem Dauerticket #439 zusammenhängen.

**Comment by AMatutat** [comment]
> Es gibt aktuell nur zwei Milestones. Der "April April Dungeon SHK" ist nur zu 25% gelöst, obwohl der April fast vorbei ist.

To be fair: Einiges muss ich noch reviewen und mergen. Aber beim ersten Überfliegen der Ergebnisse bin ich auch skeptisch geworden...

Anyway:
- Ich hätte gerne zwei Dungeon-Cleanup Milestones. Einen für Code-Cleanup und eines für die Dokumentation. Das würde ich gerne mit den SHKs in den nächsten zwei Monaten umsetzen. Dafür würde ich mir so 50% - 60% meiner Arbeitszeit einrechnen.
- Ich muss die Ergebnisse des Aprils noch sichten, aber ich denke ich werde nochmal so 20%-30% meiner Arbeitszeit damit verbringen, das so zu integrieren, wie wir es brauchen. Im Grunde sind das die restliche Inhalte die wir brauchen. Das meiste ist GUI.  
- @malt-r, auf der DSL-Seite muss diese Funktionsdefinition (Callbacks) und Task-Builder-Kram fertig werden. Wir müssen langsam die Aufgaben von der DSL in das Dungeon bekommen. Ich bekomme etwas Muffensausen. Außerdem segle ich im Dungeon langsam inhaltlich aufs Trockene. Aufräumen ist zwar wichtig, aber Inhalte nun mal auch.
- @malt-r, was die Steuermechanismen angeht, hänge ich etwas in der Luft (bin da nie über das abstrakte Verständnis hinaus gekommen), aber das sollten wir in den nächsten 2 Monaten auch auf die Kette kriegen, oder?

**Comment by malt-r** [comment]
> @malt-r, auf der DSL-Seite muss diese Funktionsdefinition (Callbacks) und Task-Builder-Kram fertig werden. Wir müssen langsam die Aufgaben von der DSL in das Dungeon bekommen. Ich bekomme etwas Muffensausen. Außerdem segle ich im Dungeon langsam inhaltlich aufs Trockene. Aufräumen ist zwar wichtig, aber Inhalte nun mal auch.

Jep, das ist inhaltlich das nächste, was ich angehen werde.

> @malt-r, was die Steuermechanismen angeht, hänge ich etwas in der Luft (bin da nie über das abstrakte Verständnis hinaus gekommen), aber das sollten wir in den nächsten 2 Monaten auch auf die Kette kriegen, oder?

Mein Ziel für die Woche ist es, die Konzepte und Notizen, die in #541, #503 und #501 in die Doku zu mergen, die beziehen sich nämlich größtenteils auf Steuermechanismen. Dann ist hoffentlich die Konzeption des "Überbaus", in den sich auch Callbacks und Task-Builder etc. einordnen müssen, soweit, dass man damit weiterarbeiten kann.

**Comment by AKirsch1** [comment]
> @AKirsch1 hast du schon Pläne für die nächsten zwei Monate?

D2A. Konkreteres bin ich gerade am raussuchen.

**Comment by AMatutat** [comment]
Ich habe für das Dungeon einige Milestones angelegt und schon mal die ersten Tickets eingeordnet.

Meine grobe (zeitliche) Planung sieht so aus:
![image](https://user-images.githubusercontent.com/32962412/235848626-345cfb89-1179-47ac-a4b2-5eabc0cc939a.png)

*Anmerkung*: Ich hab hier ein wenig zwei Diagrammtypen verschmolzen. Jeder Kasten ist ein Milestone und die länge des Kastens soll die geschätzte/gewünschte Bearbeitungslänge zeigen (im Verhältnis zu den anderen Milestones). Die X-Achse kann also als ganz grober Zeitstrahl verstanden werden. 

Ich habe das aber noch nicht auf Machbarkeit analysiert, dieser Schritt fehlt noch.
Auch den Status des Personals muss ich noch genauer in die Planung einfließen lassen. Diana ist z.B. nicht mehr lange dabei, daher sollten grafische Angelegenheiten vielleicht nach vorne geschoben werden.

Aktuell stört mich auch Block B. Für all diese Milestones sollten/sind bereits erste (oder mehrere) Schritte gemacht worden sein. Die Arbeit jetzt ruhen zu lassen, macht mir irgendwie Bauchweh. Auf der anderen Seite ist der Cleanup und die Dokumentation jetzt "wichtiger" bzw. sinnvoller zuerst aufzuräumen und dann weiterzubauen.

**Comment by AMatutat** [comment]
Zwischenstand Diskussion:

![image](https://user-images.githubusercontent.com/32962412/235858575-045a919b-3398-48ee-99bd-d6d5a88c11f7.png)


Ich bereite das Diagramm noch auf.

**Comment by AMatutat** [comment]
> Ich könnte mir vorstellen, "Dokumentation" ist nach einer (konzentrierten) Woche erledigt (80:20). Danach könnte man "Cleanup" angehen für eine Woche 

Ich glaube der cleanup sollte etwas Vorlauf bekommen, damit die Dokumentation nicht direkt veraltet und erneut überarbeitet werden muss.

Vielleicht wäre es Sinnvoll: 
1-2 Wochen Struktureller Cleanup (WiMI & cagix) parallel dazu Dokumentation Spielelemente/Components/Systeme (SHK 80:20) 

Danach rennen die SHKs in Block B rum. 
Ich überarbeite in der Zeit die Dokumentation, schreibe die Dokumentation für das große ganze (zusammenhänge, Strukturen, etc.) 

Danach/parallel (je nach Besetzung für Block B, das müsste ich nochmal anschauen) Cleancode und Testing.
Das könnte sich parallel zu Block B und C einsortieren. 

In Block C wird bestimmt noch das ein oder andere Feature hinzukommen, das wir grade nicht auf den schirm haben. 


> Größere Dinge werden wir realistisch jetzt nicht angehen (können) - auch wenn ich beispielsweise gern noch einmal über die Konfiguration von Game nachdenken würde etc.

Sehe ich ähnlich.

**Comment by cagix** [comment]
Klingt sinnvoll. Die Elemente ziehen vermutlich im Package-Tree ein wenig um, aber das stört in der Doku nicht. Nur bei Umbenennungen ... Aber das kriegt man schnell hin.

**Comment by AMatutat** [comment]
@cagix @bcg7 @malt-r @AKirsch1 

So, ich hab unsere Diskussionen jetzt mal in einen billo Gant-Diagramm-Like Konstrukt abgebildet:

![image](https://user-images.githubusercontent.com/32962412/235890940-6ef8a8ed-8ec8-48bd-b0ec-dc3978157620.png)

Der Begriff "KW" ist etwas gelogen. "Unsere KWs" enden immer mit dem Meeting am Mittwoch. Also KW 19 der Tabelle endet am Mittwoch des richtigen KW 19. 

Falls ihr lieber eine pdf haben wollt: 
[Projektplan.pdf](https://github.com/Programmiermethoden/Dungeon/files/11381521/Projektplan.pdf)

**Comment by AMatutat** [comment]
@cagix 

Mir kam eben der Gedanke, dass ich eigentlich für jede Klasse im Dungeon jeweils ein Issue für 
- Dokumentation erstellen/überarbeiten
- Testabdeckung analysieren/überarbeiten
- Cleancode

anlegen (lassen) müsste- 
Streng genommen müsste man das Dokumentationsding nochmal in Javadoc und /doc unterteilen. 

Das sind aber dann mal locker 100+ Issues. 

Pro:
- korrekter Workflow
- Klare "Übersicht" welche Klassen noch bearbeitet werden müssen
- Einfache Referenzierung in PRs + schnelle Bearbeitung, da kleine Tickets


Contra: 
- Übersicht im Issue Tracker geht verloren
- Die Isseus muss auch wer erstellen (ChatGPT vielleicht? Weiß aber nicht wie gut die GitHub API da mitspielt)


Alternative: Sammelissues für Cleancode, Javadoc, ./doc mit Liste zum abhacken. Die Nachteile sind bekannt

**Comment by cagix** [comment]
> @cagix @bcg7 @malt-r @AKirsch1
> 
> So, ich hab unsere Diskussionen jetzt mal in einen billo Gant-Diagramm-Like Konstrukt abgebildet:
> 
> ![image](https://user-images.githubusercontent.com/32962412/235892958-ea3c8f4c-c438-416c-8fa4-fba41bd5a151.png)
> 
> Der Begriff "KW" ist etwas gelogen. "Unsere KWs" enden immer mit dem Meeting am Mittwoch. Also KW 19 der Tabelle endet am Mittwoch des richtigen KW 19.
> 
> Falls ihr lieber eine pdf haben wollt: [Projektplan.pdf](https://github.com/Programmiermethoden/Dungeon/files/11381620/Projektplan.pdf)
> 
> Edit: Ich habe nochmal den Zeitplan der SHKs etwas angepasst und auch zwischen den Milestones etwas Buffer einzuplanen.


Finde ich richtig gut 👍  

Vielleicht an manchen Stellen etwas großzügig in der Planung: Ich würde Cleanup+Doku bei 3 statt 4 Wochen sehen. 

Anmerkung 1: "Finassieren" => "Finalisieren" :)
Anmerkung 2: Bei Malte fehlen das Erarbeiten einer Publikation sowie das Aufschreiben (Dokumentieren) der Arbeitsergebnisse.

Habt ihr im Meeting heute darüber gesprochen? In den Notes steht nix davon.

**Comment by cagix** [comment]
> @cagix @bcg7 @malt-r @AKirsch1
> 
> So, ich hab unsere Diskussionen jetzt mal in einen billo Gant-Diagramm-Like Konstrukt abgebildet:
> 
> ![image](https://user-images.githubusercontent.com/32962412/235892958-ea3c8f4c-c438-416c-8fa4-fba41bd5a151.png)
> 
> Der Begriff "KW" ist etwas gelogen. "Unsere KWs" enden immer mit dem Meeting am Mittwoch. Also KW 19 der Tabelle endet am Mittwoch des richtigen KW 19.
> 
> Falls ihr lieber eine pdf haben wollt: [Projektplan.pdf](https://github.com/Programmiermethoden/Dungeon/files/11381620/Projektplan.pdf)
> 
> Edit: Ich habe nochmal den Zeitplan der SHKs etwas angepasst und auch zwischen den Milestones etwas Buffer einzuplanen.


Finde ich richtig gut 👍  

Vielleicht an manchen Stellen etwas großzügig in der Planung: Ich würde Cleanup+Doku bei 3 statt 4 Wochen sehen. 

Anmerkung 1: "Finassieren" => "Finalisieren" :)
Anmerkung 2: Bei Malte fehlen das Erarbeiten einer Publikation sowie das Aufschreiben (Dokumentieren) der Arbeitsergebnisse.

Habt ihr im Meeting heute darüber gesprochen? In den Notes steht nix davon.

Edit: @AMatutat Das sind dann auch die neuen Meilensteine, oder?

**Comment by cagix** [comment]
@AMatutat 

> Mir kam eben der Gedanke, dass ich eigentlich für jede Klasse im Dungeon jeweils ein Issue für
> 
> [...]
> 
> Das sind aber dann mal locker 100+ Issues.

Auweia. Das dauert (a) ewig beim Erzeugen (selbst wenn Du das über ein Skript o.ä. machst - dann brauchst Du viel Zeit für die Vorbereitung des Skripts und die Nachbereitung der neuen Tickets) und (b) verstopft uns das den Tracker komplett.

Siehst Du Alternativen?

Ich könnte mir eine Wiki-Seite vorstellen mit einer Tabelle Klasse vs. Cleancode+Doku+Test. In den jeweiligen Zellen trägt man die Issue-Nummer ein als Link, wenn es ein Issue gibt und jemand daran arbeitet. D.h. man macht ein neues Ticket nur auf, wenn sich wirklich jemand aktiv damit beschäftigen wird und nicht im Vorfeld auf Vorrat.

Die Tabelle sollte sich relativ schnell erstellen lassen, Du brauchst ja nur ein Skript, was über alle Ordner geht und pro Klasse eine Zeile dran hängt.

Wenn die Tabelle komplett fertig ist, kann die Seite wieder gelöscht werden.

**Comment by AMatutat** [comment]
> Habt ihr im Meeting heute darüber gesprochen? In den Notes steht nix davon.

Nicht wirklich. Uns schienen die operativen Diskussionen ohne dich etwas innbefreiter. 

@bcg7 und ich haben kurz über das Thema Evaluierung gesprochen und festgestellt, dass das wohl eher in die Verlängerung geschoben werden muss, damit wir den Semesterflow berücksichtigen. 

Das wäre dann wohl auch der Zeitraum für: 

> Anmerkung 2: Bei Malte fehlen das Erarbeiten einer Publikation sowie das Aufschreiben (Dokumentieren) der Arbeitsergebnisse.


> Vielleicht an manchen Stellen etwas großzügig in der Planung: Ich würde Cleanup+Doku bei 3 statt 4 Wochen sehen.

Vermutlich hast du recht. Ich muss meinen Anspruch ablegen jetzt alles aufzuräumen. Aufwendigere Arbeiten in diesen Bereich können wir gut in die Verlängerung schieben. Passt sich eh ganz gut, ich bin eben noch über ein paar wichtige Issues "gestolpert" die sich aktuell noch nicht in die vorhanden Milestones einordnen lassen. Die muss ich auch noch einplanen. 


>  @AMatutat Das sind dann auch die neuen Meilensteine, oder?

Jop. Jeder Kasten ist ein Milestone. Die sind jetzt Teilweise schon angelegt und gefüllt, Teilweise aber auch nicht. 
@malt-r @AKirsch1 und @AMatutat sollen das bis Ende dieser Woche fertigstellen. Danach sollte das Diagramm auch final sein und ich würde das ins Wiki laden.

**Comment by AMatutat** [comment]
> @AMatutat
> 
> > Mir kam eben der Gedanke, dass ich eigentlich für jede Klasse im Dungeon jeweils ein Issue für
> > [...]
> > Das sind aber dann mal locker 100+ Issues.
> 
> Auweia. Das dauert (a) ewig beim Erzeugen (selbst wenn Du das über ein Skript o.ä. machst - dann brauchst Du viel Zeit für die Vorbereitung des Skripts und die Nachbereitung der neuen Tickets) und (b) verstopft uns das den Tracker komplett.
> 
> Siehst Du Alternativen?
> 
> Ich könnte mir eine Wiki-Seite vorstellen mit einer Tabelle Klasse vs. Cleancode+Doku+Test. In den jeweiligen Zellen trägt man die Issue-Nummer ein als Link, wenn es ein Issue gibt und jemand daran arbeitet. D.h. man macht ein neues Ticket nur auf, wenn sich wirklich jemand aktiv damit beschäftigen wird und nicht im Vorfeld auf Vorrat.
> 
> Die Tabelle sollte sich relativ schnell erstellen lassen, Du brauchst ja nur ein Skript, was über alle Ordner geht und pro Klasse eine Zeile dran hängt.
> 
> Wenn die Tabelle komplett fertig ist, kann die Seite wieder gelöscht werden.
> 
> Edit 1: Ich könnte mir sogar vorstellen, dass man in diesem Fall gar keine Tickets erst anlegt, sondern direkt über PR geht. Spart Arbeit, und Diskussionen wird es vermutlich keine weiter geben (das wäre der einzige Sinn separater Tickets hier)? Edit 2: Das wäre aber ein leichter Shift im Vorgehen. Bisher war ja alles mit Vorausplanung als Ticket. Hmmm. Edit 3: Na gut, wenn man eh per Skript so eine Ausgabe erzeugen lässt, könnte man auch direkt die API ansprechen und dann eben doch neue Tickets anlegen? Das macht aber nur Sinn, wenn dann die Summary und die Label und Projects und Milestones und so richtig eingestellt werden (können), so dass keine manuelle Nacharbeit notwendig wird.

Wenn, dann ich würde anstelle einer Wiki Seite eine Tabelle in einem Issue führen. Aber könnte funktionieren. 
Dann aber keine weiteren Issues für die PRs. Auf dem Papier klingt das gut, aber in der Realität wird das einfach nicht gescheit umgesetzt. 


Thema Skript:
Titel und Beschreibung sollten kein Problem sein. Die Metadaten.... ich bin mir nicht sicher
```
payload = {
    "title": "[Test] test test",
    "body": "Das ist ein Test",
    "labels": ["documentation"],
    "milestone": "Dungeon: Dokumentation",
    "project": "Dungeon (2022/2023)"
}
```
das könnte/sollte funktionieren, müssten man aber testen. 
Alternativ lassen sich die Metadaten auch über die UI in massen setzten. Das geht relativ flott. 

Die Frage ist halt: Wollen wir uns damit das Repo verstopfen?

**Comment by AKirsch1** [comment]
@AMatutat Kannst du bei mir das Konzept im Diagramm noch um eine Woche verlängern?

**Comment by AMatutat** [comment]
@AKirsch1 das Repostruktur Konzept oder das Tooling Konzept?

**Comment by AKirsch1** [comment]
Sorry, ich meinte das Tooling Konzept.

**Comment by AMatutat** [comment]
> > Dann aber keine weiteren Issues für die PRs. Auf dem Papier klingt das gut, aber in der Realität wird das einfach nicht gescheit umgesetzt.

> Kannst Du das noch ausführen? Man kann doch einfach den PR mit dem Issue verlinken (ohne dieses automatisch zu schließen) und dann auch den PR in die Tabelle im Issue eintragen? Damit hätten wir das Tracking - es wäre halt ein 1:n-Szenario (1 Ticket zu n PR).

1:n finde ich gut. Ich wollte nur vermeiden ein "master"-issue zu haben und dann trotzdem ein Issue "Dokumention XYZ" anlegen (sobald die Bearbeitung beginnt) "nur" damit der PR ein "fixes #XYZ" bekommen kann. Dann hätten wir nämlich ein 1:n:n - Szenario. 
 

> Wenn Du mich jetzt fragst: Ich wäre für ein solches "ewiges" Ticket mit einer Aufgabenbeschreibung und der Trackingtabelle im ersten Kommentar und PR, die gegen dieses Ticket verlinken (also GH-Verlinkung und Eintrag in der Tabelle).

Same.

**Comment by cagix** [comment]
Mist, jetzt wird das hier wieder unübersichtlich. Wann wird Github endlich Issues und Discussions mergen?!

> > Anmerkung 2: Bei Malte fehlen das Erarbeiten einer Publikation sowie das Aufschreiben (Dokumentieren) der Arbeitsergebnisse.
>
Für @AKirsch1 fehlt auch die Planung für die Publikation.



> > Vielleicht an manchen Stellen etwas großzügig in der Planung: Ich würde Cleanup+Doku bei 3 statt 4 Wochen sehen.
> 
> Vermutlich hast du recht. Ich muss meinen Anspruch ablegen **jetzt alles** aufzuräumen. Aufwendigere Arbeiten in diesen Bereich können wir gut in die Verlängerung schieben. Passt sich eh ganz gut, ich bin eben noch über ein paar wichtige Issues "gestolpert" 

Wir sollten die **wichtigsten Dinge jetzt** erledigen, weil sich sonst zu viele Schulden aufhäufen (auf der aktuellen Basis wird ja noch vier Monate aktiv gearbeitet, d.h. der Berg wird dann nur noch größer). Wenn das dann auch vier Wochen rausläuft, dann ist das halt so. Mir kam es halt nur etwas großzügig vor, aber Du bist da näher dran. Aber **alles** aufräumen wird nicht möglich sein.

**Comment by cagix** [comment]
> > > Dann aber keine weiteren Issues für die PRs. Auf dem Papier klingt das gut, aber in der Realität wird das einfach nicht gescheit umgesetzt.
> 
> > Kannst Du das noch ausführen? Man kann doch einfach den PR mit dem Issue verlinken (ohne dieses automatisch zu schließen) und dann auch den PR in die Tabelle im Issue eintragen? Damit hätten wir das Tracking - es wäre halt ein 1:n-Szenario (1 Ticket zu n PR).
> 
> 1:n finde ich gut. Ich wollte nur vermeiden ein "master"-issue zu haben und dann trotzdem ein Issue "Dokumention XYZ" anlegen (sobald die Bearbeitung beginnt) "nur" damit der PR ein "fixes #XYZ" bekommen kann. Dann hätten wir nämlich ein 1:n:n - Szenario.
> 
> > Wenn Du mich jetzt fragst: Ich wäre für ein solches "ewiges" Ticket mit einer Aufgabenbeschreibung und der Trackingtabelle im ersten Kommentar und PR, die gegen dieses Ticket verlinken (also GH-Verlinkung und Eintrag in der Tabelle).
> 
> Same.

Dann "Engage" :)

**Comment by AMatutat** [comment]
@cagix hab mein kommentar nochmal editiert (letzten Teil)

**Comment by AMatutat** [comment]
@malt-r @cagix @AKirsch1 @bcg7 

Hier die neue Version. 

![image](https://user-images.githubusercontent.com/32962412/236146876-4faf4af6-f0fc-4a
[Projektplan.pdf](https://github.com/Programmiermethoden/Dungeon/files/11395251/Projektplan.pdf)
6e-965c-d5f9be097b0f.png)


Nach der Besprechung gestern ist die Evaluierung nach dem eigentlichen Projektende verschoben. Dadurch haben wir etwas mehr Buffer bekommen. Für @malt-r ist das Zeit zum Publizieren und Dokumentieren. Für @AKirsch1 Zeit zum Publizieren und das Highscore System (auch wenn das noch etwas Magic Black box ist). 

Für die SHKs habe ich den Buffer genutzt, um die restlichen Issue die noch rumgeflogen sind  einzusortieren. 

Für mich habe ich die Zeit genutzt um a) mir etwas mehr Buffer bei den beiden wichtigen Themen Petri Netze und Aufgabenimplementierung einzuräumen. Außerdem habe ich noch einen Milestone vergessen und nachgetragen (Graphenlevel, das muss nicht aufgeräumt werden.)

**Comment by AMatutat** [comment]
So, die Meilensteine sind alle erstellt und datiert.
Auf den ersten Blick sind schon einige Tickets eingeordnet worden, aber nicht alle.
Kann jeder noch einmal gucken, ob er Tickets in seinem Aufgabenbereich hat, die noch keinem Meilenstein zugeordnet sind?
Mein Verständnis wäre nämlich: Die Umsetzung von Tickets ohne Meilenstein ist nicht geplant, außer es handelt sich um organisatorische Tickets.

Der Projektplan ist auf der Wiki-Startseite einsehbar.

**Comment by AMatutat** [comment]
Meilensteine sind angelegt und datiert. Hier sind wir dann fertig
