### ISSUE TITLE
[Github] Cleanup Label

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#586]
Wir haben eine wirklich große Anzahl an Label, in allen möglichen Farben und hübsch groß oder klein geschrieben. 

Einige Label erscheinen nicht (mehr) so richtig sinnvoll: "current week" sagt mit etwas Abstand betrachtet eigentlich nichts aus. So lange ein Ticket offen und zugewiesen ist, ist es aktuell in Bearbeitung; das Label dupliziert die Information nur. Außerdem scheint niemand (nicht mal die wiss. MA) das wirklich zu pflegen und das Label ggf. wieder zu entfernen. Zusätzlich haben wir das neue Skript zum Sammeln der PR.
Edit: Die Sinnlosigkeit von "current week" zeigt sich, wenn man mal nach offenen Issues mit diesem Label sucht: Schlappe **53** Issues! (https://github.com/Programmiermethoden/Dungeon/issues?q=is%3Aopen+is%3Aissue+label%3Acurrent_week)

Arbeitsauftrag an alle wiss. MA: Bitte erstellt zur nächsten Sitzung ein Konzept, welche Label wir wirklich minimal brauchen. Gruppiert die Label nochmal, damit jede Gruppe ihre eigene Farbe bekommt.

**Comment by AMatutat** [comment]
Aus meiner Sicht: 

Basic Labels, die beibehalten werden sollten:
- "Bug"
- "Documentation"
- "Duplicate"
- "High Priority"
- "Konzept" 
- "Later"
- "Meeting"
- "Org"
- "Publication"
- "Thesis" 
- "Wontfix"

Projektbereiche: 
- "Deploy to Grading"
- "DSL" (ohne "Basics", da redundant)
- "Dungeon" (ohne "Basics", da redundant)
- "Einsatz und Verbreitung" 
- "Evaluierung"
- "Highscore"
- "Petri-Netze"

Aufgabentypen:
- "Ersetzen"
- "Kombinieren"
- "Positionieren"
- "Quizfragen"

Zuständigkeiten: 
- "SHK"

Labels für die Lehre:
- "Bounty"
- "5P"
- "10P"

Hacktoberfest (@cagix, du musst entscheiden): 
- "Hacktoberfest-Accepted"

Nicht mehr benötigte Labels:
- "Current_Week": Ich mag das Label zwar, da wir manchmal Issues verteilen, ohne dass diese direkt bearbeitet werden sollen, und dieses "In Progress" für mich im ersten Blick schwer zu erkennen ist. Aber ich gebe @cagix recht, in der Praxis wird es zu wenig gepflegt und verliert daher seinen Nutzen.
- "DSL (Advanced)" und "Game (Advanced)": Diese Labels sind eigentlich das Label "DSL" bzw. "Game" mit dem Label "Later".
- "GUI": Das hatte ich damals eingeführt, um mir Dungeon Issues zu markieren, die sich auf die GUI beziehen (ich hatte ja gehofft, wir bekommen eine reine GUI-SHK). Aber es ist veraltet und kann entfernt werden.
- "Wimi-DSL" und "WiMi-Dungeon": Diese Labels sind irgendwie unnütz. Alles, was nicht mit "SHK" gelabelt ist, ist WiMi, und dann ergibt sich die Zuständigkeit aus dem Kontext, oder?

Jede "Überschrift" sollte in meinen Augen eine Kategorie sein und daher in einer Farbe gehalten werden. Eine Ausnahme sind die Basic-Labels. Zusätzlich sollten wir ein einheitliches System festlegen (alle Labels klein und auf Englisch(?)).



@malt-r @AKirsch1 Meinungen?

**Comment by AKirsch1** [comment]
Hier mal meine Meinung zu denen, wo ich etwas anders machen würde als @AMatutat:

### Basic Labels:
- "Duplicate": Würde ich streichen, sobald wir ein Duplicate finden, wird es geschlossen und ab da ist das Label irrelevant
- "Meeting": Dass man darüber sprechen muss, würde ich anders festhalten und nicht als Label, z.B. haben wir ja in den Protkollen die Tagespunkte
- "Org": Org tritt nur mit Meeting auf, kann also auch weg

### Projektbereiche / Aufgabentypen:
- "Highscore"
- "Petri-Netze"
- "Ersetzen"
- "Kombinieren"
- "Positionieren"
- "Quizfragen"

Gehen wir bei all diesen Labels nicht zu sehr ins Detail? Insbesondere bei den Aufgabentypen. (Wenn wir diese behalten, dann würde ich aber auch das GUI-Label behalten)

### Labels für die Lehre:
- "Bounty"
- "5P"
- "10P"

Würde ich ändern in zwei Labels mit den Namen "Bount 5P" und "Bounty 10P". Dann sparen wir uns ein Label. Wenn man beide Label auswählt, kann man sich trotzdem auch beide anzeigen lassen.

Ansonsten: Ich wäre auch für einheitliche Namen.

**Comment by cagix** [comment]
Können wir die Label mit einem "Gruppen-Präfix" noch klarer gestalten? Ich habe mal sowas in der Art gesehen: "präfix:label" - das wäre hier "lehre:bounty". 

Schön wäre es, wenn wir in Summe auf 10..12 wirklich relevante Label kommen könnten.

**Comment by malt-r** [comment]
Ich habe mir auch nochmal ein paar ergänzende Gedanken gemacht:

## Basic Labels

- https://github.com/Programmiermethoden/Dungeon/labels/duplicate würde ich behalten. Teilweise fällt das ja erst nach einer gewissen Diskussionszeit auf, dass es sich um ein Duplikat handelt. Wenn man das Duplikat-Issue mit dem "Duplicate" Label versieht und schließt, bleibt die Diskussion erhalten und das Issue kann in dem "eigentlichen" Issue verlinkt werden.
- https://github.com/Programmiermethoden/Dungeon/labels/org: Mir ist nicht ganz klar, was hiermit erreicht werden soll (steht auch keine Beschreibung dran).. wirkt irgendwie redundant und kann weg, denke ich
- https://github.com/Programmiermethoden/Dungeon/labels/high%20prio: Hier sehe irgendwie ein ähnliches Problem wie bei https://github.com/Programmiermethoden/Dungeon/labels/current_week, da das aktuell inflationär genutzt wird.. eine gute Alternative habe ich aber auch nicht
- https://github.com/Programmiermethoden/Dungeon/labels/meeting: hier stimme ich @AKirsch1 zu, da liegt es an jedem einzelnen, sich die Punkte, die im Meeting geklärt werden müssen zu merken und dann vorab als TOP ins Protokoll einzutragen. Die Idee, zum Meeting einfach nur nach dem label zu filtern ist zwar sexy, funktioniert aber in der Praxis nicht, weil zu wenig gepflegt 

## Projektbereiche / Aufgabentypen

- https://github.com/Programmiermethoden/Dungeon/labels/DSL%20%28Basics%29 und https://github.com/Programmiermethoden/Dungeon/labels/DSL%20%28Advanced%29 zusammenlegen, genau wie https://github.com/Programmiermethoden/Dungeon/labels/Dungeon%20%28Basics%29 und https://github.com/Programmiermethoden/Dungeon/labels/Dungeon%20%28Advanced%29
- https://github.com/Programmiermethoden/Dungeon/labels/Petri%20Netze: gehört zu einer Reihe an übergeordneten Kontrollmechanismen (wie z.B. auch das Laden und Auswählen von verschiedenen Aufgabendefinitionen, das "Reporting" (also Erfassung und Bewertung von Antworten)), hier könnte ich mir ein label "control_mechanism" vorstellen, um das alles zusammen zu fassen
  - https://github.com/Programmiermethoden/Dungeon/labels/Highscore könnte auch in dieses "control_mechanism" label integriert werden
- Aufgabentypen: Ich bin mir nicht sicher, ob die Unterteilung in einzelne Aufgabentypen wirklich zielführend ist. Andererseits ist ein einzelnes "tasks" Label vielleicht auch zu grobgranular. Aber damit könnte man zumindest zeigen: "Hier geht es um die Realisierung einer Aufgabe / eines Aufgabentyps".

## Labels für die Lehre 

- https://github.com/Programmiermethoden/Dungeon/labels/bounty taucht nur mit in Kombination mit https://github.com/Programmiermethoden/Dungeon/labels/5P und https://github.com/Programmiermethoden/Dungeon/labels/10P auf und könnte daher in "bounty:5P" und "bounty:10P" zusammengelegt werden 

## Labels, die weg können

Schließe mich da @AMatutat in den Punkten an:

> * "Current_Week": Ich mag das Label zwar, da wir manchmal Issues verteilen, ohne dass diese direkt bearbeitet werden sollen, und dieses "In Progress" für mich im ersten Blick schwer zu erkennen ist. Aber ich gebe @cagix recht, in der Praxis wird es zu wenig gepflegt und verliert daher seinen Nutzen.
> * "DSL (Advanced)" und "Game (Advanced)": Diese Labels sind eigentlich das Label "DSL" bzw. "Game" mit dem Label "Later".
> * "GUI": Das hatte ich damals eingeführt, um mir Dungeon Issues zu markieren, die sich auf die GUI beziehen (ich hatte ja gehofft, wir bekommen eine reine GUI-SHK). Aber es ist veraltet und kann entfernt werden.
> * "Wimi-DSL" und "WiMi-Dungeon": Diese Labels sind irgendwie unnütz. Alles, was nicht mit "SHK" gelabelt ist, ist WiMi, und dann ergibt sich die Zuständigkeit aus dem Kontext, oder?

**Comment by malt-r** [comment]
Ergebnis der Diskussion von @AMatutat, @AKirsch1 und @malt-r vom 02.05.:

### Allgemein

Vorschlag für die Label-Benennung: englisch, snake_case 

 ### Labels, die rausfliegen:

- https://github.com/Programmiermethoden/Dungeon/labels/current_week
- https://github.com/Programmiermethoden/Dungeon/labels/org
- https://github.com/Programmiermethoden/Dungeon/labels/DSL%20%28Advanced%29: das ist quasi ein verstecktes https://github.com/Programmiermethoden/Dungeon/labels/later und daher redundant
- https://github.com/Programmiermethoden/Dungeon/labels/Dungeon%20%28Advanced%29: das ist quasi ein verstecktes https://github.com/Programmiermethoden/Dungeon/labels/later und daher redundant
- https://github.com/Programmiermethoden/Dungeon/labels/Ersetzen, https://github.com/Programmiermethoden/Dungeon/labels/Kombinieren, https://github.com/Programmiermethoden/Dungeon/labels/Positionieren und https://github.com/Programmiermethoden/Dungeon/labels/Quizfragen: die Labels sind zu feingranular und werden vermutlich nur in sehr wenigen Issues eingesetzt. Von einem zusammenfassenden "tasks" oder "quest" Label wird abgesehen, da sich implizit fast alles irgendwie auf die Realisierung von Aufgaben im Dungeon bezieht
- https://github.com/Programmiermethoden/Dungeon/labels/Petri%20Netze: wird in Milestones abgebildet
- https://github.com/Programmiermethoden/Dungeon/labels/Evaluierung: wird in einem oder mehreren Milestones abgebildet
- https://github.com/Programmiermethoden/Dungeon/labels/GUI: wird in Milestones abgebildet
- https://github.com/Programmiermethoden/Dungeon/labels/WiMi-DSL: durch Markierung mit https://github.com/Programmiermethoden/Dungeon/labels/DSL%20%28Basics%29 und Abwesenheit von https://github.com/Programmiermethoden/Dungeon/labels/SHK wird das Label impliziert
- https://github.com/Programmiermethoden/Dungeon/labels/WiMi-Dungeon: durch Markierung mit https://github.com/Programmiermethoden/Dungeon/labels/Dungeon%20%28Basics%29 und Abwesenheit von https://github.com/Programmiermethoden/Dungeon/labels/SHK wird das Label impliziert
- https://github.com/Programmiermethoden/Dungeon/labels/bounty: ist redundant und wird zusammen mit https://github.com/Programmiermethoden/Dungeon/labels/5P und https://github.com/Programmiermethoden/Dungeon/labels/10P zu "bounty_5P" und "bounty_10P" zusammengefasst

### Anmerkungen zu Labels, die bestehen bleiben

- https://github.com/Programmiermethoden/Dungeon/labels/high%20prio: da sind aktuell zu viele Issues drin, als dass hierdurch wirklich angezeigt wird "hier brennt es, das muss als aller erstes vor anderen Dingen erledigt werden"; alle Issues mit dem Label prüfen, ggfs. neu priorisieren und zukünftig zurückhaltender bei der Vergabe des Labels sein
- https://github.com/Programmiermethoden/Dungeon/labels/meeting: Hiermit sind zu viele Issues markiert. Das Label ist sinnvoll, um lange Diskussionen in Issues abzukürzen, bzw. auf ein Meeting zu verschieben. Allerdings setzt das auch die Disziplin voraus, nach dem entsprechenden Meeting wieder das Label zu entfernen und die Ergebnisse des Meetings festzuhalten. 
- https://github.com/Programmiermethoden/Dungeon/labels/Einsatz%20und%20Verbreitung: Hier sind einige Issues (z.B. #499, #274) zugeordnet, die nur bedingt zu dem Label passen, die Definition von "Einsatz und Verbreitung" sollte nochmal präzisiert und Issues ggfs. umsortiert werden

### Offene Punkte

- https://github.com/Programmiermethoden/Dungeon/labels/hacktoberfest-accepted: was soll hiermit werden?

### Vorschlag für neue Labels

**Operative Labels**

- https://github.com/Programmiermethoden/Dungeon/labels/bug
- https://github.com/Programmiermethoden/Dungeon/labels/duplicate
- https://github.com/Programmiermethoden/Dungeon/labels/high%20prio
- https://github.com/Programmiermethoden/Dungeon/labels/later
- https://github.com/Programmiermethoden/Dungeon/labels/meeting
- https://github.com/Programmiermethoden/Dungeon/labels/publication
- https://github.com/Programmiermethoden/Dungeon/labels/SHK -> "shk"
- https://github.com/Programmiermethoden/Dungeon/labels/thesis
- https://github.com/Programmiermethoden/Dungeon/labels/wontfix
- https://github.com/Programmiermethoden/Dungeon/labels/Konzept -> "concept"
- https://github.com/Programmiermethoden/Dungeon/labels/5P -> "bounty_5P"
- https://github.com/Programmiermethoden/Dungeon/labels/10P -> "bounty_10P"

**Strukturelle Labels (bezogen auf Projektstruktur)** 
- https://github.com/Programmiermethoden/Dungeon/labels/documentation
- https://github.com/Programmiermethoden/Dungeon/labels/DSL%20%28Basics%29 -> "dsl"
- https://github.com/Programmiermethoden/Dungeon/labels/Dungeon%20%28Basics%29 -> "dungeon"
- https://github.com/Programmiermethoden/Dungeon/labels/Highscore -> "highscore"
- https://github.com/Programmiermethoden/Dungeon/labels/deploy-to-abgabe -> "d2a"
- https://github.com/Programmiermethoden/Dungeon/labels/Einsatz%20und%20Verbreitung -> "deployment"

**Comment by cagix** [comment]
Das ist eine gute Diskussionsgrundlage!

Aus meiner Sicht könnte man auf `duplicate` auch gut verzichten - das schreibt man als letzten Kommentar rein (mit Verweis auf das andere Ticket) und macht als "not planned" zu. Dito mit "wontfix", das ist zwar ein Standard-Label, aber irgendwie macht es hier keinen Sinn bzw. doppelt sich mit "not planned" als Closing-Grund.

Braucht man "SHK" wirklich? Die Tickets werden nicht-assigned erstellt und in die Meilensteine sortiert und dann im Meeting verteilt. Sobald zugewiesen ist das Label eigentlich redundant/obsolet.

`bounty_5P` und `bounty_10P` wäre für mich `bounty:5p` und `bounty:10p`. 

Ich möchte nochmal auf die Gruppierung "thema:unterthema" hinweisen. Damit kann man richtig viel Überblick schaffen - schaut mal https://github.com/jgm/pandoc/labels an.

Und ich würde gern alle Label klein und mit einer engl. Abkürzung schreiben, damit der unruhige Mischmasch weggeht.

"hacktoberfest" könnte weg, da das Repo an sich damit ausgezeichnet ist.

**Comment by AMatutat** [comment]
> Braucht man "SHK" wirklich? Die Tickets werden nicht-assigned erstellt und in die Meilensteine sortiert und dann im Meeting verteilt. Sobald zugewiesen ist das Label eigentlich redundant/obsolet. 

Ich finde das Label gut. Die SHKs scheinen mir auch gut damit klarzukommen und ihren Überblick über den Issue-Dschungel zu behalten. Es hilft mir beim Verteilen der Aufgaben im Meeting, da ich schnell sehen kann: "Was ist auf SHK-Ebene machbar?"
Es erleichtert den SHKs auch, selbst ein Issue auszusuchen (kommt nicht häufig vor, aber ab und zu).

> Und potentiell sind ja alle Issues ohne "Konzept" die SHK-Issues?

Ich bin mir nicht sicher, ob ich dem zustimmen würde. Zunächst beschränkt sich der Arbeitsbereich der SHKs auf das Dungeon und die Dokumentation. Der korrektere Satz wäre: "Alle Issues ohne das Label "Konzept", die sich auf das Dungeon oder die Dokumentation (aber nicht alle Dokumentation) beziehen, sind SHK-Issues". 
Allerdings impliziert dies viel, ohne es direkt zu sagen, was ich nicht besonders mag. Ich bin auch nicht sicher, ob ich der Grundprämisse selbst im eingeschränkten Arbeitsbereich zustimmen würde.

**Comment by cagix** [comment]
ja, ok. wäre dann "konzept" eher "wimi"?

**Comment by AKirsch1** [comment]
> ja, ok. wäre dann "konzept" eher "wimi"?

Wenn ich mir so anschaue, an wie vielen Issues sowohl https://github.com/Programmiermethoden/Dungeon/labels/Konzept als auch SHK stehen oder an denen auch ein/e https://github.com/Programmiermethoden/Dungeon/labels/SHK beteiligt ist, würde ich das nicht so sagen. Siehe z.B. #517, #540 oder #509.

Zu https://github.com/Programmiermethoden/Dungeon/labels/duplicate und https://github.com/Programmiermethoden/Dungeon/labels/wontfix: Da ich das bei https://github.com/Programmiermethoden/Dungeon/labels/duplicate eh schon geschrieben hatte, wäre ich auch dafür.

> und die Farben müssten nochmal überdacht werden

Hatten wir auch geplant. Steht oben nur nicht. Aber ist es nicht doppelt gemoppelt, wenn wir die Labels sowohl farbig markieren als auch mit Präfix versehen?

**Comment by malt-r** [comment]
Das würde dann zusammengefasst so aussehen:

**Operative Labels**

- https://github.com/Programmiermethoden/Dungeon/labels/bug
- https://github.com/Programmiermethoden/Dungeon/labels/high%20prio
- https://github.com/Programmiermethoden/Dungeon/labels/later
- https://github.com/Programmiermethoden/Dungeon/labels/meeting
- https://github.com/Programmiermethoden/Dungeon/labels/publication
- https://github.com/Programmiermethoden/Dungeon/labels/thesis
- https://github.com/Programmiermethoden/Dungeon/labels/SHK -> "staff:shk"
- https://github.com/Programmiermethoden/Dungeon/labels/Konzept -> "staff:concept" / "staff:wimi"
- https://github.com/Programmiermethoden/Dungeon/labels/5P -> "bounty:5P"
- https://github.com/Programmiermethoden/Dungeon/labels/10P -> "bounty:10P"

**Strukturelle Labels (bezogen auf Projektstruktur)** 
- https://github.com/Programmiermethoden/Dungeon/labels/documentation -> "struct:documentation"
- https://github.com/Programmiermethoden/Dungeon/labels/DSL%20%28Basics%29 -> "struct:dsl"
- https://github.com/Programmiermethoden/Dungeon/labels/Dungeon%20%28Basics%29 -> "struct:dungeon"
- https://github.com/Programmiermethoden/Dungeon/labels/Highscore -> "struct:highscore"
- https://github.com/Programmiermethoden/Dungeon/labels/deploy-to-abgabe -> "struct:d2a"
- https://github.com/Programmiermethoden/Dungeon/labels/Einsatz%20und%20Verbreitung -> "struct:deployment"

Für mich sieht das langsam nach einer runden Sache aus :)

**Comment by cagix** [comment]
finde ich gut. jetzt noch die farben: 

- "staff:shk" und "staff:wimi" sollten die gleiche farbe bekommen. 
- "bounty:*" sollte farblos werden (und bitte analog zu den anderen komplett klein geschrieben werden).
- die "struct:*" sollten auch alle die selbe farbe bekommen. möglichst nicht rot - vielleicht den blauton der jetzigen "documentation"?

**Comment by AMatutat** [comment]
https://github.com/Programmiermethoden/Dungeon/issues/586#issuecomment-1534290838 mit den Anmerkungen von Carsten ist umgesetzt.


@cagix Du hast damals das Bounty-Label in deinen Vorlesungsunterlagen verlinkt. Da das Label rausfliegt, muss der Link angepasst werden, richtig? Ich habe das Label erstmal nicht gelöscht, damit der Link für die Studis nicht explodiert. Wenn du den Link angepasst hast, kannst du das löschen. 
Danach kann aus meiner Sicht hier zu.

**Comment by cagix** [comment]
> [#586 (comment)](https://github.com/Programmiermethoden/Dungeon/issues/586#issuecomment-1534290838) mit den Anmerkungen von Carsten ist umgesetzt.
> 
> @cagix Du hast damals das Bounty-Label in deinen Vorlesungsunterlagen verlinkt. Da das Label rausfliegt, muss der Link angepasst werden, richtig? Ich habe das Label erstmal nicht gelöscht, damit der Link für die Studis nicht explodiert. Wenn du den Link angepasst hast, kannst du das löschen. Danach kann aus meiner Sicht hier zu.

@AMatutat Ich hatte sogar auch auf die "5P"- und "10P"-Label verlinkt gehabt...

Ich habe die Suchanfragen aktualisiert und hier das alte "Bounty"-Label entfernt. Wenn ich das richtig verstanden habe, kann ich jetzt hier das Licht ausmachen?
