### ISSUE TITLE
[Game] Cleanup TextureHandler

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#587]
Der `graphic.textures.TextureHandler` hat im Laufe der Zeit offenbar einige Veränderungen bekommen/durchgemacht, ohne dass nochmal wer das Ding von außen als Ganzes betrachtet hat. Dieses Issue ist angeregt durch #560 und die dortigen Versuche, die Probleme mit den Mehrfachreferenzen ad hoc in den Griff zu kriegen, ohne über das Gesamt-Konzept nachdenken zu wollen.

In einer `Map<String, Set<FileHandle>> pathMap` werden offenbar zu einem Pfad (als String) alle darunter befindlichen Dateien (als GDX-FileHandle?!) gespeichert. 

Die für den User gedachte öffentliche API besteht aus `TextureHandler getInstance()` und `List<String> getTexturePaths(String regex)`. Dabei konvertieren wir unsere internen GDX-FileHandles nach `String`, und die Kunden machen aus den Strings wieder `File` oder `Path`.

Fragen:
- Warum speichern wir intern überhaupt GDX-FileHandles, wo doch die gesamte öffentliche Schnittstelle `String` ist?
- Wieso arbeiten wir überhaupt mit GDX-Datentypen hier? Alles, was wir machen, ist doch an einer bestimmten Stelle im Dateisystem nach Dateien zu suchen. Das kriegt man auch mit `java.nio.file` hin und wir würden uns eine nicht nötige Abhängigkeit zu libGDX ersparen.
- Warum arbeiten wir in der API String-basiert (wie in PHP)? Warum arbeiten wir nicht mit richtigen Java-Typen wie `File` oder `Path`?
- In #560 wird ein Magic Number eingeführt ("4"), der auf der aktuellen Projektstruktur beruht. Dafür sollte in `Game` oder einer anderen geeigneten Stelle eine Konfiguration geschaffen werden und in #560 genutzt werden.

Wie soll ich das meinen Studis erklären? Bitte umgehend Re-Design!

**Comment by tgrothe** [comment]
- Die Klasse DesktopLauncher hatte quasi keinen richtigen Sinn, ich hab sie entfernt und die dazugehörige Testklasse auch
- Game hat einen private Konstruktor bekommen, der diese Funktionen/Aufgaben übernehmen kann
- Der TexturHandler wird nun ganz am Anfang erzeugt, das übrige Setup muss aber erst im ersten Render-Vorgang geschehen
- Die Tests in GameTest müssten bitte überarbeitet werden, ebenso der dispose-Test in LibgdxSetupTest
- (Der `private static TextureHandler handler;` könnte nicht final sein)
- Für die Kunden sollte sich die API eigentlich nicht geändert haben, bis auf den neuen TextureHandler-Aufruf

_Originally posted by @tgrothe in https://github.com/Programmiermethoden/Dungeon/issues/560#issuecomment-1532741048_

**Comment by tgrothe** [comment]
Ein Beispiel wäre hier https://github.com/tgrothe/Dungeon/tree/texturehandler_fix_before_revert_2

**Comment by cagix** [comment]
Siehe https://github.com/Programmiermethoden/Dungeon/pull/560/files#r1184735167: 

Der `TextureHandler` wird in `Game#setup` "aufgerufen", d.h. dort zum ersten Mal initialisiert. Da wir dabei eine _checked exception_ werfen könnten, muss man in `Game#setup` damit umgehen. Der aktuelle Workaround ist, die Exception in eine Runtime-Exception zu konvertieren und weiter nach oben zu reichen. 

- Frage 1: Ist das wirklich sinnvoll? Sollte man stattdessen in `Game#setup` beim Auftreten einer `IOException` nochmal loggen und dann direkt aussteigen?
- Frage 2: `Game#render` prüft in **jedem Frame**, ob ein Setup gemacht werden muss?! Wenn `Game#setup` die _checked exception_ (also die `IOException`) weitergeben würde, dann müsste sich `Game#render` darum kümmern. Das erscheint irgendwie unsinnig; ein Weiterleiten geht nicht wg. der Ableitung von `ScreenAdapter`... Wäre es nicht sinnvoller, man macht explizit ein Setup für das Game (also einmalig) und steigt dann in die Game-Loop ein, ohne dort immer wieder zu prüfen, ob man vielleicht doch nochmal ein Setup machen möchte?

**Comment by AMatutat** [comment]
Ich will hier auchnochmal hierauf verweisen.
https://github.com/Programmiermethoden/Dungeon/pull/560/files/9eeb87de2b947c253b468bd7f01a68d1ec4d62e6#r1181180022
