### ISSUE TITLE
[Publikationen] Analyse der Ablehnung des INFOS-Beitrags und Ableiten von Erkenntnissen für das zukünftige Vorgehen

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#601]
Der Beitrag zur INFOS 2023 wurde abgelehnt, die Gutachten findet ihr in https://github.com/Programmiermethoden/2022-freiraum-dungeon/blob/master/09_publikationen/infos2023/ABLEHUNG%20INFOS%202023.pdf 

Bitte nehmt euch 60..90 Minuten und analysiert gemeinsam das Paper zusammen mit den Gutachten und dem damaligen Vorgehen bei der Erstellung und leitet konkrete Maßnahmen für die restliche Laufzeit ab. 

Wir können dann im nächsten Meeting darüber diskutieren.

Wir sind bisher nur auf einfachen Treffen gewesen, aber noch nicht auf einer richtigen Konferenz, und wir sollten zu allen drei Bereichen (Dungeon, DSL, D2A) dringend noch was unterbringen oder zumindest soweit vorbereiten, dass wir es noch nach Projektende einreichen können.

**Comment by AMatutat** [comment]
> ![image](https://user-images.githubusercontent.com/32962412/236153737-5a9ec8de-0c65-48f1-b4b4-faa51e02be61.png)

Mein Kopf schwankt gerade zwischen "Das ist extremes Buzzword Bingo" und "Könnte man das tatsächlich nutzen, um Manipulation der Vorgaben zu verhindern?"

Anyway, die Gutachten sind relativ verheerend (und nach dem ersten Lesen auch nachvollziehbar).
- Kritik an der "handwerklichen" Gestaltung der Arbeit ist immer ärgerlich, da leicht vermeidbar. Ich würde das auf die Unerfahrenheit von uns WiMis schieben. Ist aber dennoch etwas, das sich einfach mit mehr Sorgfalt und Ruhe vermeiden lässt.
- Thema Quellen und Literatur: Ich glaube, da müssen wir projektweit denken. @cagix und @bcg7, ihr werdet vermutlich mehr zu dem Thema im Kopf haben als ich, aber besonders die Frage nach der Legitimation unserer Arbeit und der Bestätigung der Grundprämisse "Gamification erhöht die Motivation" sollten wir mit Verweisen irgendwo zentral belegen. Der andere Punkt ist "die Welt da draußen". Wir gucken zwar immer gerne etwas links und rechts und sagen dann "Guck mal, das ist doch auch nett", aber dabei bleibt es meistens und wir graben uns weiter in unsere Ideen etc. ein. Wir sollten irgendwo zentral eine Liste mit anderen Projekten führen und jeweils eine kurze Zusammenfassung. "Was machen die?" "Was machen die besser als wir?" "Was machen die schlechter als wir?" Wir müssen ja nicht unbedingt etwas von deren Ideen umsetzen, aber durch so ein zentrales Register können wir für jede Publikation relativ flott darauf zugreifen und verweisen.

Ich glaube, ein großes Problem, das ausschlaggebend für das Ergebnis war, war die falsche Priorisierung der ganzen Geschichte "Publikation". Das ist halt kein "Nebenbei"-Thema. Da muss ich besonders mir selbst an die Nase packen. 

*Anmerkung: Ich werde das Kommentar vermutlich noch ein paar Mal erweitern. Der Kopf arbeitet das im Hintergrund weiter.*

**Comment by cagix** [comment]
@AMatutat Nimm es nicht zu schwer! Sowas passiert auch bei richtig sorgfältig ausgearbeiteten Publikationen schnell (siehe mein Rant über die Gutachter). Dennoch, wir müssen uns sichtbar machen und entsprechend sollten wir Schlüsse ziehen.

**Comment by AMatutat** [comment]
Stichpunkte aus unserer Diskussion: 
- Weniger Themen, fokussieren auf Dungeon, DSL oder D2G
    - Beim Dungeon: Mehr hervorhebe, dass das besonders ist, das wir "einfache Inputs" in unterschiedliche Spielaufgaben umwandeln. Und wir ein richtiges Spiel sind (nicht auf Luftballons schießen)  
- Puplikationen fallen im Tagesgeschäft irgendwie hinten weg -> Zeit nehmen und (persönliche) Prioritäten klären
- Quellen -> Zentrales Quellenverzeichnis Aufstellen (wiki).

**Comment by cagix** [comment]
Klingt alles sinnvoll. Wie kriegen wir das so umgesetzt, dass am Ende tatsächlich noch ein paar Paper rauspurzeln? Im Prinzip müsste jeder für seinen Bereich noch einmal nach möglichen Konferenzen recherchieren, die dann bewerten und noch 1..2 Paper produzieren und einreichen.

> Arbeiten über Overleaf, damit lässt sich besser verteilt zusammen arbeiten

Im Prinzip ja. In der Praxis weiss ich nicht :)

Die Hochschule tut sich sehr schwer damit, eine HS-Lizenz zu beschaffen (habe jetzt schon mehrfach an verschiedenen Stellen nachgefragt). Angeblich ein Datenschutzthema, aber andere Hochschulen in D sind ja angeblich bereits Kunden und müssten das DS-Problem ja auch haben bzw. gelöst haben. 

In den freien Accounts kann man nur begrenzt sharen/zusammenarbeiten (wenn ich das richtig in Erinnerung habe).

Und am Ende des Tages habe ich bisher zu oft erlebt, dass die Dateien nicht persistiert/versioniert wurden. 

Insofern würde ich tatsächlich erstmal mit Markdown hier im Repo losrennen und einen Workflow mit Makefile und Pandoc und LaTeX plus dem jeweiligen Styletemplate definieren. So hat man immer das aktuelle PDF und auch die Sourcen im Repo. Nur das direkte gemeinsame Editieren fällt weg.

**Comment by AMatutat** [comment]
> Wie kriegen wir das so umgesetzt, dass am Ende tatsächlich noch ein paar Paper rauspurzeln? 

Für mich leiten sich daraus 3 Schritte für jeden ab:
1. Raussuchen von passenden Konferenzen o.ä
    a. @malt-r : DSL spezifisch
    b. @AKirsch1 Auto-Grading spezifisch
    c. @AMatutat Gamification und Didaktik
2. Raussuchen passender Quellen und eintragen in ein zentrales (Wiki) Quellenverzeichnis mit kurzer Zusammenfassung. Wenn da jeder 3-4 gute Quellen findet, dann haben wir ja schon ein kleinen Pool. 
3. Paper schreiben, Reviews lassen und einreichen

**Comment by cagix** [comment]
> Ich fürchte nur, das unsere didaktische Expertise für sowas zu gering ist, aber versuchen schadet ja nicht.

Das ist der Spirit :) ... Man könnte natürlich auch befürchten, dass die Akzeptanzwahrscheinlichkeit dadurch nach unten gedrückt wird.

**Comment by cagix** [comment]
> Raussuchen passender Quellen und eintragen in ein zentrales (Wiki) Quellenverzeichnis mit kurzer Zusammenfassung. 

@AKirsch1 @AMatutat @malt-r Wiki finde ich erstmal gut zum Sammeln. 

Damit man damit ordentlich arbeiten kann, brauchen wir aber ein maschinenlesbares Format wie Bibtex (kann man beispielsweise gut mit [JabRef](https://github.com/JabRef/jabref) verwalten) oder JSON/YAML (vgl. https://pandoc.org/MANUAL.html#specifying-bibliographic-data). D.h. mittelfristig wäre eine `*.bib`-Datei im Repo nicht schlecht.

Wie wollen wir damit umgehen? Sollen wir diese Formate dann gleich so im WIKI anlegen? Oder erstmal sammeln und dann alles gemeinsam konvertieren?

**Comment by AMatutat** [comment]
> Wie wollen wir damit umgehen? Sollen wir diese Formate dann gleich so im WIKI anlegen? Oder erstmal sammeln und dann alles gemeinsam konvertieren?

Ich würde erstmal sammeln und dann konvertieren. Danach können wir ja mit PRs das Ding erweitern. Aber wenn jetzt alle auf einmal rumlaufen, seh ich das Chaos schon kommen

**Comment by AMatutat** [comment]
@cagix @malt-r @AKirsch1 wie wollen wir mit diesen Issue weitermachen?
Die Analyse für die Ablehnung haben wir gemacht und haben uns auch Handlungsschritte abgeleitet.

Dann kam noch die Idee auf, ein Zentrales Quellen-bibfile zu erstellen. Irgendwie haben wir das aber nicht weiter verfolgt.
Wollen wir das nochmal aktiv aufnehmen, oder eher separate Related-Work Dokumentationen (wie cagix https://github.com/Programmiermethoden/2022-freiraum-dungeon/issues/74#issuecomment-1581066960 vorgeschlagen hat) anfertigen?

**Comment by cagix** [comment]
> @cagix @malt-r @AKirsch1 wie wollen wir mit diesen Issue weitermachen? Die Analyse für die Ablehnung haben wir gemacht und haben uns auch Handlungsschritte abgeleitet.
> 
> Dann kam noch die Idee auf, ein Zentrales Quellen-bibfile zu erstellen. Irgendwie haben wir das aber nicht weiter verfolgt. Wollen wir das nochmal aktiv aufnehmen, oder eher separate Related-Work Dokumentationen (wie cagix [Programmiermethoden/2022-freiraum-dungeon#74 (comment)](https://github.com/Programmiermethoden/2022-freiraum-dungeon/issues/74#issuecomment-1581066960) vorgeschlagen hat) anfertigen?

@AMatutat Ich denke, dieses Ticket kann zu. Die Analyse ist gemacht worden, weitere Paper (zumindest für Dungeon und für D2G) sind auf dem Weg bzw. bereits eingereicht. Und für die Analyse vergleichbarer Arbeiten gibt es meinen Vorschlag, jeweils im Dungeon- und im D2G-Repo in `docs/related_work/` pro Arbeit eine Markdown-Datei anzulegen mit Metadaten und den Analyseergebnissen (die aktuell in irgendwelchen Tickets/Kommentaren bzw. teilweise im Wiki stehen) und im Root-Verzeichnis der Repos jeweils eine .bib-Datei zu pflegen. Dann haben wir die relevanten Informationen zusammen und an der richtigen Stelle. Und wir sind auch unabhängig von GitHub, weil der Kram im Repo liegt (und nicht separat in Tickets/Wiki).

**Comment by cagix** [comment]
> @cagix @malt-r @AKirsch1 wie wollen wir mit diesen Issue weitermachen? Die Analyse für die Ablehnung haben wir gemacht und haben uns auch Handlungsschritte abgeleitet.
> 
> Dann kam noch die Idee auf, ein Zentrales Quellen-bibfile zu erstellen. Irgendwie haben wir das aber nicht weiter verfolgt. Wollen wir das nochmal aktiv aufnehmen, oder eher separate Related-Work Dokumentationen (wie cagix [Programmiermethoden/2022-freiraum-dungeon#74 (comment)](https://github.com/Programmiermethoden/2022-freiraum-dungeon/issues/74#issuecomment-1581066960) vorgeschlagen hat) anfertigen?

@AMatutat Ich denke, dieses Ticket kannst Du schließen. Die Analyse ist gemacht worden, weitere Paper (zumindest für Dungeon und für D2G) sind auf dem Weg bzw. bereits eingereicht. Und für die Analyse vergleichbarer Arbeiten gibt es meinen Vorschlag, jeweils im Dungeon- und im D2G-Repo in `docs/related_work/` pro Arbeit eine Markdown-Datei anzulegen mit Metadaten und den Analyseergebnissen (die aktuell in irgendwelchen Tickets/Kommentaren bzw. teilweise im Wiki stehen) und im Root-Verzeichnis der Repos jeweils eine .bib-Datei zu pflegen. Dann haben wir die relevanten Informationen zusammen und an der richtigen Stelle. Und wir sind auch unabhängig von GitHub, weil der Kram im Repo liegt (und nicht separat in Tickets/Wiki).

=> https://github.com/Programmiermethoden/2022-freiraum-dungeon/issues/166
