### ISSUE TITLE
[GAME] Dokumentation

### ISSUE THREAD

**Issue by dkirshner** [Programmiermethoden/Dungeon#603]
Für folgende Klassen im Dungeon muss noch die Dokumentation umgesetzt werden. 
Jede Klasse bekommt einen eigene PR, welcher dieses Issue referenziert und nach dem der PR gemerged wurde, soll die Klasse hier abgehackt werden:

- [ ] ConfigKey.java
- [ ] Configuration.java
- [ ] ItemConfig.java
- [ ] KeyboardConfig.java
- [ ] ConfigBooleanValue.java
- [ ] ConfigCharValue.java
- [ ] ConfigDoubleValue.java
- [ ] ConfigEnumValue.java
- [ ] ConfigFloatValue.java
- [ ] ConfigIntValue.java
- [ ] ConfigStringValue.java
- [ ] ConfigValue.java
- [ ] AbstractController.java 
- [ ] ControllerLayer.java 
- [ ] ScreenController.java
- [ ] SystemController.java
- [ ] AnimationComponent.java
- [ ] Component.java
- [ ] DropLoot.java
- [ ] HealthComponent.java
- [ ] HitboxComponent.java
- [ ] IInteraction.java 
- [ ] IOnDeathFunction.java 
- [ ] InteractionComponent.java
- [ ] InventoryComponent.java
- [ ] ItemComponent.java
- [ ] M issingComponentException.java
- [ ] PlayableComponent.java
- [ ] PositionComponent.java
- [ ] VelocityComponent.java
- [ ] AIComponent.java
- [ ] AITools.java
- [ ] CollideAI.java
- [ ] IFightAI.java 
- [ ] MeleeAI.java
- [ ] IIdleAI.java 
- [ ] PatrouilleWalk.java
- [ ] RadiusWalk.java
- [ ] StaticRadiusWalk.java
- [ ] ITransition.java 
- [ ] RangeTransition.java
- [ ] SelfDefendTransition.java
- [ ] ICollide.java 
- [ ] DamageProjectileSkill.java 
- [ ] FireballSkill.java
- [ ] ISkillFunction.java 
- [ ] ITargetSelection.java 
- [ ] ProjectileComponent.java
- [ ] Skill.java
- [ ] SkillComponent.java
- [ ] SkillTools.java
- [ ] DamageModifier.java
- [ ] StatsComponent.java
- [ ] ILevelUp.java 
- [ ] XPComponent.java
- [ ] Damage.java 
- [ ] DamageType.java 
- [ ] Chest.java
- [ ] Entity.java
- [ ] Hero.java
- [ ] IOnCollect.java 
- [ ] IOnDrop.java 
- [ ] IOnUse.java 
- [ ] ItemData.java
- [ ] ItemDataGenerator.java
- [ ] ItemType.java 
- [ ] WorldItemBuilder.java
- [ ] AISystem.java
- [ ] CollisionSystem.java
- [ ] DrawSystem.java
- [ ] ECS_System.java 
- [ ] HealthSystem.java
- [ ] PlayerSystem.java
- [ ] ProjectileSystem.java
- [ ] SkillSystem.java
- [ ] VelocitySystem.java
- [ ] XPSystem.java
- [ ] ControlPointReachable.java
- [ ] IReachable.java 
- [ ] InteractionData.java 
- [ ] InteractionTool.java
- [ ] Animation.java
- [ ] DungeonCamera.java
- [ ] Painter.java
- [ ] PainterConfig.java
- [ ] FontBuilder.java
- [ ] LabelStyleBuilder.java
- [ ] ScreenButton.java
- [ ] ScreenImage.java
- [ ] ScreenInput.java
- [ ] ScreenText.java
- [ ] TextButtonListener.java 
- [ ] TextButtonStyleBuilder.java
- [ ] TextFieldStyleBuilder.java
- [ ] TextureHandler.java
- [ ] TextureMap.java
- [ ] IOnLevelLoader.java 
- [ ] LevelAPI.java
- [ ] ILevel.java 
- [ ] IPathable.java 
- [ ] ITileable.java 
- [ ] TileLevel.java
- [ ] TileConnection.java
- [ ] TileHeuristic.java
- [ ] DoorTile.java
- [ ] ExitTile.java
- [ ] FloorTile.java
- [ ] HoleTile.java
- [ ] SkipTile.java
- [ ] Tile.java 
- [ ] TileFactory.java
- [ ] WallTile.java
- [ ] IGenerator.java 
- [ ] NoiseArea.java
- [ ] NoiseAreaValues.java
- [ ] PerlinNoise.java
- [ ] PerlinNoiseGenerator.java
- [ ] WallGenerator.java
- [ ] RandomWalkGenerator.java
- [ ] DoorDirection.java 
- [ ] GraphLevel.java
- [ ] GraphLevelGenerator.java
- [ ] LevelNode.java
- [ ] IRoom.java 
- [ ] Room.java
- [ ] RoomGenerator.java
- [ ] Coordinate.java
- [ ] DesignLabel.java 
- [ ] LevelElement.java 
- [ ] LevelSize.java 
- [ ] TileTextureFactory.java
- [ ] CustomLogLevel.java
- [ ] LoggerConfig.java
- [ ] DesktopLauncher.java
- [ ] Game.java
- [ ] LibgdxSetup.java
- [ ] Constants.java
- [ ] Point.java

**Comment by AMatutat** [comment]
wir haben uns darauf geeinigt das über die javadoc abzubilden.
Dafür gibt es eigene Issues.
Strukturen werden in `/doc` Dokumentiert, auch dafür gibt es einzelne Issues
