### ISSUE TITLE
[GAME] Cleancode

### ISSUE THREAD

**Issue by dkirshner** [Programmiermethoden/Dungeon#605]
Für folgende Klassen im Dungeon muss noch Cleancode umgesetzt werden. 
Jede Klasse bekommt einen eigene PR, welcher dieses Issue referenziert und nach dem der PR gemerged wurde, 
soll die Klasse hier abgehackt werden:

<details> 
<summary> Components </summary> 

- [x] InteractionComponent.java
- [x] InventoryComponent.java
- [x] AnimationComponent.java
- [x] HealthComponent.java
- [x] HitboxComponent.java
- [x] InteractionComponent.java
- [x] InventoryComponent.java
- [x] ItemComponent.java
- [x] M issingComponentException.java
- [x] PlayableComponent.java
- [x] PositionComponent.java
- [x] VelocityComponent.java
- [ ] AIComponent.java
- [ ] Component.java
- [ ] ProjectileComponent.java
- [ ] StatsComponent.java
- [ ] XPComponent.java
</details>

<details> 
<summary> System </summary> 

- [ ] AISystem.java
- [ ] CollisionSystem.java
- [ ] DrawSystem.java
- [ ] ECS_System.java 
- [ ] HealthSystem.java
- [ ] PlayerSystem.java
- [ ] ProjectileSystem.java
- [ ] SkillSystem.java
- [ ] VelocitySystem.java
- [ ] XPSystem.java
- [ ] LevelSystem.java

</details>

<details> 
<summary> Skills and Damage </summary> 

- [ ] FireballSkill.java
- [ ] Skill.java
- [ ] SkillTools.java
- [ ] DamageModifier.java
- [ ] Damage.java 
- [ ] DamageType.java 

</details>

<details> 
<summary> Config </summary> 
- [ ] ConfigKey.java
- [ ] Configuration.java
- [ ] ItemConfig.java
- [ ] KeyboardConfig.java
- [ ] ConfigBooleanValue.java
- [ ] ConfigCharValue.java
- [ ] ConfigDoubleValue.java
- [ ] ConfigEnumValue.java
- [ ] ConfigFloatValue.java
- [ ] ConfigIntValue.java
- [ ] ConfigStringValue.java
- [ ] ConfigValue.java

</details>

<details> 
<summary> AI </summary> 

- [ ] AITools.java
- [ ] CollideAI.java
- [ ] MeleeAI.java
- [ ] PatrouilleWalk.java
- [ ] RadiusWalk.java
- [ ] StaticRadiusWalk.java
- [ ] RangeTransition.java
- [ ] SelfDefendTransition.java
- [ ] DamageProjectileSkill.java 
- [ ] ControlPointReachable.java

</details>

<details> 
<summary> Other </summary> 

- [ ] Coordinate.java
- [ ] Constants.java
- [ ] Point.java
- [ ] CustomLogLevel.java
- [ ] LoggerConfig.java
- [ ] Game.java
- [ ] Entity.java
- [ ] DropLoot.java
- [ ] ItemData.java
- [ ] ItemDataGenerator.java
- [ ] ItemType.java 
- [ ] WorldItemBuilder.java
- [ ] InteractionData.java 
- [ ] InteractionTool.java
- [ ] Animation.java
- [ ] Painter
- [ ] PainterConfig.java

</details> 
<details> 
<summary> Level </summary> 

- [ ] DesignLabel.java 
- [ ] LevelElement.java 
- [ ] LevelSize.java 
- [ ] TileTextureFactory.java
- [ ] PerlinNoiseGenerator.java
- [ ] WallGenerator.java
- [ ] RandomWalkGenerator.java
- [ ] DoorDirection.java 
- [ ] GraphLevel.java
- [ ] GraphLevelGenerator.java
- [ ] LevelNode.java
- [ ] IRoom.java 
- [ ] Room.java
- [ ] RoomGenerator.java
- [ ] ILevel.java 
- [ ] IPathable.java 
- [ ] ITileable.java 
- [ ] TileLevel.java
- [ ] TileConnection.java
- [ ] TileHeuristic.java
- [ ] DoorTile.java
- [ ] ExitTile.java
- [ ] FloorTile.java
- [ ] HoleTile.java
- [ ] SkipTile.java
- [ ] Tile.java 
- [ ] TileFactory.java
- [ ] WallTile.java
- [ ] IGenerator.java 
- [ ] NoiseArea.java
- [ ] NoiseAreaValues.java
- [ ] PerlinNoise.java

</details>

**Comment by AMatutat** [comment]
sammel issue das realistisch gesehen nicht gepflegt wird.
