### ISSUE TITLE
[Game] Keine Animationen für Hoch/Runter in AnimationComponent

### ISSUE THREAD

**Issue by fwatermann** [Programmiermethoden/Dungeon#606]
Das wirft grad die Frage auf, warum es kein "oben" und "unten" gibt? In die Richtungen kann man ja auch gehen? (Ist vermutlich aber kein Thema für diesen PR, sondern ein neues Issue.)

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/574#discussion_r1182771767_
           
---

Für unsere Helden und Monater bräuchte es daher noch je eine Animation für "hoch" und eine Animation für "runter".

**Comment by AMatutat** [comment]
@Lena241 das ist das Issue zu #790
