### ISSUE TITLE
[D2G] Recherche zu D2G-Alternativen

### ISSUE THREAD

**Issue by AKirsch1** [Programmiermethoden/Dungeon#609]
Basierend auf den Rückmeldungen vom abgelehnten Paper habe ich ein wenig recherchiert und bin auf folgendes gestoßen:
https://www.waxmann.com/automatisiertebewertung/

Was könnte man aus deren Erfahrungen und Umsetzungen für unser D2G nutzen?

@cagix @AMatutat Inwiefern habt ihr euch mit den dort aufgezählten automatischen Bewertungssystemen schon auseinandergesetzt?

**Comment by AMatutat** [comment]
Ich hatte mich mal mit einem Team von einer anderen Universität getroffen, welche Webbasiert ganze Programmierkurse durchführen wollten. 
Die hatten sich dafür auch eine schicke Webseite gebastelt (ich glaube die war auch schon im Einsatz) und hatten auch einen Autograder verwendet.

Ich habe aber keine Ahnung mehr wie der hieß.... ich durchsuche mal bei Zeiten meine Mails. Als ich aber "JACK" gelesen hatte, klingelte irgendetwas. Vielleicht war es das.

**Comment by AKirsch1** [comment]
Klingelt es stärker, wenn ich dir sage, dass JACK von der Uni Duisburg-Essen ist?

**Comment by AMatutat** [comment]
Hab die Mail gefunden und an dich weitergeleitet. 
Will hier jetzt kein komplette Mail Posten: 

Aber die Eckdaten vielleicht: 
- Hasso-Plattner-Institut an der Universität Potsdam 
- Im Gespräch schien mir das CodeHarbor [4] ihr großes Ding zu sein/werden.  Ich hab das als eine Art OER Aufgaben und Bewertung im Kopf abgespeichert.

Und derren Link-Liste:
[1]: https://open.hpi.de/
[2]: https://github.com/openHPI/codeocean
[3]: https://bildungsraum.de/
[4]: https://github.com/openHPI/codeharbor, https://codeharbor.openhpi.de/
[5]: https://github.com/ProFormA/proformaxml
[6]: https://cssplice.github.io/SIGCSE21/proc/SPLICE2021_SIGCSE_paper_13.pdf

**Comment by AKirsch1** [comment]
Zu dem oberen Link hier mal ein Vergleich der in dem Buch beschriebenen AutoGrader: https://www.waxmann.com/?eID=texte&pdf=3606Kapitel17.pdf&typ=zusatztext

**Comment by AKirsch1** [comment]
Da das Buch mittlerweile im [zentralen Quellenverzeichnis](https://github.com/Programmiermethoden/Dungeon/wiki/Zentrales-Quellenverzeichnis) eingetragen ist, schließe ich das Issue hier.
