### ISSUE TITLE
[Game] DamageProjectileSkill umbenennen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#611]
Die Klasse `DamageProjectileSkill` ist eine `ISkillFunction` der name suggeriert aber das sich dabei um einen Skill handelt. 
Der name muss entsprechend angepasst werden.

- `DamageProjectileSkillFunction`? (Ist irgendwie echt lang

**Comment by cagix** [comment]
`DamageProjectile` würde für mich völlig ausreichen :)

---

Somewhat related: Die `ISkillFunction` ist letzlich nur ein [`Consumer`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/function/Consumer.html) (aus `java.util.function`). Sollten wir das einfach damit ersetzen? Das würde ein separates Interface sparen, für das man einen guten Namen und eine Doku braucht und was 1:1 identisch zu bereits existierenden Standardinterfaces ist?

**Comment by AMatutat** [comment]
> Somewhat related: Die ISkillFunction ist letzlich nur ein [Consumer](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/function/Consumer.html) (aus java.util.function). Sollten wir das einfach damit ersetzen? Das würde ein separates Interface sparen, für das man einen guten Namen und eine Doku braucht und was 1:1 identisch zu bereits existierenden Standardinterfaces ist?

#511 

> @AMatutat DamageProjectile würde für mich völlig ausreichen :)

Jetzt muss ich aber sagen `DamageProjectile` klingt für mich nach einer Entität. Das Ding macht zwar eine Entität, ist aber keine.

**Comment by cagix** [comment]
> Jetzt muss ich aber sagen DamageProjectile klingt für mich nach einer Entität. Das Ding macht zwar eine Entität, ist aber keine.

Aber es ist halt auch kein Skill. 

Ich glaube, aus Kundensicht (hatte heute lange Diskussionen dazu im Praktikum) könnte man die durch DamageProjectile erzeugte Entität schon irgendwie als "DamageProjectile" betrachten (von ganz weit weg aus gesehen).

Wenn man beim Skill bleiben möchte, muss noch ein Verb mit her. Also sowas wie `LaunchDamageProjektile`, was dann auch der SkillFunction mehr entspricht.
