### ISSUE TITLE
[Game] Consumer-Interface anstelle von eigenem Interface ISKillFunction nutzen?

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#613]
@AMatutat `DamageProjectile` würde für mich völlig ausreichen :)

---

Somewhat related: Die `ISkillFunction` ist letzlich nur ein [`Consumer`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/function/Consumer.html) (aus `java.util.function`). Sollten wir das einfach damit ersetzen? Das würde ein separates Interface sparen, für das man einen guten Namen und eine Doku braucht und was 1:1 identisch zu bereits existierenden Standardinterfaces ist?

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/issues/611#issuecomment-1535904851_

**Comment by cagix** [comment]
@AMatutat Das ist immer noch das Strategie-Pattern, daran möchte ich gar nicht rütteln! 

Meine Frage war nur, ob wir wirklich ein eigenes (funktionales) Interface definieren müssen, wo es im JDK für genau diese Zwecke schon was gibt. "Consumer" heisst es nur, weil die Methode einen Parameter bekommt und nichts zurück liefert, also das Argument "konsumiert".

**Comment by AMatutat** [comment]
@Lena241 schau dir das mal an. Klingt sinnvoll und sparrt (dir) dokumentazinsarbeit

**Comment by cagix** [comment]
@AMatutat @Lena241 Das betrifft durchaus noch mehr Interfaces :) ... `ITargetSelection` ist beispielsweise einfach ein `Supplier<Point>`.

**Comment by AMatutat** [comment]
Im Grunde ist das doch #578, oder?
