### ISSUE TITLE
[Game] BuffComponent und System

### ISSUE THREAD

**Issue by tgrothe** [Programmiermethoden/Dungeon#614]
Es kam die Frage auf, ob man die Stats unter

[DamageModifier.java](https://github.com/Programmiermethoden/Dungeon/blob/master/game/src/ecs/components/stats/DamageModifier.java) (#450)
[StatsComponent.java](https://github.com/Programmiermethoden/Dungeon/blob/master/game/src/ecs/components/stats/StatsComponent.java) (#450)

(es gibt noch keine Doc dazu (#603)) zurücksetzen könnte. Soweit ich sehe, gibt es diese zusätzliche Funktionalität noch nicht.

**Comment by tgrothe** [comment]
@cagix @AMatutat: Hier bedarf es, vermute ich, eure Aufmerksamkeit.

Wäre so ein Feature sinnvoll? Oder ließe sich so eine Eigenschaft auch i-wie anders bekommen?

**Comment by AMatutat** [comment]
Bin mir nicht sicher, ob ich "zurücksetzten" richtig verstehe, aber könnte man das Component nicht einfach aus der Entität entfernen und ein neues `StatsComponent` hinzufügen?

**Comment by tgrothe** [comment]
@AMatutat Ich bin mir auch nicht genau sicher, wie das gemeint war. Das war eine Studi-Frage. Vielleicht kann der Betreffende hierzu genaueres schreiben.

Ich denke, es ging um neue, zusätzliche Methoden, um die Werte der StatsComponent nach einiger Zeit (zurück)setzen zu können (und um das Speichern des Initialwerts).

**Comment by Pascal378** [comment]
Hey,
ich war der Studi mit o.g. Frage. Wie bereits richtig erkannt wurde ging es mir da um eine Art Buff System. Ich habe versucht mir Gedanken darum zu machen wie mehrere Statuseffekte die über verschiedene Zeiten hinweg die selben Werte wie z.B. Health manipulieren korrekt abgehandelt werden können. 

Habe den StatComponent gefunden, bisher aber nicht wirklich feststellen können wie genau er funktioniert und was er tut. Aktuell wirkt er sich glaube ich ausschließlich auf den Schaden aus wenn ich das richtig sehe.

Sollen die Stats generell irgendwann mal alle Stats verwalten die sich auf verschiedene Werte auswirken wie in anderen Rollenspielen z.B. die Ausdauer auch die Lebenspunkte erhöht, die Beweglichkeit z.B. die Geschwindigkeit?

Für die Aufgabe in meinem derzeitigen Zyklus habe ich ein Workaround gefunden, das ist aber nicht schön und auch nicht sehr langfristig gedacht.

**Comment by AMatutat** [comment]
Hmm, okay, ich verstehe.

Ohne jetzt tiefgründig darüber nachgedacht zu haben, würde ich in diesem Fall das `StatsComponent` als Basis nehmen und dort so etwas wie eine Collection von `Buff`-Objekten speichern. 
So ein `Buff` weiß dann, wie lange er hält und welchen Wert er verändert (dafür würde sich vermutlich ein Enum eignen). 

Dann müssen die Buffs noch mit den richtigen Werten verrechnet werden, dafür sehe ich zwei Möglichkeiten: 

1. Ein eigenes `BuffSystem`/`StatsSystem`, welches über die `Buff`-Collection iteriert und dann die Werte in den anderen Components setzt (z.B. im `HealthComponent`). Dort könnte man dann auch den "Cooldown" der Buffs runtertickern lassen.
2. Die einzelnen Systeme prüfen, ob es einen Buff gibt, der zugehörige Werte manipuliert. So könnte das `HealthSystem` prüfen, ob die betrachtete Entität ein `StatsComponent` hat und sich dort ein Buff mit dem `HEALTH` Enum-Wert befindet. 
Dann müsste man sich nur überlegen, wie man den "Cooldown" der Buffs implementiert.

**Comment by tgrothe** [comment]
Aber dann würde ich es auch Buff(System) oder StatsModification(System) nennen, ich wusste nämlich erst gar nicht, dass es um einen Buff/Turbo und das langsame Abklingen/Cooldown des Buffs ging...

Möglichkeit 1. klingt gut. :) Zusätzlich könnte noch eine "Abklingfunktion" als Argument übergeben werden.

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
