### ISSUE TITLE
[Game] Create round single choice buttons for Quiz GUI

### ISSUE THREAD

**Issue by dkirshner** [Programmiermethoden/Dungeon#615]
Die Single Choice Fragen in der Quiz GUI werden trotz des Skins nicht mit Radio Buttons, sondern mit rechteckigen Checkboxen dargestellt.
Hier geht es nur um das optische.

**Comment by AMatutat** [comment]
@AHeinisch ich glaube der Bug hat sich wieder Eigenschlichen, bzw der fix ist im laufe von #702 verloren gegangen.
Kannst du dich mit @dkirshner nochmal ran setzen?
