### ISSUE TITLE
[GAME] Questlog

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#616]
Dem Spieler sollte ein Questlog zur Verfügung gestellt werden. 
Das Questlog zeigt an, welche Aufgaben (und Unteraufgaben) zu erledigen sind.
Die Aufgabenbeschreibung sowie die Struktur kommt aus der DSL und dem hinterlegten Petri-Netz

**Comment by malt-r** [comment]
Das Questlog ist in irgendeiner Form ein HUD-Element, aus dem Information abgelesen werden können, welche Aufgaben aktuell bearbeitet werden müssen/können.
