### ISSUE TITLE
[D2G] Dateistruktur von Aufgaben

### ISSUE THREAD

**Issue by AKirsch1** [Programmiermethoden/Dungeon#622]
Jede Aufgabe stellt ein eigenes vollständiges Java-Projekt mit folgendem Aufbau dar (Basiert zum Teil auf [Link](https://github.com/Programmiermethoden/Deploy-to-Grading/issues/1#issuecomment-1201149664)):

```
taskX/
|__.config/
|  |__task.yml            # Konfiguration der Aufgabe für D2A
|  |__checkstyle.xml
|  |__(Sonstige Konfigurationen)
|__.editorconfig
|__gradle/wrapper         # Wenn nicht anderweitig auslagerbar
|__src/
|__loesung/               # Notwendig?
|__test/
|__README.md              # Aufgabenstellung
|__build.gradle
|__(Restliche Gradle-Dateien)
```

Das Vorgaben-Repo enthält dann auf obersten Ebene die taskX-Ordner.

*Anmerkung: Zur genauen Definition der task.yml siehe #623.*
*Anmerkung: Es sollte noch geprüft werden, ob Gradle-Standardsachen aus den Aufgaben ausgelagert werden können.*

**Comment by cagix** [comment]
tatsächlich würde ich den gradle-wrapper nach möglichkeit gern aus den tasks raushalten. der ist zwar nicht so groß, aber das summiert sich über die tasks dann doch auf. und ich muss beim aktualisieren dann nicht nur einen wrapper hochziehen, sondern viele.

am besten wäre es, wenn es in der ebene über den tasks den gradle-wrapper und eine allgemeine gradle-konfiguration gäbe. in den tasks kann es dann noch eine zusätzliche build.gradle mit detailskonfigs geben.

**Comment by cagix** [comment]
src und test sollten dabei dem maven-/gradle-projektlayout gehorchen. ich glaube, test liegt normalerweise in src.

den ordner "loesung" brauchen wir nicht. da sollten die studis im alten konzept ihre lösung reintun, aber das ist imho queso.

denkst du mit, dass wir intern eine lösung vorhalten wollen, die dann mit den vorgaben irgendwie zusmmenspielen muss? nur so können wir die vorgabetests prüfen und auch schauen, ob die vorgegebenen dateien funktionieren. d.h. die vorgaben und die musterlösung muss sich irgendwie in ein intellij-projekt ziehen lassen.

**Comment by AKirsch1** [comment]
Geschlossen, da Umsetzung in #704 erfolgen soll.
