### ISSUE TITLE
[Game] Adjust the scaling of the questions and answers

### ISSUE THREAD

**Issue by dkirshner** [Programmiermethoden/Dungeon#625]
Die Fragestellungen und Antworten in der Quiz GUI werden noch nicht richtig skaliert.
Haben die Fragen nicht exakt die gleiche Länge an Zeichen, wird der Abstand zum linken Rand immer größer. 
Die Anweisung im Code für die linksbündige Formatierung scheint nicht angenommen zu werden.

**Comment by AMatutat** [comment]
Wenn damit auch
![image](https://github.com/Programmiermethoden/Dungeon/assets/32962412/512e2202-fafd-490e-adce-526eda3b8238)

gemeint ist, dann hat sich der Bug wieder Eigenschlichen Bzw der fix ist durch #702 verloren gegangen.
@AHeinisch kannst du dir das mit @dkirshner nochmal ansehen?
