### ISSUE TITLE
[GAME] Kollision wird nicht richtig erkannt

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#627]
Die Kollision wird nicht richtig berechnet. Manchmal trifft mein Feuerball das Monster obwohl es Meilen weit weg ist. 
Ich hab das mal versucht aufzunehmen: 

![2023-05-09 09 06 10](https://user-images.githubusercontent.com/32962412/237020382-9e659ad0-548b-41a1-aa19-35f31b9c7a90.gif)

Meine Monster haben die default Hitbox Settings.
Ihr könnt meinen Code aus `am/demo`zum überprüfen verwenden.

**Comment by AHeinisch** [comment]
382e5419faf0fb899bf9db07b2f48991ec280969
legt fest, dass der Feuerballskill eine Größe von 10 x 10 Feldern hat und nicht nur (10/16) x (10/16) Felder. Die Collision wird also richtig erkannt die Hitbox wird nur etwa 16-mal so groß angelegt wie dir Textur anzeigt.

**Comment by AMatutat** [comment]
ack, da wurden vermutlich pixel mit tiles verwechselt

**Comment by cagix** [comment]
@AMatutat Das ist auch noch ne Baustelle ... Pixel vs. Tiles ...
