### ISSUE TITLE
[D2A] Sammlung an Konferenzen für D2A

### ISSUE THREAD

**Issue by AKirsch1** [Programmiermethoden/Dungeon#629]
## Konkretes:

**[Workshop "Automatische Bewertung von Programmieraufgaben"](https://www.abp-workshop.de/)** (Deutschland) (h-Index: Nichts gefunden)

Einreichfrist: 15. Juni 2023 12:00 Uhr
Workshop: 12.-13. Oktober 2023

## Weiteres:

**[ACM/SIGCSE conference on Innovation and Technology in Computer Science Education (ITiCSE)](https://iticse.acm.org/2023/)** (Europa) (h-Index: 32)
**[SIGCSE Technical Symposium](https://sigcse.org/events/symposia/index.html)** (USA) (h-Index: 24 (Irgendwie kann ich mir nicht vorstellen, dass der Europäische besser sein soll. Dieses Symposium ist laut SIGCSE größer.)

Bereits zu spät für beides, aber unter SIGCSE habe ich schon ein paar Paper zum Thema AutoGrader gesehen. Für ITiCSE 2024 könnte die nächste Deadline im Januar 2024 sein, habe aber noch nicht genaueres gefunden.

**[IEEE Transactions on Learning Technologies](https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4620076)** (h-Index: 52)

Als Alternative noch ein Journal.

**Comment by cagix** [comment]
@AKirsch1 kannst dafür auch gleich eine wiki-seite anlegen?

**Comment by AKirsch1** [comment]
Ist jetzt in ein Wiki übertragen.

**Comment by AKirsch1** [comment]
Da war ich etwas voreilig mit Schließen. Ich kann gerade irgendwie keine neue Wiki-Seite erstellen. GitHub leitet mich nur auf eine leere Seite weiter.

**Comment by AKirsch1** [comment]
Als Zwischenspeicher, hier der Inhalt, der eigentlich auf die Seite sollte:

Ein zentrales Verzeichnis für Workshops, Konferenzen und Journals, die thematisch in unser Feld passen. Zu jedem Eintrag sollten immer Important Dates und h-Index angeben werden. (Auch bei vergangenen Workshops/Konferenzen/Journals, damit man einschätzen kann, wann die nächste Deadline sein könnte.)

## Allgemein

- [IEEE Transactions on Learning Technologies](https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4620076) (h-Index: 52)
  - Journal, daher keine Important Dates

- [ACM/SIGCSE conference on Innovation and Technology in Computer Science Education (ITiCSE)](https://iticse.acm.org/2023/) (Europa) (h-Index: 32)
  - Einreichfrist: 15. Januar 2023
  - Konferenz: 10.-12. Juli 2023

- [SIGCSE Technical Symposium](https://sigcse.org/events/symposia/index.html) (USA) (h-Index: 24)
  - Einreichfrist: Nicht gefunden
  - Konferenz: 15.-18. März 2023

## Gamification

## DSL

## Autograding

- [Workshop "Automatische Bewertung von Programmieraufgaben"](https://www.abp-workshop.de/) (Deutschland) (h-Index: Nichts gefunden)
  - Einreichfrist: 15. Juni 2023 12:00 Uhr
  - Workshop: 12.-13. Oktober 2023

**Comment by cagix** [comment]
> 

@AKirsch1 Github hat in letzter Zeit öfter mal Probleme - ich konnte neulich ca. eine Stunde lang nichts kommentieren. Aber jetzt scheint es wieder zu gehen (https://www.githubstatus.com).

**Comment by AKirsch1** [comment]
Ich habe es jetzt auch in das Wiki eintragen können.
