### ISSUE TITLE
[D2G] Eindeutige Bennung von D2A / D2G

### ISSUE THREAD

**Issue by AKirsch1** [Programmiermethoden/Dungeon#630]
Für eine Publikation sollten wir uns für einen eindeutigen Namen entscheiden. Momentan verwenden wir ja sowohl Deploy-2-Abgabe als auch Deploy-2-Grading.

**Comment by cagix** [comment]
"Deploy-to-Grading" oder kurz D2G. 

"Deploy-to-Abgabe" ist bestes Denglish :) ...

**Comment by AKirsch1** [comment]
Dann ist ja gut, dass wir momentan überall D2A verwenden. 🙈

**Comment by cagix** [comment]
> Dann ist ja gut, dass wir momentan überall D2A verwenden. 🙈

Ja, sorry. Ich glaube, das kommt von mir - die Studis sollten für die Abgabe einen Deploy-Vorgang (im Sinne von CI/CD) anstoßen. Deshalb "Deploy-to-Abgabe" und das hat sich so eingeschliffen. Aber ich denke, wenn wir ernst genommen werden wollen, sollten wir uns für Deutsch _oder_ Englisch entscheiden :)

**Comment by AKirsch1** [comment]
Label, Milestones und Issue Titel sind jetzt umbenannt. An ein paar Stellen könnte in den Issue-Beschreibungen könnte noch D2A stehen, das ich anpassen würde, wenn es mir auffällt.

**Comment by cagix** [comment]
danke dir!
