### ISSUE TITLE
[GAME] Potentieller Bug, mehrere HUD´s im Game

### ISSUE THREAD

**Issue by eWeidling** [Programmiermethoden/Dungeon#634]
Wir haben einen DialgoueHUD welche wie das PauseMenu in Game als Objekt vorhanden ist, und ebenfalls den selben Actor erhält. Gleiches gilt für ein InventoryHUD. 
Problem: Sowohl im DialogueHUD als auch im InventoryHUD haben wir Buttons, welche einen ScreenButtonListener besitzen. Der Actor in Game scheint jedoch nur den zuletzt, in die ArrayList controller aus Game.java, eingefügte HUD zu beachten. 
Bedeutet: Wenn das Inventar zuletzt in die ArrayList geaddet wird, kann man zwar im Inventar die Buttons anklicken, so dass deren Funktionalitäten auch ausgeführt werden, während dafür im DialogueHUD die Buttons über den Listener nicht mehr aktiviert werden.

**Comment by AMatutat** [comment]
@AHeinisch sag mal was schlaues.

**Comment by AHeinisch** [comment]
Hier mal etwas schlaues dazu. Der PauseDialog nutzt im hintergrund jeweils einen eigenen Screencontrooler dieser handelt alle interaktionen auf sich selbst ab. Da aber nun mehr als einer erstellt wird. kann nur der erste alles abarbeiten. Dies liegt daran das der Screen auf welchen sich die Actors befinden den älteren überdeckt und somit dieser nicht mehr angesteuert wird. 

Lösungsmöglichkeiten die Actors auf einem gemeinsamen Screencontroller packen oder die Screencontroller verbinden. Da ich aus dem Kopf auf die schnelle nicht den Code kenne, würde ich dazu einmal etwas mit Beispielcode bereitstellen, sobald ich genaueres weis.

**Comment by eWeidling** [comment]
Danke für Ihre Antwort, etwas Beispielcode würde uns in der Hinsicht sicherlich weiterhelfen.

**Comment by eWeidling** [comment]
Ok Danke, wir warten dann mal auf das Ergebnis deines Pull requests

**Comment by eWeidling** [comment]
Vielen Dank für die Hilfe, wir haben Variante 1 umgesetzt und es funktioniert.
