### ISSUE TITLE
[D2G] GitHub Education Autograding

### ISSUE THREAD

**Issue by AKirsch1** [Programmiermethoden/Dungeon#638]
@cagix @AMatutat Hat sich einer von euch schon einmal mit dem [Autograding](https://docs.github.com/de/education/manage-coursework-with-github-classroom/teach-with-github-classroom/use-autograding) von GitHub Education befasst? Deren Umsetzung klingt stark nach unserer Idee, wenn auch mit einigen Einschränkungen möglicherweise.

Im Hinblick auf Paper sollten wir uns davon auf jeden Fall abgrenzen können.

**Comment by cagix** [comment]
Noch nicht ausprobiert mangels Zeit und der Aussicht, dass wir das ja nicht einsetzen dürfen (Datenschutz).

Aber ich habe tatsächlich das Gefühl, dass wir hier Funktionalität nachbauen. Wäre vermutlich gut, wenn Du Dir das mal bei Gelegenheit näher anschauen könntest.

**Comment by AKirsch1** [comment]
Ich habe das mal in die Liste in #598 aufgenommen. Dann kann ich dieses Issue hier schließen.
