### ISSUE TITLE
[Publikationen] Mögliche Referenzen für Publikationen zum Dungeon

### ISSUE THREAD

**Issue by AKirsch1** [Programmiermethoden/Dungeon#643]
Hier ein paar Paper, die für eine Publikation zum Dungeon interessant sein könnten:

- https://ieeexplore.ieee.org/document/9173738
- https://ieeexplore.ieee.org/document/6827214

Und eine Liste an Publikationen zum allgemeineren Thema Programming eduction von SIGSCE: https://sigcse.org/events/workinggroups.html. Vielleicht ist da auch etwas für uns bei.

Wenn bei den Links etwas Sinnvolles dabei ist, sollte man das ins Wiki eintragen.

**Comment by AMatutat** [comment]
Grade drüber gestolpert aber nur den Titel gelesen:
https://www.idunn.no/doi/full/10.18261/ISSN1891-943X-2006-03-02

**Comment by AMatutat** [comment]
[Hier](https://d1wqtxts1xzle7.cloudfront.net/78820467/muhammad1_collerShernoffIJEE-libre.pdf?1642279675=&response-content-disposition=inline%3B+filename%3DVideo_Game_Based_Education_in_Mechanical.pdf&Expires=1685474626&Signature=Y-vsyd9ScfyIoi54jRm0bHDMH3Tk~lB4jN8M79mywVWpAhT8AnnuII~vCG~ziyy-Niro--Min6Ayp~NCvQeCdH8oeNy-VAIQAO18yZJQnj0b9hKhLGuMRfloxV9nWK9dmJ~6P-P8H5N2iNMzUecsWtiod9d0tuqmOiB7v--6~HQnNke3~nJwGGZmqlkvoc5Bv-6R-A6ltKxf4V0JaQma5VcoC9PlxYyp7AVOJ3QZ3GLzJ2bzwuLtUqt0rG7wowh3nIOwFyuMGC5GhwafTTn-WvwwZjy2u7X1gyaFYzNTGHh2K5VOYdUt8hEp4NZURGAwVz7dG6rhJHh50rF9OxcI5Q__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA)

tldr: Haben ein Auto Spiel gemacht und die Studis fanden das voll toll und waren motiviert.

**Comment by AMatutat** [comment]
Ich link mir das mal in mein Dokumentations-Issue und mache hier zu
@AKirsch1 nochmal danke für die links
