### ISSUE TITLE
[GAME] Items auf Knopfdruck einsammeln

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#646]
Items sollen auf Knopfdruck aufgehoben werden (nicht mehr der Kollision).
Dafür sollten wir das `InteractionComponent`auf dem `WorldItem`-Entity anwenden können. 
Man müsste nur gucken, dass man immer nur ein Item auf einmal aufsammelt.

**Comment by fwatermann** [comment]
Ja, das kann gut sein.
