### ISSUE TITLE
[AUFGABEN] "Elemente in richtiger Reihenfolge auswählen" als Spezialfall von "Zuordnen"

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#648]
> So wie ich das sehe haben wir hier zwei Möglichkeiten:
> 
> 1. Wir diskutieren _nochmal_ im nächsten Mittwoch über die Rechtfertigung des Aufgabentyps und das bleibt noch länger liegen, obwohl das eigentlich schon entschieden war (das Beispiel mit den Türen habe ich auch schon unter [[AUFGABEN] Merge von Aufgabentypen "Positionieren" und "Elemente in der richtigen Reihenfolge wählen" #519](https://github.com/Programmiermethoden/Dungeon/issues/519) angeführt).
> 2. Wir handeln im Sinne des Pragmatismus und streichen den Aufgabentyp. Ich kann das Argument, dass das Beispiel eigentlich 3 SC Fragen sind, gut nachvollziehen. Wenn zusätzlich die Einschränkung, dass nicht alle Elemente vorher bekannt sein müssen, wegfällt, dann grenzt sich der Aufgabentyp meiner Meinung nach zu schwach von "Zuordnen" ab (was auch hier: [Kontrollmechanismus Brainstorming 2022-freiraum-dungeon#110 (comment)](https://github.com/Programmiermethoden/2022-freiraum-dungeon/pull/110#discussion_r1147954617) schonmal Diskussionsgegenstand war)

@malt-r Ich kann Deinen Widerwillen verstehen, aber es zeigt sich halt in dieser Diskussion, dass die Konzepte offenbar doch noch nicht so klar oder gut abgegrenzt waren/sind, wie wir alle gedacht hatten. 

Deshalb würde ich den Typ aber nicht gleich sofort streichen - man muss halt nochmal nachdenken. Ist "in richtiger Reihenfolge auswählen" eventuell ein Spezialfall von "Zuordnen"?

Meeting: Entweder wir lassen diesen PR offen und diskutieren das im nächsten Meeting, oder es gibt ein neues Issue für diese Diskussion und dann kann hier resolved werden und entsprechend gemergt werden und das Issue im nächsten Meeting besprochen werden.

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/444#discussion_r1192159346_

**Comment by AMatutat** [comment]
@malt-r hatten wir darüber schon gesprochen?
