### ISSUE TITLE
[GAME] Systeme sollten Singleton sein

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#649]
> > @AMatutat Interessant. Frage zur API: Die ganzen Hilfsfunktionen sind static und public. Soll das so, also sollen das wirklich (a) Klassenmethoden und (b) von außen aufrufbar sein
> 
> Die Funktionen sind nicht wirklich vom Debugger-Systme abhängig und können daher gerne auch woanders benutzt werden, daher hab ich sie public static gelassen. Das Debugger-System übernimmt für mich nur den Aufruf per Tastendruck.
> 
> Oder in einfach: Macht nix kaputt und kann für den ein oder anderen bestimmt nützlich sein.

Hmmm. Klingt für mich noch nicht so richtig überzeugend. 

Die nächste Frage wäre nämlich: Wieviele Debugger gibt es? Eigentlich ist es ein `System`, d.h. es dürfte zu einem Zeitpunkt nur einen geben (BTW: Wie ist das eigentlich mit unseren Systems, können die mehrfach instantiiert werden oder ist da Singleton drin?) und über den mache ich den Kram. 

Und es gibt zusätzlich vielleicht eine Util-Klasse, die dann statische Methoden anbietet ... 

---

@AMatutat In der Hoffnung, dass Du weisst, was Du tust: ok(ish) ;)

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/495#pullrequestreview-1424282964_

**Comment by AMatutat** [comment]
Da man das Singleton-Pattern in jedem System implementieren müsste (was recht fuddelig ist und bei einem neuen System schnell vergessen werden kann), wäre es vielleicht besser, nicht das Erzeugen der Systeme, sondern das Registrieren der Systeme beim `Game` zu beschränken.

Meine Idee wäre jetzt: Die Systeme in einer HashMap `<Class, System>` zu speichern. Wenn sich ein neues System registriert, wird es dort abgelegt. Falls bereits ein System der gleichen Klasse existiert, wird das alte beibehalten. Dadurch wird versehentliches "Überschreiben" des Systems vermieden, und wenn jemand die Systeme tauschen möchte, muss das alte System zuvor explizit entfernt werden.

@cagix, was hältst du davon?

**Comment by cagix** [comment]
> Da man das Singleton-Pattern in jedem System implementieren müsste (was recht fuddelig ist und bei einem neuen System schnell vergessen werden kann), wäre es vielleicht besser, nicht das Erzeugen der Systeme, sondern das Registrieren der Systeme beim `Game` zu beschränken

richtig, das wird fummelig. 

kriegt man das irgendwie in die basisklasse rein? 


> 
> Meine Idee wäre jetzt: Die Systeme in einer HashMap `<Class, System>` zu speichern. Wenn sich ein neues System registriert, wird es dort abgelegt. Falls bereits ein System der gleichen Klasse existiert, wird das alte beibehalten. Dadurch wird versehentliches "Überschreiben" des Systems vermieden, und wenn jemand die Systeme tauschen möchte, muss das alte System zuvor explizit entfernt werden.

eine `Map<Class, System>` macht das handling wieder komplizierter. 

ich würde es bei `Set<System>` belassen. man könnte in `Game` eine `register(System)`-methode haben, um sich explizit beim game zu registrieren. darin könnte man prüfen, ob es ein element dieser klasse bereits gibt und das dann austauschen. klar, man müsste dazu über jedes element gehen und nach der klasse fragen - aber wie oft macht man das wirklich - einmal pro spiel, oder?

varianten:
(a) `register(System)` liefert das alte registrierte system zurück und ersetzt es intern mit dem neuen. dann kann der aufrufer überlegen, ob er versehentlich was überschrieben hat und das damit ggf. rückgängig machen.
(b) `register(System)` wirft eine exception, falls bereits ein system der selben klasse registriert war. dann muss es aber auch eine `unregister(System)`-methode geben.

ich finde beides nicht so gut wie die systeme als singleton, würde aber eher (a) bevorzugen mit einer klaren dokumentation dazu. in c/c++ haben wir mit `signal()` exakt dieses verhalten für signalhandler.
