### ISSUE TITLE
[GAME] Braucht Entity wirklich eine ID

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#652]
Die Klasse `Entity` hat eine ID. 
Braucht es die wirklich?
Bisher wird die nur in ein paar wenigen Tests verwendet.

**Comment by AMatutat** [comment]
Die ID wird im CollisionSystem verwendet, um die Entitäten miteinander zu Vergleichen und so doppelte Kollisions-Tupel (A,B);(B,A) zu vermeiden.
Das bedeutet für mich: Ja die ID ist sinnvoll und sollte bleiben.

**Comment by cagix** [comment]
@AMatutat Die `toString`-Methode arbeitet nur mit dem Namen, der auch anonym sein kann. Sollte hier auch die ID einfließen?

Und man braucht die Möglichkeit, Entitäten zu vergleichen. Sollte `Comparable` implementiert werden basierend auf dem Namen und/oder der ID?

**Comment by AMatutat** [comment]
> Und man braucht die Möglichkeit, Entitäten zu vergleichen. Sollte Comparable implementiert werden basierend auf dem Namen und/oder der ID?

Das ist #754 


> @AMatutat Die toString-Methode arbeitet nur mit dem Namen, der auch anonym sein kann. Sollte hier auch die ID einfließen? Wird auch im Logging benötigt?!

Eigentlich ja. In meinem Ursprünglichen Gedanken ersetzte der Name die ID im Logging, aber wenn du zwei "Hero"s hast, dann wäre zusätzlich die id noch praktisch.
