### ISSUE TITLE
[GAME] Factory Methode für Chest überdenken

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#654]
Es kam etwas Diskussion auf, wie die API der `EntityFactory` für Entitäten alla Schatzkiste aussehen sollte.

Aktuell kann ich mir eine Kiste mit zufälligen Items zufälliger Position im Dungeon platzieren oder eine Kiste mit konkreten Items an eine konkrete Position.

Wäre es intuitiver eine leere Kiste zu generieren und der Aufrufer packt dann seine Items da rein?

**Comment by cagix** [comment]
oder die factory ist tatsächlich ein builder ... dann hast du beides.
