### ISSUE TITLE
[GAME] Systeme sollen über Queues auf Components zugreifen. 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#660]
Aktuell können alle Systeme schreibend auf alle Komponenten zugreifen und dort die Datensätze ändern. Eine Ausnahme ist hier das `DrawComponent`. Hier fügen die Systeme ihre Änderungen als eine Art Queue-Anfrage hinzu. Das `DrawSystem` wertet dann die Queue aus (in diesem Fall spielen noch Prioritäten eine Rolle) und verändert dann die Daten. Das hat den Vorteil, dass immer nur ein System auf eine Komponente schreibt, dadurch werden klare Zuständigkeitsbereiche definiert. Außerdem kann so duplizierter Code vermieden werden.

Das Konzept sollte auf alle Komponenten und Systeme ausgeweitet werden. Dabei muss untersucht werden, welche Bedingungen (z.B., die Prioritäten bei Animationen) für die einzelnen Anfragen sinnvoll sein können.

---
> > > Alles ander ist content. Führt auch dazu, dass eigentlich nur das VelocitySystem noch auf content zugreift, und das sollte man einfach umbesinnen können. Siehe vorschlage oben,
> 
> 
> 
> > Das scheint mir ein grundsätzliches Problem am ECS zu sein. Was machen denn andere?
> 
> 
> 
> Ist irgendwie auch die große Frage für #499 . Mein Eindruck ist, jeder macht irgendwie was er will. Gibt Projekte die eine starke Trennung forcieren und dann mit (in meinen Augen wirren) Konstrukten Arbeiten, um irgendwelche Infos abzulegen und von jemanden anderen bearbeiten zu lassen. Andere Projekte schienen mir da wieder mehr in unsere Richtung zu gehen. 
> 
> 
> 
> Wir haben natürlich den Sonderfall, dass wir nicht ein Spiel sind sondern ein Framework+. 
> 
> @AHeinisch Deine Einschätzung? 
> 
> 
> 
> > Wenn ein System immer nur auf "seine" Components zugreifen darf, dann schränkt man sich ziemlich schnell ziemlich ein.
> 
> 
> 
> Entweder das, oder die Implementierung wird richtig unschön, weil du dauernd irgendwo irgendwelche Flags setzten und anschauen würdest. 
> 
> 
> 
> 
> 
> > Wenn es aber quasi alle Freiheiten beim Zugriff gibt, bekommt man schnell alle möglichen Probleme (welche Animation wird nun genau abgespielt bzw. wer darf wann was setzen bzw. in welcher Reihenfolge sollte wer was setzen).
> 
> 
> 
> Vielleicht wäre die Regel: Gucken aber nicht anfassen sinnvoll. Müsste ich aber durchdenken. Dann dürfte ein System nur Werte zum direkt zugehörigen Component ändern. 
> 
> Auf der anderen Seite ist das auch irgendwie murks, dann müsste das VelocitySystem irgendwo aufschreiben, dass doch mal bitte jemand die Position der Entität ändert. 
> 
> 
> 
> > wer darf wann was setzen bzw. in welcher Reihenfolge sollte wer was setzen).
> 
> 
> 
> Für das Problem hatte ich mal #244 angelegt. Bisher war es halt nie sonderlich problematisch

ne ganz blöde idee: die systems könnten auf den components arbeiten (lesend) und ihre ergebnisse (neue werte oder components oder was auch immer) in eine art message-queue einspeisen. wenn alle systems durch sind, könnte man die queue nach bestimmten regeln reduzieren und dann auf die entitäten anwenden.

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/657#issuecomment-1546717580_

**Comment by AMatutat** [comment]
in #964 haben wir das ganze tatsächlich für das `DrawComponent` umgesetzt.
Andere Systeme werfen eine Animation die gesetzt werden soll wird in die queue gepackt.
Das `DrawSystem` reduziert die Queue dann nach gewissen regeln und setzt die werte. 

Das könnte man auf die anderen Systeme auch anwenden, das sollte meistens sogar noch deutlich einfacher sein, da hier keine komplexen Prioritäten o.ä berücksichtigt werden müssen.

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
