### ISSUE TITLE
[GAME] Projektbezogene Inhalte aus dem game Module extrahieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#661]
Die Inhalte für die Umsetzung der Aufgabentypen sollen in ein eigenes Modul extrahiert werden.
Aktuell ist das nur die Basis-Struktur der Quiz-Fragen sowie einige UI-Funktionen welche die Quiz-Fragen im HUD anzeigen. 

Edit: Auch die [Diskussion](https://github.com/Programmiermethoden/Dungeon/pull/702#discussion_r1225792126) zum Thema Quizfragen-Dummy soll gelöst werden.

**Comment by AMatutat** [comment]
@AHeinisch davon ausgehen dass bis Mittwoch #702 durch ist: Können wir uns kurz von dem SHK Meeting treffen und das zusammen machen? Es gibt da 1-2 stellen die mit der GUI verbunden sind und zusammen reißen wir das bestimmt flotter auseinander.

**Comment by AHeinisch** [comment]
Können wir gerne machen. Bei dem Wetterumschwung vielleicht 2 Stunden einplanen (also 2 Stunden vor SHK Meeting)

**Comment by AMatutat** [comment]
Aus dem meeting Protokoll 037:
 *   Allgemeine Entscheidung: Dummy-Inhalte sollen nicht im Produktivcode (`/src`) liegen.
    *   Für demonstrative Zwecke sollen Branches angelegt werden.
    *   Für Testzwecke/Entwicklungszwecke soll in `/test` ein Package mit manuellen Tests angelegt werden. Dort kann dann die Umgebung entsprechend zusammengebaut werden (Entitäten anlegen, Quizfragen erstellen usw.) und von dort aus manuell gestartet und evaluiert werden.
    *   Gegebenenfalls eignen sich Code-Snippets aus den Tests/Demos für die Dokumentation.
