### ISSUE TITLE
[GAME] remove SystemController

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#675]
Der SystemController kann durch ein einfaches `private static Set<System>` in `Game` ersetzt werden. 

Zusätzlich soll `Game` eine `static addSystem` und `static removeSystem` und `static Stream<System> getSystemsStream` (braucht es die wirklich? Wenn nicht, weglassen) Methoden bekommen.

**Comment by cagix** [comment]
@AMatutat ich bin kein großer freund davon, interne strukturen per getter nach draußen zu geben, um dann außerhalb der datenstruktur damit zu arbeiten. oft kann man das durch passende methoden auf der datenstruktur selbst erledigen (siehe teile der diskussion um die delayedset). 

brauchen wir hier ein `getSystems()` wirklich? könnten wir methoden anbieten, die den intendierten use-case innerhalb der klasse erledigen, ohne die inneren strukturen zu entblößen?

**Comment by cagix** [comment]
edit: üblicherweise heißt die methode, die einen stream zurückliefert: `stream()` ... das ist fast überall im jdk so.
