### ISSUE TITLE
[DSL] API für überarbeitetes DrawComponent 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#679]
In #348 wurde ein neues Konzept für das `DrawComponent` vorgestellt.
Die Frage ist jetzt, wie dieses Konzept mit der DSL/API verbindbar ist? 
Braucht es ein ähnliches Konstrukt wie aktuell (`AnimationBuilder`)?

**Comment by malt-r** [comment]
Ja braucht es, wobei es sogar erst noch https://github.com/Programmiermethoden/Dungeon/pull/272 braucht. Damit wird ein Mechanismus eingebaut, der auch auf die Ebene von Komponenten erweitert werden könnte.
