### ISSUE TITLE
[Game] LevelManager wird zweimal geladen

### ISSUE THREAD

**Issue by tgrothe** [Programmiermethoden/Dungeon#680]
Hab einen möglichen Bug in der Klasse Game entdeckt.

Anstatt
```java
        IGenerator generator = new RandomWalkGenerator();
        levelManager = new LevelManager(batch, painter, generator, this);
        initBaseLogger();
        hero = EntityFactory.getHero();
        levelManager =
                new LevelManager(
                        batch, painter, new WallGenerator(new RandomWalkGenerator()), this);
        levelManager.loadLevel(LEVELSIZE);
        createSystems();
```
würde ich schreiben
```java
        initBaseLogger();
        IGenerator generator = new RandomWalkGenerator();
        levelManager =
                new LevelManager(
                        batch, painter, new WallGenerator(generator), this);
        levelManager.loadLevel(LEVELSIZE);
        hero = EntityFactory.getHero();
        createSystems();
```

Ich bin mir nicht sicher, weshalb `levelManager` doppelt zugewiesen wird, und glaube, das ist ein Bug.

Zum Teil habe ich damit in #659 und in #664 angefangen.

Ich denke, es gibt noch kein Issue hierzu.

**Comment by tgrothe** [comment]
Sorry, zu spät gesehen, anscheinend wird einmal das Level generiert und einmal werden die Walls generiert. Dennoch sollte `getHero()` erst später aufgerufen werden.

**Comment by AMatutat** [comment]
a) Verursacht das `getHero` dort keine Probleme
b) Wird das mit #582 hinfällig, dort soll das ganze von außen mit der `Game#setHero` Methode passieren. 
c) das mit den LevelManger ist aber in der tat falsch... kein bug aber unnötig

**Comment by tgrothe** [comment]
nein, hier ist nicht closed, der LevelManager wird nach wie vor zweimal geladen:

https://github.com/Programmiermethoden/Dungeon/blob/0fbb193120b828b1f6dbe8666f2c73c3f8356e6d/game/src/core/Game.java#L628-L632

und ich verstehe nicht, wieso das nicht auffällt @AMatutat @cagix

**Comment by tgrothe** [comment]
Danke @AMatutat ich hab mal ne Diskussion gestartet, #742
