### ISSUE TITLE
[GAME] HealthSystem#execute überarbeiten

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#681]
Den letzten Filter verstehe ich nicht wirklich. In Zeile 43 filtern wir alle toten Entitäten, in Zeile 54 nehmen wir sie aus dem Spiel. Aber was macht der Filter in Zeile 44?

- Wenn die Entität tot ist und keine Sterbe-Animation hat oder diese noch läuft - dann true und entsprechend in 54: nimm mich raus? Klingt irgendwie falsch?
- Wenn die aktuelle Animation nicht die Sterbe-Animation ist, setze sie. -> Das ist kein Filter, sondern ein Nebeneffekt.
- Und last not least: Wenn die Entität tot ist und die aktuelle(!) Animation durch ist, dann true und in 54 weg damit. Das klingt ungefähr sinnig - könnte sich aber nicht um die Sterbe-Animation handeln.

=> hier macht ein Filter irgendwie ganz viel. Das müsste nochmal in verschiedene Vorgänge gesplittet werden (die eigentlichen Filter und das Setzen der Animation). Zusätzlich sollte es eine Variable mit einer Hilfsfunktion o.ä. geben, die die komplexere Abfrage für den Filter macht mit entsprechenden Kommentaren.

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/669#discussion_r1201532899_

**Comment by JudiTeller** [comment]
Dass in execute() die DeathAnimation gesetzt wurde, ist sehr awkward.
Soll das an dieser Stelle nur ein Safeguard sein?
Zumal die DeathAnimation dann in removeDeadEntities(), die nach diesem Filter erst aufgerufen wird, auch noch mal gesetzt wird

Wäre das nicht sinniger z.B. in HealthComponent bei triggerOnDeath unabhängig vor dem call auf onDeath.accept() zu setzen?
Natürlich mit Check, ob die Entity ne DrawComponent und ne DeathAnimation hat
