### ISSUE TITLE
[DSL] Definition von korrekter Antwort in Task-Definition

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#686]
Es ist noch nicht klar definiert, wie die Definition der korrekten Antwort auf eine Frage syntaktisch und semantisch erfolgen soll (wie   https://github.com/Programmiermethoden/Dungeon/pull/678#discussion_r1199591171 zeigt).

Falls für eine Aufgabe mehrere Antwortmöglichkeiten definiert werden, wie im folgenden Beispiel:

```
single_choice_task my_task {
  answers: ["a", "b", "c"]
}
```

könnte die Definition der korrekten Antwort auf unterschiedliche Weisen erfolgen:

### 1. Zugriff auf Array-Element

```
single_choice_task my_task {
  answers: ["a", "b", "c"],
  correct_answer: answers[0]
}
```

Hiermit referenziert `correct_answer` direkt den Wert aus dem Array. In einer Scoring-Funktion kann der Wert von `correct_answer` direkt verwendet werden, um in mit der gegebenen Antwort zu vergleichen:

```
fn score(task t, string a) -> float {
  if (t.correct_answer == a)
    return 1.0;
  else 
    return 0.0;
}
```

### 2. Festlegung als Index (Datentyp `int`)

```
single_choice_task my_task {
  answers: ["a", "b", "c"],
  correct_answer: 0
}
```

Hiermit sind DSL-Nutzende selbst dafür verantwortlich, den `int`-Wert von `correct_answer` in einer Scoring-Funktion zu verwenden, um auf den entsprechenden Array-Eintrag zuzugreifen.

```
fn score(task t, string a) -> float {
  if (t.answers[correct_answer] == a)
    return 1.0;
  else 
    return 0.0;
}
```

### 3. Festlegung als Index (Datentyp `index`)

```
single_choice_task my_task {
  answers: ["a", "b", "c"],
  correct_answer: [0]
}
```

Der Datentyp `index` könnte anzeigen, dass es sich bei dem Wert um einen "partiellen Wert" handelt, der erst in Kombination mit einem Array vollständig wird. Intern könnte der DSL-Interpreter den Array-Zugriff auf das `answers`-Array durchführen, sodass DSL-Nutzende beim Zugriff auf `my_task.correct_answer` den entsprechenden Array-Eintrag erhalten: 

```
fn score(task t, string a) -> float {
  if (t.correct_answer == a)
    return 1.0;
  else 
    return 0.0;
}
```

Dieses Szenario ist eine semantische Sonderbehandlung von `correct_answer`, da implizit mit dem übergebenen Wert auf das `answers`-Array zugegriffen wird und beim lesenden Zugriff von `correct_answers` ein anderer Wert gelesen wird, als ursprünglich definiert. Das wird vermutlich zu Verwirrung führen.

**Comment by cagix** [comment]
Option (1) ist sowas wie eine Referenz auf die richtige Antwort und macht die Auswertung in der Score-Funktion leichter.

Option (2) fühlt sich dagegen für mich deutlich natürlicher an. Ich definieren in der Struktur die Antworten und einen Index mit der richtigen Antwort, und in der Score-Funktion gehe ich mit diesem Index in die Liste der Antworten. ✅ 

Option (3) ist irgendwie schräg.

**Comment by malt-r** [comment]
Falls wir mit Option (2) gehen, würde ich allerdings das Feld von `correct_answer` in `correct_answer_index` umbenennen. 
Ist allerdings die Frage, wie gut das auf andere Aufgabentypen übertragen werden kann. Bei Multiple Choice Fragen, könnte man das Array/Liste von Indizes angeben. Für z.B. Zuordnungsaufgaben sieht das ja nochmal ganz anders aus.

Option (3) war bewusst etwas experimenteller ausgelegt.

**Comment by cagix** [comment]
> Falls wir mit Option (2) gehen, würde ich allerdings das Feld von `correct_answer` in `correct_answer_index` umbenennen. 

würde sinn machen, ja,

> 
> Ist allerdings die Frage, wie gut das auf andere Aufgabentypen übertragen werden kann. Bei Multiple Choice Fragen, könnte man das Array/Liste von Indizes angeben. Für z.B. Zuordnungsaufgaben sieht das ja nochmal ganz anders aus.

dann erstelle doch mal ein konzept dafür und stelle es zur diskussion. die (gesamt-) entscheidung sollten wir erst treffen, wenn für alle aufgaben etwas da ist und man das gesamte bild sieht.
