### ISSUE TITLE
[DSL] `@DSLType` automatisch einlesen

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#695]
Wie hier https://github.com/Programmiermethoden/Dungeon/pull/687#issuecomment-1561976953 dargestellt, stellt es eine Fehlerquelle dar, dass die per `@DSLType` markierten Datentypen nochmals händisch in das `GameEnvironment` eingebunden werden müssen. Daher sollte das Einlesen dieser Datentypen automatisiert werden. 

Dafür müsste das gesamte Java-Projekt nach Klassen, die mit `@DSLType` markiert sind durchsucht werden und für diese Klassen muss an dieser [Stelle](https://github.com/Programmiermethoden/Dungeon/blob/master/dsl/src/runtime/GameEnvironment.java#L137-L154) `typeBuilder.createTypeFromClass` aufgerufen werden. 

@AMatutat das SHK-Label kommt daher, dass es hier prinzipiell nicht um funktionale Entwicklung der DSL geht, sondern um eine Hilfsfunktion

**Comment by JudiTeller** [comment]
Ich hab mal eine erste Iteration hierfür im jetzt gelinkten Branch geschrieben.
Leider weiß ich nicht, wie ich das genau testen könnte, ob die Klassen korrekt geladen werden :sweat_smile:

**Comment by JudiTeller** [comment]
Aktuell gibts noch Probleme mit den relativen Pfaden zu contrib und core unter game/src
und ich baue gerade noch Methoden mit ein, dass ich aus der File den fully qualified name der Klasse rausziehen kann.

**Comment by JudiTeller** [comment]
Ok die Probleme sind soweit gefixt
aktuell werden die 6 Klassen gefunden, die vorher hardcoded waren (QuestConfig.class, Entity.classPosition Component.class VelocityComponent.class AIComponent.class CollideComponent.class) plus zusätzlich die HealthComponent.class

der Aufbau ist gerade noch etwas unschön, vorallem das mehrfache Einlesen des Codes der jeweiligen Files, aber für ein Konzept sieht es so aus, als ob es funktioniert :D

**Comment by malt-r** [comment]
Das sieht schon ziemlich gut aus :+1: Eine Frage, die ich mir aktuell stelle, ist, ob das auch im ausgelieferten Programm funktioniert und wie sich das da mit den Dateipfaden verhält (sind die Dateien auch in dem `.jar` enthalten?). Um das abzuschätzen, stecke ich aber ehrlichweise nicht tief genug in der Java-Welt drin.
Und einen Änderungswunsch hätte ich, nämlich, dass die [Methode `loadClasses`](https://github.com/Programmiermethoden/Dungeon/compare/master...la/read_dsl_type#diff-413b424ba3c96e2a1d840b8d7b6d831c580f97d4735bcaeae8f760f0860e3930R72-R89) nach unterschiedlichen Annotationen filtern kann (also bspw. auch `DSLTypeAdapter`).

**Comment by malt-r** [comment]
@JudiTeller wie ist hier der Stand?

**Comment by JudiTeller** [comment]
Mit dem aktuellen Stand können auf jeden Fall schon nach beliebigen Annotations gesucht werden.
Es wird fest in core und contrib nach den Klassen gesucht.

Es wird aber aktuell nur funktionieren, wenn direkt per gradle gestartet wird.

In #818 werden wir noch allgemein einen Fileread einbauen, der automatisch zwischen .jar compiled / nicht compiled unterscheiden werden kann.
Darauf können wir hier dann noch erweitern.

**Comment by AMatutat** [comment]
Auf #818 warten, dann sollte das gehen

**Comment by AMatutat** [comment]
ich pack hier mal das later dran, wegen der Abhängigkeit mit #818

**Comment by malt-r** [comment]
Das hier gehört nicht wirklich in den [Taskbuilder](https://github.com/Programmiermethoden/Dungeon/milestone/40)-Milestone, eher zu einem "General/Convenience"-Milestone, den es (noch) nicht gibt.
