### ISSUE TITLE
[Doc] `EncapsulatedObject` angemessen dokumentieren

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#703]
Folgende Notizen stammen aus #328, sind allerdings aktuell nicht high-prio:

- Sequenzdiagram für die Erstellung von `EncapuslatedObject`s
- Dokumentation, welche Relevanz das in der
  [Funktionsschnittstelle - Issue #97](https://github.com/Programmiermethoden/Dungeon/issues/97) hat
  und wie das umgesetzt wird
    - Notizen dazu: Das ist insbesondere mit Hinblick auf die Schnittstelle zwischen Dungeon und DSL
      entstanden, da wir irgendwann mal vor der Herausforderung stehen, Event-Handler
      Methoden, die in der DSL definiert sind, vom Dungeon aufzurufen
    - Die Idee für diesen Fall ist, dass (bevor die eigentliche Interpretation
      der Funktion beginnt) das "nackte" Java-Objekt, das vom Dungeon übergeben wird,
      in eine `EncapsulatedObject` verpackt wird, was sich nach außen wie ein
      `IMemorySpace` verhält
    - Dabei wird der DSL-Datentyp, der die nackte Java-Klasse repräsentiert mit dem
      `EncapsulatedObject`  zusammen als AggregateValue gespeichert
    - Damit muss der `DSLInterpreter` gar nicht wissen, was da eigentlich für ein
      Objekt hintersteht -> über den DSL-Typ, den es für das "nackte" Java-Objekt gibt,
      ist bekannt, auf welche Member eines `Encapsulated`-Objekts zugegriffen werden
      kann

Darüber hinaus ist die Funktionalität von `EncapsulatedObject` bisher nicht stabil implementiert und getestet, sodass eine umfassende Dokumentation der Klasse aktuell nicht sinnvoll ist.

**Comment by AMatutat** [comment]
hab diese issue falsch verlinkt gehabt, sorry

**Comment by malt-r** [comment]
Das ist zeitlich nicht mehr drin.
