### ISSUE TITLE
[DSL] Aufgabenabhängigkeiten in Petri-Netz übersetzen

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#706]
In #653 werden die Konzepte zu der Übersetzung von Aufgabenabhängigkeiten in Petri-Netze festgehalten.
Die Übersetzung muss implementiert werden.

**Comment by AMatutat** [comment]
![image](https://github.com/Programmiermethoden/Dungeon/assets/32962412/b8d3500f-7cd5-4148-bae4-84b6ea4f61e0)

**Comment by AMatutat** [comment]
Ich muss die Schablonen nochmal genau untersuchen,
bisher bin ich immer von "einheitlichen" Kanten ausgegangen, sprich alle kanten die von t1 rausgehen sind vom selben typen.
Denkbar wäre ja aich t1->t2 (st_m),  t1->t3 (st_s). t1->t4 (st_o)

**Comment by AMatutat** [comment]
Villeicht um meine Grundidee nochmal festzuhalten:

Ich möchte eine Schablone für die Darstellung eines beliebigen Task als Petr Netz finden. 
Dann könnte man im ersten Schritt erstmal jeden Task "auflösen" sprich in diese schablone gießen.
Dann verbindet man die einzelnen Netze abhängig von der Beziehung zueinander.
Mein Gendanke ist, die Transition als mögliche Docking-Punkte zu verwenden.
Wenn ich also t1 mit t2 verbinden will, würde ich etwa sagen müssen `t1.connect(CORRECT,t2.ACTIVE)`
Was soviel bedeuten würde wie: verbinde die Transition "CORRECT" aus t1 mit der Transition "ACTIVE" aus t2 (dafür muss dann eine Stelle angelegt werden). 

Das wäre dann die Art und Weise wie eine Bedingte Folgeaufgabe realisiert werden könnte. 

Das muss man nun für jede Möglichkeit mal durchspielen und dafür sorgen das die Schablone entsprechend gestaltet ist.

**Comment by AMatutat** [comment]
fixed in https://github.com/Programmiermethoden/Dungeon/pull/1052 aber war falsch verlinkt
