### ISSUE TITLE
[DSL] Konzept zur Interpretation von Petri-Netzen zur Laufzeit

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#707]
In #653 werden die Konzepte zu der Übersetzung von Aufgabenabhängigkeiten in Petri-Netze festgehalten.

Es muss zusätzlich ein Konzept für die Interpretation dieser Petri-Netze zur Spiellaufzeit entwickelt und festgehalten werden.

**Comment by AMatutat** [comment]
@malt-r ist das noch aktuell?
Irgendwie klingt das nach mehr als wir machen, oder verstehe ich das Issue falsch?

**Comment by malt-r** [comment]
Mit "Interpretation der Petri-Netze zur Laufzeit" ist gemeint, dass es "irgendeine" Instanz geben muss, welche die Petri-Netze zur Spiellaufzeit "ausführt". Ursprünglich war der Gedanke, dass das so aussehen könnte, dass bspw. jeden Frame (oder in einer fest definierten Zykluszeit) für alle Transitionen geprüft wird, ob sie feuern können. Das ist ja aber in den implementierten Petri-Netzen anders umgesetzt (https://github.com/Programmiermethoden/Dungeon/pull/994), daher würde ich das hier auch mal zumachen.

**Comment by AMatutat** [comment]
> Mit "Interpretation der Petri-Netze zur Laufzeit" ist gemeint, dass es "irgendeine" Instanz geben muss, welche die Petri-Netze zur Spiellaufzeit "ausführt". Ursprünglich war der Gedanke, dass das so aussehen könnte, dass bspw. jeden Frame (oder in einer fest definierten Zykluszeit) für alle Transitionen geprüft wird, ob sie feuern können. Das ist ja aber in den implementierten Petri-Netzen anders umgesetzt (#994), daher würde ich das hier auch mal zumachen.

Um das "anders umgesetzt" kurz hier zu erläutern: Das Petri-Netz wird zu beginn einmal in der `Main` angestups und danach agieren die `Task`s mithilfe des Observer-Pattern auf das Netz (und die Tasks werden von Callbacks angestupst (z.B Interaction-Callback)). Intern arbeitet das Petri-Netz auch mit dem Observer-Pattern. Transitionen observieren Stellen.
