### ISSUE TITLE
[GAME] better API for Item use

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#715]
@AMatutat api: das sollte direkt per `item.onUse()` gehen!

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/710#discussion_r1216987103_

Die Situation müsste einmal analysiert und ausgewertet werden. Ist das ein sinnvoller Vorschlag oder ist der gegebene Code "unnötig" wirr und wir haben bereits eine einfachere Schnittstelle dafür.

---

Edit: Der ursprüngliche Code war dieser: `item.getItem().getOnUse().onUse(Game.getHero().orElseThrow(), item.getItem())`. Das taucht im Kunden-Code dutzende Male hintereinander auf und wirkt unnötig komplex. Im Prinzip sollte es auf dem Typ von `item` eine neue Methode `onUse(a,b)` geben, die einfach intern `this.getItem().getOnUse().onUse(a, b)` aufruft.

**Comment by fwatermann** [comment]
@AMatutat dafür gibt es doch `ItemData#triggerUse(Entity)` oder bin ich jetzt hier verwirrt was hier gemeint ist?

**Comment by cagix** [comment]
> @AMatutat dafür gibt es doch `ItemData#triggerUse(Entity)` oder bin ich jetzt hier verwirrt was hier gemeint ist?

@fwatermann bin nicht sicher, ob das wirklich die lösung ist.

was ich meinte (und was @AMatutat leider nicht in das ticket geschrieben hat): wir erzwingen ziemlich häufig im kundenseitigen code das furchtbare konstrukt `item.getItem().getOnUse().onUse(a, b)`. 

es soll geprüft werden, ob man nicht eine api anbieten kann, die das für die kunden auf `item.onUse(a, b)` verkürzt. intern in item müsste imho beim aufruf von `item.onUse(a, b)` einfach nur auf `this.getItem().getOnUse().onUse(a, b)` umgeleitet werden.

**Comment by cagix** [comment]
Verstehe ich grad nicht. Wir hatten `ItemData`, um die Kerneigenschaften eines Items zu kapseln, damit ich den Übergang Item -> Inventar und andersrum hinkriege. Im Inventar habe ich also `ItemData`, außerhalb ist es eine `Entity` (oder?). 

Ich bin "damals" (anfangs des Semesters) mehrfach über das obige Konstrukt gestolpert, wobei ich nicht mehr weiß, welchen Typ die Variable `item` hatte.

**Comment by fwatermann** [comment]
> Ich bin "damals" (anfangs des Semesters) mehrfach über das obige Konstrukt gestolpert, wobei ich nicht mehr weiß, welchen Typ die Variable `item` hatte.
> 
> Edit: Im verlinkten Kommentar sehe ich, dass der Typ ein `InventoryItem` war.

Ja die InventarGUI und CraftingGUI steht bei mir als nächstes auf dem Plan, jedoch habe ich eigentlich nicht vor das so zu übernehmen wie es aktuell im Branch `ah_dk/InventarGUI` der Fall ist. Daher soll es später, wenn alles so klappt, wie ich mir das gerade vorstelle, keine extra `InventoryItems` geben.

> Im Inventar habe ich also `ItemData`, außerhalb ist es eine `Entity` (oder?).
Jein. Es gibt ja kein Extra Item-Entity nur das `ItemComponent` was ein `ItemData`-Objekt an ein Entity klebt.
