### ISSUE TITLE
[GAME] Nutze Class.cast in Entity.getComponent und mache den extra Cast überflüssig

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#718]
Siehe https://github.com/Programmiermethoden/Dungeon/pull/702/files#r1218892029:

`Class` bietet eine `cast`-Methode an. Damit können wir das `getComponent` umbauen:
```java
// allgemeines Beispiel
<T> T getComponent(Class<T> cls) {
    Object o;
    // snip
    return cls.cast(o);
}

// Entity#getComponent
public <T extends Component> Optional<T> getComponent(Class<T> klass) {
    return Optional.ofNullable(klass.cast(components.get(klass)));
}
```

Und dann können wir uns dieses bescheuerte Casten bei der Abfrage sparen! Es wird dann mit:
```java
public class MissingComponentException extends NullPointerException {
    ... 
    public static <T extends Component> MissingComponentException newMissingComponentException(final Entity entity, final Class<T> klass) {
        return new MissingComponentException(
            entity.getClass().getName() + "is missing " + klass.getName()
        );
    }
}
```

aus
```java
        PositionComponent x = (PositionComponent)
            entity.getComponent(PositionComponent.class)
                .orElseThrow(
                    () ->
                        new MissingComponentException(
                            entity.getClass().getName()
                                + "is missing PositionComponent"));
```

ein schlichtes
```java
        PositionComponent y =  entity.getComponent(PositionComponent.class)
            .orElseThrow(() -> MissingComponentException.newMissingComponentException(entity, PositionComponent.class));
```

Edit: Schiebe die Builder-Methode direkt nach `MissingComponentException`. Kein Grund, das in `PositionComponent` zu haben. So kann man das für alle Components nutzen :)

**Comment by cagix** [comment]
Der Dank für das Wiederauffinden von `Class.cast` geht an @AHeinisch  :)

**Comment by cagix** [comment]
.o0( Wenn man dann noch `PositionComponent.newMissingPositionComponentException` irgendwie nett kürzer schreiben könnte, dann würden auch die vom Formatter erzwungenen Umbrüche wegfallen )

**Comment by AMatutat** [comment]
> Edit: OK, da wir das T an sich gar nicht brauchen, müsste auch einfach public static MissingComponentException newMissingComponentException(final Entity entity, final Class<? extends Component> klass) gehen ... 

Das war nämlich auch mein Gedanke, aber es sah so gewollt aus

**Comment by cagix** [comment]
> > Edit: OK, da wir das T an sich gar nicht brauchen, müsste auch einfach public static MissingComponentException newMissingComponentException(final Entity entity, final Class<? extends Component> klass) gehen ... 
> 
> 
> 
> Das war nämlich auch mein Gedanke, aber es sah so gewollt aus

kam vermutlich im überschwang von der modifikation bei getComponents, dort macht es nämlich durchaus sinn und ich hab nicht weiter drüber nachgedacht...
