### ISSUE TITLE
[GAME] Errorhandling Konzept erstellen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#719]
Im Framework werfen wir an der ein oder anderen stelle Exceptions.
Die typischsten sind hierbei
* `MissingComponentException` wenn eine Entität ein erwartetes Component nicht beinhaltet
* `MissingHeroException` wenn im Spiel kein Hero registriert ist. 
* Unterschiedliche `IOException`s, vorallem beim einladen und erstellen der assets.

DIe ersten beiden werfen wir meist direkt über das Optional `orElseThrow`.
Die IO-Exceptions reichen wir solange hoch, bis es nicht mehr geht und stürzen dann im catch block ab.  Muss das so sein? Muss das Spiel wirklich abstürzen, wenn ein Asset nicht geladen werden kann? Muss das wirklich bis nach oben hochgereicht werden, nur um dann abstürzen? 

---

              Nicht so richtig Teil dieses PR, aber es fällt mir grad ins Auge: Wir re-branden den Fehler, aber warum? Der Aufrufer muss jetzt prüfen, ob er `null` zurück bekommen hat. Wir könnten genauso gut die Exception einfach hochreichen und der Aufrufer muss sich eben darum kümmern? Das würde uns den Code einfacher machen und auch die Beschreibung?

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/688#discussion_r1218341141_

Wir sollten bei der Gelegenheit alle solche stellen identifizieren und einheitlich damit umgehen. 

Ebenso sollten wir für Optionals überall konkrete Exceptions werfen, falls diese `null` sind. Aktuell haben wir teilweise noch stellen wie `Game.hero().get()`, das ist unschön.

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
