### ISSUE TITLE
[Game] Systeme können nicht auf Entitäts Änderungen reagieren

### ISSUE THREAD

**Issue by AHeinisch** [Programmiermethoden/Dungeon#727]
Aktuell können Implementierungen von Systemen nicht auf Änderungen von Entitäten reagieren. Es könnte Gründe geben, warum ein System beobachten möchte, ob eine Entität nun von dem System beobachtet wird oder eben nicht mehr.
- [`core.System#addEntity(Entity)`](https://github.com/Programmiermethoden/Dungeon/blob/84e1b9a82872facb6addf5c6fa1f55108cb32a4e/game/src/core/System.java#L101) ist private
-  [`core.System#removeEntity(Entity)`](https://github.com/Programmiermethoden/Dungeon/blob/84e1b9a82872facb6addf5c6fa1f55108cb32a4e/game/src/core/System.java#LL115C27-L115C27) ist final

Dies wurde vermutlich gemacht, weil es zu dem Zeitpunkt keinen Grund für den Zugriff darauf benötigt war. Da jetzt aber z.b. beim Hud ein solcher Fall auftritt, muss dafür eine Idee der Umsetzung erstellt werden.

Zwei grundsätzliche Ideen, die mir dazu einfallen: 
 1. Erstellen von einem Observer-Pattern für die jeweilige Methode
    - Grundverhalten kann nicht verändert werden
 2. Überschreiben in Subklassen erlauben z.b. `HudSystem`
    - direktes abarbeiten bzw. beeinflussen

Wieso brauch z.b. das Hud zugriff:
 - wenn eine Entität mit HudComponente hinzugefügt, wird muss der Dialog(Der UI Inhalt) auf eine Stage gepackt werden, welche alle Ereignisse für die Elemente verwaltet
 - Wenn eine Entität nicht mehr die HudComponente besitzt, muss der Dialog von der Stage genommen werden.

**Comment by cagix** [comment]
@AHeinisch @AMatutat Wir sollten über das Observer-Pattern nachdenken. Aktuell haben wir irgendwie sowas ähnliches eingebaut/umgesetzt, aber vielleicht muss das einfach allgemeiner für Systeme und Entitäten (und Components?) implementiert werden.

**Comment by AHeinisch** [comment]
Einmal was theoretisch was beim HudSystem passieren muss. Damit ich den Code im PR entfernen kann.

` java
        @Override
        private void addEntity(Entity entity) {
            stage.addActor(entity.getComponent(UIComponent.class).map(UIComponent.class::cast).map(UIComponent::getDialog).get());
        }
 
        @Override
        public void removeEntity(Entity entity) {
            entity.getComponent(UIComponent.class).map(UIComponent.class::cast).map(UIComponent::getDialog).get().remove();
        }
`

**Comment by AMatutat** [comment]
Wäre das Observer-Pattern hier nicht over-engineered?

Die Entscheidung, `addEntity` in `System` auf `private` zu setzen, kam daher, dass es woanders nicht gebraucht wird. 
Es spricht erstmal nichts dagegen, dass man sie auf `public` oder `protected` setzt.
Man sollte sich nur überlegen, ob `addEntity` dann nicht vielleicht auch prüft, ob alle Components vorhanden sind, sonst könnte ich als User theoretisch eine kaputten Entität in die Liste werfen. 

Das `removeEntity` als `final` zu markieren, kam auch nur aus dem Gedanken "warum sollte man das überschreiben wollen".
Hänge ich jetzt nicht sonderlich stark dran.

**Comment by AMatutat** [comment]
alternativ könnte man eine 
`Consumer<Entity> onEntityAdd` und `Consumer<Entity> onEntityRemove` zum überschreiben einbauen.

**Comment by AHeinisch** [comment]
Mal weit gesponnen. Welche Consumer wären vielleicht interessant:
 - Consumer<Entity> onEntityAdd
 - Consumer<Entity, Component> onComponentAdd
 - Consumer<Entity> onEntityRemove 
 - Consumer<Entity, Component> onComponentRemove 

Es wäre super, wenn nicht nur ein "Observer" existieren kann.  Dadurch können simple Observer Methoden geschrieben werden. Z.b. onEntityAdd füge in Liste x ein und benachrichtige Nachbarn 

Dies wäre aber jetzt nur aus Sicht der Systeme, da ich gerade irgendwie sehr dort unterwegs bin. Vielleicht gibt es noch andere "Observeables" wie einzelne Komponenten, Updates oder so.

**Comment by AHeinisch** [comment]
> Kannst du mir einen Anwendungsfall geben, wann `onComponentAdd` bzw `onComponentRemove` aus Systemsicht relevant wird, außer beim generellen bestimmen ob eine Entität verwaltet wird oder nicht?

`onEntityAdd` würdest du also beim `System.addEntity` einbauen. Ich hätte gedacht vielleicht es eher beim Game selbst anzusiedeln. Aber im System würde mir für `onComponentAdd` nichts einfallen. Beim `onComponentRemove` würde ich vielleicht beim HudComponent sehen "Komponente X wurde von Entität Y entfernt" daher "entferne Dialog welcher bei Komponente X liegt von der Stage". Aber ja dies könnte auch über Umwege bei `onEntityRemove` passieren. Es muss nur für die Entität ein Zwischenspeicher angelegt werden, mit der Komponente/Dialog, welche in der Entität ja vielleicht nicht mehr vorhanden ist.

**Comment by cagix** [comment]
Wenn ich das richtig sehe, haben wir bisher eine Art automatisches Entfernen einer Entität aus der Liste eines Systems, wenn die "spannende" Component nicht mehr da ist. Wenn wir das zum Überschreiben freigeben, besteht die Gefahr, dass jemand dieses Verhalten kaputt macht. 

Wenn ich @AHeinisch richtig verstehe, müsste das Verhalten im Prinzip umgedreht werden. Die Entitäten sind das "Observable" und die Systeme die "Observer". Wenn sich in einer Entität etwas an den Components ändert (Hinzufügen, Entfernen, Modifizieren), müsste die Entität dann die registrierten Systeme benachrichtigen und die Systeme könnten dann eine entsprechende Aktion durchführen (sich als Observer auslisten lassen oder die Sachen der Entität von der Stage werfen ...).

D.h. man hätte sowas wie
```
Game.frame():
    systems.foreach().update()            // lass alle Systeme auf "ihren" Entitäten arbeiten
    entities.foreach().notifyObservers()  // die Entitäten sagen ihren Systemen über Änderungen an Components Bescheid; die Systems finden dann individuell heraus, ob neue oder gelöschte Components oder Modifikation der Werte der Grund waren und reagieren darauf
```
??? 


Oder müssen Systeme auch andere Systeme "überwachen" können?

**Comment by AMatutat** [comment]
> müsste die Entität dann die registrierten Systeme benachrichtigen und die Systeme könnten dann eine entsprechende Aktion durchführen 

Das klingt für mich so doppelt gemoppelt.
Die Entität sagt ja schon `Game` das es sich verändert hat und `Game` sagt den `System`en über `showEntity` bescheid.
Also eigentlich haben wir schon das Observer-Pattern drinne, nur weiß der Beobachte nicht, wer ihn beobachtet (creepy). 


Für mich scheinen sperate Consumer irgendwie die eleganteste Lösung zu sein.

**Comment by cagix** [comment]
hmmm, ja. ist doppelt und von hinten durch die brust ins auge (oder so).

bin grad nicht sicher, ob ich das mit den consumers richtig verstehe. das sind callbacks, die in der defaultimplementierung aufgerufen werden (und dort einfach eine leere implementierung haben) und die in den ableitenden systemen bei bedarf geeignet gesetzt werden können, oder? dann sollte das passen 😆

**Comment by AMatutat** [comment]
yes, so wäre mein gedanke gewesen.

In #688 haben wir das für `onFrame` und `onLevelLoad` auch gemacht

**Comment by AHeinisch** [comment]
Danke werde da weiter machen danke schon mal
