### ISSUE TITLE
[Workflow] Github action kontrollieren wegen SSL handshake error 40

### ISSUE THREAD

**Issue by AHeinisch** [Programmiermethoden/Dungeon#728]
Dies scheint zu passieren, wenn ein Server mehrere Namen hat. Sorgt aber dafür, dass die CI fehlschlägt. Dies kann zu Verwirrungen führen.

Wir nutzen ja eigentlich keine selbst geschriebenen Github actions daher unsicher, ob wir das überhaupt Lössen können.

**Comment by cagix** [comment]
@AHeinisch An welcher Stelle schlägt es fehl? Ist das immer dieselbe Stelle/Action? Dann sollten wir im Repo dieser Action ein Ticket aufmachen mit einer möglichst präzisen Beschreibung.

**Comment by AMatutat** [comment]
Ich versteh nur Bahnhof.
Mag mich wer abholen?

**Comment by AHeinisch** [comment]
![image](https://github.com/Programmiermethoden/Dungeon/assets/32952411/fabfd395-dbcb-4953-9f9d-bcbadda8dc5c)
https://github.com/Programmiermethoden/Dungeon/actions/runs/5241916204/jobs/9464635881
aktuell kann es random zu einen SSL Fehler kommen dies ist aber soweit ich das sehe außerhalb unserer Macht. Leider finde ich aktuell keine wirklichen Auslöser dafür Vielleicht wenn zu viele Pushes in einem kleinen Zeitfenster kommen. Bin ich aktuell am Suchen ob ich es "Fast" konsistent reproduzieren kann. Noch ohne erfolg.

**Comment by AMatutat** [comment]
Das liegt an dem hier, richtig?

```
            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@v1
```

Die Frage ist: Brauchen wir das?
Ich hab mir mal grade flott den [Blog-Eintrag](https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action) zu der Action durchgelesen und der Anwendungsfall, dass externe den Wrapper aktualisieren, haben wir (noch) nicht.

**Comment by cagix** [comment]
> Das liegt an dem hier, richtig?
> 
> ```
>             -   name: Validate Gradle wrapper
>                 uses: gradle/wrapper-validation-action@v1
> ```
> 
> Die Frage ist: Brauchen wir das? Ich hab mir mal grade flott den [Blog-Eintrag](https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action) zu der Action durchgelesen und der Anwendungsfall, dass externe den Wrapper aktualisieren, haben wir (noch) nicht.

wenn es das ding wirklich ist: raus damit. ich habe eh nie verstanden, warum wir das hier drin haben. irgendwer hatte früher mal auf die beispiele von github gezeigt und dort wird es verwendet, aber auch nicht erklärt. 

wir sind die einzigen, die den wrapper aktualisieren. warum sollte der jedesmal validiert werden müssen?

**Comment by cagix** [comment]
PS: Ich würde sowieso keinen PR von "draußen" akzeptieren, der mir einen Binärklumpen modifiziert. Wegen mir kann das wirklich weg.
