### ISSUE TITLE
[Org] Paper auch auf GitHub hochladen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#745]
Wollen wir Paper `.pdf`s im öffentloichen GitHub-Repo hochladen?
Wenn ja: Welche Filterkritierien sollen beachte werden?
Was muss bzgl. möglicher Lizenzen beachtet werden?

**Comment by AMatutat** [comment]
@cagix ping.

Wir hatten da mal im Meeting drüber gesprochen, aber nie final entschieden was wir machen wollen.
Time to make a decision.

**Comment by cagix** [comment]
das kam von mir, finde ich immer noch gut.

filter: zumindest alle paper, die unter cc-by-sa sind. eigentlich sollten das alle paper sein? (dito "drüben" im d2g bei @AKirsch1).

dazu könnte es einen ordner 'paper/' geben. 


offene fragen:
- kopieren wir nur die pdf oder auch die quellen?
- das repo ist unter 'mit', die paper unter 'cc by-sa'. 
- namens-schema für die pdf.

im prinzip könnte man sowas wie 'y-m-d_tagung_titel.pdf' machen. 

die cc-by-sa-license.md in den 'paper/'-ordner kopieren und im readme unten eine klarstellung einbauen ("except ..."). und man müsste im toplevel-license irgendwie einen schalter einbauen (ala crafting-interpreters)?

die quellen wären irgendwie auch interessant, dann wäre das selfcontained. aber auch deutlich mehr doppelung?

@AMatutat was denkst du?

**Comment by AMatutat** [comment]
> offene fragen:
> 
> * kopieren wir nur die pdf oder auch die quellen?
> * das repo ist unter 'mit', die paper unter 'cc by-sa'.
> * namens-schema für die pdf.
> 
> im prinzip könnte man sowas wie 'y-m-d_tagung_titel.pdf' machen.

find ich gut. 

> 
> die cc-by-sa-license.md in den 'paper/'-ordner kopieren und im readme unten eine klarstellung einbauen ("except ..."). 

klingt sinnvoll. 

> und man müsste im toplevel-license irgendwie einen schalter einbauen (ala crafting-interpreters)?

da versteh ich nicht ganz was du willst. 

> die quellen wären irgendwie auch interessant, dann wäre das selfcontained. aber auch deutlich mehr doppelung?

Die Paper werden nicht mehr bearbeitet, also reichen aus meiner Sicht die PDF-Files und dann sind die jeweiligen Quellen IM pdf eingebunden. 

Andere Frage: Wir haben auch einige Puplikationen ohne Paper und nur mit abstract + Präsentation (UFF,DaaD, ..?), was machen wir mit denen?

**Comment by cagix** [comment]
> > und man müsste im toplevel-license irgendwie einen schalter einbauen (ala crafting-interpreters)?
> 
> da versteh ich nicht ganz was du willst.

ala https://github.com/munificent/craftinginterpreters/blob/master/LICENSE

normalerweise steht da der text zu genau einer lizenz drin. wenn nun aber ein repo unter mehreren lizenzen steht, müsste das nach meinem verständnis auch in dieser datei (bei uns `LICENSE.md`) entsprechend eingetragen werden.

Mir ist nur nicht klar, wie Github damit umgeht. So lange das exakt eine Lizenz ist und mit dem Github bekannten Template übereinstimmt, wird im Repo entsprechend "MIT" oder "CC BY-SA 4.0" o.ä. angezeigt. In dem Moment, wo man die Datei modifiziert, ist mir nicht klar, was GH dann anzeigt.

zusätzlich haben wir unten im `Readme.md` ja auch noch den Lizenz-Schnipsel, wo man das anpassen müsste.

> 
> > die quellen wären irgendwie auch interessant, dann wäre das selfcontained. aber auch deutlich mehr doppelung?
> 
> Die Paper werden nicht mehr bearbeitet, also reichen aus meiner Sicht die PDF-Files und dann sind die jeweiligen Quellen IM pdf eingebunden.

quellen im sinne der ausgangsmarkdown-datei und/oder der einzelnen abbildungen und/oder einer PPTX/Keynote ... 

einerseits wäre es schön, hier alles zusammen zu haben, andererseits (a) bearbeiten wir das hier nicht (mehr) und (b) wäre es eine doppelung der sourcen.

> 
> Andere Frage: Wir haben auch einige Puplikationen ohne Paper und nur mit abstract + Präsentation (UFF,DaaD, ..?), was machen wir mit denen?

dann kommt das eben rein. für mich sind poster und präsentationen an der stelle äquivalent zu papers (ist das der richtige denglische plural?).
