### ISSUE TITLE
[Publikation] Related Work "Designing an Educational Game Evaluation Framework Based on Game Mechanics"

### ISSUE THREAD

**Issue by AKirsch1** [Programmiermethoden/Dungeon#749]
Ich habe ein interessantes Paper gefunden, in dem ein Framework beschrieben wird, mit dem die Qualität eines Educational Games bewertet werden kann. Das könnte für unsere Evaluation interessant sein.

[Designing an Educational Game Evaluation Framework Based on Game Mechanics](https://ieeexplore.ieee.org/document/9527418)

PS: Ist es eigentlich sinnvoll, für solche Sachen Issues zu erstellen? Oder soll ich die besser per Discord oder so verschicken?

**Comment by cagix** [comment]
> [Designing an Educational Game Evaluation Framework Based on Game Mechanics](https://ieeexplore.ieee.org/document/9527418)

schick! 👍 


> 
> PS: Ist es eigentlich sinnvoll, für solche Sachen Issues zu erstellen? Oder soll ich die besser per Discord oder so verschicken?

Discord? Im Prinzip könnte das direkt in die "Related Work"-Sektion. Aber da das in diesem Fall @AMatutat machen muss, ist ein Ticket der richtige Weg :)

**Comment by AKirsch1** [comment]
> Discord? Im Prinzip könnte das direkt in die "Related Work"-Sektion. Aber da das in diesem Fall @AMatutat machen muss, ist ein Ticket der richtige Weg :)

Discord an @AMatutat direkt meinte ich (Alternative wäre Mail, aber das ist dann auch Quatsch).  Ich will das nur nicht selber ins Related Work schreiben, wenn es nicht D2G ist, weil 1. bekommt es sonst keiner mit und 2. ist es vielleicht auch nicht so relevant für euch wie ich dachte. Aber dann mache ich das weiter als Issues.

**Comment by cagix** [comment]
@AKirsch1 Ja, bitte keine Kommunikation über andere Kanäle, bitte nur hier auf Github (oder im Meeting). Am Ende findet man sonst nix mehr wieder, und es bekommen dann immer nur ausgewählte Personen mit.

**Comment by AMatutat** [comment]
Ich hab mir das jetzt mal zu Gemüte getan (eigentlich in der Hoffnung ein paar Sachen für unsere Evaluation mitnehmen zu können).

Das Ziel des Paper ist eigentlich recht cool, die wollen eine Objektives Bewertungsmatrix (keine Ahnung warum die das unbedingt Framework nennen wollten) für Education-Games erstellen.
Was sie gemacht haben, ist aber eher eine Liste an "Features" aufgestellt die (aus teilweise undurchsichtigen gründen) einen Mehrzweck für Education-Games liefern (sollen). 

Die Bewertung besteht dann im Abhaken welche Features ich habe und welche nicht, dabei spielt es keine Rolle ob das Feature jetzt gut oder schlecht umgesetzt ist.
Eine Verbindung zu den eigentlichen Ziel von Education-Games (also das Lernen) konnte ich (obwohl diese dauernd erwähnt wurde) in der Bewertungsmatrix nicht finden.


tldr: Ich find das doof (oder ich bin zu doof es zu verstehen).

**Comment by cagix** [comment]
Hmmm. Ich würde es trotzdem mit aufnehmen, zusammen mit Deinem Kommentar.
