### ISSUE TITLE
[GAME] ProtectOnAttack `peek` vs `filter` überdenken

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#751]
Ich verstehe den Sinn von diesem `peek` nicht: Du beschwerst Dich hier im Stream (!), wenn eine Entität keine `HealthComponent` hat - d.h. eigentlich möchtest Du eine Filter-Operation, die nur noch Entitäten mit `HealthComponent` übrig lässt für die Verarbeitung in `forEach`?

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/722#discussion_r1232204446_

**Comment by cagix** [comment]
Hmmm, das wirft für mich die neue Frage auf, warum ein Monster nur Entitäten mit HC beschützen kann? Kann es nicht auch eine Kiste beschützen?

Ich finde den `peek` nicht so gut lesbar an der Stelle (deshalb meine Nachfrage) - und traditionell ist das eher zum Debuggen gedacht wg. der Nebenwirkungen. Ich glaube, ich hätte dann lieber nach "hat keine HC" gefiltert und mit `count()` abgeschlossen und die Exception außerhalb der Stream-Operation geworfen, wenn das Ergebnis nicht leer ist. Danach könnte man das `add()` machen.

Also irgendwie so (nur als Idee: kompiliert nicht, weil mir eine der "kaputten" Entitäten fehlt): 

```java
        long hasHC = entities.stream()
            .flatMap(e -> e.fetch(HealthComponent.class).stream())
            .count();
        if (hasHC < entities.size()) throw new MissingComponentException.build(???, HealthComponent.class));

        toProtect.addAll(entities);
```

Oder sowas (sollte laufen):

```java
        List<MissingComponentException> missingHC = entities.stream()
            .filter(e -> e.fetch(HealthComponent.class).isEmpty())
            .map(e -> MissingComponentException.build(e, HealthComponent.class))
            .collect(Collectors.toList());
        if (missingHC.size() > 0) throw missingHC.get(0);

        toProtect.addAll(entities);
```

Oder sogar so (auch wenn dann noch im Stream throw aufgerufen wird):

```java
        entities.stream()
            .filter(e -> e.fetch(HealthComponent.class).isEmpty())
            .map(e -> MissingComponentException.build(e, HealthComponent.class))
            .forEach(mce -> { throw mce; });

        toProtect.addAll(entities);
```

**Comment by JudiTeller** [comment]
Wenn ich das richtig verstehe, adden wir hier sowieso alle entities, nur wird für alle ohne HC eine Exception geworfen?

**Comment by AMatutat** [comment]
> Wenn ich das richtig verstehe, adden wir hier sowieso alle entities, nur wird für alle ohne HC eine Exception geworfen?

Klingt irgendwie nach unfug, oder? 
Ich hätte jetzt sowas wie
For each Entity
Wenn HC da -> add 
Wenn HC nicht da -> throw MCE 

erwartet
