### ISSUE TITLE
[Game] isIDSmallerThen moven oder Entity Comparable implementieren

### ISSUE THREAD

**Issue by AHeinisch** [Programmiermethoden/Dungeon#754]
Hmmm, für mich klingt es immer noch nach Feature-Neid :) ... Die Methode operiert eigentlich nur auf den (inneren) Daten der übergebenen Parameter. Ich glaube, das wäre besser in `Entity` angesiedelt. Und wenn Du schon dabei bist, könnte man überlegen, ob man das im Rahmen von `Comparable` und Co macht?

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/753#discussion_r1233277270_

Das CollisionSystem hat eine Methode `isIDSmallerThen(Entity, Entity) : boolean` welche genutzt wird, um nur Entitäten zu vergleichen, wo die zweite eine größere ID ist. Dabei ist dann die Frage aufgekommen, ob dies nicht bei der Entität implementiert werden soll oder ob dort z.b. Comparable implementiert werden soll.

**Comment by AMatutat** [comment]
Nach  Absprache: Comparable mit ID Vergleich
` return id-other.id`
