### ISSUE TITLE
[GAME] Pause Funktion

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#76]

**Comment by malt-r** [comment]
Wir könnten alternativ auch darüber nachdenken, ob nicht einfach alle interaktiven UI-Elemente (Textboxen, evlt. Pop-Ups für Questtexte) das Spiel anhalten. Dann würden wir auch ausschließen, dass die Spieler*Innen bei der Texteingabe von Monstern angegriffen werden.

**Comment by AMatutat** [comment]
Ne Pause-Funktion wäre tatsächlich ganz cool und sollte easy in der Umsetzung sein.
Es braucht nur nen `static boolean stopGame` und eine Überprüfung in jeder Update Methode von Entitäten ob das Ding gesetzt ist (evtl sogar im EntityController (den müssen wir dann aber selbst schreiben)

**Comment by AMatutat** [comment]
@Lena241 bitte in dieser Woche bearbeiten.

**Comment by AMatutat** [comment]
evtl ein generelles pausensystem?

**Comment by AMatutat** [comment]
Mit dem ECS könnte das total easy sein. Einfach die Systeme anhalten. Libgdx und non-game Elemente laufen weiter, alles was man so typischerweise pausieren will wird pausiert. 


Umsetzung:
ECS_System um boolean run und entsprechenden Setter/Getter ergänzen. 
Im Systemcontroller vor dem updaten prüfen, ob das entsprechende System an ist. 
Im ECS (Main class) eine CD statische Methode tigglePause() hinzufügen. Die itteriert über alle systeme im Systemcontroller und toggelt das run boolean.

Falls systeme nicht pausiert werden dürfen (keine Ahnung warum, aber vielleicht kommt das Mal vor) einfach den be setter überschreiben.
