### ISSUE TITLE
[GAME] PlayerComponent überdenken

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#760]
@AMatutat Ich bin noch nicht so richtig glücklich mit diesem Design.

(a) Ich muss irgendwo gültige Tastaturcodes herkriegen und hier dezentral speichern und mit einem Callback verknüpfen. (Implizite Abhängigkeit zu libGDX, verstreut über den Code/mehrere potentielle Instanzen von PlayerComponent?)
(b) Ich muss jedesmal alle registrierten Tastaturcodes durchgehen _und_ libGDX fragen, ob einer davon gedrückt wurde. (Aufwand, Abhängigkeit zu libGDX).
(c) Beim Aufruf gebe ich den registrierten Callbacks die Entität mit. Dann stellt sich die Frage, warum ich die Funktionen hier in der Component speichere (wenn sie quasi auch auf anderen Entitäten arbeiten könnten) oder warum ich sie nicht bereits beim registrieren "personalisiere" und dann beim Aufruf die Parameter-Übergabe spare?
(d) Warum hat hier die Component so viel aktive Funktionalität und das System ist irgendwie "dumm"? Normalerweise sollte im ECS doch das System die Dinge ausführen und die Component mehr oder weniger eine Datenhalde sein?
(e) Will man wirklich mit einfachen Integern für die Keycodes arbeiten?

Wie wäre es, wenn man die konkreten libGDX-Tastaturcodes in einer Enum kapselt und hier im Framework nur noch die Enum-Konstanten nutzt? Außerdem könnte das PlayerSystem die Abfrage der gedrückten Tasten machen und die entsprechenden Enum-Konstanten dann hier mit reinreichen. Dann habe ich nur noch an zwei Stellen die Abhängigkeit zu libGDX (Enum, PlayerSystem).

Noch besser wäre es, man würde aus der PlayerComponent heraus eine Reihe von "Commands" erzeugen (Objekte mit einer `execute`-Methode und verknüpft mit einer Entität (dieser hier)) und diese beim PlayerSystem für eine Enum-Konstante (Button, Tastatureingabe) registrieren. Dann könnte das PlayerSystem bei libGDX erfragen, was grad gedrückt wurde und in der internen Map nachschauen, welche Commands für exakt diese Eingabe registriert wurden und für diese dann `execute` aufrufen. => [Command-Pattern](https://www.hsbi.de/elearning/data/FH-Bielefeld/lm_data/lm_1359639/pattern/command.html#command-objektorientierte-antwort-auf-callback-funktionen) plus [Observer-Pattern](https://www.hsbi.de/elearning/data/FH-Bielefeld/lm_data/lm_1359639/pattern/observer.html#observer-pattern-verallgemeinert)

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/758#discussion_r1234219841_
            
Edit: Ergänze (d) und (e) (vgl. https://github.com/Programmiermethoden/Dungeon/pull/758#pullrequestreview-1488406914).

**Comment by cagix** [comment]
auweia. da hab ich wieder was in die luft geworfen.

**Comment by cagix** [comment]
Ich fände es schon gut, wenn wir bei den Refactorings die Trennung zu libGDX auch wieder etwas verstärken könnten. Auch wenn es irgendwie absurd klingt, aber mit der Kapselung der libGDX-Konstanten in einer eigenen Enum würden wir im nutzendem Code nur noch unsere eigenen Strukturen nutzen und die Schnittstelle zu libGDX würde sich an der Stelle auf dieses eine Enum beziehen.

Dito wenn nur noch das System die Schnittstelle zu libGDX abfragt und nicht eine oder ggf. mehrere PlayerComponents. _Wir_ benutzen das Ding nur für den Hero (_derzeit_), aber wer sagt denn, dass nicht auch diverse Kisten oder Schalter eine PlayerComponent mit angepassten Key-Event-Listenern bekommen könnten? Dann hast Du sofort einige Entitäten mit dieser Component und da wäre es nett, wenn die Abhängigkeit zu/von libGDX nicht in jede einzelne Instanz getragen würde.

Im Prinzip sind die "personalisierten" Callbackfunktion bereits Command-Objekte: Es sind Funktionsobjekte, die eine Referenz auf ihren Empfänger (die Entität) enthalten und die man aufrufen kann. Wenn die Dinger beim PlayerSystem registriert werden, könnte das System gezielt auf eine Eingabe reagieren (`Map<Key, List<Function>>`) und müsste nicht erst alle registrierten Enitäten nach ihren Components befragen und diese dann bitten, ihre jeweiligen Key-Event-Listener durchzuiterieren und eventuell eine Funktion auszuführen, die zwar in der Component gespeichert ist, aber wo man dennoch extra noch jedesmal beim Aufruf die betroffene Entität mitgeben muss.

**Comment by AMatutat** [comment]
Irgendwie hast du mich auf einen wirren Gedanken gebracht:
Was ist wäre wenn, jede Taste-Callback Funktion eine eigene Entität wäre (mit einem `KeyActionComponent`)? 
Das `PlayerSystem` wäre dann hinfällig und wir hätten ein `KeySystem`, welches sich dann erst den `Key` aus dem Component holt, prüft ob der gedrückt ist und dann den Callback triggert (direkt, oder indirekt). 

Einen Schritt weitergedacht, baut sich das System die von dir beschriebene Map auf und agiert darauf. Diese muss dann beim registrieren/deregistrieren der Entitäten geupdated werden.

**Comment by cagix** [comment]
> Was ist wäre wenn, jede Taste-Callback Funktion eine eigene Entität wäre (mit einem `KeyActionComponent`)? 

uff. meditieren den gedanken ich werde.

> ein `KeySystem`, welches sich dann erst den `Key` aus dem Component holt, prüft ob der gedrückt ist und dann den Callback triggert (direkt, oder indirekt).

ich würde den schuh anders herum aufziehen: das `keysystem` fragt/prüft, welche taste oder was gedrückt wurde und wendet sich damit an die "empfänger". 

am einfachsten wäre es dann, wenn die callbacks dann bereits in einer dem jeweiligen key zugeordneten liste im `keysystem` stecken würde - dann könnte das `keysystem` einfach all diese callbacks aufrufen. aber das ist nicht mehr ecs, denke ich. 

oder wie beschrieben, es wendet sich mit der aktuellen taste an seine kunden (ob nun entitäten oder components) und bitte diese um den passenden callback und führt die dann der reihe nach aus. das ist ecs und du musst eigentlich kaum irgendwas in deiner struktur wirklich ändern :)

 
> Einen Schritt weitergedacht, baut sich das System die von dir beschriebene Map auf und agiert darauf. Diese muss dann beim registrieren/deregistrieren der Entitäten geupdated werden.

sí.
