### ISSUE TITLE
[GAME] LevelSystem

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#762]
> Hmmm. Der PR fixt die Sym­p­tome. Aber wäre es nicht besser, die Ursache zu beheben? Also welches System auch immer das ist, aber dort eben den Zugriff zu loggern und dann die Entität zu ignorieren und keine Exception mehr zu werfen?

(https://github.com/Programmiermethoden/Dungeon/pull/761#pullrequestreview-1486522520) 

Das ist in keinem System sondern in unserer Kern-Gameloop. Also das bisschen logik was zwischen den System-Loops ausgeführt wird. 

Man könnte jetzt mal überlegen, ob das Teil eines eigenen `LevelLoadSystem` sein sollte oder irgendwie in das `PlayerSystem` integriert werden kann/sollte. 

Aktuell scheint mir das aber alles irgendwie etwas unfug/overkill.  

Edit: Hmm man könnte aus `LevelManger` ein `LevelSystem` machen... Das wäre nochmal etwas mehr struktur umbauen, aber mehr ECS.

**Comment by AMatutat** [comment]
> Ja schon. Aber mir erscheint es auch als Unfug, jetzt an den Symptomen herumzudoktorn statt die eigentliche Ursache zu fixen. Machen wir doch anderen Stellen auch nicht, oder?

In meinen Augen ist #761 nicht "n den Symptomen herumzudoktorn" aber ist ja jetzt auch egal.

Je mehr ich über ein eigenes System dafür nachdenke, desto besser gefällt es mir.
a) könnte ich den ganzen Levelkram aus Game extrahieren und nach `LevelSystem` schieben.
    aa) Würde ich dann auch die API zugriffe verschieben? Also anstelle von `Game.tileAt` ein `LevelSystem.tileAt`?
b) Wieder ein non-ECS Fragment weniger
c) Multiplayer freut sich, da das System auf mehrere Entitäten reagieren könnte, also auch mehrere Spieler das neue Level triggern könnten

**Comment by cagix** [comment]
>  Edit: @Lena241 irgendwie eskalieren deine Tickets immer. xD

@Lena241 Nimm das nicht persönlich. Ich habe das Gefühl, ich bin der verdammte äußere Störfaktor 🙈🤣😺 Manchmal stolpere ich über Dinge, manchmal nicht.

**Comment by AHeinisch** [comment]
Ich laufe gerade wohl im Yagni herum aber wäre es nicht gut wenn auch eine art Liste von onLevelLoader verfügbar sind. 

Nutzen:
- Entitäten hinzufügen nicht in einer riesigen Methode
- Sonderverhalten z.b. Truhen erstellen 
- UI erstellen (HeroUI) welches durchgehend eigentlich offen ist

Aber dies ist vielleicht ein nachfolge Issue oder unrelevant. War mir gerade bei diesen Issue eingefallen ist.

**Comment by AMatutat** [comment]
Verstehe was du meinst.
Würde erstmal YAGNI sagen. 
Außerdem kannst du ja in deiner onLevelLoad einfach ne Reihe an Methoden aufrufen. 
Bei einer Liste müssten wir wieder register/derigster Methoden anbieten und ich weiß nicht, ob das für zweit Semester nicht zu viel wird. Vorallem müsste man eine Reihenfolge der Methodenaufrufe festlegen...
