### ISSUE TITLE
[Doc] Wiki-Eintrag "Zentrales Konferenzverzeichnis" noch relevant?

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#764]
Wir haben Konferenzen in `https://github.com/Programmiermethoden/Dungeon/blob/master/doc/related_work/conferences.md` abgelegt. 

Ist die alte Wiki-Seite [Zentrales Konferenzverzeichnis](https://github.com/Programmiermethoden/Dungeon/wiki/Zentrales-Konferenzverzeichnis) noch relevant?

- [x] Bitte Inhalte abgleichen und ggf. in `doc/` ergänzen.
- [x] Wiki-Seite löschen.

**Comment by AMatutat** [comment]
> Ist die alte Wiki-Seite [Zentrales Konferenzverzeichnis](https://github.com/Programmiermethoden/Dungeon/wiki/Zentrales-Konferenzverzeichnis) noch relevant?

nö. könnte aus meiner sicht weg

**Comment by AMatutat** [comment]
ist alles da, ich lösche

**Comment by AMatutat** [comment]
done
