### ISSUE TITLE
[GAME] Iterator für `Component`s in `Entity`

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#778]
Für Eventhandler aus #197 ist es nötig, dass `Entity`-Instanzen aus dem Dungeon-Kontext in die DSL überführt werden. Dafür muss dynamisch für eine `Entity`-Instanz ermittelt werden, welche `Component`s in der `Entity` enthalten sind.

Aktuell erfordert dies, alle im DSL-Typsystem geladenen Datentypen nach `Component`s zu durchsuchen und für jedes `Component` per `isPresent()`-Aufruf zu überprüfen, ob die Komponent in der Entität enthalten ist. Das ist ziemlich umständlich.

Daher sollte ein Iterator für die Komponenten einer Entität implementiert werden.

**Comment by malt-r** [comment]
@AMatutat kein Assignee?

**Comment by cagix** [comment]
> Für Eventhandler aus #197 ist es nötig, dass `Entity`-Instanzen aus dem Dungeon-Kontext in die DSL überführt werden. Dafür muss dynamisch für eine `Entity`-Instanz ermittelt werden, welche `Component`s in der `Entity` enthalten sind.
> 
> Aktuell erfordert dies, alle im DSL-Typsystem geladenen Datentypen nach `Component`s zu durchsuchen und für jedes `Component` per `isPresent()`-Aufruf zu überprüfen, ob die Komponent in der Entität enthalten ist. Das ist ziemlich umständlich.
> 
> Daher sollte ein Iterator für die Komponenten einer Entität implementiert werden.

@malt-r Ich bin mir nicht sicher, aber das klingt für mich, als ob Du einen Stream deiner Entitäten machen möchtest und mit einem flatMap die gewünschte Component rausholst und dann in einem finalen foreach über die verbleibenen Components im Stream gehen willst und die gewünschte Operation auf die über die Component erreichbaren Entitäten anwenden willst? Oder liege ich da grad ganz weit daneben?

**Comment by AMatutat** [comment]
> @AMatutat kein Assignee?

Bin mir nicht sicher ob ich das mache ohne an eine SHK abdrücke. Eigentlich können die das auch, aber high prio. Falls sich einer der @Programmiermethoden/codrs berufen fühlt, kann er/sie sich das schnappen. Ich assigne mir das um, wenn ich es aktiv angehe.

**Comment by cagix** [comment]
@AMatutat Vorher sollte aber geklärt werden, was wirklich gebraucht wird. Wir arbeiten aktuell vor allem mit Streams - Iterable scheint mir irgendwie so halb parallel zu liegen.

**Comment by AMatutat** [comment]
> @AMatutat Vorher sollte aber geklärt werden, was wirklich gebraucht wird. Wir arbeiten aktuell vor allem mit Streams - Iterable scheint mir irgendwie so halb parallel zu liegen.

@malt-r hmm jetzt wo er es sagt, vielleicht willst du auch einfach einen Stream über alle Components? Also quasi über das Value-Set der HashMap. Dann müsstest du dir natürlich noch selbst raussuchen, welchen Typ das jeweilige Component hat (aber das ist ja ein stumpfes, `getClass`)

**Comment by malt-r** [comment]
Das funktioniert wahrscheinlich genau so gut für mich. *Irgendeine* Möglichkeit, über die enthaltenen `Component`s zu iterieren (in welcher Form auch immer), würde mir da schon weiterhelfen. Wenn im Rest der Codebasis aktuell eher mit streams gearbeitet wird, dann sollten wir das wahrscheinlich hier auch weiter durchziehen.
