### ISSUE TITLE
[GAME] Abhängigkeit zwischen den Tests und den Animationsdateien auflösen

### ISSUE THREAD

**Issue by Lena241** [Programmiermethoden/Dungeon#808]
Was die Tests betrifft: Es scheint, dass wir eine unangenehme Abhängigkeit zwischen den Tests und den Animationsdateien haben. Normalerweise würden wir dafür spezielle Testressourcen im Verzeichnis "/test" anlegen. In diesem Pull Request wäre mir eine schnelle Lösung ausreichend, und dann sollten wir ein separates Issue erstellen, um das Problem auf konzeptioneller Ebene zu beheben.

_Originally posted by @AMatutat in https://github.com/Programmiermethoden/Dungeon/issues/783#issuecomment-1606795709_

**Comment by JudiTeller** [comment]
Ich hab jetzt mal angefangen alle animationpaths der Tests zu den Testresourcen zu leiten
spezifisch werden die in HealthSystemTest, DrawComponentTest und VelocitySystemTest genutzt

beim DrawComponentTest wird aber per DrawComponent::isCurrentAnimation() mit dem vorgegebenen enum CoreAnimation verglichen
Das failed, ich kann nicht ganz nachvollziehen warum

**Comment by AMatutat** [comment]
@AHeinisch hatte hierfür eine Idee

**Comment by AHeinisch** [comment]
Das Problem liegt daran, dass ausgegangen wurde das die Standard Idle Animation die IDLE_LEFT ist. Dies stört dann beim Testen, ob die Animation geändert werden kann. Da dort ein extra Test gemacht wurde, ob die Standard Idle Animation IDLE_LEFT ist. Jedoch, wenn es eine IDLE_DOWN vorhanden ist schlägt der Test mit dem Ändern fehl.


Meine Idee war einfach einen neuen Test oder mehrere einzelne zu erstellen, wo die Standards getestet werden.
- Alle Idles vorhanden
- IDLE_DOWN nicht vorhanden
- IDLE_LEFT nicht vorhanden
- IDLE_RIGHT nicht vorhanden
- IDLE_UP nicht vorhanden
- IDLE nicht vorhanden

Die Reihenfolge habe ich aus dem ctor der DrawComponente genommen. Und keine extra Kontrolle des standard wert mehr im Test für das ändern. Dadurch existiert der Test "core.components.DrawComponentTest#currentAnimation" nur noch um zu testen, ob das Ändern geht und nicht ob auch der Standard gesetzt wird.

**Comment by Lena241** [comment]
Im Grunde waren die Aniamtionen IDLE_DOWN und IDLE_UP nicht nötig. Sie werden im `HealthSystemTest` und `VelocitySystemTest` nicht genutzt und im `DrawComponentTest` wird explizit verlangt, dass sie nicht da sind.

Die Idee von @AHeinisch sehe ich gerade im Moment auch als Overkill. Dazu müssten mehrer Test-Assets-Ordner angelegt werden, wo jeweils eine andere Kombination von Animationen vorhanden sein muss. Im Moment, bei den wenigen Tests, die auf Assets angewiesen sind, würde ich die Anzahl der Test-Assets so gering wie möglich halten.

Auf Dauer, falls es zu einem Problem kommen sollte, wäre es eine Überlegung wert, zu schauen, ob man nicht einen eignen Test-Assets-Ordner für jede Testklasse anlegt.
