### ISSUE TITLE
[GAME] Spiel friert ein, Programm reagiert nicht mehr

### ISSUE THREAD

**Issue by Lena241** [Programmiermethoden/Dungeon#811]
@AMatutat hab jetzt alle verbesserungsvorschläge implementiert, passt jetzt eigenlich alles bis auf einem bug den ich einmal beim testen begegnet bin. Das Spiel ist bei mit aus irgenteinem Grund eingefroren (Fenster wurde weiß, Windows sagt programm reagiert nicht mehr). Da keine exception danach gegeben wird und ich den Bug bis jetzt nicht reproduzieren konnte kann ich nicht sagen, was das verursacht.

_Originally posted by @DaniBor in https://github.com/Programmiermethoden/Dungeon/issues/776#issuecomment-1603910083_

Siehe auch: https://github.com/Programmiermethoden/Dungeon/pull/776#issuecomment-1604268784

**Comment by AMatutat** [comment]
Das Problem ist lange bei niemanden mehr aufgetreten. 
Wir konnten Ihn damals auch nicht richtig reproduzieren.


Ich mach hier dicht und wenn das Problem neu auftritt, können wir hier neu aufmachen
