### ISSUE TITLE
[DSL/GAME] Replacement-Taks Aufgabenelemente in Items konvertierten (Konzept erstellen)

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#814]
Im Meeting vom 03.07 ist die Frage aufgekommen:
Wie werden aus den Elementen der Aufgabenbeschreibung Items im Spiel? Passiert die Umwandlung in der DSL oder im Dungeon per Factory-Methoden? Was ist dann, wenn die Lehrperson definieren möchte, wie das Element als Item aussieht? 

Im Meeting haben wir folgenden Pseudo-Code gekritzelt: 
```
replacment chemie{
    ...
    // regeln -> Rezepte 
    c+o+o  = co2v // c =  pilz  o = Schrifftrolle => in Java?
}

//oder direkt hier Items daraus machen?
converter {
    für jedes Element aus den Regeln
        stell durch crafting item da z.B jedes a ist ein Pilz jedes b eine Paprika   (woher mögliche item-typen nehmen?)
}



item a {
    typ: item
    texture ="/schriftrolle",
    discription "a"
}


Entity item_auf_den_boden
{
    ....
    item_component(a)
}



function kessel_interaction {
    answers = Dungeon.CRAFTING(regeln) //anwers -> Sequenz an Schritten die ausgeführt werden
    callback(answers)
}

entity zauberkessel {
    position_component,
    draw_component("/kessel"),
    interaction_component(kessel_interaction)
    ...
    ...
}

Dungeon.gib(zauberkessel);
```

**Comment by AMatutat** [comment]
@malt-r das ist doch eigentlicb das was wir die Tage zu #903 besprochen haben, oder? 
  

      item_type scroll_type {
            name: ,
            animation1: ,
            animation2: ,
            task_content_component: ,
        }

**Comment by AMatutat** [comment]
@malt-r irgendwie auch die tage besprochen, oder?

**Comment by malt-r** [comment]
Ich würde die gesamte Umsetzung der Ersetzungsaufgaben nach #801 verlagern
