### ISSUE TITLE
[DUNGEON] Dateipfadfilter jar/file extrahieren

### ISSUE THREAD

**Issue by JudiTeller** [Programmiermethoden/Dungeon#818]
In PR #740 hat @fwatermann eine Funktionalität implementiert, die es erlaubt Rezepte aus Klassen zu laden, je nachdem, ob das Projekt direkt per Gradle gestartet, oder zuvor als .jar compiled wurde.

Gemäß [dieser Diskussion](https://github.com/Programmiermethoden/Dungeon/pull/740#discussion_r1250774195) soll diese als eigenständige Klasse extrahiert werden und jegliche Pfade und Arten an Klassen einlesen können.

**Comment by AMatutat** [comment]
könnte auch für #253 interessant sein.

**Comment by AMatutat** [comment]
Für den Meilsten "Einsatz und Verbreitung" habe ich in #953 meine eigenen Methoden geschrieben.
Daher ist das jetzt eher "Cleancode"

**Comment by AMatutat** [comment]
Nachdem ich (und @Lena241) jetzt selbst mit dem auslesen von Dateien aus Jars beschäftigt waren bin ich zum schluss gekommen, dass das Implementierung davon sehr Situationsabhänig ist und sich nicht generalisieren lässt. 
Es macht z.B einen großen Unterschied ob ich. Datein, Datei-Inhalte, Verzeichnisse oder Pfade einlesen will.
