### ISSUE TITLE
[GAME] Kampfsystem implementieren

### ISSUE THREAD

**Issue by Lena241** [Programmiermethoden/Dungeon#823]
Ich mach das mal hier als zusammenfassung:
Ich verstehe die Intention hinter der Abfrage ob der Held kämpft oder nicht, da dies ja auch andere Animationen bedeutet.
Das hat in diesem System aber nichts zu suchen. Das Velocity-System ist nur für Animationen related zur Bewegung zuständig. 
Aktuell haben wir kein System für das Kämpfen (@Lena241 mach dafür mal ein Issue auf)

_Originally posted by @AMatutat in https://github.com/Programmiermethoden/Dungeon/pull/790#discussion_r1241706386_

**Comment by AMatutat** [comment]
Vielleicht ist Kämpfen auch ein SKill, analog zum Feuerball.

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
