### ISSUE TITLE
[GAME] Dokumentation in `/doc` anpassen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#835]
Die Dokumentation des Frameworks in `/doc` ist  veraltet und konzeptionell fragwürdig.
Aus meiner Sicht gäbe es folgendes zu tun:
1. Struktur festlegen
2. Überflüssige Dokumentation entfernen (die JavaDoc erklärt die Components und Systeme)
3. quickstart updaten

@cagix zu 1:
Ich hatte mir überlegt, ob es nicht sinnvoll wäre die `readme.md` weiterhin als Quickstart zu verwenden und zusätzlich zwei Files `for_users.md`. und `for_developer.md` anzulegen.
In den Files würde ich den ganzen kleinkram Dokumentieren wollen, etwas wie ein FAQ.  Eine H3 Header pro Thema/Frage und dann einfach runterschreiben
In `for_users.md` würde das ganze für die Studis (also den Unser des Frameworks) geschrieben werden. Da wäre also viel "Wie geht xyz" (sofern das nicht aus der Javadoc herausgeht)
In `for_developer.md` wäre es für die Entwickler des Frameworks geschrieben. Hier würde ich die kleineren Design-Entscheidungen erklären. 

Ziel wäre für mich, so wenig wie möglich (aber so viel wie nötig) in `/doc` zu haben

**Comment by cagix** [comment]
aufräumen finde ich super. der quickstart könnte gut im readme bleiben, müsste aber vielleicht nochmal etwas gekürzt werden - für ein readme ist mir das etwas lang. 

und es müsste auf alle fälle noch ein abschnitt rein mit den links auf die jeweilige doku (analog zur linksammlung am ende).

die vorgeschlagene trennung ist in etwa das, was @malt-r mit seinem "user-facing" und "dev-facing" verfolgt. auf den dungeon bezogen würden alle derzeit vorhandenen sachen in "user" gehen, und für den dev-kram würde vermutlich nur eine kleine readme übrig bleiben, oder? dann würde ich das eher nicht so strikt trennne/benennen - es reicht ja eine datei "designchoices.md" oder so.

**Comment by AMatutat** [comment]
irgendwie duplicate with https://github.com/Programmiermethoden/Dungeon/issues/962
