### ISSUE TITLE
[GAME] Mathe in Javadoc

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#839]
Für Mathematische Formeln wäre es gut, wenn wir diese in Javadoc gescheit formatiert (Latex?) schreiben und anzeigen könnten. 
Wie geht das am besten in Java?
Brauchen wir externe Tools o.ä, wenn ja welche? 

Beispiel Anwendungsfall siehe https://github.com/Programmiermethoden/Dungeon/blob/master/game/src/contrib/components/XPComponent.java

**Comment by cagix** [comment]
Die Frage ist doch eigentlich gewesen, ob man in Javadoc sowas wie `$\mathrm{x}^2$`, also die TeX-Notation nutzen darf. Oder ob Javadoc da selbst was für anbietet. 

Tools werden wir da nicht brauchen?!

**Comment by AMatutat** [comment]
system ist raus, lohnt nimma
