### ISSUE TITLE
[GitHub] Bounty Label entfernen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#842]
@cagix Da das Semester jetzt vorbei ist, wollen wir die bounty-label entfernen/löschen oder ungepflegt beibehalten?

**Comment by cagix** [comment]
@AMatutat Erster Instinkt: Nö, lass mal dran. Wenn nächstes Jahr davon noch Sachen auf sind, kann ich die direkt verwenden. 

Was spräche aus Deiner Sicht für ein Entfernen zum jetzigen Zeitpunkt? Was spräche dagegen?

**Comment by AMatutat** [comment]
Gegen das Entfernen spricht, dass das Label sonst neu erstellt und verteilt werden muss (im nächsten Semester). Das bedeutet, dass zu Beginn des nächsten Semesters jemand alle Issues überprüfen und prüfen müsste, welche sich für ein Bounty eignen.

Für das Entfernen spricht, dass es aktuell keinen Zweck erfüllt und daher nur als Hintergrundrauschen dient. Die Tickets werden nicht entsprechend dem Bounty-Label aktualisiert. Wenn Teilaspekte gelöst wurden, könnte ein Bounty weniger wert werden, da derzeit niemand darauf achtet. Es werden wahrscheinlich auch keine neuen Labels verteilt. 
=> Am Anfang des nächsten Semesters muss jemand alle neuen Issues überprüfen und prüfen, ob sie sich für ein Bounty anbieten, und die alten Bounty-Issues auf Aktualität überprüfen.

**Comment by cagix** [comment]
ok, in jedem fall muss jemand nächstes jahr drüber, richtig? dann weg damit.

**Comment by AMatutat** [comment]
done
