### ISSUE TITLE
[GAME] Richtigen Umgang mit negativen `DamageModifier` überdenken

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#846]
Nochmal ne blöde Frage von der Seite ;)

Es ist ein Multiplikator, d.h. ich kann auch locker negative Werte reintun. Aber dann kehrt sich alles einmal um, d.h. aus Resistances werden Vulnerabilities und umgedreht, oder?

Soll das so? Oder sollte man gezielt zwei Multiplikatoren anbieten, die beide stets positiv bleiben (per Zwangs-`Math.abs()`) und wo man gezielt von außen hoch- und runterdrehen kann - im Bereich zw. 0 und 100 für beide und intern wird das entsprechend umgerechnet? Oder wird das verwirrender für die Anwender?

Edit: Oder sollten wir das so lassen und nur den Zwangs-`Math.abs()` einführen?

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/pull/829#discussion_r1258220343_

**Comment by cagix** [comment]
@AMatutat ist das wirklich staff:shk? das müsstest du doch durchdenken und dann ansagen? 🤣

**Comment by AMatutat** [comment]
> @AMatutat ist das wirklich staff:shk? das müsstest du doch durchdenken und dann ansagen? 🤣

macht der gewohnheit
