### ISSUE TITLE
[GAME] Virtuelle Größe umbauen Tiles per width 

### ISSUE THREAD

**Issue by AHeinisch** [Programmiermethoden/Dungeon#852]
Aktuell wird die virtuelle Größe anhand der Fensterbreite, geteilt durch die Standard Texturegröße berechnet. Also z.b. 640/16 für die breite. 
Dies sorgt beim Vergrößern und verkleinern dazu, dass mehr oder weniger Tiles angezeigt werden. Um Chancengleichheit zuhaben, sollten die Tiles im Maximum identisch sein.

Daher so wass wie umdrehen der Berechnung. Sodass die virtuelle Größe immer maximal z.b. 32 Tiles in die breite anzeigt und daran sich die virtuellegröße anpasst.

**Comment by AMatutat** [comment]
@AHeinisch magst du dir mal angucken?
@fwatermann könnte das Einfluss auf das HUD haben?

**Comment by AMatutat** [comment]
Entscheidung im Meeting: Machen wir nicht mehr (viel Aufwand, wenig Nutzen)
