### ISSUE TITLE
[DUNGEON] Task Question als TaskContent in Basisklasse speichern

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#862]
an der stelle habe ich überlegt, ob es nicht besser wäre in `Task#taskText` besser als `TaskContent` Objekt zu speichern. 
In diesen konkreten Fall brauche ich, um der Fragestellung einen Typen anzuheften, damit ich weiß ob im der Fragestellung ein Pfad zu einem Bild gespeichert ist und ich diesen im UI extrahieren muss. 

So ist es halt etwas unschön, da ich den `questionText` zweimal Speicher (einmal im `Task` und einmal im `QuizContent`) und ich mir so irgendwie zwei Fragen erschaffe. 

Ich kann aber nicht einschätzen, ob das für die anderen Aufgabentypen auch sinnvoll ist, daher hab ich es erstmal gelassen, wollte es hier aber einmal erwähnen. 

@malt-r aber mal so drüber nachgedacht, eigentlich könnte eine Fragestellung immer ein Text, ein Bild oder Text + Bild sein, oder? Unabhängig vom Aufgabentyp. 
Vielleicht sollte `QuizContentType` ein `ContentType` werden? Allerdings speichern wir aktuell in `abstract ContentType` nichts außer dem `Task` und ich weiß nicht, ob jeder `ContentType` einen `String` braucht. 

_Originally posted by @AMatutat in https://github.com/Programmiermethoden/Dungeon/pull/858#discussion_r1263524243_

**Comment by cagix** [comment]
ein task besteht semantisch immer aus einer question und antwortoptionen o.ä. sowie aus einem auswertemechanismus für das überprüfen der antworten.

ich würde deshalb in betracht ziehen, tatsächlich einen typ `question` zu definieren, der den fragetext plus bild plus ... kapselt. ein `task` **hat** dann eine `question`.

für die antwortoptionen braucht man eine vererbungshierarchie: sc, mc, freitext, ersetzen, ...

der auswertemechanismus ist vermutlich direkt an die antwortoptionen-hierarchie gekoppelt und sollte deshalb vermutlich besser bereits dort modelliert werden.
