### ISSUE TITLE
[DUNGEON] `Quiz.Content.Type` dynamisch bestimmen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#866]
Quizfragen und Antorten können 
- Text ("Test"
- Bilder ("/test.png")
- Text + Bilder ("Das ist ein /text.png Testbild")

enthalten.
Aktuell muss manuell angegeben werden, um welchen Typen es sich bei der jeweiligen Eingabe handelt. 
Dies soll durch ein dynamisches Konzept entfallen. 

Der eingegebene String soll mit regex analysiert werden. 
Dafür werden Bildpfade im String immer mit $ `PATH` $ gekennzeichnet ("Hallo $mein/path.png$ wie gehts?").

Es sollte untersucht werden, ob. das Enum `Quiz.Content.Type` entfernt werden soll (dann müsste der String bei jedem "verwenden" neu analysiert werden) oder beibehalten wird.

**Comment by malt-r** [comment]
Damit das zusammenhängend ist und wir wissen, wo wir herkommen: das hier https://github.com/Programmiermethoden/Dungeon/pull/858#discussion_r1264635750 scheint mir die Ursprungsdiskussion für das Issue zu sein. Korrigiert mich, falls ich das falsch sehe.

**Comment by malt-r** [comment]
So ein Gedanke, der mir grade zum `Quiz.Content.Type` kommt (der ehrlicherweise auch früher hätte kommen können): Wollen wir uns hier wirklich auf Text und Bilder festlegen oder auch Zahlwerte (ganzzahlig und dezimal) zulassen?

**Comment by AMatutat** [comment]
> So ein Gedanke, der mir grade zum `Quiz.Content.Type` kommt (der ehrlicherweise auch früher hätte kommen können): Wollen wir uns hier wirklich auf Text und Bilder festlegen oder auch Zahlwerte (ganzzahlig und dezimal) zulassen?

Müssen wir denn einen unterschied zwischen Zahlenwert und String machen? Ich hätte jetzt gesagt ein Zahlenwert kann ich als String darstellen.

**Comment by malt-r** [comment]
Klar. Nur wenn ich jetzt explizit in einer Bewertungsfunktion den Zahlwert überprüfen will (und diese Information ja aus dem `Content`-Objekt kommen muss), wird das schwieriger, wenn wir alles als String betrachten.

**Comment by AMatutat** [comment]
> Klar. Nur wenn ich jetzt explizit in einer Bewertungsfunktion den Zahlwert überprüfen will (und diese Information ja aus dem `Content`-Objekt kommen muss), wird das schwieriger, wenn wir alles als String betrachten.

Hmm da kommt bei mir die Frage auf, würde `Content` dann auch ein `int` speichern oder einen `String` in dem ein `int`-Wert drinne steht? 
Aktuell speichert das Ding nur Strings und der Typ gibt an, wie der String zu interpretieren ist. 

Wenn wir bei dem Konzept bleiben, müsstest du in der Bewertungsfunktion ein switch-case über den Wert des Typen machen. Kommt bei mir die Frage auf: Weißt du in der Bewertungsfunktion nicht schon, dass du ein int haben willst? Brauchst du das dann überhaupt noch als Typen? 

Schöner wäre es dann natürlich, wenn `Content` auch den richtigen Typen speichert. Dann müsste man da aber nochmal Konzeptionell ran.

**Comment by malt-r** [comment]
Dann lass es uns erstmal bei Strings belassen.

**Comment by cagix** [comment]
`Content` sollte die Frage speichern und als String zurückgegeben können. Wenn es Bilder gibt, dann eben alternativ als Bild bzw. bei gemischt eben beides. Dann kannst Du die interne Repräsentation von `Content` bei Bedarf immer noch aufbohren.

Wenn ich einen Zahlenwert überprüfen muss, dann muss der irgendwie bereits in `Content` geeignet gekapselt sein - das kommt aus der DSL. Dort kann ich mit Grammatik+ANTLR auf komplexere Ausdrücke zielen und ein passendes Content-Objekt bauen. Hier im Dungeon sollte es nur noch String (und ggf. Bild) sein.

**Comment by cagix** [comment]
Ich würde sogar `Content(String text, File path)` oder `Content(String text, Image img)` sehen. Strings sind kein guter Datentyp.

**Comment by AMatutat** [comment]
Da bleibt dann aber eine frage offen: Woher weiß ich wo das Bild im Text stehen soll? 
Oder es kommt halt immer erst Text und dann das Bild und danach kein Text mehr.
Vielleicht ist Text Bild Text unnötig?
