### ISSUE TITLE
[DSL] `getConfigs()` zum Anzeigen aller Config-Einstiegspunkte

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#869]
Im Spiel möchte ich alle verfügbaren "Level/Quests" im Hauptmenü ausführbar machen.
Dafür sollen im DSL-Dateiverzeichnis die Dateien eingelesen werden und jede "QuestConfig"/"LevelConfig" (Einstiegspunkte) zurückgegeben werden. 
Zusätzlich sollte noch ein Anzeigename zurückgegeben werden. 

Die Methode müsste ungefähr so aussehen: 
```java
public Map<String, String> getConfigs(String dslFile) {
    HashMap<String, String> map = new HashMap<>();
    for (each config in dslFile) {
        if (config contains startpoint) {
            map.put(startpoint, anzeigename);
        }
    }
    return map;
}
```

@malt-r vermutlich brauchst du noch dem Pfad zum directory als Parameter, oder?

**Comment by malt-r** [comment]
Ich sehe die Verantwortung, ein Verzeichnis nach Dateien zu durchsuchen auf der Seite, die z.B. auch das Hauptmenü mit Daten füttert, also im Dungeon, nicht beim Interpreter. Es ist meiner Meinung nach deutlich sauberer, für *eine* DSL-Datei alle Level-Konfigs zurückzugeben, aber die Logik, die DSL-Dateien selbst zu suchen, da nicht mit einzubauen. 

Das bezieht sich jetzt auf die DSL-Dateien, die Aufgabendefinitionen enthalten. Bzgl. der Standard-Bibliothek wird der DSLInterpreter eigene Logik haben, um Dateien, die in der Bibliothek liegen, zu finden.

**Comment by AMatutat** [comment]
Habe den Code-Snippet entsprechend angepasst.
Dann geb ich dir den Inhalt eines Files, und du gibst mir dann die Configs+Anzeigenamen in den FIle zurück

**Comment by AMatutat** [comment]
Skizziertes Diagramm aus unseren Meeting

![getConfig](https://github.com/Programmiermethoden/Dungeon/assets/32962412/642a29df-3653-4775-b052-3045d40688f9)


Das entspricht in etwa den Kasten 1 aus https://github.com/Programmiermethoden/Dungeon/blob/master/doc/dsl/dsl_zu_level.md

![Interprete](https://github.com/Programmiermethoden/Dungeon/assets/32962412/929fbe71-fa33-4e71-a33c-f6f9c46048f5)

Das entspricht in etwa den Kasten 2-3 aus https://github.com/Programmiermethoden/Dungeon/blob/master/doc/dsl/dsl_zu_level.md
wobei wir hier die Feinheiten der API noch definieren müssen.
