### ISSUE TITLE
[DUNGEON] Sourcefiles noch in Module integrieren? 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#870]
Wir hatten bereits darüber gesprochen, wie wir das Spiel und die Inhalte verbreiten wollen.
[Hier ist der Link zur Diskussion.](https://github.com/Programmiermethoden/Dungeon/wiki/Verbreitung:-Themen-Module)

Wir hatten damals auch festgehalten, dass wir die Option anbieten wollen, Java-Source-Dateien in die Modul-JAR zu packen. 

In der WiMi-Runde ist dieses Vorhaben auf wenig Gegenliebe gestoßen. 
1. Warum sollte ich das wollen? Was möchten wir denn an Source-Dateien mitgeben? 
2. Wenn ich als Lehrperson dazu in der Lage bin, Java-Code zu schreiben, dann forke ich mir das Projekt eigenständig und führe dort meine Änderungen/Add-Ons durch. 
3. Es erfordert einen hohen konzeptionellen und implementativen Aufwand. Wer ruft den Code auf? Wann wird der Code aufgerufen? Wer definiert das? Wo wird das definiert? 

Wir sollten erneut darüber sprechen.

**Comment by cagix** [comment]
@AMatutat Bitte nur die Leute assignen, die aktuell wirklich hier was zu tun haben. Das Label https://github.com/Programmiermethoden/Dungeon/labels/meeting reicht, um es im nächsten Meeting hochzupoppen. Für die Information reicht ein Taggen im Issue :)
