### ISSUE TITLE
[DUNGEON] Bilder als Antworten ermöglichen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#874]
Aktuell kann zwar die Fragestellung eines Quiz ein Bild enthalten, die Antwortmöglichkeiten aber noch nicht.
Aktuell Filter `QuizDialogDesign#createAnswerButtons` Antworten die nur ein Bild enthalten raus.

**Comment by AHeinisch** [comment]
In Irgendeinen Meeting hatten wir irgendwie besprochen das es als Antwort nicht ganz bestimmt war. Und durch die damals 640x480 auflösung welche in #851 geändert wurde auch vom darstellen kaum möglich da sonst die Bilder für die Antwort nur Max 200x100px (bei 3 oder 4 Antwortmöglichkeiten) sein dürfen, welches rein technisch für ein Bild zu klein ist um was zu erkennen. Wir sind nun bei 1280x720 geben wir also die Hälfte an die Fragestellung bleiben für den Antwortbereich etwa 1280 x 360 übrig somit beides durch 2 640 x 180px für die bereitgestellten Bilder für die Antwort welches etwas besser klappen kann.

**Comment by AMatutat** [comment]
Durch unser HUD-Quiz System (was libGDX bedingt nicht besonders toll ist), ist unsere Skalierung der UI sehr zerbrechlich. 
Mehrere Bilder würden dafür sorgen, dass die Skalierung kaputt geht (und die Bilder nicht zu erkennen sind weil verzogen).

Man müsste hierfür ein anderes System überlegen (Tabellenbasiert anstelle von Liste).

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
