### ISSUE TITLE
[GAME] Brauchen wir die Zirkelabhängigkeit Entity-Component wirklich?

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#884]
Zwischen `Entity` und `Component` besteht eine zirkuläre Abhängigkeit: Eine Entität hat je eine Referenz auf alle ihre Components, und jede Component hat eine Referenz auf ihre Entität. 

Das hat Vorteile, weil man so aus jeder Richtung an "alles" kommt. 

Andererseits erzwingt es die Zwangsregistrierung der Components, die im Moment in der Basisklasse gemacht wird und damit beim Lesen des Codes nicht wirklich offensichtlich ist - man muss das im Hinterkopf behalten == mentaler Load. Wenn man das alternativ aber erst in den ableitenden Klassen macht, könnte ein "Kunde" das mal vergessen. 

Der Zugriff ist quasi beliebig von "jeder Seite" möglich - das erinnert ein wenig an Architekturen von Microsoft ;) Besser wäre eine bestimmte Herangehensweise für ein bestimmtes Problem, also eher der Unix-Weg.

Möglicherweise wird auch der GC dadurch vereitelt. 

Wir sollten systematisch prüfen, wie wir wo auf Entitäten bzw. Components zugreifen. Vielleicht lässt sich das mit nur wenig Refactoring auflösen. Im Ergebnis könnte man dann eine saubere Baum-artige Struktur haben: `Game -> Entity -> Component`.

**Comment by AMatutat** [comment]
Passend dazu: #782
