### ISSUE TITLE
[GAME] Doppelte Buchhaltung für Entitäten in Game und den Systemen vermeiden

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#885]
Aktuell haben wir eine Art doppelte Buchführung für Entitäten: Das Game kennt alle Entitäten, und für den schnelleren Zugriff führt jedes System noch eine Liste der für das System relevanten Entitäten. Zusätzlich ist die Liste in den Systemen noch "delayed", d.h. es gibt in den Systemen eine Art temporäre Schatten-Liste und die Hauptliste in den Systemen wird nur unter bestimmten Bedingungen aktualisiert. 

Wenn man alles richtig macht und an alles gedacht hat, _kann_ das zuverlässig funktionieren. Die tatsächlich aufgetretenen Race-Conditions sprechen allerdings dagegen. Auch macht es die Strukturen und Zusammenhänge deutlich schlechter lesbar und verständlich - die Verwaltung der Entitäten ist jetzt über drei verschiedene Listen verstreut mit relativ komplexen Bedingungen und Annahmen, wann wer auf welche Liste zugreifen soll.

Ursprünglich wurden Entitäten nur im Game verwaltet. Da aber jedes System in jedem Frame immer wieder alle Entitäten abgefragt hat und nach den relevanten Entitäten gefiltert hat, wurde auf der Suche nach einer effizienteren Verwaltung das bestehende Regime implementiert. Außerdem war dieser Filterschritt in allen Systemen immer wieder neu zu implementieren, was durch die doppelte Buchhaltung behoben wurde.

Mein Ziel wäre es, wieder zurückzukehren zur alleinigen Verwaltung der Entitäten im Game. Dazu müsste die API in `Game` entsprechend angepasst werden: `public static Stream<Entity> entityStream(final Class<? extends Component>... klasses)`. Über die "Var Args" kann ein System alle zugehörigen `Component.class` in _einem_ Funktionsaufruf übergeben und einen Stream der relevanten Entitäten zurückbekommen. Damit ist `Game` wieder die alleinige zuständige Instanz, die Entitäten verwalten darf. Das Filtern für die Systeme entfällt, ebenso die DelayedSet-Listen in den Systemen. Man kann dann innerhalb von `Game` noch überlegen, ob man die Entitäten anders verwaltet, etwa nach Components oder Zuständigkeiten/Systemen sortiert - aber das ist gegenüber den Systemen transparent.

**Comment by AMatutat** [comment]
Ich habe mir die Situation jetzt nochmal genauer angeschaut, und hier ist mein Lösungsvorschlag-Skizze:

Vorab muss klargestellt werden, dass einige HUD-Funktionalitäten auf die im System hinterlegten `onAdd` und `onRemove` Methoden angewiesen sind. Nach meiner Einschätzung bekommen wir das auch nicht so einfach daraus, und ein Umbau würde uns sicherlich über einen Monat kosten. 
Daher möchte ich diese Funktionalität beibehalten. Die beiden Funktionen werden immer dann aufgerufen, wenn eine Entität dem System hinzugefügt/entfernt wird, nicht zwingend der globalen Liste.

Nun zur Lösung:

Im ersten Schritt würde ich gerne die System-Sets nach Game holen und in einer Map speichern: `Map<System, Set<Entity>>`. Die könnten wir genauso füllen wie die Listen in den Systemen. Wir behalten daher im ersten Schritt auch unseren Registrierungs-Loop. Wir lagern das Ganze nur zurück nach Game. So können wir auch die `onAdd` und `onRemove` Funktionalität einfach beibehalten. An dieser Stelle könnte das `DelayedSet` vermutlich schon rausfliegen.

Im zweiten Schritt will ich den Registrierungs-Loop aufbrechen. Dafür möchte ich keine `Map<System, Set<Entity>>` mehr speichern, sondern eine `Map<Filter, Set<Entity>>` und eine `Map<System, Filter>`. `Filter` ist eine Hilfsstruktur, welche ein Set an Component-Klassen speichert, die die Filterkriterien erfüllen. `Filter#equals` gibt dann `true` zurück, wenn die internen Sets die gleichen Component-Klassen speichern.

Dadurch speichere ich nicht mehrfach die gleichen Entity-Sets mit den gleichen Bedingungen.

Mit der `Map<System, Filter>` kann ich dann die Systeme den Filtern zuordnen und damit zu den Entitäten. 

Die Zuordnung der Systeme zu den Filtern geschieht beim registrieren der Systeme im Game.

Damit das Ganze in Game übersichtlicher bleibt, würde ich die beiden Maps nochmal in einer Hilfsklasse vereinen.

**Comment by cagix** [comment]
@AMatutat Schöne Gedanken! Damit würde die Verantwortlichkeit für die Buchführung der Entitäten komplett bei `Game` liegen und wäre nicht mehr über verschiedene Akteure verteilt.

Es fehlt noch eine Definition, wie die Listen in Game konsistent aktualisiert werden sollen: Gestorbene Entitäten müssten ja "zeitgleich" aus allen Listen entfernt werden.

---

Hier spielen zwei Gedanken rein: (a) Einfaches Abfragen der für ein System relevanten Entitäten, und (b) Effizienz, d.h. möglichst keine (wiederholten) Suchvorgänge.

Ich bin nicht sicher, wie stark (b) sich bei uns auswirkt. Wenn wir das vernachlässigen, könnte `Game` einfach nur ein `Set<Entity>` verwalten und eine Schnittstelle `Stream<Entity> entities(Predicate<Entity>)` anbieten. Die Systeme könnten das Prädikat als Lambda-Ausdruck übergeben und darin einen UND-Ausdruck über die benötigten Components bilden: `(e) -> e.has(ComponentA.class) && e.has(ComponentB.class) && e.has(ComponentC.class)`. Damit wäre die Verwaltung in `Game` maximal einfach, und in den Systemen muss man nicht jedesmal einen Filter implementieren. ... Aber das würde den Aspekt (b) vernachlässigen, weil in jedem Frame für jedes System diese Abfrage realisiert werden würde.

**Comment by AMatutat** [comment]
> Es fehlt noch eine Definition, wie die Listen in Game konsistent aktualisiert werden sollen: Gestorbene Entitäten müssten ja "zeitgleich" aus allen Listen entfernt werden.

Das würde ich dann in `Game#addEntity` bzw. `Game#removeEntity` machen.

Im Falle vom Hinzufügen muss die Entität einmal durch jeden Filter in `Map<Filter, Set<Entity>>` geschleift werden und ggf. dem Set hinzugefügt werden.
Wenn für den Filter-Key die Entität hinzugefügt wird, dann müsste ich in `Map<System, Filter>` jedem System, der den Filter als Value hat, davon berichten, also das `System#onAdd` auslösen.

Der Remove-Fall ist im Grunde identisch, nur wird hier halt gelöscht.

Ausführen würde ich das sofort, also sobald `addEntity` oder `removeEntity` aufgerufen wird. Kein `DelayedSet` mehr.

---

Bei deinem anderen Vorschlag habe ich leider keine Idee, wie ich `onAdd` und `onRemove` auf System-Ebene umsetzen soll.


PS: Was ist den aus Urlaub geworden? hihihi :P

**Comment by cagix** [comment]
> Bei deinem anderen Vorschlag habe ich leider keine Idee, wie ich onAdd und onRemove auf System-Ebene umsetzen soll.

wofür waren die beiden gut? 

> PS: Was ist den aus Urlaub geworden? hihihi :P

muss dringend die app deinstallieren (oder die notifications komplett abschalten) 🤣

**Comment by AMatutat** [comment]
> > Bei deinem anderen Vorschlag habe ich leider keine Idee, wie ich onAdd und onRemove auf System-Ebene umsetzen soll.
> 
> wofür waren die beiden gut?
> 
> edit: wurden die nicht ausschließlich in `System` genutzt, um die verwaltung der internen `DelayedSet` hinzukriegen? die braucht es doch dann gar nicht mehr oder übersehe ich hier was?

In `System` gibt es kein `DelayedSet`, das ist ein normales Set. Das `DelayedSet` liegt in Game. 
Die Methoden werden für den setup von HUD-Anzeigen genutzt. 
Um das mal anhand eines Beispiel zu machen:
Wenn du als Entity das `HealthComponent` bekommst, hast du dich auch gleichzeitg für das `HealthbarSystem` qualifiziert. Das System sorgt dafür, dass du auch grafisch einen Lebensbalken auf den HUD siehst. 
Dieser Lebensbalken ist selbst eine Entität mit bestimmen UI-Components. 

[Falls du das im Code sehen willst.](https://github.com/Programmiermethoden/Dungeon/blob/master/game/src/contrib/systems/HealthbarSystem.java)

Etwas abstrakter und mit mehr libGDX Magie gibt es das auch noch im [HudSystem](https://github.com/Programmiermethoden/Dungeon/blob/master/game/src/core/systems/HudSystem.java).




> 
> > PS: Was ist den aus Urlaub geworden? hihihi :P
> 
> muss dringend die app deinstallieren (oder die notifications komplett abschalten) 🤣

Kenn ich... und dann geht man über den Browser rein

**Comment by cagix** [comment]
> > > Bei deinem anderen Vorschlag habe ich leider keine Idee, wie ich onAdd und onRemove auf System-Ebene umsetzen soll.
> > 
> > 
> > wofür waren die beiden gut?
> > edit: wurden die nicht ausschließlich in `System` genutzt, um die verwaltung der internen `DelayedSet` hinzukriegen? die braucht es doch dann gar nicht mehr oder übersehe ich hier was?
> 
> In `System` gibt es kein `DelayedSet`, das ist ein normales Set. Das `DelayedSet` liegt in Game. Die Methoden werden für den setup von HUD-Anzeigen genutzt. Um das mal anhand eines Beispiel zu machen: Wenn du als Entity das `HealthComponent` bekommst, hast du dich auch gleichzeitg für das `HealthbarSystem` qualifiziert. Das System sorgt dafür, dass du auch grafisch einen Lebensbalken auf den HUD siehst. Dieser Lebensbalken ist selbst eine Entität mit bestimmen UI-Components.
> 
> [Falls du das im Code sehen willst.](https://github.com/Programmiermethoden/Dungeon/blob/master/game/src/contrib/systems/HealthbarSystem.java)
> 
> Etwas abstrakter und mit mehr libGDX Magie gibt es das auch noch im [HudSystem](https://github.com/Programmiermethoden/Dungeon/blob/master/game/src/core/systems/HudSystem.java).

Ja, ich hatte mal IJ aufgemacht und gesucht. 

In `System` werden die beiden Callbacks `onAdd` und `onRemove` nur genutzt, wenn die jeweils übergebenen Entitäten in/aus die/den (Delayed) Sets hinzugefügt/gelöscht werden (`if (entities.add(entity)) { onEntityAdd.accept(entity); }`). 

Und das einzige System, was die Callbacks tatsächlich nutzt (also selbst setzt), ist das `HealthbarSystem`. Da frage ich mich, ob man das nicht irgendwie anders lösen kann (also ob die aktuelle Implementierung des `HealthbarSystem` nicht einfach nur bequemen Gebrauch der vorhandenen Möglichkeiten macht).



> 
> > > PS: Was ist den aus Urlaub geworden? hihihi :P
> > 
> > 
> > muss dringend die app deinstallieren (oder die notifications komplett abschalten) 🤣
> 
> Kenn ich... und dann geht man über den Browser rein

Hmmm, aber deutlich seltener :)

**Comment by AMatutat** [comment]
> Und das einzige System, was die Callbacks tatsächlich nutzt (also selbst setzt), ist das HealthbarSystem. Da frage ich mich, ob man das nicht irgendwie anders lösen kann (also ob die aktuelle Implementierung des HealthbarSystem nicht einfach nur bequemen Gebrauch der vorhandenen Möglichkeiten macht).

Das UISystem auch, aber anyway. Tatsächlich haben wir dafür diese Möglichkeit überhaupt erst implementiert. 

Will nicht ausschließen dass es da bessere Möglichkeiten gibt, aber ich würde das konstrukt erstmal so behalten wollen und seperat untersuchen. 

Der Filter-Typ hilft uns auch für #504, da hier die Laufzeit dann tatsächlich zu einen problem werden kann, wenn für jedes System über jede Entität gefiltert wird.

**Comment by cagix** [comment]
ja gut, manches habe ich nicht auf dem schirm.

im prinzip könnte man auch über einen cache nachdenken: die filterung werden pro frame gecached (in einer map wie von dir vorgeschlagen) und bei weiteren anfragen anderer systeme schaut man erst im cache nach und macht nur zu not einen neuen filtervorgang. am ende des frames wird der cache aber wieder gelöscht - dadurch hast du dann wirklich nur noch eine einzige "truth" ("liste" mit entitäten).

löst aber nicht das ui-problem.

**Comment by AMatutat** [comment]
> Ich habe mir die Situation jetzt nochmal genauer angeschaut, und hier ist mein Lösungsvorschlag-Skizze:
> 
> Vorab muss klargestellt werden, dass einige HUD-Funktionalitäten auf die im System hinterlegten `onAdd` und `onRemove` Methoden angewiesen sind. Nach meiner Einschätzung bekommen wir das auch nicht so einfach daraus, und ein Umbau würde uns sicherlich über einen Monat kosten. Daher möchte ich diese Funktionalität beibehalten. Die beiden Funktionen werden immer dann aufgerufen, wenn eine Entität dem System hinzugefügt/entfernt wird, nicht zwingend der globalen Liste.
> 
> Nun zur Lösung:
> 
> Im ersten Schritt würde ich gerne die System-Sets nach Game holen und in einer Map speichern: `Map<System, Set<Entity>>`. Die könnten wir genauso füllen wie die Listen in den Systemen. Wir behalten daher im ersten Schritt auch unseren Registrierungs-Loop. Wir lagern das Ganze nur zurück nach Game. So können wir auch die `onAdd` und `onRemove` Funktionalität einfach beibehalten. An dieser Stelle könnte das `DelayedSet` vermutlich schon rausfliegen.
> 
> Im zweiten Schritt will ich den Registrierungs-Loop aufbrechen. Dafür möchte ich keine `Map<System, Set<Entity>>` mehr speichern, sondern eine `Map<Filter, Set<Entity>>` und eine `Map<System, Filter>`. `Filter` ist eine Hilfsstruktur, welche ein Set an Component-Klassen speichert, die die Filterkriterien erfüllen. `Filter#equals` gibt dann `true` zurück, wenn die internen Sets die gleichen Component-Klassen speichern.
> 
> Dadurch speichere ich nicht mehrfach die gleichen Entity-Sets mit den gleichen Bedingungen.
> 
> Mit der `Map<System, Filter>` kann ich dann die Systeme den Filtern zuordnen und damit zu den Entitäten.
> 
> Die Zuordnung der Systeme zu den Filtern geschieht beim registrieren der Systeme im Game.
> 
> Damit das Ganze in Game übersichtlicher bleibt, würde ich die beiden Maps nochmal in einer Hilfsklasse vereinen.
> 
> ## Vorteile
> * Wir entfernen die Doppelte Buchhaltung
> * Wir entfernen das wirre delayed set
> * Der Registrierungs-Loop wird einfacher
> * Durch die Filter sollte die Laufzeit immernoch recht gut bleiben
> * Wir behalten die `onAdd` und `onRemove` Funktionalitäten
> 
> ## Nachteil
> * Map<Filter, Set>`und`Map<System, Filter>`könnten auf den ersten Blick etwas verwirren, aber vermutlich weniger als`DelayedSet`
> 
> @AHeinisch kannst du auch eine Einschätzung abgeben?

> > Es fehlt noch eine Definition, wie die Listen in Game konsistent aktualisiert werden sollen: Gestorbene Entitäten müssten ja "zeitgleich" aus allen Listen entfernt werden.
> 
> Das würde ich dann in `Game#addEntity` bzw. `Game#removeEntity` machen.
> 
> Im Falle vom Hinzufügen muss die Entität einmal durch jeden Filter in `Map<Filter, Set<Entity>>` geschleift werden und ggf. dem Set hinzugefügt werden. Wenn für den Filter-Key die Entität hinzugefügt wird, dann müsste ich in `Map<System, Filter>` jedem System, der den Filter als Value hat, davon berichten, also das `System#onAdd` auslösen.
> 
> Der Remove-Fall ist im Grunde identisch, nur wird hier halt gelöscht.
> 
> Ausführen würde ich das sofort, also sobald `addEntity` oder `removeEntity` aufgerufen wird. Kein `DelayedSet` mehr.

@Lena241 im Grunde kannst du erstmal das hier so umsetzen. 
Die Systeme sollen sich dann bei `Game#entitiesFor(this)`, einen Stream der Kopie des Sets im zugehörigen Map Eintrag abholen.

**Comment by AMatutat** [comment]
@Lena241 

Mir ist grade bewusst geworden, das `Set#equals(Set other)` immer dann `true` zurückliefert, wenn beide Sets die selben Items beinhalten.
In unseren Fall bedeutet das, wir brauchen die Klasse `Filter` nicht und speichern dann direkt `Set<Class<? extends Component>>` in der Map

**Comment by AMatutat** [comment]
Okay, ich hab das ganze noch dreimal druchdacht und bin hier gelandet: 

<img width="943" alt="image" src="https://github.com/Programmiermethoden/Dungeon/assets/32962412/7038c5d3-ae92-40c5-89d0-c0f190131e5c">

In `Game` habe ich nur die Methoden aufgelistet die für das neue System erstellt/bearbeitet werden müssen. Teilweise hab ich die namen von addEntity in add geändert (Parameter macht klar das es eine entity hinzufügt): 

Ich würde noch einen `Filter` ohne Regeln vorschlagen, das wären dann quasi alle Entitäten (für den Fall das eine Entität hinzugefügt wird, die von keinen System bearbeitet werden kann => kein System-Filter passt)
