### ISSUE TITLE
[Org] Review-Regeln und Codeowner überdenken

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#895]
> @AHeinisch magst du auch einmal gucken? @cagix ist kein code mehr, hihihihi ^^

ja, das war mir zuviel noise ... ich hab ja nix gegen eine notification, aber wenn das dann bei mir in der todo-liste aufschlägt ("pr > review requested" oder "issue > assigned") und ich eigentlich nicht wirklich der ansprechpartner bin, dann macht das keinen sinn. 

@AMatutat habe das gefühl, wir müssten über die codeowners und die review-regeln nochmal nachdenken. aber noch wichtiger ist, dass alles so eingestellt ist, dass ihr im august auch ohne mich arbeiten könnt :)

_Originally posted by @cagix in https://github.com/Programmiermethoden/Dungeon/issues/894#issuecomment-1647779100_

**Comment by AMatutat** [comment]
Dann haben wir das für Mittwoch auf dem schirm ^^

**Comment by cagix** [comment]
> Dann haben wir das für Mittwoch auf dem schirm ^^

Mittwoch ist diese Woche Freitag ...

**Comment by AMatutat** [comment]
In #740 geht crazy Krams diesbezüglich aus. 

- aus irgendeinen Grund muss @malt-r als Codeowner für /dungeon ein Review geben, obwohl ich doch auch ein owner bin.


@cagix sollten auch owner von gradle werden

**Comment by cagix** [comment]
> In #740 geht crazy Krams diesbezüglich aus. 
> * aus irgendeinen Grund muss @malt-r als Codeowner für /dungeon ein Review geben, obwohl ich doch auch ein owner bin.

Seltsamerweise wurden auch weder @Programmiermethoden/codrs (für Game) noch @Programmiermethoden/dungeon (für Dungeon) mit aufgerufen. Ist das ein Glitch in GitHub, das hat sonst doch immer sehr zuverlässig funktioniert?

> 
> @cagix sollten auch owner von gradle werden

Wenn es sein muss. 

---

Idealerweise sollte es so sein, dass mein Approval reicht und die Gruppen dann nicht noch extra müssen. Und ich möchte eigentlich nur direkte (explizite) Review-Anforderungen in meiner Liste sehen (https://github.com/pulls/review-requested) und nicht, wenn ich durch die Mitgliedschaft in einer Gruppe implizit auch ein Review machen könnte/sollte. 

D.h. ich sollte eigentlich nicht in irgendwelchen Gruppen drin sein, und die Ownership sollte sich vererben. Aber letzteres scheint nicht zu funktionieren.

**Comment by cagix** [comment]
> Das sollte eigentlich gehen, wenn man dich in jede OWNERSHIP explizit nennt.

das fordert dann aber (wie auch über eine gruppenmitgliedschaft) ein review automatisch mit an.

> Vielleicht kann man die Benachrichtigungen abschalten....

das nutzt halt nur semi - die review-aufforderungen landen ja trotzdem in meiner todo-liste. und ich muss immer erst reinschauen, ob ich wirklich was machen soll oder ob das nur wegen einer liste oder mit-codeownership passiert ist.
