### ISSUE TITLE
[GAME] Level müssen ihre Entitäten speichern

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#900]
Für die Raum-Level müssen `ILevel` die Entitäten in ihnen verwalten/speichern/zugeordnet werden. 

## Ausgangsituation 
Aktuell werden alle im Spiel existierenden Entitäten in `Game` (und in `System`, aber das ist hier nicht wichtig) gespeichert.
Was nicht in `Game` liegt, existiert nicht.

Beim laden eines neuen Levels werden alle Entitäten gelöscht oder in das neue Level mitgenommen (z.B der Held). 
Aktuell gibt es keine Möglichkeit in das alte Level zurück zu gehen, daher passt das für den aktuellen ansatz. 

## Raum Level

Raum-Level basieren auf Graphen, wobei jeder Knoten ein `Room` ist und jede Kante angibt, welche Räume miteinander verbunden sind. Ein Raum hat maximal vier Kanten (an jede level Seite gibt es es maximal eine Tür)
Jeder Raum ist intern als eigenes Level implementiert (das erlaubt eine einfache Anbindung an das aktuelle System).
Da wir in den Räumen jedoch hin und her laufen können, müssten die Räume jedoch wissen welche Entitäten in ihnen gespeichert sind und diese dann beim betreten in den "aktiven" status bringen.

**Comment by cagix** [comment]
Könnte man die Position so erweitern, dass sie nicht nur die Koordinaten/die Kachel kennt, sondern auch den zugehörigen Raum?

Ich tue mich ziemlich schwer damit, Entitäten noch in anderen Zusammenhängen außer `Game` zu verwalten - ich sehe rückblickend die Einführung von Entitäten-Listen/-Mengen in den Systemen als Schritt in die falsche Richtung.

**Comment by AMatutat** [comment]
> Könnte man die Position so erweitern, dass sie nicht nur die Koordinaten/die Kachel kennt, sondern auch den zugehörigen Raum?

Theoretisch ja, praktisch sehe ich da viele kleine Stolpersteine. Die Systeme müssten prüfen, ob die Entität im aktuellen Level ist sonst lohnt es sich ja nicht die zu aktualisieren.. Was ist wenn eine Entität kein PositionComponent hat aber trotzdem zu einem Level gehört (irgendwelche Kontroll-Elemente). 


> Ich tue mich ziemlich schwer damit, Entitäten noch in anderen Zusammenhängen außer `Game` zu verwalten - ich sehe rückblickend die Einführung von Entitäten-Listen/-Mengen in den Systemen als Schritt in die falsche Richtung.

Ich bin noch am grübeln, könnte mir aber eine Art `Map<ILevel,DelayedSet<Entity>>` in `Game` vorstellen und alle Aktionen die jetzt direkt auf dem Entity-Set ausgeführt werden prüfen zuerst welches level das aktuelle ist und agieren dann auf dem jeweiligen Set.

Hier würde es sich auch anbieten die doppelte Buchhaltung aufzulösen (also weg mit den Entitäten aus den Systemen). Sonst müssten die Systeme eine ähnliche Map führen....

**Comment by cagix** [comment]
> > Könnte man die Position so erweitern, dass sie nicht nur die Koordinaten/die Kachel kennt, sondern auch den zugehörigen Raum?
> 
> 
> 
> Theoretisch ja, praktisch sehe ich da viele kleine Stolpersteine. Die Systeme müssten prüfen, ob die Entität im aktuellen Level ist sonst lohnt es sich ja nicht die zu aktualisieren.. Was ist wenn eine Entität kein PositionComponent hat aber trotzdem zu einem Level gehört (irgendwelche Kontroll-Elemente). 

Ich könnte mir die Erweiterung der Positions-Information um Raum- und Level-Information trotzdem als sehr sinnvoll vorstellen. Dann kann ein System damit direkt arbeiten, sobald es eine Entität in die Finger kriegt.

Wenn man das weiter denkt, könnte es ja auch eine Position "bin im Level X" oder "bin im Raum Y" geben. Das könnte man dann den Entitäten mitgeben, die bisher keine PositionComponent haben und die aber trotzdem über das Level angesprochen werden sollen. Diese Positionen könnten dann freilich nicht eine Koordinate oder eine Kachel zurückliefern. 

Oder man führt noch eine LevelComponent und eine RoomComponent ein. Dann wäre das Problem mit der nicht-Koordinate von eben weg. Andererseits sind die Konzepte so nah beieinander, dass sich das Einführen neuer Components hier einfach falsch anfühlt.


> 
> 
> 
> 
> 
> > Ich tue mich ziemlich schwer damit, Entitäten noch in anderen Zusammenhängen außer `Game` zu verwalten - ich sehe rückblickend die Einführung von Entitäten-Listen/-Mengen in den Systemen als Schritt in die falsche Richtung.
> 
> 
> 
> Ich bin noch am grübeln, könnte mir aber eine Art `Map<ILevel,DelayedSet<Entity>>` in `Game` vorstellen und alle Aktionen die jetzt direkt auf dem Entity-Set ausgeführt werden prüfen zuerst welches level das aktuelle ist und agieren dann auf dem jeweiligen Set.
> 
> 
> 
> Hier würde es sich auch anbieten die doppelte Buchhaltung aufzulösen (also weg mit den Entitäten aus den Systemen). Sonst müssten die Systeme eine ähnliche Map führen.... 
> 
> 

In `Game` könnte eine Map für die Entitäten Sinn machen. Aber wir haben ja noch mehr Kriterien - ist beispielsweise eine bestimmte Component vorhanden etc. ... Das stößt dann schnell an Grenzen, man bräuchte im Grunde für jedes Kriterium eine eigene Map mit dem Kriterium als Key.
 
Bisher hatten wir immer gesagt, dass wir nur relativ wenige Entitäten haben und pro Frame einfach filtern können (das Übertragen als Liste in die Systeme hatte ja eher funktionalen Hintergrund und wurde nicht gemacht, weil wir Laufzeitprobleme hatten). Deshalb würde ich nochmal drüber nachdenken, ob wir nicht eher passende Filtermethoden in `Game` anbieten sollen, die u.a. auch Level oder Räume beinhalten. 

Wenn es ein bestimmtes Feature gibt, was wirklich immer gebraucht wird, dann vielleicht das als Key für die Map. Sonst würde ich eher bei einem Set bleiben. Filtern müssen wir ja sowieso.

Aber ich sehe in `Game` noch nicht den Sinn für die `DelayedMap`. Die wurde ja vor allem gebaut, weil wir eben in den Systemen dezentral auf der eigentlich zentralen Entitäten-Liste arbeiten wollten. Wenn ich grad so drüber nachdenke, brauchen wir das wirklich? `Game` gibt einem System auf Anfrage einen Stream mit passenden Entitäten, das System arbeitet damit und verändert die Entitäten (bzw. deren Components). Danach ist das nächste System dran ... Im Prinzip ist das eigentlich vor allem eine Frage nach der Reihenfolge der Systeme bzw. nach der Priorität. Alternativ könnte ich mir eine Art Command-Queue vorstellen: Jedes System ändert nicht die Entitäten direkt, sondern packt die Änderungswünsche in eine Queue in `Game`. Wenn alle Systeme durch sind, kann `Game` diese Queue abarbeiten und dann die aufgelaufenen Änderungen an einer Entität gemeinsam durchführen. Aber auch hier hat man eigentlich wieder das Problem, wenn zwei Systeme widersprüchliche Dinge mit einer Entität anstellen: Wer von den beiden darf dann bzw. wer darf zuerst? Wie gehen denn andere ECS-Frameworks damit um?

**Comment by cagix** [comment]
Das Auslagern von Teilen der Entitäten an die Level finde ich erstmal irgendwie schnieke. Man hätte dann einen Baum `Game -> Level -> Entity`, d.h. das `Game` hält ne Menge `Level`, und ein `Level` hat dann eine Menge von `Entity`. Das klingt aufgeräumt und spart den einen Filterschritt, den man sonst immer noch hat.

Die zu klärende Frage bei dieser Modellierung wäre noch: Wie kann eine Entität das Level wechseln (API)?

Die doppelte Buchführung und `DelayedSet` hängt aber damit imho nicht zusammen, sondern das ist eine Frage, wann welches System warum eine Entität bzw. deren Components ändern darf. Also eher eine Frage der Prioritäten und des Vorrangs auf `System`-Ebene, und wenn wir über das Löschen von Entitäten während der Iteration sprechen, auch die "concurrent modification exception".

**Comment by AMatutat** [comment]
> Das Auslagern von Teilen der Entitäten an die Level finde ich erstmal irgendwie schnieke. Man hätte dann einen Baum `Game -> Level -> Entity`, d.h. das `Game` hält ne Menge `Level`, und ein `Level` hat dann eine Menge von `Entity`. Das klingt aufgeräumt und spart den einen Filterschritt, den man sonst immer noch hat.

Theoretisch speichert das `Game` nichtmal eine Menge an `Level`, sondern nur ein Level (bzw das `LevelSystem` speichert das aktive Level). 
Die Verbindungen zwischen den Leveln werden in den Door-Tiles der Level gespeichert (Knoten und Kanten lassen sich erkennen).
 

> Die zu klärende Frage bei dieser Modellierung wäre noch: Wie kann eine Entität das Level wechseln (API)?

Könnte ich mir sowas wie `switchLevel(Entity entity, Level currentLevel, Level targetLevel)` in `Game` vorstellen, was dann in `currentLevel#removeEntity` aufruft und `targetLevel#addEntity`,
Um die position im neuen Level zu bestimmen könnte ich mir dann noch sub-Varianten mit weiteren Parametern (Point,Tile) vorstellen.

**Comment by cagix** [comment]
hmmm, dann wäre das levelsystem aber was herausstechendes: alle systeme arbeiten auf entitäten, nur das levelsystem nicht ...

glaube, es wäre besser, wenn das game die level verwaltet und das levelsystem damit nur arbeitet. oder vielleicht nicht mal das, weil wir sonst das ecs-paradigma sprengen.

**Comment by AMatutat** [comment]
> hmmm, dann wäre das levelsystem aber was herausstechendes: alle systeme arbeiten auf entitäten, nur das levelsystem nicht ...

Das LevelSystem arbeitet ja weiterhin auf Entitäten es verwaltet eben nur die "Hilfsstruktur" `currentLevel`.



Im Grunde ist das wie das `DrawSystem`, welches den `Painter` verwaltet oder das `CameraSystem` welches die `Camera` verwaltet.

**Comment by cagix** [comment]
> > hmmm, dann wäre das levelsystem aber was herausstechendes: alle systeme arbeiten auf entitäten, nur das levelsystem nicht ...
> 
> Das LevelSystem arbeitet ja weiterhin auf Entitäten es verwaltet eben nur die "Hilfsstruktur" `currentLevel`.
> 
> Vielleicht sollte man nochmal Verwalten definieren: In dieses Kontext heißt das speichern und das zeichnen des Levels anstoßen.

In dem Moment, wo die Entitäten einem Level zugeordnet werden und dort verwaltet werden (im Sinne von "speichern"), dann sticht das LevelSystem massiv heraus. Dann haben wir nämlich ein System, welches nicht mit Entitäten _arbeitet_, sondern diese (indirekt) _verwaltet_. 


> 
> Im Grunde ist das wie das `DrawSystem`, welches den `Painter` verwaltet oder das `CameraSystem` welches die `Camera` verwaltet.

Die Frage ist, ob all diese Systeme tatsächlich "Systeme" im Sinne von ECS sind? Wenn ich das richtig in Erinnerung habe, sollen Systeme auf Entitäten und ihren Components arbeiten. Der Rest sind quasi (Sub-) Systeme von Game, aber keine ECS-Systeme mehr?

**Comment by AMatutat** [comment]
> Die Frage ist, ob all diese Systeme tatsächlich "Systeme" im Sinne von ECS sind? Wenn ich das richtig in Erinnerung habe, sollen ECS-Systeme auf Entitäten und ihren Components arbeiten. Der Rest sind quasi (Sub-) Systeme von Game, aber keine ECS-Systeme mehr?

Das macht Kopfweh beim nachdenken.... :/
Eigentlich müsste das Level und die Tiles darin auch Entitäten sein, dann wäre das ganze deutlich besser trennbar.
Dann bräuchte es auch kein `LevelSystem` mehr und das Level wäre einfach DIE eine Entität in Game. 
`Camera` und `Painter` müssten eigentlich in den Systemen als private Hilfsstrukturen liegen und von außen unbekannt sein.
Dann stellt sich die Frage auch nicht mehr.

**Comment by cagix** [comment]
> > Die Frage ist, ob all diese Systeme tatsächlich "Systeme" im Sinne von ECS sind? Wenn ich das richtig in Erinnerung habe, sollen ECS-Systeme auf Entitäten und ihren Components arbeiten. Der Rest sind quasi (Sub-) Systeme von Game, aber keine ECS-Systeme mehr?
> 
> Das macht Kopfweh beim nachdenken.... :/ Eigentlich müsste das Level bzw die Tiles darin auch Entitäten sein, dann wäre das ganze deutlich besser trennbar. Dann bräuchte es auch kein `LevelSystem` mehr und das Level wäre einfach DIE eine Entität in Game. Da wären wir wieder bei #504 (und wenn ich bedenke das es mir in #902 auch wieder hochgekommen ist, sollte man das vielleicht doch in Angriff nehmen)

Die Frage ist dann: Wer ist eine Entität? Das Level als solches? Die Räume im Level? Die Tiles im Level? 

Mir scheint die Ebene der Tiles ganz günstig zu sein. Da wir die Entitäten sowieso (vermutlich) levelweise festhalten wollen, würde das auch keinen besonders großen Overhead verursachen. Dann kann man Tiles zu einem "Raum" gruppieren, und Räume und Übergangsstrukturen dann zu einem Level.


> `Camera` und `Painter` müssten eigentlich in den Systemen als private Hilfsstrukturen liegen und von außen unbekannt sein. Dann stellt sich die Frage auch nicht mehr.

Das ist aber nur bunt angemalt ;) Eigentlich müssten das beides Services vom Game sein, die dann von den entsprechenden Systemen genutzt werden.

**Comment by AMatutat** [comment]
Ich merk schon, hier haben sich wieder neue Issues gefunden.....
Langsam macht ECS kein spaß mehr

**Comment by cagix** [comment]
> Ich merk schon, hier haben sich wieder neue Issues gefunden..... Langsam macht ECS kein spaß mehr

Ich glaube, wir haben das Thema halt einfach nicht konsequent durchdekliniert. Deshalb poppt es auch immer wieder auf.


> 
> Was die eigentliche Problematik dieses Issues angeht, sind wir uns glaub erstmal einig. Level speichern die Entitäten ab und die Systeme agieren auf die Entitäten des currentLevel. Damit kann ich erstmal weiterarbeiten

Würde ich so sehen, ja. Mit der Einschränkung: Das Game speichert die Level, so dass hier eine Baumstruktur da ist und letztlich das Game immer noch die Entitäten verwaltet, nur jetzt eben indirekt über die Level.

**Comment by AMatutat** [comment]
> > Ich merk schon, hier haben sich wieder neue Issues gefunden..... Langsam macht ECS kein spaß mehr
> 
> Ich glaube, wir haben das Thema halt einfach nicht konsequent durchdekliniert. Deshalb poppt es auch immer wieder auf.
> 
> > Was die eigentliche Problematik dieses Issues angeht, sind wir uns glaub erstmal einig. Level speichern die Entitäten ab und die Systeme agieren auf die Entitäten des currentLevel. Damit kann ich erstmal weiterarbeiten
> 
> Würde ich so sehen, ja. Mit der Einschränkung: Das Game speichert die Level, so dass hier eine Baumstruktur da ist und letztlich das Game immer noch die Entitäten verwaltet, nur jetzt eben indirekt über die Level.

Genau, die API würde ich in `Game` behalten wollen. 
Ich verstehe nicht ganz was du mit 

> Das Game speichert die Level, so dass hier eine Baumstruktur da ist

meinst. Willst du den "Levelgraphen" in `Game` speichern?

**Comment by cagix** [comment]
Ich würde in `Game` die Level in irgendeiner Art speichern (referenzieren, verwalten).

**Comment by AMatutat** [comment]
Wir haben in #885 ein Konzept besprochen bei den es eine Datenstrukt gibt, die Maps für Systeme, Entitäten und Filter hält.

Wir könnten in `Game` um diese Struktur (nennen wir sie mal `EntityCollection`)  eine Map `<Level,EntityCollection>` schließen.
Dann würde `Game` die Entitäten für die jeweiligen Level speichern (Game bleibt der zentrale Anlaufpunkt für alles) und müsste im `onLevelLoad` dann die aktive `EntityCollection` entsprechend setzen.

**Comment by AMatutat** [comment]
Einwurf:
Durch die Lösung für #885 haben wir (wenn das durch ist) in `Game` eine `Set<EntityStorage>` welches Entitäten und Systeme miteinander verknüpft. 


Wenn wir in Game jetzt eine `Map<ILevel,Set<EntityStorage>>` anlegen, könnten wir die Level den Entiäten problemlos zuordnen. 
Die ganzen getter würden immer auf dem Set des `currentLevel` arbeiten. 

Beim wechseln des Levels sollten die `System#onRemove(entity)` Methoden für die Entitäten des alten Levels ausgelöst werden, für die Entitäten des neuen Level entsprechend System#onAdd(entity)`.
Dadurch wird dann alles korrekt aufgeräumt bzw aufgebaut (ich denke da vorallem an GUI Elemente für die Lebensbalken etc.).
