### ISSUE TITLE
[GAME] Endlosschleife im `RandomWalkGenerator#randomFloor`

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#901]
In `RandomWalkGenerator#randomFloor` hat sich eine mögliche endlose Rekursion eingeschlichen.

Wir hatten so etwas Ähnliches mal im Level gehabt und dort mit verschiedenen Listen für jeden Tile-Typen (also Wand, Floor, etc.) gelöst.
Vielleicht kann man das hier auch so machen, sollte aber genau hinschauen, ob das geht, da wir uns hier im Generierungsprozess des Levels befinden.
Und wenn, dann nur für Typen, bei denen es auch Sinn macht (mir scheint das aktuell nur für Floor zu sein).

> ```java
>private Coordinate randomFloor(LevelElement[][] layout) {
>       Coordinate coordinate =
>               new Coordinate(RANDOM.nextInt(layout[0].length), >RANDOM.nextInt(layout.length));
>       LevelElement randomTile = layout[coordinate.y][coordinate.x];
>        if (randomTile == LevelElement.FLOOR) {
>          return coordinate;
>      } else {
>           return randomFloor(layout);
>      }
>  }
> ```

first of all: WTF. Das ist ja ein potenzieller Endlos-loop. 
second of all: WTF das hab ich geschrieben..... Yikes.... (Edit: stimmt gar nicht war ich gar nicht, puh....)

_Originally posted by @AMatutat in https://github.com/Programmiermethoden/Dungeon/issues/547#issuecomment-1649670046_

**Comment by AMatutat** [comment]
Mal grade so hingeklatscht, muss man nochmal genau anschauen

```java
 private LevelElement[][] drunkWalk(MinMaxValue minMaxValueX, MinMaxValue minMaxValueY) {
        int xSize = RANDOM.nextInt(minMaxValueX.min(), minMaxValueX.max());
        int ySize = RANDOM.nextInt(minMaxValueY.min(), minMaxValueY.max());
        LevelElement[][] layout = new LevelElement[ySize][xSize];
        for (int y = 0; y < ySize; y++) {
            for (int x = 0; x < xSize; x++) {
                layout[y][x] = LevelElement.SKIP;
            }
        }

        List<Coordinate> floorPositions = new ArrayList<>();
        Coordinate position = new Coordinate(RANDOM.nextInt(0, xSize), RANDOM.nextInt(0, ySize));
        int steps =
                RANDOM.nextInt(
                        (xSize * ySize) / MIN_STEPS_FACTOR, (xSize * ySize) / MAX_STEPS_FACTOR);
        for (; steps > 0; steps--) {
            layout[position.y][position.x] = LevelElement.FLOOR;
            floorPositions.add(position);
            if (RANDOM.nextBoolean()) {
                if (RANDOM.nextBoolean()) {
                    position.x = Math.min(position.x + 1, xSize - 1);
                } else {
                    position.x = Math.max(position.x - 1, 0);
                }
            } else {
                if (RANDOM.nextBoolean()) {
                    position.y = Math.min(position.y + 1, ySize - 1);
                } else {
                    position.y = Math.max(position.y - 1, 0);
                }
            }
        }

        // pick random floor tile as exit
        Coordinate c = floorPositions.get(RANDOM.nextInt(floorPositions.size()));
        layout[c.y][c.x] = LevelElement.EXIT;
        return layout;
    }
```

**Comment by AHeinisch** [comment]
Aktuell macht das Level doch bereits das Finden eines gültigen Exits automatisch, wenn keiner vorhanden ist. Warum wird es hier überhaupt erneut gemacht?
