### ISSUE TITLE
[GAME] HUD-Dialog skaliert nicht gut

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#907]
Beispiel anhand einer Quizfrage:

![image](https://github.com/Programmiermethoden/Dungeon/assets/32962412/88e35f55-21ba-4674-8f53-bbbb77991acf)

Der Aufgabentext ist sehr lang und müsste in mehrere Zeilen gebrochen werden, wird aber in einer Zeile zusammengequetscht (aber vollständig angezeigt). Bei der hohen Anzahl der Antworten hätte ich mir einen Scroll-Bar gewünscht (die gibt es ja), anstatt es so seltsam zu quetschen.

Beim Text-Dialog wird dann selbst ein kleiner Text nicht vollständig angezeigt und muss mit der Scroll-Bar angesehen werden.

![image](https://github.com/Programmiermethoden/Dungeon/assets/32962412/93de3795-f6a6-497b-a46e-51657cdfa642)

Die Fenster sollten allgemein besser skaliert sein.

**Comment by AKirsch1** [comment]
Bei zu langen Fragen wird in meinem Fall die UI zu breit, sodass der `confirm`-Button "verschwindet":

![dungeon_error_quiz_ui](https://github.com/Programmiermethoden/Dungeon/assets/32961997/17dd0cac-4d4b-419d-8632-f5b2c73cfd94)

**Comment by AMatutat** [comment]
Da ich grade an anderer Stelle daran rumgespielt habe:
In `DialogFactory#createTextDialog` habe ich für ein work arround (nichts was gemerged ist) `textDialog.setWidth(title.length()*20);` eingefügt, damit wird die breite des Fensters abhängig von der Anzahl der Zeichen im Titel des Text-Fensters bestimmt.
Ich denke irgendwie so muss man das machen, dann aber mit gescheiten Werten und ich glaube auch nicht, dass der Titel die beste Ausgangsvariable ist

**Comment by cagix** [comment]
@AMatutat Was wird denn als Container für den Text verwendet? Versteht das libGDX-Widget HTML? Dann könnte man das evtl. in ein Div oder so einsperren?

**Comment by AMatutat** [comment]
> @AMatutat Was wird denn als Container für den Text verwendet? 

Das ganze Fenster ist eine libGDX `Dialog` welcher dann "Slots" Für Titel, Content und Buttons hat. 
Der Slot für den Content (z.B das Textfeld) ist eine `Table`, da kannst du dann mehre `Actor` einfügen. 
So ein `Actor` kann dann nochmal in Gruppen kombiniert werden oder in einen andern Actor verschachtelt werden (so typisches GUI zeugs halt).

Um deine Frage jetzt zu beantworten: Der Text selbst ist ein `Label` und der speichert dann einfach eine Charsequenz.

Das Ding hat sogar eine Funktion den Text entsprechend der verfügbaren Fläche zu wrappen. Jetzt muss ich nur noch die fläche gescheit berechnen. 


Versteht das libGDX-Widget HTML? Dann könnte man das evtl. in ein Div oder so einsperren?

Fände ich ganz cool, dann könnten wir vielleicht sogar etwas von den libGDX HUD-Elementen verwerfen und eher auf HTML arbeiten. Muss ich nachgucken und Möglichkeiten abstecken.

**Comment by AMatutat** [comment]
Wir hatten früher mal eine Funktion die den Text entsprechend anpasst aber scheinbar hat jemand (angeblich ich) die rausgeworfen

https://github.com/Programmiermethoden/Dungeon/commit/39d9c286defa6556a2c608380dc917f8de05075f#diff-c6100fe68b797b2d6bad861233041d03dd2c2951d9652c4247f79b610f5723daR54


```java
/**
     * String formatting for content of the 'msg'(message) to be output on the screen
     *
     * @param arrayOfMessages Content 'msg', which is to be output on the screen, optional the name
     *     of the button, as well as the label heading can be passed. [0] Content displayed in the
     *     label; [1] Button name; [2]label heading
     */
    private static void formatStringForDialogWindow(String[] arrayOfMessages) {
        if (arrayOfMessages != null && arrayOfMessages.length != 0) {
            String infoMsg = arrayOfMessages[0];
            infoMsg = infoMsg.replaceAll("\n", " ");

            String[] words = infoMsg.split(" ");
            String formattedMsg = Constants.EMPTY_MESSAGE;
            int sumLength = 0;

            for (String word : words) {
                sumLength += word.length();
                formattedMsg = formattedMsg.concat(word).concat(" ");

                if (sumLength > MAX_ROW_LENGTH) {
                    formattedMsg += "\n";
                    sumLength = 0;
                }
            }
            arrayOfMessages[0] = formattedMsg;
        }
    }
```
