### ISSUE TITLE
[GAME] Verschiedene Inventare für verschiedene Items

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#924]
Im SHK Meeting am 02.08 besprochen: 

Für verschiedene Item-Typen soll es verschiedene Inventare geben, damit dort richtig damit umgegangen werden kann.

Dabei wird auch die Idee des QuestInventory aus #903 aufgegriffen. 

@AHeinisch @fwatermann Könnt ihr das nochmal besser erläutern? Ich habe grade versehentlich meine Notizen gelöscht und krieg es nur noch grob zusammen.

**Comment by AHeinisch** [comment]
Meine kurze Zusammenfassung:
Wir bauen nun für die QuestItems theoretisch ein neues Inventar. Jetzt könnte man zusätzlich argumentieren das wir ein ähnliches Vorgehen bei Waffen, Rüstung, Tränke und Zettel benötigen.

Daher war die Überlegung, per Vererbung diese Struktur zu erstellen.

**Comment by AMatutat** [comment]
ich glaube das haben wir zu schnell zu gemacht

**Comment by AMatutat** [comment]
@Lena241 so drüber nachgedacht ist die Idee mit den verschiedenen Inventaren für verschiedene Item-Typen eigentlich over the top.

Idee: InventaryComponent speichert eine Collection an Item und hat zwei Methoden
=> `Set<Item> items(){//return copy of item collection} `
=> `Set<Item> items(Class<? extends Item> klass){ //return set mit allen Items im Inventar die instace of klass sind`
