### ISSUE TITLE
[GAME] Held kann optisch in die Wand laufen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#925]
Es sieht optisch so aus, als würde man in die Wand rennen können, wenn man nach Links oder Oben in eine Wand rennt.

![image](https://github.com/Programmiermethoden/Dungeon/assets/32962412/54a282a3-d453-417a-bff7-cd4bd96a6676)

Besonders an Ecken irgendwie sehr unschön

![image](https://github.com/Programmiermethoden/Dungeon/assets/32962412/50fe3ed1-c480-4fb8-a695-8a0c30bedc0e)

**Comment by cagix** [comment]
Das ist die Perspektive, oder?

@AMatutat Mich würde viel mehr stören, dass der Gesundheitsbalken nicht über dem Moster/Spieler ist (wie sonst üblich).
