### ISSUE TITLE
[GAME] Animation System

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#94]
Wir brauchen ein System, welches den Übergang zwischen den verschiedenen Animationen regelt.
Laufanimation kann über die Velocity gesteuert werden aber was ist mit anderen Animationen?
Schlagen? Truhe öffnen? Hinfallen? Sterben? 

In Unity gibt es einen AnimationManager, aber ich hab keinen Plan wie man das korrekt in das ECS einbindet.

**Comment by AMatutat** [comment]
Idee: 
Irgendwie müsste man eine Statemachine in das `AnimationComponent` integrieren. 
Die States wären dann die einzelnen Animationen, der aktuelle State die `currentAnimation´ und die Übergänge würden durch den Zustand anderer Components getätigt. 
Ein `AnimationSystem` würde dann die Statemachine updaten und `DrawSystem` holt sich dann die `currentAnimation`.

Ich hab nur noch keine Idee wie man das mit den Übergängen richtig machen würde 
Wenn ich drüber nachdenke, wie man das in der DSL implementiert platzt mein Kopf.

**Comment by malt-r** [comment]
Man könnte das auf DSL Seite quasi in der Graphen-Notation aufschreiben (dot kann ja auch gerichtete Kanten). Verknüpfung der Animationstates könnte man über Attribute der Knoten regeln. Zustandsübergänge könnten manuell per Funktionsaufruf (aus der DSL) mit Referenz auf den Knoten des Graphen, also den Zustand der Statemachine, in den gewechselt werden soll.. komfortabel geht anders, klickibunti können wir ja nur leider noch nicht.

**Comment by AMatutat** [comment]
Hmm weiß nicht ob das ne Sache für die DSL ist. 
Will ich mich als User wirklich mit den Animationsübergängen beschäftigen?
Das ist zu feingranular.... 

Ich sehe hier ehr ein Ranking zwischen den Components die Animationen haben.

**Comment by AMatutat** [comment]
@Lena241 in der DSL sollen die Pfade zu den Animation nur "grob" angegeben werden. 
Aktuell haben wir für jede Entität ein Ordner in dem alle Texturen für die Entität liegen. Wir müssen da jetzt noch Unterordner einziehen.
