### ISSUE TITLE
Tool: Spotless-Formatter auf Google-Style wechseln

### ISSUE THREAD

**Issue by fwatermann** [Programmiermethoden/Dungeon#944]
Ich halte es für sinnvoll den Formatter von Spottless auf den Standard-Google-Style zu ändern, anstatt den AOSP (Android Open Source Project) Style, da der AOSP-Style eine doppelte Einrückung bei Zeilenumbrüchen vorsieht, welche den Code schnell "nach rechts wandern lässt" und meiner Meinung nach durch mehr als nötige Umbrüche, aufgrund dann zu langer Zeilen, unleserlicher macht als es eigentlich durch einen Formatter gedacht ist.

Die Änderung ist ziemlich einfach, da jeglich das `.aosp()` aus der `build.gradle` entfernt werden müsste.

@AMatutat ist es egal, welchen Style wir nehmen.

**Comment by cagix** [comment]
finde ich gut. 

wenn ich mich richtig erinnere, hatten wir das früher aber schon mal so und sind aus irgendeinem grund explizit auf asop umgestiegen. @AMatutat bitte versuchen rauszukriegen.

wenn wir umstellen, dann bitte in einer konzertierten aktion (alle pr zu, reformat und merge, danach normal weiter) wg. mergekonflikten.

**Comment by cagix** [comment]
es sieht tatsächlich so aus, als ob mit https://github.com/Programmiermethoden/__pm-dungeon/commit/b26066a18f24a7bc81503e2c36c08e8bc102e85e das spotless-"feature" exakt so ins projekt kam, wie es jetzt ist. 

und dennoch meine ich mich zu erinnern, dass wir vorher irgendeine andere konfiguration hatten und wir aus bestimmten gründen auf asop umgestiegen sind ... aber ich finde auch keine hinweise, weder im blame noch in den issues/pr ... :/

**Comment by AMatutat** [comment]
"Hab es dir mal nachgemacht, ist schon ... anders. Ich weiß nicht, ob es einfach die Gewohnheit macht.

Ich bin aber bei @fwatermann. Gerade jetzt, wo wir öfters funktional und mit Streams arbeiten, sind die Zeilenumbrüche teilweise echt eklig.

+ Ausprobieren kostet nichts. Wenn wir in 1 Monat feststellen, dass wir das doch richtig doof finden, können wir immer noch zurückkehren."

**Comment by cagix** [comment]
> Ausprobieren kostet nichts. Wenn wir in 1 Monat feststellen, dass wir das doch richtig doof finden, können wir immer noch zurückkehren.

hmmm, ja und nein. das eigentliche formatieren ist flink gemacht, ja. aber du musst jedesmal das projekt anhalten dazu. und es macht aus git-sicht ziemlich viel noise, so dass du wirklich relevante sachen schwieriger wiederfindest. 

mein vorschlag wäre, mal ein paar ausgewählte relevante/kritische stellen zusammenzusuchen und per screenshots ein "vorher vs. nachher" hier zusammenzustellen. dann können wir abstimmen.

**Comment by cagix** [comment]
> ist schon ... anders 

zumal in vielen anderen sprachen vier spaces aktuell die norm sind: markdown, rust, haskell ...

na gut, haskell's hindent ist bei 2 spaces default. ruby iirc auch. und lisp/racket rückt per default auch mit 2 spaces ein, wobei da aber i.d.R. andere überlegungen eine rolle spielen.

**Comment by malt-r** [comment]
Ich persönlich habe keinen Stress mit der Änderung auf 2 Spaces.

**Comment by AMatutat** [comment]
@cagix hier auch nochmal ping.

Vorm abschließen umsetzen, oder das Ticket zu machen

**Comment by cagix** [comment]
ich finde zwei spaces ... nicht schön. aber mach.

**Comment by AMatutat** [comment]
@fwatermann Wenn wir das Projekt abschließen, sperren wir dich ja hier im Repo ein:
Das ist eine super: Mach ich wenn alle weg sind Aufgabe für dich.

**Comment by cagix** [comment]
@fwatermann any news?
