### ISSUE TITLE
[GAME] Projektile sliden an der Wand anstelle zerstört zu werden

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#945]
Wenn ein Projektil eine Wand trifft, sollte das Projektil eigentlich gelöscht werden.
Durch 74c1212bd3f9dc1ecf42532c14d43a0fa245800d (#936 ) sliden diese jetzt aber an der Wand rum. 

https://github.com/Programmiermethoden/Dungeon/assets/32962412/45971d05-fd7d-4e9e-80cb-040560eda8e9

**Comment by cagix** [comment]
sieht doch cool aus ... können wir beide varianten haben?

**Comment by AMatutat** [comment]
> sieht doch cool aus ... können wir beide varianten haben?

du siehst cool aus ... ne warte ... Mist....

Aber ja, das sollte gehen. Das ist dann ein extra Projektil-Typ (oderso).
Ich mach mal ein neues Issue auf.
