### ISSUE TITLE
[GAME]  Gleit-Projektile hinzufügen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#948]
Durch einen Fehler (siehe #945) bleiben Projektile an der Wand hängen, anstatt gelöscht zu werden.

[Link zur Problemstellung](https://github.com/Programmiermethoden/Dungeon/assets/32962412/45971d05-fd7d-4e9e-80cb-040560eda8e9)

@cagix findet das cool und hätte das gerne als Funktion im Spiel. 
Es sollen also zusätzliche Projektile hinzugefügt werden, die eine gewisse Strecke an der Wand "entlanggleiten" können, bevor sie gelöscht werden.

Auf den ersten Blick scheint dies eine Überarbeitung des `ProjectileSystem`s zu erfordern. Bei normalen Projektilen wird ein Projektil bei Kollision mit einer Wand gelöscht, während bei Gleit-Projektilen sichergestellt wird, dass sie für eine gewisse Strecke an der Wand entlanggleiten können, bevor sie verschwinden.

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
