### ISSUE TITLE
[DSL] Builder-Datentyp stärker vom Instance-Datentyp trennen

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#949]
Das Typsystem der DSL funktioniert aktuell so, dass für die Definition eines Objekts (z.B. die Definition der Werte eines `Component` in einem `entity_type` oder die Definition der Aufgaben) und die Verwendung des Instanziierten Objekts (also ein `AggregateValue`, dessen `MemorySpace` ein Java-Objekt kapselt) den gleichen Datentyp verwendet.

Für #781 macht die Abbildung dieser beiden Anwendungsfälle auf den gleichen Datentyp Probleme, da diese Methoden von einem konkreten instanziierten Objekt abhängig sind, d.h. vor dem Zeitpunkt der Instanziierung kann die Methode gar nicht verwendet werden, obwohl sie eigentlich laut Datentyp verfügbar sein sollte.

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
