### ISSUE TITLE
[API] API zum laden von Entitäten

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#95]
In der DSL wird ein Monster erstellt:
- Texturen
- Hit Points
- Auswahl aus vorgegeben Movementverhalten

das muss dann in das Spiel geladen werden.

**Comment by malt-r** [comment]
Für die Verwendung von Java-Klassen aus der DSL sind zwei Dinge notwendig:
1. Übergang von Java-Klassen des Dungeon-Frameworks ins DSL-Typsystem (bspw. um Entitäten mit Komponenten zu definieren)
2. Übergang von DSL-Typen in Java-Klassen des Dungeon-Frameworks (um die in der DSL konfigurierten Entitäten & Komponenten im Spiel zu verwenden)

### Übergang Java -> DSL

Aktuell können per `@DSLType`-Annotation markierte Klassen und Records als DSL-Typen in das Typsystem geladen werden. Alle Klassenmember, die auch Teil des entsprechenden DSL-Typen sein sollen müssen mit `@DSLTypeMember` markiert werden.
Der Name der Member wird zur Verwendung in der DSL in `snake_case` konvertiert, um einheitliche Namen in der DSL zur Verfügung zu stellen.

#### Beispiel

```java
@DSLType
public class MyClassComponent {
    @DSLTypeMember
    private int member1;
    @DSLTypeMember
    private String member2;
}

@DSLType
public record MyRecordComponent(
    @DSLTypeMember int member3, 
    @DSLTypeMember String member4
) {}
``` 

Die oben definierten Komponenten können dann in der DSL wie folgt verwendet werden, um ein Game-Object zu definieren:

```
// ...
game_object my_game_object {
    my_class_component {
        member1: 42,
        member2: "Hello, World!"
    },
    my_record_component {
        member3: 314,
        member4: "Moin"
    }
}
// ...
```

### Übergang DSL -> Java

Soll eine in der DSL definierte Entität im Dungeon instanziiert werden, müssen aus den Werten, die die DSL-Objekte gespeichert haben, Instanzen der Java-Klassen, aus denen ursprünglich der DSL-Typ erzeugt wurde, erstellt werden. Also für das obere Beispiel würde zuerst eine Entität erstellt werden, in die dann die Komponenten `MyClassComponent` und `MyRecordComponent` mit entsprechend der DSL konfigurierten Werten hinzugefügt werden.

Um diesen Schritt nicht für jede neue Komponente händisch implementieren zu müssen, soll hierzu Reflection verwendet werden. Der TypeInstantiator (aktuell in diesem [branch](https://github.com/Programmiermethoden/Dungeon/pull/102/files))
erstellt per Reflektion eine Instanz der ursprünglichen Java-Klasse (oder des Records). Hierbei gibt es einige Einschränkungen:
- Der Konstruktor eines `record`s hat als Parameter alle Member des Records. Der `TypeInstantiator` muss bei dem Konstruktor-Aufruf alle Member des `record`s in korrekter Reihenfolge übergeben. Daher müssen alle Member des `record`s mit `@DSLTypeMember` markiert werden.
- Für Klassen erstellt der `TypeInstantiator` eine neue Instanz per Defaultkonstruktor und setzt die Fields der Klasse nachher per Reflection. Daher muss eine Klasse, die mit `DSLType` markiert ist, einen Defaultkonstruktor mit 0 Parametern haben, bzw. für bestimmte Anwendungsfälle (wie z.B. Komponenten, die immer einen `entity`-Parameter haben) genau definiert sein, welche Parameter wie an den Konstruktor übergeben werden müssen. Dafür ist allerdings aktuell noch kein Mechanismus vorhanden, der muss noch gebaut werden (@AMatutat ).
