### ISSUE TITLE
[Game] Items aus Inventar per Tastendruck verwenden

### ISSUE THREAD

**Issue by fwatermann** [Programmiermethoden/Dungeon#950]
Ein Kontextmenü (Rechtsklick) auf Items im Inventar ermöglichen, um Funktionen wie "Use" oder "Wegwerfen" einzubauen. 
Siehe [Kommentar von @AMatutat in #934](https://github.com/Programmiermethoden/Dungeon/pull/934#issuecomment-1674355642)

---

Edit: Da wir Drag an Drop wegwerfen haben (#1079) reicht hier ein "Drücke Taste X um das Item zu verwenden"

**Comment by AMatutat** [comment]
@Lena241 da wir jetzt Drag&Drop rauswerfen haben, reicht mir hier eigentlich ein "Schieb die Maus auf das Item im Inventar und drücke Taste XYZ um es zu benutzen (z.B Trank trinken))"
