### ISSUE TITLE
[ORG] Readme verbessern

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#958]
Unsere GitHub-Readme ist irgendwie etwas ... traurig. Wir sollten sie erstmal wieder auf den aktuellen Stand bringen und danach etwas aufpeppen. Wir haben ein Spiel, das sollten wir auch in Form von Bildern (noch besser als `.gifs`) zeigen. Außerdem spricht dieses Repository mittlerweile drei verschiedene Nutzergruppen an:

1. Studierende, die sich für das Framework interessieren.
2. Lehrende, die die DSL verwenden wollen.
   a. Hierbei zählen irgendwie auch die Studierenden dazu, die das Spiel mit den Quests dann spielen sollen.
3. Contributors (Mitwirkende).
   a. Dies schließt insbesondere auch die Studierenden ein, die hier eine Abschlussarbeit durchführen möchten.

das sollten wir in die Struktur der Readme mit aufnehmen.

**Comment by cagix** [comment]
@AMatutat Bevor Du da (viel) Zeit investierst, poste mal bitte 2..4 Links zu Readme.md aus anderen Projekten, die Du passend/nett/... findest. Dann kann man die Strukturen analysieren und schauen, was wir daraus machen. 

Ich finde einerseits ein Gif und ein Install und ein HowTo immer ganz nett im Readme, andererseits braucht das in unserem Fall viel Platz. Vielleicht sollte das Readme eher das Projekt und die Strukturen grob "erklären" und auf die einzelnen relevanten Sachen verweisen (Howto, API-Doku, Java-Klassen?, ...)? Hmmm.

**Comment by AMatutat** [comment]
> @AMatutat Bevor Du da (viel) Zeit investierst, poste mal bitte 2..4 Links zu Readme.md aus anderen Projekten, die Du passend/nett/... findest. Dann kann man die Strukturen analysieren und schauen, was wir daraus machen.
> 
> Ich finde einerseits ein Gif und ein Install und ein HowTo immer ganz nett im Readme, andererseits braucht das in unserem Fall viel Platz. Vielleicht sollte das Readme eher das Projekt und die Strukturen grob "erklären" und auf die einzelnen relevanten Sachen verweisen (Howto, API-Doku, Java-Klassen?, ...)? Hmmm.

Ich hab noch nicht im Detail drüber nachgedacht, aber spontan kam mir die Idee quasi eine Haupt-Readme (das ist die auf der Startseite) zu haben, dort erklärt man kurz die verschiedenen Projekt(bausteine) und verlinkt dann jeweils zu einer Readme die sich auf den jeweiligen Aspekt fokussiert (also minimium eine Framework-Readme und eine Dungeon/DSL-Readme) 

Ein Bild/Gif vom Spiel würde ich dennoch in die Hauptreadme reinpacken, einfach damit man sofort sieht wie das aussieht.

**Comment by cagix** [comment]
Hmmm, klingt erstmal nicht schlecht. Es darf halt nur nicht zu lang werden - 2..3 Bildschirmseiten sind i.d.R. viel.

Ich bin auch grad am überlegen, drüben in https://github.com/Programmiermethoden/PM-Lecture die Strukturen zu ändern. Aktuell ist alles an Hugo orientiert, was die Nutzung der Markdown-Dateien in GitHub oder VSCode schwer macht: Dateinamen sind schräg ("_index.md"), Links auf andere Seiten der Vorlesung funktionieren nicht (weil Hugo-Shortcodes verwendet werden müssen), .... Trotzdem ist die Struktur noch nicht 100% Hugo-kompatibel (oder zum Theme, wer weiss das schon - jedenfalls funktioniert das Print-Feature nicht richtig, siehe auch https://github.com/McShelby/hugo-theme-relearn/issues/587). Mein aufkeimender und noch nicht zuende gedachter Plan ist jetzt, die bisher im [`markdown/`](https://github.com/Programmiermethoden/PM-Lecture/tree/master/markdown)-Ordner "versteckte" Landingpage [`index.md`](https://github.com/Programmiermethoden/PM-Lecture/blob/master/markdown/_index.md) als Projekt-Readme zu nutzen (umbenennen in `readme.md` und verschieben auf Top-Level) und auch die ganzen Unterordner für die VL-Themen aus dem [`markdown/`](https://github.com/Programmiermethoden/PM-Lecture/tree/master/markdown)-Ordner raus- und auf Top-Level-Ebene zu holen. Dann wäre mein Readme.md in PM-Lecture auch richtig lang (Einleitung, Orga, Fahrplan, ...). Hmmm.
