### ISSUE TITLE
[Org] `/doc` überarbeiten und aufräumen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#962]
In [https://github.com/Programmiermethoden/Dungeon/tree/master/doc](https://github.com/Programmiermethoden/Dungeon/tree/master/doc) lagern wir viel Dokumentation zu den verschiedenen Bausteinen. Mittlerweile hat sich dort ein ziemliches Chaos angesammelt, und es läuft mehr auf ein "Wissen, wo es liegt" oder ein "hilfloses Suchen" hinaus, wenn man etwas nachschlagen möchte.

Aus meiner Sicht gibt es folgendes zu tun:
- [x] Die Top-Level Struktur an die Projektstrukturen anpassen. Für mich würde das bedeuten, jeweils ein Unterverzeichnis für das Framework und das Dungeon-Projekt anzulegen (`/dsl`, `/game`). (Ersetzt durch #1204)
- [ ] Unter den Top-Level Strukturen benötigt es dann eine Gliederung für die verschiedenen Aspekte der Dokumentation. Ich denke, es wäre hier sinnvoll, etwas in Richtung `./user` und `./coder` anzulegen. Unter `./user` würde ich die Dokumentation für den Benutzer platzieren. Im Framework wären das der Quickstart und die Übersicht der Systeme, Komponenten usw. Im Dungeon wären das einerseits die Lehrpersonen, die DSL-Code schreiben, und andererseits die Studierenden, die DSL-Spiele spielen. Unter `./coder` würde ich die Dokumentation für die Weiterentwicklung und Wartung der Projekte ablegen. Dort sollten auch die Designentscheidungen festgehalten werden.
- [x] Ausmisten: Es liegt viel veralteter Kram herum. Im Dungeon haben wir zum Beispiel begonnen, die Systeme und Komponenten ausführlich in der Javadoc zu erklären. Daher benötigen wir keine separate Dokumentation für jede einzelne Klasse. Ein Überblick sollte ausreichen.

**Comment by AMatutat** [comment]
@cagix irgendwie hab ich das vergessen in Meeting anzusprechen: Kannst du deine Meinung zur beschriebenen Struktur abgeben?

**Comment by cagix** [comment]
> * [ ]  Die Top-Level Struktur an die Projektstrukturen anpassen. Für mich würde das bedeuten, jeweils ein Unterverzeichnis für das Framework und das Dungeon-Projekt anzulegen (`/dsl`, `/game`).

ja. aber am besten erst, wenn die projektstrukturen auch angepasst wurden? sonst musst du hier 2x ran ... andererseits kannst du die projektstrukturen vermutlich erst recht spät anpassen, so dass es vielleicht dann doch sinnvoll ist, die doc _jetzt_ schon aufzuräumen und dann am ende nochmal mit den strukturen nachzuziehen?


> * [ ]  Unter den Top-Level Strukturen benötigt es dann eine Gliederung für die verschiedenen Aspekte der Dokumentation. Ich denke, es wäre hier sinnvoll, etwas in Richtung `./user` und `./coder` anzulegen. Unter `./user` würde ich die Dokumentation für den Benutzer platzieren. Im Framework wären das der Quickstart und die Übersicht der Systeme, Komponenten usw. Im Dungeon wären das einerseits die Lehrpersonen, die DSL-Code schreiben, und andererseits die Studierenden, die DSL-Spiele spielen. Unter `./coder` würde ich die Dokumentation für die Weiterentwicklung und Wartung der Projekte ablegen. Dort sollten auch die Designentscheidungen festgehalten werden.

das _könnte_ sinnvoll sein, wenn wir wirklich signifikant viele entsprechende dokumente hätten. glaube ich aber im moment nicht und halte das für overkill. 

ich würde lieber im obligatorischen `readme.md` eine entsprechende struktur nach "user" und "coder" einziehen (hauptüberschriften) und dann auf die jeweiligen dateien verlinken. 

wenn du es dann noch besonders toll machen willst, verpasse den dateien noch einen präfix "`user_`" bzw. "`coder_`" ... aber das geht schon wieder richtung overkill. keep it simple.


> * [ ]  Ausmisten: Es liegt viel veralteter Kram herum. Im Dungeon haben wir zum Beispiel begonnen, die Systeme und Komponenten ausführlich in der Javadoc zu erklären. Daher benötigen wir keine separate Dokumentation für jede einzelne Klasse. Ein Überblick sollte ausreichen.

so hatten wir das mal besprochen. der javadoc sollte erklären, was eine klasse/einheit tut und mit einem kurzen beispiel zeigen, wie man sie benutzt. in der markdown-doc gibt es einen überblick über die verschiedenen systeme, components und entitäten, und es wird der zusammenhang dargestellt.

**Comment by AMatutat** [comment]
Zu 

>- [ ] Unter den Top-Level Strukturen benötigt es dann eine Gliederung für die verschiedenen Aspekte der Dokumentation. Ich denke, es wäre hier sinnvoll, etwas in Richtung `./user` und `./coder` anzulegen. Unter `./user` würde ich die Dokumentation für den Benutzer platzieren. Im Framework wären das der Quickstart und die Übersicht der Systeme, Komponenten usw. Im Dungeon wären das einerseits die Lehrpersonen, die DSL-Code schreiben, und andererseits die Studierenden, die DSL-Spiele spielen. Unter `./coder` würde ich die Dokumentation für die Weiterentwicklung und Wartung der Projekte ablegen. Dort sollten auch die Designentscheidungen festgehalten werden.

Wie von cagix schon angemerkt (und jetzt am ende bestätigt) unsere Dokumentation ist zu "flach", um diese Trennung zu rechtfertigen. Die "User" Doc für das Framework ist der Quickstart + Javadoc. Im Dugeon gibt es auch einen guten Quickstart für die User.
Der Rest ist coder
