### ISSUE TITLE
[Game] Globale Möglichkeit GUIs mit `ESC` zu schließen

### ISSUE THREAD

**Issue by fwatermann** [Programmiermethoden/Dungeon#966]
Aktuell lassen sich die GUIs nur mit `I` schließen. Es sollte eine globale und einheitliche Möglichkeit her GUIs (nacheinander?) zu schließen.

**Comment by AHeinisch** [comment]
@fwatermann wolltest du hier nicht noch was zu schreiben?

**Comment by fwatermann** [comment]
Ja richtig. 
Und zwar wäre meine Idee zu diesem Thema gewesen, dass jedes `UIComponent `einen `z-index`, wie bei CSS, hat bzw. zugewiesen bekommt, und bei Druck von `ESC` dann immer das oberste `UIComponent` gelöscht wird. 
Um jetzt die "ingame" UIs nicht schließbar zu machen, wäre eine Idee:
Positive `z-index` Werte sind UIs, die geschlossen werden können, negative Werte sind nicht schließbar.
Alternativ könnte man auch einfach ein `boolean` im Konstruktor vom `UIComponent` angeben.

**Comment by AMatutat** [comment]
> Ja richtig.
> Und zwar wäre meine Idee zu diesem Thema gewesen, dass jedes `UIComponent` einen `z-index`, wie bei CSS, hat bzw. zugewiesen bekommt, und bei Druck von `ESC` dann immer das oberste `UIComponent` gelöscht wird.
> Um jetzt die "ingame" UIs nicht schließbar zu machen, wäre eine Idee:
> Positive `z-index` Werte sind UIs, die geschlossen werden können, negative Werte sind nicht schließbar.
> Alternativ könnte man auch einfach ein `boolean` im Konstruktor vom `UIComponent` angeben.

Jetzt hatte ich mal meinen Nerd moment und habe an Counter Strike gedacht. 

@fwatermann irgendwie fehlt mir die zweite hälfte deiner Idee. Was mach ich denn mit dem z-index?

**Comment by fwatermann** [comment]
Die `UIComponents` werden nach diesem Index sortiert, daher höchster Wert ist ganz vorne. Und mit dem Druck der `ESC`-Taste wird dann immer das `UIComponent` mit dem höchsten Wert gelöscht → geschlossen.
