### ISSUE TITLE
Tool: build.gradle für Sub-Projekte aufteilen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#996]
Aktuell haben wir eine [build.gradle](https://github.com/Programmiermethoden/Dungeon/blob/master/build.gradle), die sowohl für das Framework (`./game`) als auch das Dungeon-Projekt (`./dsl` und `./dungeon`) verwendet wird.

Gerade wenn wir das Framework auch weiterhin ohne Dungeon-Projekt verwenden wollen, sollten wir für jedes Sub-Projekt ein eigenes Build-Skript erstellen. Dabei sollten wir auch noch einmal überprüfen, ob die Trennung zwischen `./dsl` und `./dungeon` auf Projektebene überhaupt noch Sinn ergibt. DSL ohne API scheint mir irgendwie unsinnig, und API ohne DSL sowieso.

Sind evtl. Java-Module dazu geeignet (oder macht das die Sache nur komplexer)? Quellen dazu: https://dev.java/learn/modules/, https://www.oracle.com/corporate/features/understanding-java-9-modules.html

**Comment by cagix** [comment]
> Gerade wenn wir das Framework auch weiterhin ohne Dungeon-Projekt verwenden wollen, sollten wir für jedes Sub-Projekt ein eigenes Build-Skript erstellen. 

Finde ich super.

@AMatutat Weisst Du zufällig, ob und wie weit libGDX mit Maven klarkommt? Wir verwenden immer komplexere Strukturen in unseren Gradle-Skripten, und erfahrungsgemäß wirft das Gradle-Projekt so alle 2 Jahre gern mal die Syntax über den Haufen - dagegen "halten" Maven-Skripte i.d.R. "ewig" ...


> Dabei sollten wir auch noch einmal überprüfen, ob die Trennung zwischen `./dsl` und `./dungeon` auf Projektebene überhaupt noch Sinn ergibt. DSL ohne API scheint mir irgendwie unsinnig, und API ohne DSL sowieso.

`game` steht für sich und sollte auch in Zukunft alleine verwendet werden können. Aber geht das überhaupt wg. der DSL-Annotationen?

`dsl` und `dungeon` finde ich im Moment nicht so klar: Man wird sicher `dsl` nicht ohne `dungeon` (und auch `game`) verwenden können/wollen. Aber wäre es nicht denkbar, dass man `dsl` außen vor lässt und nur mit `dungeon` plus `game` arbeiten möchte? Schließlich sind die ganzen Spielelemente ja in `dungeon`?

**Comment by AMatutat** [comment]
> game steht für sich und sollte auch in Zukunft alleine verwendet werden können. Aber geht das überhaupt wg. der DSL-Annotationen?

Mit den Annotations sagst du natürlich was. Vielleicht müsste man die in das Framework schieben?

> dsl und dungeon finde ich im Moment nicht so klar: Man wird sicher dsl nicht ohne dungeon (und auch game) verwenden können/wollen. Aber wäre es nicht denkbar, dass man dsl außen vor lässt und nur mit dungeon plus game arbeiten möchte? Schließlich sind die ganzen Spielelemente ja in dungeon?

Hmm, die Spielelemente liegen nicht im `dungeon` die liegen in `game`, aber die Task-Elemente.
Du könntest dir theoretisch ein Petri Netz und Aufgaben "einfach" in Java schreiben und die DSL rauslassen.
Auf der anderen Seite haben wir das nie so konzeptioniert, daher haben wir viele abhängikeiten von `dungeon`-> `dsl` und umgedreht.
In `game` habe ich immer darauf geachtet, keine Abhängigkeiten nach `dungeon` einzubauen.


> @AMatutat Weisst Du zufällig, ob und wie weit libGDX mit Maven klarkommt? Wir verwenden immer komplexere Strukturen in unseren Gradle-Skripten, und erfahrungsgemäß wirft das Gradle-Projekt so alle 2 Jahre gern mal die Syntax über den Haufen - dagegen "halten" Maven-Skripte i.d.R. "ewig" ... Und der einzige "große" Gradle-Vorteil ist jetzt auch bei Maven zu finden - die haben wohl auch einen Wrapper mittlerweile.

[libGDX](https://libgdx.com/wiki/articles/maven-integration) selbst sagt dazu:

> Instead of using Gradle to setup your libGDX project, you can also use Maven. However, this is not recommended! When issues arise, getting support will most certainly prove very difficult!

Und wenn ich den Artikel grob überfliege sieht das auch nicht spaßig aus

**Comment by cagix** [comment]
verstehe. dann sollten wir vielleicht das aktuelle `dungeon` und `dsl` mergen, und in einem zweiten schritt die ganzen spielsachen (die über ein basis-framework hinaus gehen) aus `game` nach `dungeon` schieben? also quasi `game/contrib` auflösen in ein eigenes java-projekt?

**Comment by AMatutat** [comment]
@fwatermann Wenn wir das Projekt abschließen, sperren wir dich ja hier im Repo ein:
Das ist eine super: Mach ich wenn alle weg sind Aufgabe für dich.

**Comment by cagix** [comment]
duplikat con #1323
