### ISSUE TITLE
[DUNGEON] Unterscheidung zwischen Task `aktiv ohne Bearbeitung` und Task `aktiv mit Bearbeitung` 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#998]
In der [Beschreibung der Petri Netze](https://github.com/Programmiermethoden/Dungeon/blob/master/doc/control_mechanisms/petri_nets.md)

Werden die verschiedenen Task-States definiert, darunter auch: 

> **inaktiv**: die Aufgabe wird den Studierenden nicht angezeigt und die mit der Aufgabe verknüpften Entitäten zeigen in einer definierten Form an, dass die entsprechende Aufgabe noch nicht aktiviert wurde oder sind nicht interagierbar

> **aktiv ohne Bearbeitung**: die Aufgabe wird den Studierenden im Questlog angezeigt, die verknüpften Entitäten verhalten sich wie bei inaktiv, alle Teilaufgaben der Aufgabe werden ebenfalls aktiviert

> **aktiv mit Bearbeitung**: die Aufgabe wird den Studierenden im Questlog angezeigt, mit den verknüpften Entitäten kann interagiert werden, um eine Antwort auf die Aufgabe zu geben

In dem in #994 eingeführten Petri-Netz findet erst einmal keine Unterscheidung zwischen "aktiv ohne Bearbeitung" und "aktiv mit Bearbeitung" statt. Es wird kein TaskState-Wert dafür implementiert.

**Beschreibung**

Mit diesen unterschiedlichen Zuständen können Aufgabenabhängigkeiten wie:

Gegeben seien zwei (Teil-) Aufgaben $t_1$ und $t_2$.

Für $t_2$ muss eine Antwort abgegeben werden, bevor $t_1$ abgeschlossen werden kann; $t_1$
wird zuerst aktiviert und bleibt aktiv, während $t_2$ bearbeitet wird.

Kürzel: “subtask_mandatory”/“st_m”

DSL-Eingabe:
```
task_dependency t {
  t1 -> t2 [type="st_m"]
}
```

definiert werden.

Im Spiel würde sich das so äußern, dass man zuerst zum Quest-Wizard von Task 1 geht, dieser einem sagt: "Hey, wir wollen XYZ machen, aber dafür musst du erst Task 2 lösen. Mach das mal und komm dann wieder."

Dann geht der Spieler zum Wizard von Task 2, löst die Aufgabe und kehrt zum Wizard von Task 1 zurück. Dieser würde dann etwas sagen wie: "Oh, toll, jetzt können wir XYZ machen. Los, mach weiter!"

**Grund:**

Was wir mit "aktiv ohne Bearbeitung" spielerisch ausdrücken, ist, dass es die Entitäten zum Lösen der Aufgabe zwar schon gibt, aber man nicht mit ihnen "arbeiten" kann. Und genau dieses "nicht damit arbeiten können" müsste je nach Entitätstyp genauer definiert werden. Kann ich dann nicht mit den Zauberer reden? Kann ich dann nicht den Schalter umlegen? Okay, das ist noch relativ intuitiv. Kann ich dann aber auch keine Quest-Items aufheben? Quest-Monster töten? Quest-Gegenstände craften?

Hier steckt ein höherer konzeptioneller Aufwand drin, und daher wird dieses Feature erst einmal auf später verschoben.

**Idee zur Implementierung:**

Das `TaskContentComponent` könnte um einen `active`-Boolean ergänzt werden. Wird der Task auf "aktiv mit Bearbeitung" gesetzt, wird das Flag `active` auf `true` gesetzt. Dann müsste man die anderen Komponenten der `TaskContent-Entitäten` entsprechend so verändern, dass sie sich wie gewollt verhalten.

**Folgen:**

Nach aktueller Betrachtung scheint dies keine Auswirkungen auf die Möglichkeiten der Gestaltung von Aufgabenabhängigkeiten zu haben. Dem Spieler wird nur nicht vorher gesagt, warum er die jeweiligen Teilaufgaben löst. Dies kann aber durch entsprechende Beschreibungstexte für die Teilaufgaben abgefedert werden.

**Comment by cagix** [comment]
clean-up: das wird nicht mehr passieren. wer soll das machen?!
